### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by smilesw** [theislab/scvelo#1003]
Thanks for great tool.

Recently, I have following error message when I entered "import scvelo as scv" in jupyter notebook.

What's wrong with this message?  And how can I solve it? 

Thanks in advance for any help.

------------------------------------------------------------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_1240/1935582919.py in <cell line: 1>()
----> 1 import scvelo as scv
      2 scv.settings.verbosity = 3  # show errors(0), warnings(1), info(2), hints(3)
      3 scv.settings.presenter_view = True  # set max width size for presenter view
      4 scv.set_figure_params('scvelo')  # for beautified visualization

~/anaconda3-2021.11/lib/python3.9/site-packages/scvelo/__init__.py in <module>
      1 """scvelo - RNA velocity generalized through dynamical modeling"""
      2 from anndata import AnnData
----> 3 from scanpy import read, read_loom
      4 
      5 from scvelo import datasets, logging

~/anaconda3-2021.11/lib/python3.9/site-packages/scanpy/__init__.py in <module>
     12     # (start with settings as several tools are using it)
     13     from ._settings import settings, Verbosity
---> 14     from . import tools as tl
     15     from . import preprocessing as pp
     16     from . import plotting as pl

~/anaconda3-2021.11/lib/python3.9/site-packages/scanpy/tools/__init__.py in <module>
     15 from ._leiden import leiden
     16 from ._louvain import louvain
---> 17 from ._sim import sim
     18 from ._score_genes import score_genes, score_genes_cell_cycle
     19 from ._dendrogram import dendrogram

~/anaconda3-2021.11/lib/python3.9/site-packages/scanpy/tools/_sim.py in <module>
     21 from anndata import AnnData
     22 
---> 23 from .. import _utils, readwrite, logging as logg
     24 from .._settings import settings
     25 from .._compat import Literal

~/anaconda3-2021.11/lib/python3.9/site-packages/scanpy/readwrite.py in <module>
      8 import pandas as pd
      9 from matplotlib.image import imread
---> 10 import tables
     11 import anndata
     12 from anndata import (

~/anaconda3-2021.11/lib/python3.9/site-packages/tables/__init__.py in <module>
     40 # Import the user classes from the proper modules
     41 from .exceptions import *
---> 42 from .file import File, open_file, copy_file
     43 from .node import Node
     44 from .group import Group

~/anaconda3-2021.11/lib/python3.9/site-packages/tables/file.py in <module>
     21 import numpy as np
     22 
---> 23 from . import hdf5extension
     24 from . import utilsextension
     25 from . import parameters

ImportError: /home/smilesw/anaconda3-2021.11/lib/python3.9/site-packages/tables/hdf5extension.cpython-39-x86_64-linux-gnu.so: undefined symbol: H5Pset_fapl_direct

**Comment by WeilerP** [comment]
@smilesw please update the issue description according to the issue template and provide all necessary and asked-for information. Closing this until the needed information is provided s.t. we can actually help.
