### ISSUE TITLE
How to understand if velocity direction is inverted

### ISSUE THREAD

**Issue by fbrundu** [theislab/scvelo#101]
Hi @VolkerBergen ,
I am aware that sometimes velocity streams can result inverted (for example https://github.com/theislab/scvelo/issues/68).

I currently recomputed PCA and neighbors graph with scanpy, and I am getting a result that seems totally opposite to my expectation (i.e. cells that appear to be expressing "quiescent" state markers, both at the level of spliced and unspliced counts, are indeed at the end of the stream).
It could be a totally legit description of the data, however, how can I troubleshoot the results? I used the `direct_pca_projection=False` parameter.

Please let me know if you need additional information.
Thanks

**Comment by VolkerBergen** [comment]
Hi, this invertion bug has been resolved. Do you get the same support from single-cell velocities?

**Comment by fbrundu** [comment]
Hi, how can I test for it? Thanks

**Comment by VolkerBergen** [comment]
Simply check for velocities on single cell level via `scv.tl.velocity_embedding`. If splicing kinetics supports the directionality, you may check on gene level via `scv.pl.velocity`.

**Comment by fbrundu** [comment]
Ok thanks!
