### ISSUE TITLE
fatal: 'origin/develop' is not a commit and a branch 'develop' cannot be created from it

### ISSUE THREAD

**Issue by chen-peng-1874** [theislab/scvelo#1010]
I am trying to install the latest development version. I first get clone from Github as follows:
...

```python
# git clone https://github.com/theislab/scvelo && cd scvelo
git checkout --track origin/develop
```
Then it comes out like this:

<details>
fatal: 'origin/develop' is not a commit and a branch 'develop' cannot be created from it
<summary> Error output </summary>

```pytb
# paste the error output here, if applicable
```

</details>

<details> <summary> Versions </summary>

```pytb
# paste the ouput of scv.logging.print_versions() here
```

</details>

**Comment by WeilerP** [comment]
The develop branch is no longer in use. Latest changes are directly merged into `master`.

**Comment by WeilerP** [comment]
@chen-peng-1874, does the documentation still refer to the develop branch somewhere or why did you try to check it out?

**Comment by chen-peng-1874** [comment]
> 

I just followed the "scVelo tutorials". And I think after check it out, I will need to "pip install -e ."

**Comment by chen-peng-1874** [comment]
> The develop branch is no longer in use. Latest changes are directly merged into `master`.

Thank you! But how can I use the "master" syntax?

**Comment by WeilerP** [comment]
> I just followed the "scVelo tutorials". And I think after check it out, I will need to "pip install -e ."

Okay, sorry, the docs are not up to date. I'll fix them.

> Thank you! But how can I use the "master" syntax?

Sorry, I don't understand the question. If you want to install the latest version (_i.e.,_ including content/features not yet released) simply run either

```
pip install git+https://github.com/theislab/scvelo
```

or

```
git clone https://github.com/theislab/scvelo && cd scvelo
pip install -e .
```

**Comment by chen-peng-1874** [comment]
Yes, I have installed it now.
But I can't import it...
It indicates that "importerror: DLL load failed while importing defs: The specified procedure could not be found".

And I am sure I installed scvelo(version 0.2.5).


Chen Peng

Postdoctoral Scholar - Research Associate

Center for Craniofacial Molecular Biology

Herman Ostrow School of Dentistry

2250 Alcazar St. CSA 119

Los Angeles, CA 90089

________________________________
发件人: Philipp Weiler ***@***.***>
发送时间: Tuesday, February 28, 2023 10:02:10 PM
收件人: theislab/scvelo ***@***.***>
抄送: Peng Chen ***@***.***>; Mention ***@***.***>
主题: Re: [theislab/scvelo] fatal: 'origin/develop' is not a commit and a branch 'develop' cannot be created from it (Issue #1010)


I just followed the "scVelo tutorials". And I think after check it out, I will need to "pip install -e ."

Okay, sorry, the docs are not up to date. I'll fix them.

Thank you! But how can I use the "master" syntax?

Sorry, I don't understand the question. If you want to install the latest version (i.e., including content/features not yet released) simply run either

pip install git+https://github.com/theislab/scvelo


or

git clone https://github.com/theislab/scvelo<https://urldefense.com/v3/__https://github.com/theislab/scvelo__;!!LIr3w8kk_Xxm!ssRAUu5EhHLCkL2ZswbmKKovp5IIIiM_CDNbqEs4UWqKWtBvU10bS_IGdVo6NGkKP8KK9VYILCF-Y52VVAqB09l_7w$> && cd scvelo
pip install -e .


―
