### ISSUE TITLE
ImportError: DLL load failed while importing defs: The specified procedure could not be found.

### ISSUE THREAD

**Issue by chen-peng-1874** [theislab/scvelo#1012]
Hi all,
When I import scvelo as scv, it runs out with error.
...

```python
# (velo) C:\Users\Peng Chen>python
>>>import scvelo as scv
```
Python 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

<details>

<summary> Error output </summary>

```pytb
# Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Public\miniconda3\envs\velo\lib\site-packages\scvelo\__init__.py", line 2, in <module>
    from anndata import AnnData
  File "C:\Users\Public\miniconda3\envs\velo\lib\site-packages\anndata\__init__.py", line 7, in <module>
    from ._core.anndata import AnnData
  File "C:\Users\Public\miniconda3\envs\velo\lib\site-packages\anndata\_core\anndata.py", line 17, in <module>
    import h5py
  File "C:\Users\Public\miniconda3\envs\velo\lib\site-packages\h5py\__init__.py", line 33, in <module>
    from . import version
  File "C:\Users\Public\miniconda3\envs\velo\lib\site-packages\h5py\version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py\h5.pyx", line 1, in init h5py.h5
ImportError: DLL load failed while importing defs: The specified procedure could not be found.
```

</details>

<details> <summary> Versions </summary>
conda list:

pip list:
(velo) C:\Users\Peng Chen>pip list
Package            Version
------------------ ---------
anndata            0.8.0
Bottleneck         1.3.5
certifi            2022.12.7
click              8.1.3
colorama           0.4.6
contourpy          1.0.7
cycler             0.11.0
dunamai            1.16.0
fonttools          4.38.0
get_version        3.5.4
h5py               3.8.0
hnswlib            0.6.2
igraph             0.10.4
importlib-metadata 6.0.0
joblib             1.2.0
kiwisolver         1.4.4
legacy-api-wrap    0.0.0
llvmlite           0.39.1
loompy             3.0.7
louvain            0.8.0
matplotlib         3.7.0
mkl-service        2.4.0
mock               5.0.1
natsort            8.3.0
networkx           3.0
numba              0.56.4
numexpr            2.8.4
numpy              1.23.5
numpy-groupies     0.9.20
packaging          23.0
pandas             1.5.3
patsy              0.5.3
Pillow             9.4.0
pip                22.3.1
pybind11           2.10.3
pynndescent        0.5.8
pyparsing          3.0.9
python-dateutil    2.8.2
python-igraph      0.10.4
pytz               2022.7.1
scanpy             1.9.2
scikit-learn       1.2.1
scipy              1.10.1
scvelo             0.2.5
seaborn            0.12.2
session-info       1.0.0
setuptools         65.6.3
setuptools-scm     7.1.0
sinfo              0.3.1
sip                4.19.13
six                1.16.0
statsmodels        0.13.5
stdlib-list        0.8.0
tables             3.7.0
texttable          1.6.7
threadpoolctl      3.1.0
tomli              2.0.1
tornado            6.2
tqdm               4.64.1
typing_extensions  4.5.0
umap-learn         0.5.3
wheel              0.38.4
wincertstore       0.2
zipp               3.15.0
```pytb
# paste the ouput of scv.logging.print_versions() here
```

</details>

**Comment by WeilerP** [comment]
Cannot reproduce the error and works fine for me. I suggest you try installing `scvelo` via pip.

**Comment by chen-peng-1874** [comment]
Yes, thank you! I already installed scvelo.
________________________________
