### ISSUE TITLE
params does not work

### ISSUE THREAD

**Issue by Pedramto89** [theislab/scvelo#1016]
...Hi. When I want to follow the vignette, after loading the loom object, in normalization step, an error pops up! My data comes from Visium.

```python
# scv.pp.filter_and_normalize(adata, **params)
scv.pp.moments(adata, **params)
```

<scv.pp.filter_and_normalize(adata, **params)
scv.pp.moments(adata, **params)>

<summary> Error output </summary>

NameError                                 Traceback (most recent call last)
[<ipython-input-15-c4717daa24ec>](https://localhost:8080/#) in <module>
----> 1 scv.pp.filter_and_normalize(adata, **params)
      2 scv.pp.moments(adata, **params)

NameError: name 'params' is not defined
```

```

</details>

**Comment by WeilerP** [comment]
Seems like the variable `params` is not defined, _i.e._, not an issue with scVelo.

**Comment by Pedramto89** [comment]
Thank you. So how can I set the params? If there is a weblink out of the vignette, please share it.
