### ISSUE TITLE
Determining cluster order for colouring

### ISSUE THREAD

**Issue by GBeattie** [theislab/scvelo#103]
Hey!

I am attempting to visualise velocity on top of a seurat generated clusters, displayed as a UMAP, which has worked, however I am having difficulty syncing the colours between what I've made in Seurat, with the scvelo output.

My approach was to extract the colours from seurat, and use them as the palette variable (as below). However the clusters in the output are coloured in the wrong order (I imagine the order may have been lost when merging the loom files?). I've looked through my adata's metadata but can't find a cluster order that matches the output.

How do I extract the cluster order that scvelo uses for colouring so I can re-order my palette variable accordingly?

Thanks!

```
ident_colours = ['#F8766D','#E18A00','#BE9C00','#8CAB00','#24B700','#00BE70','#00C1AB','#00BBDA','#00ACFC','#8B93FF','#D575FE','#F962DD','#FF65AC']

scv.pl.velocity_embedding_stream(adata, basis = "X_umap_cell_embeddings", color = "ClusterName", palette = ident_colours)
```

**Comment by VolkerBergen** [comment]
Hi, you can set the colors via `adata.uns['ClusterName_colors']=ident_colours`. 
Let me know, if that works for you.

**Comment by GBeattie** [comment]
No luck I'm afraid. Simple question (I'm new to python), what command would I use to view the order of my clusters in the Anndata object? If it is different from seurat's then that's the issue and I can manually arrange the colours accordingly. Thanks!

**Comment by VolkerBergen** [comment]
You can access the ordered cluster labels and corresponding color codes with
`adata.obs['ClusterName'].cat.categories` and `adata.uns['ClusterName_colors']`,
assuming that you have the clusters stored in `adata.obs['ClusterName']`.

**Comment by GBeattie** [comment]
Sorted! Somewhere in the processing seurat's ordering has been changed, just had to manually reorder the colours to match. Thank you for the assistance!

**Comment by Elo-mars** [comment]
Hi @GBeattie,


"My approach was to extract the colours from seurat" 

stupid question, but how did you extract your colours from Seurat to end up with such vector?

ident_colours = ['#F8766D','#E18A00','#BE9C00','#8CAB00','#24B700','#00BE70','#00C1AB','#00BBDA','#00ACFC','#8B93FF','#D575FE','#F962DD','#FF65AC']

Cheers,

Elodie

**Comment by GBeattie** [comment]
@Elo-mars Hey, this was a while ago so I can't remember the approach I chose in the end, but I used one of the methods oulined in satijalab/seurat#257

**Comment by Elo-mars** [comment]
sweet, I'll try that!

Thanks @GBeattie !
