### ISSUE TITLE
Merging adata and ldata

### ISSUE THREAD

**Issue by EJCresswell** [theislab/scvelo#1035]
Hi there,
I'm trying to do an RNA velocity using scVelo, taking my Seurat object and converting to an Anndata object using my loom files. I have been following the tutorial here: https://smorabit.github.io/tutorials/8_velocyto/

I have been trying to merge the adata and ldata using this code:
adata = scv.utils.merge(adata, ldata)

I keep getting this error message:

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In[177], line 1
----> 1 adata = scv.utils.merge(adata, ldata)

File ~\anaconda3\lib\site-packages\scvelo\core\_anndata.py:526, in merge(adata, ldata, copy, **kwargs)
    524 if "id_length" in kwargs:
    525     id_length = kwargs.get("id_length")
--> 526 clean_obs_names(adata, id_length=id_length)
    527 clean_obs_names(ldata, id_length=id_length)
    528 common_obs = adata.obs_names.intersection(ldata.obs_names)

UnboundLocalError: local variable 'id_length' referenced before assignment

I'm really unsure how to fix this. I do all my coding in R normally and I am new to python. Any (detailed) help would be greatly appreciated.

**Comment by WeilerP** [comment]
Please search existing issues before opening a new one.

**Comment by qiuhuiqq** [comment]
@emily-003 see issue #983
