### ISSUE TITLE
scv.tl.recover_dynamics errror: float division by zero

### ISSUE THREAD

**Issue by AnnaLaddach** [theislab/scvelo#104]
Hi,

If I run scv.tl.recover_dynamics  I obtain an error (after 2% has run):

ZeroDivisionError: float division by zero

Traceback shows:

/usr/local/lib/python3.6/dist-packages/scvelo/tools/dynamical_model_utils.py in get_loglikelihood(self, **kwargs)
    473         distx = udiff ** 2 + sdiff ** 2
    474         varx = np.mean(distx) - np.mean(np.sign(sdiff) * np.sqrt(distx))**2  # np.var(np.sign(sdiff) * np.sqrt(distx))
--> 475         return - 1 / 2 / len(distx) * np.sum(distx) / varx - 1 / 2 * np.log(2 * np.pi * varx)
    476 
    477     def get_likelihood(self, **kwargs):

Thanks for your help!

**Comment by VolkerBergen** [comment]
Hi, 
apologies for my absence; I'm currently traveling.
Have you done basic gene filtering beforehand via `pp.filter_and_normalize`?

**Comment by AnnaLaddach** [comment]
Apologies for the delayed reply. Yes, I have run pp.filter_and_normalize. I attach a screenshot of my notebook. Interestingly if I run scv.tl.velocity(adata_velo_gm, mode='dynamic') it does not give me any errors from the information on https://scvelo.readthedocs.io/getting_started.html I believe it is essential to run scv.tl.recover_dynamics first. I also have no problems running this in the stochastic mode.

Thanks again!
![scvelo](https://user-images.githubusercontent.com/8480634/68656855-7fda4e00-052a-11ea-9d4c-087f774bed9b.png)

**Comment by VolkerBergen** [comment]
Would be grateful to hear whether this is resolved with the latest commit.

**Comment by AnnaLaddach** [comment]
Thank you very much - yes the problem is now resolved :)

**Comment by babiddy** [comment]
Same here!
