### ISSUE TITLE
scvelo error

### ISSUE THREAD

**Issue by alyzas** [theislab/scvelo#107]
I am trying to compute RNA velocity for mouse single-cell data. I am able to compute the velocities but when I run the scv.tl.velocity_graph(adata) command I get this error: ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-78cbd7bfd37d> in <module>
----> 1 scv.tl.velocity_graph(adata, n_neighbors=10)
~/anaconda3/lib/python3.7/site-packages/scvelo/tools/velocity_graph.py in velocity_graph(data, vkey, xkey, tkey, basis, n_neighbors, n_recurse_neighbors, random_neighbors_at_max, sqrt_transform, gene_subset, approx, copy)
    168     vgraph = VelocityGraph(adata, vkey=vkey, xkey=xkey, tkey=tkey, basis=basis, n_neighbors=n_neighbors, approx=approx,
    169                            n_recurse_neighbors=n_recurse_neighbors, random_neighbors_at_max=random_neighbors_at_max,
--> 170                            sqrt_transform=sqrt_transform, gene_subset=gene_subset, report=True)
    171 
    172     if isinstance(basis, str):
~/anaconda3/lib/python3.7/site-packages/scvelo/tools/velocity_graph.py in __init__(self, adata, vkey, xkey, tkey, basis, n_neighbors, sqrt_transform, n_recurse_neighbors, random_neighbors_at_max, gene_subset, approx, report)
     65         if 'neighbors' not in adata.uns.keys(): neighbors(adata)
     66         if n_neighbors is None or n_neighbors <= adata.uns['neighbors']['params']['n_neighbors']:
---> 67             self.indices = get_indices(dist=adata.uns['neighbors']['distances'], n_neighbors=n_neighbors)[0]
     68         else:
     69             if basis is None: basis = [key for key in ['X_pca', 'X_tsne', 'X_umap'] if key in adata.obsm.keys()][-1]
~/anaconda3/lib/python3.7/site-packages/scvelo/tools/utils.py in get_indices(dist, n_neighbors)
    103 
    104     D.data -= 1e-6
--> 105     indices = D.indices.reshape((-1, n_neighbors))
    106     return indices, D
    107 
ValueError: cannot reshape array of size 0 into shape (0)
Can you please help me debug this message?

**Comment by VolkerBergen** [comment]
Thanks for raising this.

After recomputing the neighbor graph via `scv.pp.neighbors(adata)` could you print the following:
```
n_neighs = (adata.uns['neighbors']['distances'] > 0).sum(1).A1
print(n_neighs.min())
```

**Comment by alyzas** [comment]
Here are is the output:

Skip filtering by dispersion since number of variables are less than `n_top_genes`
WARNING: Did not modify X as it looks preprocessed already.
computing neighbors
    finished (0:03:53) --> added to `.uns['neighbors']`
    'distances', weighted adjacency matrix
    'connectivities', weighted adjacency matrix
computing moments based on connectivities
    finished (0:00:02) --> added
    'Ms' and 'Mu', moments of spliced/unspliced abundances (adata.layers)
computing neighbors
    finished (0:00:40) --> added to `.uns['neighbors']`
    'distances', weighted adjacency matrix
    'connectivities', weighted adjacency matrix
0


On Nov 13, 2019, at 11:38 AM, Volker Bergen <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for raising this.

After recomputing the neighbor graph via scv.pp.neighbors(adata) could you print the following:

n_neighs = (adata.uns['neighbors']['distances'] > 0).sum(1).A1
print(n_neighs.min())

**Comment by VolkerBergen** [comment]
after installing `pip install hnswlib`, could you repeat that with `scv.pp.neighbors(adata, method='hnsw')`, and please let me know your versions via `scv.pp.logging.print_versions()`.

**Comment by alyzas** [comment]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-c30ec636d0cf> in <module>
----> 1 scv.pp.logging.print_versions()

AttributeError: module 'scvelo.pp' has no attribute 'logging'


On Nov 13, 2019, at 11:59 AM, Volker Bergen <notifications@github.com<mailto:notifications@github.com>> wrote:


after installing pip install hnswlib, could you repeat that with scv.pp.neighbors(adata, method='hnsw'), and please let me know your versions via scv.pp.logging.print_versions().

**Comment by VolkerBergen** [comment]
edited my last msg, it's `scv.logging.print_versions()`. And please check with `scv.pp.neighbors(adata, method='hnsw')`

**Comment by alyzas** [comment]
scvelo==0.1.23  scanpy==1.4.4.post1  anndata==0.6.22.post1  loompy==2.0.17  numpy==1.17.2  scipy==1.3.1  matplotlib==3.1.1  sklearn==0.21.2  pandas==0.24.2


On Nov 13, 2019, at 12:11 PM, Volker Bergen <notifications@github.com<mailto:notifications@github.com>> wrote:

scv.pp.neighbors(adata, method='hnsw')

**Comment by VolkerBergen** [comment]
versions look fine. Would you please `print(len(set(adata.obsm['X_pca'].sum(1))), adata.n_obs)` to check whether you have duplicated cells.

**Comment by alyzas** [comment]
14865 123409


On Nov 13, 2019, at 12:27 PM, Volker Bergen <notifications@github.com<mailto:notifications@github.com>> wrote:


versions look fine. Would you please print(len(set(adata.obsm['X_pca'].sum(1))), adata.n_obs) to check whether you have duplicated cells.

**Comment by VolkerBergen** [comment]
That's it.. There's tons of duplicate cells in your data. How did you generate the file? Did you merge or concatenate any anndatas? How many cells do you expect to have, 123k or rather around 15k?

**Comment by VolkerBergen** [comment]
could you please finally check whether you the same numbers as above with `print(len(set(adata.layers['spliced'].sum(1).A1)), adata.n_obs)`

you can remove the duplicates via 
```
l=list(adata.obsm['X_pca'].sum(1))
indexes = [l.index(x) for x in set(l)]
adata = adata[indexes].copy()
```

**Comment by alyzas** [comment]
1747 123409

I removed duplicates and re-ran scv.tl.velocity_graph(adata) but got this message:

computing neighbors
    finished (0:00:54) --> added to `.uns['neighbors']`
    'distances', weighted adjacency matrix
    'connectivities', weighted adjacency matrix


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-33-699687a77a69> in <module>
----> 1 scv.tl.velocity_graph(adata)

~/anaconda3/lib/python3.7/site-packages/scvelo/tools/velocity_graph.py in velocity_graph(data, vkey, xkey, tkey, basis, n_neighbors, n_recurse_neighbors, random_neighbors_at_max, sqrt_transform, gene_subset, approx, copy)
    168     vgraph = VelocityGraph(adata, vkey=vkey, xkey=xkey, tkey=tkey, basis=basis, n_neighbors=n_neighbors, approx=approx,
    169                            n_recurse_neighbors=n_recurse_neighbors, random_neighbors_at_max=random_neighbors_at_max,
--> 170                            sqrt_transform=sqrt_transform, gene_subset=gene_subset, report=True)
    171
    172     if isinstance(basis, str):

~/anaconda3/lib/python3.7/site-packages/scvelo/tools/velocity_graph.py in __init__(self, adata, vkey, xkey, tkey, basis, n_neighbors, sqrt_transform, n_recurse_neighbors, random_neighbors_at_max, gene_subset, approx, report)
     65         if 'neighbors' not in adata.uns.keys(): neighbors(adata)
     66         if n_neighbors is None or n_neighbors <= adata.uns['neighbors']['params']['n_neighbors']:
---> 67             self.indices = get_indices(dist=adata.uns['neighbors']['distances'], n_neighbors=n_neighbors)[0]
     68         else:
     69             if basis is None: basis = [key for key in ['X_pca', 'X_tsne', 'X_umap'] if key in adata.obsm.keys()][-1]

~/anaconda3/lib/python3.7/site-packages/scvelo/tools/utils.py in get_indices(dist, n_neighbors)
    103
    104     D.data -= 1e-6
--> 105     indices = D.indices.reshape((-1, n_neighbors))
    106     return indices, D
    107

ValueError: cannot reshape array of size 0 into shape (0)


On Nov 13, 2019, at 12:48 PM, Volker Bergen <notifications@github.com<mailto:notifications@github.com>> wrote:


could you please finally check whether you the same numbers as above with print(len(set(adata.layers['spliced'].sum(1).A1)), adata.n_obs)

you can remove the duplicates via

l=list(adata.obsm['X_pca'].sum(1))
indexes = [l.index(x) for x in set(l)]
adata = adata[indexes].copy()

**Comment by VolkerBergen** [comment]
The data seems very odd. Is there any chance, you can share your data. feedback@scvelo.org.

Otherwise let me know what you have in 
`print(adata.obs_names, adata.var_names, adata.n_vars)`

**Comment by alyzas** [comment]
I will let you know if I can share the data. But here is the output:

Index(['AAACCTGAGACTAAGT.06', 'AAACCTGAGACTGGGT.06', 'AAACCTGCAGCTCGCA.06',
       'AAACCTGCAAGTAGTA.06', 'AAACCTGCACTGTGTA.06', 'AAACCTGCATCCTTGC.06',
       'AAACCTGGTAGCTTGT.06', 'AAACCTGGTAGGGTAC.06', 'AAACCTGGTCCGACGT.06',
       'AAACCTGTCCTGTACC.06',
       ...
       'ACTTTCATCAGCTTAG.06', 'GATCAGTGTTCCCGAG.06', 'GGTGCGTTCGATCCCT.06',
       'TACTTGTAGCCGATTT.06', 'CGCCAAGTCACCCTCA.06', 'CTTCTCTGTCTTGCGG.06',
       'CTCATTAAGGTCATCT.07', 'CTTAGGACACTCAGGC.07', 'TTTATGCGTCCGAGTC.07',
       'CATCGGGTCAAACCGT.06'],
      dtype='object', name='index', length=14865) Index(['ENSMUSG00000064370.1', 'ENSMUSG00000064368.1', 'ENSMUSG00000064367.1',
       'ENSMUSG00000064351.1', 'ENSMUSG00000064345.1', 'ENSMUSG00000064341.1',
       'ENSMUSG00000026034.17', 'ENSMUSG00000066406.15',
       'ENSMUSG00000056054.9', 'ENSMUSG00000056071.12',
       'ENSMUSG00000038642.10', 'ENSMUSG00000004207.14',
       'ENSMUSG00000020719.14', 'ENSMUSG00000038612.16',
       'ENSMUSG00000027398.13', 'ENSMUSG00000026234.12',
       'ENSMUSG00000034994.10', 'ENSMUSG00000003814.8', 'ENSMUSG00000038418.7',
       'ENSMUSG00000028649.18', 'ENSMUSG00000053641.9',
       'ENSMUSG00000022443.17', 'ENSMUSG00000029580.14',
       'ENSMUSG00000044786.6', 'ENSMUSG00000031207.16', 'ENSMUSG00000018476.7',
       'ENSMUSG00000005198.15', 'ENSMUSG00000035202.8', 'ENSMUSG00000034892.8',
       'ENSMUSG00000073421.6', 'ENSMUSG00000024014.8', 'ENSMUSG00000069833.13',
       'ENSMUSG00000024653.2', 'ENSMUSG00000021998.16',
       'ENSMUSG00000030536.10', 'ENSMUSG00000024661.7',
       'ENSMUSG00000039218.17', 'ENSMUSG00000021025.8', 'ENSMUSG00000096887.2',
       'ENSMUSG00000060126.14', 'ENSMUSG00000022108.8',
       'ENSMUSG00000106481.1'],
      dtype='object', name='index') 42





On Nov 13, 2019, at 1:09 PM, Volker Bergen <notifications@github.com<mailto:notifications@github.com>> wrote:


The data seems very odd. Is there any chance, you can share your data. feedback@scvelo.org<mailto:feedback@scvelo.org>.

Otherwise let me know what you have in
print(adata.obs_names, adata.var_names, adata.n_vars)

**Comment by VolkerBergen** [comment]
added a module `pp.remove_duplicate_cells`.
you have only very few vars/genes; looks like it was aligned with kallisto?

**Comment by VolkerBergen** [comment]
After removing duplicates, you have to recompute `scv.pp.neighbors`.

**Comment by alyzas** [comment]
I re-computed the scv.pp.neighbors. However, when re-running scv.tl.velocity_graph(adata): I get this message:

computing velocity graph



---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-55-699687a77a69> in <module>
----> 1 scv.tl.velocity_graph(adata)

~/anaconda3/lib/python3.7/site-packages/scvelo/tools/velocity_graph.py in velocity_graph(data, vkey, xkey, tkey, basis, n_neighbors, n_recurse_neighbors, random_neighbors_at_max, sqrt_transform, gene_subset, approx, copy)
    176
    177     logg.info('computing velocity graph', r=True)
--> 178     vgraph.compute_cosines()
    179
    180     adata.uns[vkey+'_graph'] = vgraph.graph

~/anaconda3/lib/python3.7/site-packages/scvelo/tools/velocity_graph.py in compute_cosines(self)
    123         if self.report: progress.finish()
    124
--> 125         vals = np.hstack(vals)
    126         vals[np.isnan(vals)] = 0
    127

<__array_function__ internals> in hstack(*args, **kwargs)

~/anaconda3/lib/python3.7/site-packages/numpy/core/shape_base.py in hstack(tup)
    342         return _nx.concatenate(arrs, 0)
    343     else:
--> 344         return _nx.concatenate(arrs, 1)
    345
    346

<__array_function__ internals> in concatenate(*args, **kwargs)

ValueError: need at least one array to concatenate



In [10]:

On Nov 13, 2019, at 1:50 PM, Volker Bergen <notifications@github.com<mailto:notifications@github.com>> wrote:


After removing duplicates, you have to recompute scv.pp.neighbors.

**Comment by VolkerBergen** [comment]
Now the issue is that you've got very low R squared values, which unselects all genes by default threshold. `del adata.var['velocity_genes']` and try again.

You've got very unusual data. What system is that and what did you use for read alignment?

**Comment by alyzas** [comment]
It is 2 mouse samples, treated and untreated. I have aligned the data using kallisto and computed the spliced and unspliced data using bustools.

Where do I run "del adata.var['velocity_genes’]” ?

On Nov 13, 2019, at 4:35 PM, Volker Bergen <notifications@github.com<mailto:notifications@github.com>> wrote:


Now the issue is that you've got very low R squared values, which unselects all genes by default threshold. del adata.var['velocity_genes'] and try again.

You've got very unusual data. What system is that and what did you use for read alignment?

**Comment by alyzas** [comment]
I shared the h5ad file with you.

**Comment by VolkerBergen** [comment]
spliced and unspliced count matrices being identical was causing this (see email).

**Comment by YiweiNiu** [comment]
Hello,

I found the same warning about 'duplicate cells' when processioning the data.

![图片](https://user-images.githubusercontent.com/25263399/79626995-4fe14780-8167-11ea-9f85-4c68d9b71909.png)

I did not found duplicate cell names in my `adata`, but it did show different number using `print(len(set(vdata.obsm['X_pca'].sum(1))), vdata.n_obs) `

I wonder what is the meaning of this warning?

Any comments or suggestions would be highly appreciated.

**Comment by VolkerBergen** [comment]
Cells may have slightly different obs_names, e.g. 
'AAACCTGAGAGGGATA-0' and 
'AAACCTGAGAGGGATA-1'. 

Yet, due to concatenation of same samples, they may exhibit the exact same expression profiles. You can find the indices and obs_names of the duplicates with 
```
l = list(np.sum(adata.obsm['X_pca'], 1))
idx_dup = [i for i, x in enumerate(l) if l.count(x) > 1]
idx_dup, adata.obs_names[idx_dup]
```

**Comment by YiweiNiu** [comment]
@VolkerBergen Thank you for your prompt reply!

Yes, since I merged several 10X libraries into one big matrix, some cells may have slightly different obs_names like you point out: 'AAACCTGAGAGGGATA-0' and 'AAACCTGAGAGGGATA-1'. But they are **indeed different** cells.

Also, some cells also have the same expression profiles, though I am sure that they are from different samples.

![图片](https://user-images.githubusercontent.com/25263399/79637584-51386180-81b3-11ea-900f-d88278e26ca6.png)

Should I remove these cells? or rename them? or just ignore the warning?

Thank you again for your help!

**Comment by VolkerBergen** [comment]
sum over PCs is just a proxy, which would be extremely unlikely though to yield the exact same value for two different cells.

Try this code snippet to see which of these really have the same expression profile.
```
l = list(np.sum(adata.obsm['X_pca'], 1))
idx_dup = [i for i, x in enumerate(l) if l.count(x) > 1]

X = adata.X.A  # if sparse else adata.X
diffs = np.sum(X[idx_dup][:, None] - X[idx_dup][None, :], -1) == 0 
df = pd.DataFrame(diffs, index=idx_dup, columns=idx_dup)
def highlight_max(s):
    return ['background-color: yellow' if v else '' for v in s == s.max()]
df.style.apply(highlight_max)
```

**Comment by YiweiNiu** [comment]
Thank you for your reply!

Only values in the diagonal showed `True` and all other values were `False` after running the commands.

```python
l = list(np.sum(vdata.obsm['X_pca'], 1))
idx_dup = [i for i, x in enumerate(l) if l.count(x) > 1]

X = vdata.X  # if sparse else adata.X
diffs = np.sum(X[idx_dup].toarray()[:, None] - X[idx_dup].toarray()[None, :], -1) == 0 
df = pd.DataFrame(diffs, index=idx_dup, columns=idx_dup)
def highlight_max(s):
    return ['background-color: yellow' if v else '' for v in s == s.max()]
df.style.apply(highlight_max)
```

**Comment by VolkerBergen** [comment]
So they're different indeed, yet ending up in the same pca coordinate. Wouldn't have thought that is possible. I'll adjust the test for duplicates. Thanks for raising this.

**Comment by YiweiNiu** [comment]
You are welcome! Thank you for developing this cool tool.

**Comment by JBreunig** [comment]
Just to chime in, the tool has been working very well for me but I've had the identical warning with bigger 10X datasets concatenated together.
