### ISSUE TITLE
Not able to open Jupyter Notebook

### ISSUE THREAD

**Issue by TamaraSall** [theislab/scvelo#1074]
Hello,
typing jupyter notebook does not open a new window. I tried reinstalling and pasting the links in the browser. This is the file that opens. Please help!
![image](https://github.com/theislab/scvelo/assets/113796021/c0291b1a-0523-4108-9431-dea94c1cb83a)

**Comment by WeilerP** [comment]
Closing this issue as it is clearly not related to scvelo.
