### ISSUE TITLE
#scv.pl.scatter error

### ISSUE THREAD

**Issue by DriskellLab** [theislab/scvelo#108]
I have a problem with scv.pl.scatter error.

I have succesfully loaded and run the "pancreatic endocrinogenesis" data through the tutorial up until I try to run the scv.pl.scatter command:
scv.pl.scatter(adata, basis=top_genes[:10], legend_loc='none',
               size=80, frameon=False, ncols=5, fontsize=20)
I then get the following error: 

![Screenshot from 2019-11-13 17-04-14](https://user-images.githubusercontent.com/41922042/68817782-ac2fc080-0637-11ea-9b80-f812c17bca93.png)
![Screenshot from 2019-11-13 17-03-46](https://user-images.githubusercontent.com/41922042/68817785-af2ab100-0637-11ea-8435-181419edef0f.png)

Is this something to do with a package that isn't up to date?
Thank you.

**Comment by VolkerBergen** [comment]
Thanks for raising this. The most important part of the error message is cut from your screenshot. Would be great if you provide the full error message.

**Comment by VolkerBergen** [comment]
Can you check whether the latest commit fixes your issue?

**Comment by DriskellLab** [comment]
Here is the full screenshot. I will try the latest commit fixes.
![Screenshot from 2019-11-15 08-03-07](https://user-images.githubusercontent.com/41922042/68957834-b4931300-077f-11ea-93a4-eae4e9c0c5dd.png)

**Comment by DriskellLab** [comment]
Tried the latest commit and don't think it worked. Screen shot attached.
Thank you for the help!
![Screenshot from 2019-11-15 09-09-48](https://user-images.githubusercontent.com/41922042/68961956-5c144380-0788-11ea-9b7d-275ea5ffcbea.png)

**Comment by VolkerBergen** [comment]
would you please `print(top_genes[:10])` and let me know the versions `scv.logging.print_versions()`?

**Comment by DriskellLab** [comment]
the pipeline works now. Thank you very much!

**Comment by hejian41** [comment]
@DriskellLab I have encountered the same problem. How did you solve it? The scvelo version is 0.1.24. 
Thank you.

**Comment by VolkerBergen** [comment]
hi @hejian41 same issue when installing from source? 
`pip install git+https://github.com/theislab/scvelo`

**Comment by hejian41** [comment]
> hi @hejian41 same issue when installing from source?
> `pip install git+https://github.com/theislab/scvelo`

Thanks a lot! it works.
