### ISSUE TITLE
Rank dynamical genes: Multi-dimensional indexing is no longer supported

### ISSUE THREAD

**Issue by AndiMunteanu** [theislab/scvelo#1087]
Hello and thank you for this package, it is really useful in my analysis!

I have been following the documentation of the package, especially the tutorials, and I tried to make my analysis follow the same steps.
However, I have encountered an error when running `scv.tl.rank_dynamical_genes` .

I have tested it using the exact code provided in the "Dynamical Modeling" tutorial, and the same error appear, namely `ValueError: Multi-dimensional indexing (e.g. 'obj[:, None]') is no longer supported. Convert to a numpy array before indexing instead.`

I have attached the traceback of the error.
Thank you!
<details>

```
ValueError                                Traceback (most recent call last)
Cell In[18], line 1
----> 1 scv.tl.rank_dynamical_genes(adata, groupby='clusters')
      2 df = scv.get_df(adata, 'rank_dynamical_genes/names')
      3 df.head(5)

File [~/miniconda3/envs/rna_velocity/lib/python3.10/site-packages/scvelo/tools/_em_model_core.py:1152]~/miniconda3/envs/rna_velocity/lib/python3.10/site-packages/scvelo/tools/_em_model_core.py:1152), in rank_dynamical_genes(data, n_genes, groupby, copy)
   1144 ll = get_divergence(
   1145     vdata,
   1146     mode="gene_likelihood",
   1147     use_connectivities=True,
   1148     clusters=adata.obs[groupby],
   1149 )
   1151 idx_sorted = np.argsort(np.nan_to_num(ll), 1)[:, ::-1][:, :n_genes]
-> 1152 rankings_gene_names = vdata.var_names[idx_sorted]
   1153 rankings_gene_scores = np.sort(np.nan_to_num(ll), 1)[:, ::-1][:, :n_genes]
   1155 key = "rank_dynamical_genes"

File [~/miniconda3/envs/rna_velocity/lib/python3.10/site-packages/pandas/core/indexes/base.py:5327]~/miniconda3/envs/rna_velocity/lib/python3.10/site-packages/pandas/core/indexes/base.py:5327), in Index.__getitem__(self, key)
   5325 # Because we ruled out integer above, we always get an arraylike here
   5326 if result.ndim > 1:
-> 5327     disallow_ndim_indexing(result)
   5329 # NB: Using _constructor._simple_new would break if MultiIndex
   5330 #  didn't override __getitem__
   5331 return self._constructor._simple_new(result, name=self._name)

File [~/miniconda3/envs/rna_velocity/lib/python3.10/site-packages/pandas/core/indexers/utils.py:341]~/miniconda3/envs/rna_velocity/lib/python3.10/site-packages/pandas/core/indexers/utils.py:341), in disallow_ndim_indexing(result)
    333 """
    334 Helper function to disallow multi-dimensional indexing on 1D Series/Index.
    335 
   (...)
    338 in GH#30588.
    339 """
    340 if np.ndim(result) > 1:
--> 341     raise ValueError(
    342         "Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer "
    343         "supported. Convert to a numpy array before indexing instead."
    344     )
```
</details>

<details> <summary> Versions </summary>

```pytb
scvelo==0.3.0  scanpy==1.9.3  anndata==0.9.1  loompy==3.0.7  numpy==1.24.3  scipy==1.10.1  matplotlib==3.7.1  sklearn==1.1.3  pandas==2.1.0.dev0+953.g7e6649386 
```

</details>

**Comment by WeilerP** [comment]
@AndiMunteanu, can you please verify that the error still occurs when you use the latest (developer) version of scVelo (the version on the master branch) and the latest released version of Pandas (instead of some developer version)?

**Comment by AndiMunteanu** [comment]
@WeilerP thank you for your response! I have downgraded the `pandas` package and made sure that scVelo is installed using the master branch. I have used the command `pip install git+https://github.com/theislab/scvelo` , is this the one I should be using to get the latest version?

The output for `scv.logging.print_versions()` is now the following
```
scvelo==0.3.0  scanpy==1.9.3  anndata==0.9.1  loompy==3.0.7  numpy==1.24.3  scipy==1.10.1  matplotlib==3.7.1  sklearn==1.1.3  pandas==2.0.2  
```

However, the error persists

**Comment by WeilerP** [comment]
Yes, `pip install git+https://github.com/theislab/scvelo` is the correct command. You can verify that the correct version is installed by running `pip freeze | grep scvelo`, which should give you `scvelo @ git+https://github.com/theislab/scvelo@e9dffff5b887baa6bc85dc8107b48013d4dd530a`.

Can you share a version of the data you are using? Otherwise, I do not know how to reproduce and debug the issue (unless it is also occurring with the data used in the tutorial).

**Comment by AndiMunteanu** [comment]
Indeed, it gives me exactly this output!

Sure! I went through the example from the [Dynamical Modeling](https://scvelo.readthedocs.io/en/stable/DynamicalModeling/) tutorial and got the error
