### ISSUE TITLE
Issue with running scv.tl.velocity_graph() function

### ISSUE THREAD

**Issue by ruiqiizhou** [theislab/scvelo#1096]
When I run scv.tl.velocity_graph() and scv.tl.recover_dynamics() on Jupyter Notebook, it throws an error. 
Even when I use sample dataset adata = scv.datasets.pancreas(), it also has the same error.
I tried to update packages, but it doesn't work.

My code is as same as the sample on the tutorial.

ValueError                                Traceback (most recent call last)
Cell In[32], line 1
----> 1 scv.tl.velocity_graph(adata)

File ~/opt/anaconda3/envs/2023_summer/lib/python3.11/site-packages/scvelo/tools/velocity_graph.py:363, in velocity_graph(data, vkey, xkey, tkey, basis, n_neighbors, n_recurse_neighbors, random_neighbors_at_max, sqrt_transform, variance_stabilization, gene_subset, compute_uncertainties, approx, mode_neighbors, copy, n_jobs, backend)
    359 n_jobs = get_n_jobs(n_jobs=n_jobs)
    360 logg.info(
    361     f"computing velocity graph (using {n_jobs}/{os.cpu_count()} cores)", r=True
    362 )
--> 363 vgraph.compute_cosines(n_jobs=n_jobs, backend=backend)
    365 adata.uns[f"{vkey}_graph"] = vgraph.graph
    366 adata.uns[f"{vkey}_graph_neg"] = vgraph.graph_neg

File ~/opt/anaconda3/envs/2023_summer/lib/python3.11/site-packages/scvelo/tools/velocity_graph.py:175, in VelocityGraph.compute_cosines(self, n_jobs, backend)
    172 n_obs = self.X.shape[0]
    174 # TODO: Use batches and vectorize calculation of dX in self._calculate_cosines
--> 175 res = parallelize(
    176     self._compute_cosines,
    177     range(self.X.shape[0]),
    178     n_jobs=n_jobs,
    179     unit="cells",
    180     backend=backend,
    181 )()
    182 uncertainties, vals, rows, cols = map(_flatten, zip(*res))
    184 vals = np.hstack(vals)

File ~/opt/anaconda3/envs/2023_summer/lib/python3.11/site-packages/scvelo/core/_parallelize.py:138, in parallelize.<locals>.wrapper(*args, **kwargs)
    126     pbar, queue, thread = None, None, None
    128 res = Parallel(n_jobs=n_jobs, backend=backend)(
    129     delayed(callback)(
    130         *((i, cs) if use_ixs else (cs,)),
   (...)
    135     for i, cs in enumerate(collections)
    136 )
--> 138 res = np.array(res) if as_array else res
    139 if thread is not None:
    140     thread.join()

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 4) + inhomogeneous part.
<summary> Error output </summary>

```pytb
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 4) + inhomogeneous part.
<summary> Error output </summary>
```

</details>

This are my versions:

Package                  Version
------------------------ -----------
Python 3.11.3
absl-py                  1.4.0
adjustText               0.8
aiofiles                 22.1.0
aiohttp                  3.8.4
aiosignal                1.3.1
aiosqlite                0.18.0
airr                     1.4.1
anndata                  0.9.1
anndata2ri               1.1
annoy                    1.17.2
anyio                    3.7.0
appdirs                  1.4.4
appnope                  0.1.3
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
arrow                    1.2.3
asttokens                2.2.1
async-timeout            4.0.2
attrs                    23.1.0
awkward                  2.3.1
awkward-cpp              21
Babel                    2.11.0
backcall                 0.2.0
beautifulsoup4           4.12.2
bleach                   6.0.0
blessed                  1.20.0
brotlipy                 0.7.0
cached-property          1.5.2
cattrs                   23.1.2
certifi                  2023.5.7
cffi                     1.15.1
charset-normalizer       2.0.4
chex                     0.1.7
click                    8.1.3
comm                     0.1.3
contextlib2              21.6.0
contourpy                1.0.5
croniter                 1.3.15
cryptography             39.0.1
cycler                   0.11.0
Cython                   0.29.35
dateutils                0.6.12
debugpy                  1.6.7
decorator                5.1.1
deepdiff                 6.3.0
defusedxml               0.7.1
Deprecated               1.2.14
dm-tree                  0.1.8
dnspython                2.3.0
docrep                   0.3.2
dunamai                  1.17.0
emptydrops               0.0.5
entrypoints              0.4
etils                    1.3.0
executing                1.2.0
fastapi                  0.88.0
fastjsonschema           2.17.1
filelock                 3.12.0
flax                     0.6.10
fonttools                4.25.0
fqdn                     1.5.1
frozenlist               1.3.3
fsspec                   2023.5.0
future                   0.18.3
get_version              3.5.4
glob2                    0.7
graphtools               1.5.3
h11                      0.14.0
h5py                     3.8.0
hnswlib                  0.7.0
hyperopt                 0.1.2
idna                     3.4
igraph                   0.10.4
imageio                  2.31.0
importlib-resources      5.12.0
inquirer                 3.1.3
ipykernel                6.23.1
ipython                  8.14.0
ipython-genutils         0.2.0
ipywidgets               8.0.6
isoduration              20.11.0
itsdangerous             2.1.2
jax                      0.4.11
jaxlib                   0.4.11
jedi                     0.18.2
Jinja2                   3.1.2
joblib                   1.2.0
json5                    0.9.6
jsonpointer              2.3
jsonschema               4.17.3
jupyter                  1.0.0
jupyter_client           8.2.0
jupyter-console          6.6.3
jupyter_core             5.3.0
jupyter-events           0.6.3
jupyter_server           2.6.0
jupyter_server_fileid    0.9.0
jupyter_server_terminals 0.4.4
jupyter_server_ydoc      0.8.0
jupyter-ydoc             0.2.4
jupyterlab               3.6.3
jupyterlab-pygments      0.2.2
jupyterlab_server        2.22.0
jupyterlab-widgets       3.0.7
kiwisolver               1.4.4
lazy_loader              0.2
leidenalg                0.9.1
Levenshtein              0.21.1
lightning                2.0.3
lightning-cloud          0.5.36
lightning-utilities      0.8.0
llvmlite                 0.40.1rc1
loompy                   3.0.7
louvain                  0.8.0
lxml                     4.9.2
lz4                      4.3.2
markdown-it-py           2.2.0
MarkupSafe               2.1.3
matplotlib               3.7.1
matplotlib-inline        0.1.6
mdurl                    0.1.2
mistune                  2.0.5
mkl-fft                  1.3.6
mkl-random               1.2.2
mkl-service              2.4.0
ml-collections           0.1.1
ml-dtypes                0.2.0
mpmath                   1.3.0
msgpack                  1.0.5
mudata                   0.2.3
multidict                6.0.4
multipledispatch         0.6.0
munkres                  1.1.4
natsort                  8.3.1
nbclassic                1.0.0
nbclient                 0.8.0
nbconvert                7.4.0
nbformat                 5.9.0
nest-asyncio             1.5.6
networkx                 3.1
notebook                 6.5.4
notebook_shim            0.2.3
numba                    0.57.0
numpy                    1.24.3
numpy-groupies           0.9.22
numpyro                  0.12.1
opt-einsum               3.3.0
optax                    0.1.5
orbax-checkpoint         0.2.4
ordered-set              4.1.0
overrides                7.3.1
packaging                23.0
pandas                   2.0.2
pandocfilters            1.5.0
parasail                 1.3.4
parso                    0.8.3
patsy                    0.5.3
pexpect                  4.8.0
phate                    1.0.11
pickleshare              0.7.5
Pillow                   9.4.0
pip                      23.0.1
platformdirs             3.5.1
ply                      3.11
pooch                    1.7.0
prometheus-client        0.17.0
prompt-toolkit           3.0.38
psutil                   5.9.5
ptyprocess               0.7.0
pure-eval                0.2.2
pybind11                 2.10.4
pycparser                2.21
pydantic                 1.10.9
Pygments                 2.15.1
PyGSP                    0.5.1
PyJWT                    2.7.0
pymongo                  4.3.3
pynndescent              0.5.10
pyOpenSSL                23.0.0
pyparsing                3.0.9
PyQt5-sip                12.11.0
pyro-api                 0.1.2
pyro-ppl                 1.8.5
pyrsistent               0.19.3
PySocks                  1.7.1
python-dateutil          2.8.2
python-editor            1.0.4
python-igraph            0.10.4
python-json-logger       2.0.7
python-Levenshtein       0.21.1
python-multipart         0.0.6
pytorch-lightning        2.0.3
pytz                     2022.7
pytz-deprecation-shim    0.1.0.post0
PyWavelets               1.4.1
PyYAML                   6.0
pyzmq                    25.1.0
qtconsole                5.4.3
QtPy                     2.3.1
rapidfuzz                3.1.1
readchar                 4.0.5
requests                 2.29.0
requests-cache           1.0.1
rfc3339-validator        0.1.4
rfc3986-validator        0.1.1
rich                     13.4.1
rpy2                     3.5.12
s-gd2                    1.8.1
scanpy                   1.9.3
scikit-image             0.21.0
scikit-learn             1.2.2
scikit-misc              0.2.0
scipy                    1.10.1
scirpy                   0.13.0
scprep                   1.2.3
scrublet                 0.2.3
scvelo                   0.2.5
scvi-tools               1.0.0
seaborn                  0.12.2
Send2Trash               1.8.2
session-info             1.0.0
setuptools               67.8.0
sip                      6.6.2
six                      1.16.0
sklearn                  0.0.post5
sniffio                  1.3.0
soupsieve                2.4.1
sparse                   0.14.0
squarify                 0.4.3
stack-data               0.6.2
starlette                0.22.0
starsessions             1.3.0
statsmodels              0.14.0
stdlib-list              0.8.0
sympy                    1.12
tasklogger               1.2.0
tensorstore              0.1.37
terminado                0.17.1
texttable                1.6.7
threadpoolctl            2.2.0
tifffile                 2023.4.12
tinycss2                 1.2.1
toml                     0.10.2
toolz                    0.12.0
torch                    2.0.1
torchmetrics             0.11.4
torchvision              0.15.2
tornado                  6.3.2
tqdm                     4.65.0
traitlets                5.9.0
typing_extensions        4.5.0
tzdata                   2023.3
tzlocal                  4.3
umap-learn               0.5.3
uri-template             1.2.0
url-normalize            1.4.3
urllib3                  1.26.16
uvicorn                  0.22.0
wcwidth                  0.2.6
webcolors                1.13
webencodings             0.5.1
websocket-client         1.5.2
websockets               11.0.3
wheel                    0.38.4
widgetsnbextension       4.0.7
wrapt                    1.15.0
xarray                   2023.5.0
xlrd                     2.0.1
y-py                     0.5.9
yamlordereddictloader    0.4.0
yarl                     1.9.2
ypy-websocket            0.8.2

<details> <summary> Versions </summary>

```pytb
# paste the ouput of scv.logging.print_versions() here
```

</details>

**Comment by ruiqiizhou** [comment]
Please tell me which issue I should check and which one is as same as mine!!!!~

**Comment by Streisenberg** [comment]
@ruiqiizhou I had a similar issue and found that mentioned at #1044. Downgrading the numpy to version 1.23.5 solved my problem.
