### ISSUE TITLE
scv.utils.merge() returns NotImplementedError

### ISSUE THREAD

**Issue by hungms** [theislab/scvelo#1116]
Hi scvelo team thank you for developing the package. I was able to load my merged loom files (loompy.combine) as anndata but am unable to concatenate it with my analysed anndata using scv.utils.merge(). Not sure if it is an error on my side as I am new to python. Thank you for the time!
...

```python
print(adata)
print(ldata)
adata = scv.utils.merge(adata, ldata)
```
I have printed the structure of the adata and ldata below:

AnnData object with n_obs × n_vars = 43091 × 18719
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'nCount_HTO', 'nFeature_HTO', 'nCount_ADT', 'nFeature_ADT', 'sample.id', 'pct.mt', 'pct.rb', 'pct.hb', 'qc', 'HTO_maxID', 'HTO_secondID', 'HTO_margin', 'HTO_classification', 'HTO_classification.global', 'hash.ID', 'nCount_IG', 'nFeature_IG', 'sc.s', 'sc.g2m', 'phase', 'time.point', 'nCount_SCT', 'nFeature_SCT', 'sc.Ighg', 'SCT_rpca_0.1', 'SCT_rpca_0.2', 'SCT_rpca_0.3', 'SCT_rpca_0.4', 'SCT_rpca_0.5', 'SCT_rpca_0.6', 'SCT_rpca_0.7', 'SCT_rpca_0.8', 'SCT_rpca_0.9', 'SCT_rpca_1', 'SCT_rpca_1.1', 'SCT_rpca_1.2', 'SCT_rpca_1.3', 'SCT_rpca_1.4', 'SCT_rpca_1.5', 'SCT_rpca_1.6', 'SCT_rpca_1.7', 'SCT_rpca_1.8', 'SCT_rpca_1.9', 'SCT_rpca_2', 'seurat_clusters', 'pc', 'sc.decontx', 'SCT_rpca2_0.1', 'SCT_rpca2_0.2', 'SCT_rpca2_0.3', 'SCT_rpca2_0.4', 'SCT_rpca2_0.5', 'SCT_rpca2_0.6', 'SCT_rpca2_0.7', 'SCT_rpca2_0.8', 'SCT_rpca2_0.9', 'SCT_rpca2_1', 'SCT_rpca2_1.1', 'SCT_rpca2_1.2', 'SCT_rpca2_1.3', 'SCT_rpca2_1.4', 'SCT_rpca2_1.5', 'SCT_rpca2_1.6', 'SCT_rpca2_1.7', 'SCT_rpca2_1.8', 'SCT_rpca2_1.9', 'SCT_rpca2_2', 'mice.id', 'dpt_pseudotime'
    uns: 'SCT_rpca2_0.5_colors', 'SCT_rpca2_0.5_sizes', 'diffmap_evals', 'draw_graph', 'iroot', 'neighbors', 'paga'
    obsm: 'X_diffmap', 'X_draw_graph_fa', 'X_pca', 'X_umap'
    layers: 'lognormalized'
    obsp: 'connectivities', 'distances'

AnnData object with n_obs × n_vars = 41752 × 32285
    obs: 'initial_size_unspliced', 'initial_size_spliced', 'initial_size'
    var: 'Accession', 'Chromosome', 'End', 'Start', 'Strand'
    layers: 'matrix', 'ambiguous', 'spliced', 'unspliced'

<details>
Below is the error code from scv.utils.merge():

<summary> Error output </summary>

```pytb
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[18], line 2
      1 import anndata
----> 2 adata = scv.utils.merge(adata, ldata)

File ~/.conda/envs/scrna/lib/python3.11/site-packages/scvelo/core/_anndata.py:531, in merge(adata, ldata, copy, **kwargs)
    528     common_obs = adata.obs_names.intersection(ldata.obs_names)
    530 if copy:
--> 531     _adata = adata[common_obs].copy()
    532     _ldata = ldata[common_obs].copy()
    533 else:

File ~/.conda/envs/scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1521, in AnnData.copy(self, filename)
   1515 if not self.isbacked:
   1516     if self.is_view and self._has_X():
   1517         # TODO: How do I unambiguously check if this is a copy?
   1518         # Subsetting this way means we don’t have to have a view type
   1519         # defined for the matrix, which is needed for some of the
   1520         # current distributed backend. Specifically Dask.
-> 1521         return self._mutated_copy(
   1522             X=_subset(self._adata_ref.X, (self._oidx, self._vidx)).copy()
   1523         )
   1524     else:
   1525         return self._mutated_copy()

File ~/.conda/envs/scrna/lib/python3.11/site-packages/anndata/_core/anndata.py:1453, in AnnData._mutated_copy(self, **kwargs)
   1451         new[key] = kwargs[key]
   1452     else:
-> 1453         new[key] = getattr(self, key).copy()
   1454 if "X" in kwargs:
   1455     new["X"] = kwargs["X"]

File ~/.conda/envs/scrna/lib/python3.11/site-packages/anndata/_core/aligned_mapping.py:298, in LayersBase.copy(self)
    296 def copy(self) -> "Layers":
    297     d = self._actual_class(self.parent)
--> 298     for k, v in self.items():
    299         d[k] = v.copy()
    300     return d

File <frozen _collections_abc>:861, in __iter__(self)

File ~/.conda/envs/scrna/lib/python3.11/site-packages/anndata/_core/aligned_mapping.py:142, in AlignedViewMixin.__getitem__(self, key)
    141 def __getitem__(self, key: str) -> V:
--> 142     return as_view(
    143         _subset(self.parent_mapping[key], self.subset_idx),
    144         ElementRef(self.parent, self.attrname, (key,)),
    145     )

File ~/.conda/envs/scrna/lib/python3.11/functools.py:909, in singledispatch.<locals>.wrapper(*args, **kw)
    905 if not args:
    906     raise TypeError(f'{funcname} requires at least '
    907                     '1 positional argument')
--> 909 return dispatch(args[0].__class__)(*args, **kw)

File ~/.conda/envs/scrna/lib/python3.11/site-packages/anndata/_core/views.py:205, in as_view(obj, view_args)
    203 @singledispatch
    204 def as_view(obj, view_args):
--> 205     raise NotImplementedError(f"No view type has been registered for {type(obj)}")

NotImplementedError: No view type has been registered for <class 'anndata._core.anndata.AnnData'>
```

</details>

<details> <summary> Versions </summary>

```pytb
scvelo==0.2.5  scanpy==1.9.3  anndata==0.9.2  loompy==3.0.7  numpy==1.24.3  scipy==1.9.3  matplotlib==3.7.1  sklearn==1.3.0  pandas==2.0.3  
```

</details>

**Comment by zhouzhendiao** [comment]
I used `adata.concat` to merge loom files, and use `scv.utils.merge` merge GEX and RNA velocity data. Everything worked fine. You can try my code:

For loom files:
```
def read_loom(loom_file):
    _adata_loom = scv.read(loom_file)
    _adata_loom.var_names_make_unique()
    return _adata_loom
    
adata_loom = ad.concat([read_loom(_) for _ in loom_files], )
```

For merging GEX and velocity:
```
adata_merge = scv.utils.merge(adata, adata_loom, copy=True)
```
Make sure indexs(obs_name) are same between GEX and velocity, then velocity  matrix can merge into GEX.

I tried used `loompy.combine`, but it take way long time to loading compare using `adata.concat`

**Comment by hungms** [comment]
Thanks for the advice - it did run quicker than loompy.combine. Also figured out the issue - accidentally saved one of the layers as anndata_.core instead of sparse matrix in my "adata". Fixed once layer is stored correctly.
