### ISSUE TITLE
issue with modified indices using concatenate

### ISSUE THREAD

**Issue by dxl3742** [theislab/scvelo#1118]
Hi, I have multiple 10x loom files that I wish to concatenate and merge into my seurat object, however I have noticed that the concatenate adds -0, -1, -2, -3 ... to the end of the object names (barcodes), which doesn't match with the seurat barcodes and gives the local variable 'id_length' error. 

ldata = ldata1.concatenate([ldata2, ldata3,ldata4, ldata5,ldata6,ldata7,ldata8,ldata9])
<img width="321" alt="image" src="https://github.com/theislab/scvelo/assets/94665211/71ff44dc-a194-40e5-bbab-9ea43a1242fe">

I have edited my seurat object barcodes to match these. Is there a way around this though? I'm rather new to python, probably doing something not right, any help would be appreciated :)

**Comment by yamihn** [comment]
Hi, I'm facing same issue!
Any solution? I also downgraded pandas but the solution does not work

**Comment by dxl3742** [comment]
@yamihn I got it to work by manually editing your seurat object barcodes to match the ones in the ldata. the -0 -1 -2 is the same for each cluster cellid.

**Comment by ShiyaoLi0405** [comment]
I have encountered the same question. I got it work by add all the ldata into a list and use anndata.concat() to have them merged.
