### ISSUE TITLE
 Sharing Software Versions for Successful scvelo Execution

### ISSUE THREAD

**Issue by wlqtriumph** [theislab/scvelo#1144]
Hello everyone,

I wanted to share the versions of the software I used for a successful run of scvelo. I successfully completed the run on November 25, 2023.

scvelo==0.2.5  scanpy==1.9.6  anndata==0.9.2  loompy==3.0.7  numpy==1.23.5  scipy==1.10.1  matplotlib==3.7.4  sklearn==1.2.2  pandas==1.1.5 

I must admit, these codes can be a bit of a head-scratcher for a medical student like myself. 😅 Though I might not fully grasp it, the good news is it ran without a hitch! If any fellow medical students have questions or want to share their experiences with similar software versions, let's navigate this complex world together.
![image](https://github.com/theislab/scvelo/assets/95834424/d4f797b8-7fee-48c1-8109-3343a9929c00
<img width="857" alt="Snipaste_2023-11-25_20-28-17" src="https://github.com/theislab/scvelo/assets/95834424/49c4e924-8f90-487d-9236-1792aad55b3d">

**Comment by yuanwsy** [comment]
what 's the versions of cellrank you use?it seems that pandas==1.1.5 is incompatible to cellrank==2.0.2

**Comment by wlqtriumph** [comment]
> what 's the versions of cellrank you use?it seems that pandas==1.1.5 is incompatible to cellrank==2.0.2

I did not use CellRank. Here is the code with all the libraries I used: 
import pandas as pd, 
import scvelo as scv, 
import numpy as np, 
import anndata.
