### ISSUE TITLE
eigenvalue calculation

### ISSUE THREAD

**Issue by smgroves** [theislab/scvelo#115]
Why, in the eigs function in terminal_states.py, do you take the transpose of the transition matrix before finding eigenvalues?

        eigvals, eigvecs = linalg.eigs(T.T, k=k, which='LR')  # find k eigs with largest real part

**Comment by VolkerBergen** [comment]
The module used herein is from `scipy.sparse.linalg.eigs`, see the [docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigs.html), which internally computes right eigenvectors. The transpose of the transition matrix is used as we want to find left eigenvectors.
