### ISSUE TITLE
scv.pl.velocity plots Ms instead of expression

### ISSUE THREAD

**Issue by GMaciag** [theislab/scvelo#116]
Hi

Great package, I enjoy using it very much. I have a question regarding plotting after estimation of velocity. The `scv.pl.velocity` function by default plots phase plot, velocity and *'expression'*.  However, it is not really expression (which I would assume to be taken from `.X`), but the rather the first order moment of spliced counts (`Ms`). This happens on the line highlighted below:
https://github.com/theislab/scvelo/blob/dd52df7d10cff2354d008d75c7fe888e7ed92b4f/scvelo/plotting/velocity.py#L84

This is very confusing and not accurate. I would like to have the velocity plots consistent with other plots (made with `pl.umap` or `pl.paga`) and right now they are not. 

It would be great if you could implement the ability to plot `.X` with `scv.pl.velocity` (that is normalised and log-transformed counts). Or at the very least, don't call it *'expression'*. `Ms` is not the same as `.X`

**Comment by VolkerBergen** [comment]
Good point! You can now do that via
`scv.pl.velocity(adata, var_names='geneA', layers=['velocity', 'X'], perc=None)`

**Comment by hamishking** [comment]
Hi there, 
Thanks for a great package, I've found it to be really helpful.
I just wanted to revisit this thread - I have been plotting gene "expression" across velocity pseudotime or latent time and have found some very interesting patterns in a transitional cell state that fit with other hypotheses we have tested. But the picture looks different whether I use 'Ms' or raw expression values as described above. 
I understand that the Ms values relate to the first order moment of spliced counts, but I am confused about how to biologically describe this measurement, similarly to the OPs point. Would something like "expression dynamic" be appropriate, or would it be better to look at the velocity values directly for that?

**Comment by VolkerBergen** [comment]
`Ms` is simply expression smoothed/averaged across neighboring cells, thus can be viewed as imputed data. Generally, studying expression dynamics is mostly done on imputed data anyways. So you can go ahead with `Ms`, which shows much more signal than raw counts.

**Comment by hamishking** [comment]
Brilliant, thank you for the explanation!
