### ISSUE TITLE
Update version for release

### ISSUE THREAD

**Issue by WeilerP** [theislab/scvelo#1165]
## Description

The version in `pyproject.toml` needs to be updated to `0.3.1`.

**Comment by smallfishcui** [comment]
Hi,

why I get the error message "TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases" when import scvelo as scv, for the newst version?

thanks,
Cui

**Comment by smallfishcui** [comment]
> Hi,
> 
> why I get the error message "TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases" when import scvelo as scv, for the newst version?
> 
> thanks, Cui

Okay, I answer my own question again. I deleted all the old packages, and reinstalled everything, then this error disappeared. 

Cui

**Comment by smallfishcui** [comment]
Hi,

I've tried many versions of matplotlib, but none of them worked with the new version of scvelo, including 3.8.2, 3.8.0,3.7.4,3.6.2 and more. Could you please tell which version of matplotlib is required? Strangely, when I use a matplotlib version that is incompatible with scvelo , most of the time scanpy doesn't work either...

thanks,
Cui
