### ISSUE TITLE
Dynamic streamline plots

### ISSUE THREAD

**Issue by ilan-gold** [theislab/scvelo#1178]
It would be very cool to somehow do dynamic streamline plots.  See

https://github.com/theislab/scvelo/assets/43999641/334d0577-5c14-4b8f-9416-9bd19850b787

for an example from geospatial data.  There are probably a few routes forward:

1.  A feature in [vitessce](vitessce.io) which they would likely accept.  This is very heavyweight, but could mean the whole thing is decoupled from this package, aside from potentially a dependency here.  This could be a good, less intensive starting point for vitessce - scverse integration (scanpy could be too much)
2. Import vitessce layer for scatterplot and then use https://deckgl.readthedocs.io/en/latest/ over it to generate stream plots (maybe a second layer would be needed)
3. Do everything from scratch here via https://deckgl.readthedocs.io/en/latest/
4. Make a new package and link to it from here, with some combination of the above three

I think each option has an upside and a downside.  I think this would make a great hackathon project for me.

**Comment by WeilerP** [comment]
Won't be implemented; streamline projections onto 2D embeddings are highly discouraged.
