### ISSUE TITLE
using scvelo with single nuclei rna seq data

### ISSUE THREAD

**Issue by marshbp** [theislab/scvelo#118]
Thanks for developing this package! I have been testing it using single-nucleus RNA sequencing data (rather than single cell) and it seems to be working quite well. Nuclei data has an average of ~25% spliced, ~70% unspliced, and ~5% ambiguous transcripts and is also slightly lower coverage than normal single cell rna seq. Running scvelo using the dynamical model gives velocity arrows in the opposite direction of known pos. ctr. trajectories from lineage tracing. However, the stochastic model recapitulates these known trajectories. Additionally, the latent time (derived from dynamical model) matches the results of the stochastic model and known trajectories. I assume the proportion of spliced/unspliced reads might violate some assumptions of scvelo. 

I am curious if you have tested scvelo on nuclei data and if you have any insight into how using nuclei would impact/confound calculation of velocities, especially with respect to the different models? Thanks for your time and thoughts!

**Comment by VolkerBergen** [comment]
Thanks! We've applied it to a few sn datasets so far, which have proportions like yours and yield good results; would be exciting to evaluate dyn. inference in sc compared to sn data. The dyn. model sometimes (when having small cell numbers) runs into an issue of ambiguous transcriptional state assignment. Could you share the phase portraits of the top10 likelihood genes?

**Comment by VolkerBergen** [comment]
Some concerns with single nuclei: The assumption made within all models are constant rates of splicing and degradation across cells for each gene. This can be controlled in parts and systematically filtered out, as alternative splicing and modulations in degradation often result in multiple slopes in phase space. However, for single nuclei you'd basically replace degradation with nuclear export, where the assumption might not be realistic.

**Comment by AnnaLaddach** [comment]
Following on from this, I was wondering if any further investigation has been done on the application of scVelo to single nuclei data? Whether it has been applied to "matched" single nuclei and whole-cell datasets?

Thank you!
