### ISSUE TITLE
module 'jax.random' has no attribute 'KeyArray'

### ISSUE THREAD

**Issue by spatts14** [theislab/scvelo#1186]
I cannot import scvelo as not compatible with most updated jax (0.4.24) and jaxlib (0.4.24).
What version do I need to have to be compatible? 
...

```python
import scvelo as scv
```

<details>

<summary> Error output </summary>

```pytb
AttributeError: module 'jax.random' has no attribute 'KeyArray'
```

</details>

<details> <summary> Versions </summary>

```pytb 
Version: 0.3.1
```

</details>

**Comment by christophechu** [comment]
same question

**Comment by Zethson** [comment]
Install scvi-tools from main. We'll make a new release soon that fixes this.

**Comment by hvgogogo** [comment]
> Install scvi-tools from main. We'll make a new release soon that fixes this.

could you indicate how to install scvi-tools from main, thanks so much.

**Comment by Zethson** [comment]
@hvgogogo 

1. you git clone the repository and cd into it
2. `pip install -U .`

If this is unclear, please consults your favorite search engine or LLM

**Comment by christophechu** [comment]
@hvgogogo  @Zethson 
just using jax == 0.4.19
its the error from scvi

**Comment by hvgogogo** [comment]
> @hvgogogo @Zethson just using jax == 0.4.19 its the error from scvi

Thanks so much, It works. 
 just a reminder to the following ones, you need downgrade the pip install jaxlib==0.4.19 too.

**Comment by christophechu** [comment]
SCVI will upgrade to 1.1.0. They will fix this problem soon.

**Comment by spatts14** [comment]
The workaround works on my desktop however, I'm trying to run it on the HPC and did the install per instructed and am running into errors. 

 I installed doing the following:
        ```
        git clone https://github.com/scverse/scvi-tools.git 
        
        ```
 
        ```
        pip install -U scvi-tools

        ```
   
        ```
        pip install jax==0.4.19



I am getting the following error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 import scvelo

File ~/anaconda3/envs/scVelo/lib/python3.11/site-packages/scvelo/__init__.py:5
      2 from anndata import AnnData
      3 from scanpy import read, read_loom
----> 5 from scvelo import datasets, logging
      6 from scvelo import plotting as pl
      7 from scvelo import preprocessing as pp

File ~/anaconda3/envs/scVelo/lib/python3.11/site-packages/scvelo/datasets/__init__.py:1
----> 1 from ._datasets import (
      2     bonemarrow,
      3     dentategyrus,
      4     dentategyrus_lamanno,
      5     forebrain,
      6     gastrulation,
      7     gastrulation_e75,
      8     gastrulation_erythroid,
      9     pancreas,
     10     pancreatic_endocrinogenesis,
     11     pbmc68k,
     12     toy_data,
     13 )
     14 from ._simulate import simulation
     16 __all__ = [
     17     "bonemarrow",
     18     "dentategyrus",
   (...)
     28     "toy_data",
     29 ]

File ~/anaconda3/envs/scVelo/lib/python3.11/site-packages/scvelo/datasets/_datasets.py:10
      6 import pandas as pd
      8 from scanpy import read
---> 10 from scvelo.core import cleanup
     11 from scvelo.read_load import load
     13 url_datadir = "https://github.com/theislab/scvelo_notebooks/raw/master/"

File ~/anaconda3/envs/scVelo/lib/python3.11/site-packages/scvelo/core/__init__.py:1
----> 1 from ._anndata import (
      2     clean_obs_names,
      3     cleanup,
      4     get_df,
      5     get_initial_size,
      6     get_modality,
      7     get_size,
      8     make_dense,
      9     make_sparse,
     10     merge,
     11     set_initial_size,
     12     set_modality,
     13     show_proportions,
     14 )
     15 from ._arithmetic import clipped_log, invert, multiply, prod_sum, sum
     16 from ._linear_models import LinearRegression

File ~/anaconda3/envs/scVelo/lib/python3.11/site-packages/scvelo/core/_anndata.py:15
     11 from scipy.sparse import csr_matrix, issparse, spmatrix
     13 from anndata import AnnData
---> 15 from scvelo import logging as logg
     16 from ._arithmetic import sum
     17 from ._utils import deprecated_arg_names

File ~/anaconda3/envs/scVelo/lib/python3.11/site-packages/scvelo/logging.py:12
      8 from packaging.version import parse
     10 from anndata.logging import get_memory_usage
---> 12 from scvelo import settings
     14 _VERBOSITY_LEVELS_FROM_STRINGS = {"error": 0, "warn": 1, "info": 2, "hint": 3}
     17 def info(*args, **kwargs):

File ~/anaconda3/envs/scVelo/lib/python3.11/site-packages/scvelo/settings.py:91
     83 """See set_figure_params.
     84 """
     87 # --------------------------------------------------------------------------------
     88 # Functions
     89 # --------------------------------------------------------------------------------
---> 91 warnings.filterwarnings("ignore", category=cbook.mplDeprecation)
     94 # default matplotlib 2.0 palette slightly modified.
     95 vega_10 = list(map(colors.to_hex, cm.tab10.colors))

AttributeError: module 'matplotlib.cbook' has no attribute 'mplDeprecation'

**Comment by aterceros** [comment]
Hi,
Having the same issue, downgraded to jax==0.4.19 but still having the "module 'jax.random' has no attribute 'KeyArray'" error...any hints?

**Comment by christophechu** [comment]
@aterceros @spatts14 
upgrade scvi to 1.1.0 may solve this issue.

**Comment by spatts14** [comment]
Solution:

I updated to scvi-tools 1.1.1 and upgraded pandas.

Current versions:
scanpy                    1.9.8           
scvelo                    0.3.1                
scvi-tools                1.1.1                   

Now running on the HPC. 

Of note, I use Parse data. The Parse website says to use pandas==1.5.3, however I needed to update.

**Comment by aterceros** [comment]
Hi,
Thank you for the comments, I upgraded to scvi-tools 1.1.0post2 (which seems to be the latest, no 1.1.1. version), but error still persisting. @spatts14 what version of pandas do you have?
Thanks a lot!

**Comment by spatts14** [comment]
I have pandas== 2.2.0, but I also have version scvi-tools 1.1.1 (released yesterday). I would suggest setting up a new environment and install from the main

**Comment by epignatelli** [comment]
Just bumped here by total chance while searching for the error.

This might help:
https://jax.readthedocs.io/en/latest/jep/9263-typed-keys.html#type-annotations-for-prng-keys

**Comment by dvagbear** [comment]
> Just bumped here by total chance while searching for the error.
> 
> This might help: https://jax.readthedocs.io/en/latest/jep/9263-typed-keys.html#type-annotations-for-prng-keys

it is a quick resolution that change jax,random.KeyArray into jax.Array in chen/_scr/pytypes.py as the error hint

**Comment by Xxianna** [comment]
Bug still exists in 1.1.2 😭
with jax==0.4.25

**Comment by WeilerP** [comment]
You can now pip install scvelo without scvi and jax as a dependency.

**Comment by littlewhitesea** [comment]
I met with a same problem and solved it through the following command line from [stackoverflow](https://stackoverflow.com/questions/78302031/stable-diffusion-attributeerror-module-jax-random-has-no-attribute-keyarray).
```
pip install "jax[cuda12_pip]==0.4.23" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```

**Comment by canergen** [comment]
Just seeing this. The dependency of Chex is removed in scVI-tools 1.1.0 and the error is not supposed to happen. If your still facing it, I would recommend setting up a new environment or otherwise report directly at scVI-tools.
