### ISSUE TITLE
scv.vl.velocity_graph won't finish after hours with 0

### ISSUE THREAD

**Issue by didiren** [theislab/scvelo#1196]
...

```python
# paste your code here, if applicable
```

<details>

<summary> Error output </summary>

```pytb
# paste the error output here, if applicable
```

</details>

<details> <summary> Versions </summary>

```pytb
# paste the ouput of scv.logging.print_versions() here
```

</details>

**Comment by didiren** [comment]
Hi, 
After following the tutorial of using scvelo, all steps ran fine but stuck when running scv.tl.velocity_graph. 
The run didn't show any error but took long hours without any progress.

My packages list are here:
Package                   Version
------------------------- ---------------
absl-py                   2.1.0
anndata                   0.9.2
anyio                     4.2.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.1
async-lru                 2.0.4
attrs                     23.2.0
Babel                     2.14.0
backcall                  0.2.0
beautifulsoup4            4.12.3
bleach                    6.1.0
certifi                   2024.2.2
cffi                      1.16.0
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
comm                      0.2.1
contourpy                 1.1.1
cycler                    0.12.1
debugpy                   1.8.1
decorator                 5.1.1
defusedxml                0.7.1
exceptiongroup            1.2.0
executing                 2.0.1
fastjsonschema            2.19.1
flatbuffers               2.0.7
fonttools                 4.48.1
fqdn                      1.5.1
get-annotations           0.1.2
gitdb                     4.0.11
GitPython                 3.1.41
h5py                      3.10.0
idna                      3.6
igraph                    0.10.8
importlib-metadata        7.0.1
importlib-resources       6.1.1
ipykernel                 6.29.2
ipython                   8.12.3
ipython-genutils          0.2.0
ipywidgets                7.7.1
isoduration               20.11.0
jax                       0.3.13
jaxlib                    0.3.7
jedi                      0.19.1
Jinja2                    3.1.3
joblib                    1.3.2
json5                     0.9.14
jsonpointer               2.4
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
jupyter_client            8.6.0
jupyter_core              5.7.1
jupyter-events            0.9.0
jupyter-lsp               2.2.2
jupyter_server            2.12.5
jupyter_server_terminals  0.5.2
jupyterlab                4.0.12
jupyterlab_pygments       0.3.0
jupyterlab_server         2.25.2
jupyterlab_widgets        3.0.10
kiwisolver                1.4.5
llvmlite                  0.41.1
loompy                    3.0.7
louvain                   0.8.1
MarkupSafe                2.1.5
matplotlib                3.7.4
matplotlib-inline         0.1.6
mistune                   3.0.2
multivelo                 0.1.3
natsort                   8.4.0
nbclient                  0.9.0
nbconvert                 7.16.0
nbformat                  5.9.2
nest-asyncio              1.6.0
networkx                  3.1
notebook                  7.0.8
notebook_shim             0.2.3
numba                     0.58.1
numpy                     1.24.4
numpy_groupies            0.9.22
opt-einsum                3.3.0
overrides                 7.7.0
packaging                 23.2
pandas                    2.0.3
pandocfilters             1.5.1
parso                     0.8.3
patsy                     0.5.6
pickleshare               0.7.5
pillow                    10.2.0
pip                       24.0
pkgutil_resolve_name      1.3.10
platformdirs              4.2.0
prometheus-client         0.19.0
prompt-toolkit            3.0.43
psutil                    5.9.8
pure-eval                 0.2.2
pycparser                 2.21
Pygments                  2.17.2
pynndescent               0.5.11
pyparsing                 3.1.1
python-dateutil           2.8.2
python-json-logger        2.0.7
pytz                      2024.1
pywin32                   306
pywinpty                  2.0.12
PyYAML                    6.0.1
pyzmq                     25.1.2
referencing               0.33.0
requests                  2.31.0
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.17.1
scanpy                    1.9.8
scikit-learn              1.1.3
scipy                     1.10.1
scvelo                    0.3.1
seaborn                   0.13.2
Send2Trash                1.8.2
session-info              1.0.0
setuptools                49.2.1
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.0
soupsieve                 2.5
stack-data                0.6.3
statsmodels               0.14.1
stdlib-list               0.10.0
terminado                 0.18.0
texttable                 1.7.0
threadpoolctl             3.2.0
tinycss2                  1.2.1
tomli                     2.0.1
tornado                   6.4
tqdm                      4.66.2
traitlets                 5.14.1
types-python-dateutil     2.8.19.20240106
typing_extensions         4.9.0
tzdata                    2024.1
umap-learn                0.5.5
uri-template              1.3.0
urllib3                   2.2.0
wcwidth                   0.2.13
webcolors                 1.13
webencodings              0.5.1
websocket-client          1.7.0
widgetsnbextension        3.6.6
zipp                      3.17.0

**Comment by WeilerP** [comment]
Since there is no stack trace or anything to work with, I cannot help you here, unfortunately. Everything works fine on my end.
