### ISSUE TITLE
scvelo neighbors

### ISSUE THREAD

**Issue by wangjiawen2013** [theislab/scvelo#12]
Dear,
I am trying to get RNA velocity with scvelo and I find that scvelo will search neighbors by default. Now I have an scanpy anndata object, of which the neighbors are made by a customized method. I wanna keep these neighbors, are there any methods to stop scvelo re-searching neighbors automatically ?

**Comment by VolkerBergen** [comment]
Good point! Neighbors get only updated if..
- not computed yet
- or `n_neighbors` attribute (default: 30) in `scv.pp.moments` is larger than the current one given in `adata.uns['neighbors']['params']['n_neighbors']` 

If it got recomputed in your case, it prob traces back to your `n_neighbors` being less than 30. Just set it to a lower value in `scv.pp.moments`.

**Comment by wangjiawen2013** [comment]
Thanks!
Another question, I want to harmonize scanpy with scvelo. In scanpy pipeline, there is a step called sc.pl.scale() to scale the data, which is absent in scvelo. Will it affects sc.tl.louvain and sc.tl.umap or paga when projecting the velocity graph onto an embedding ?

**Comment by VolkerBergen** [comment]
You can still use `sc.tl.scale()`. It will only affect the actual data matrix `adata.X` and thus implicitly any downstream.

The spliced and unspliced contained in `adata.layers` are not (and should not be) affected by `sc.tl.scale()`

**Comment by wangjiawen2013** [comment]
And, during data preprocessing, could I replace scvelo's scv.pp.show_proportions(adata) and scv.pp.cleanup(adata, clean='all') and scv.pp.filter_and_normalize(adata) with scanpy's sc.pp.filter_cells() and sc.pp.filter_genes() and sc.pp.normalize_per_cell() ?

**Comment by VolkerBergen** [comment]
Sure, you don't need to do any preprocessing within scvelo. Only normalization on the layers is necessary, which is automatically done within `scv.pp.moments`.

`scv.pp.show_proportions` does not do anything with your AnnData object; it just return the fractions of spliced/unspliced/ambiguous abundances, which can be useful to know. 

`scv.pp.cleanup(adata)` is not needed at all; only if you have a very large datasets that needs to be cleaned.

`scv.pp.filter_and_normalize` is equivalent to running `sc.pp.filter_genes` and `sc.pp.normalize_per_cell`.

**Comment by wangjiawen2013** [comment]
When combining data from multiple 10x genomics libraries, cellranger recommend equalizing the read depth between libraries before merging, to reduce the batch effect introduced by sequencing, the command is "cellranger aggr --nomalize=mapped". Will scvelo equalize the read depth per cell per sample when merging mutliple samples ?

**Comment by wangjiawen2013** [comment]
And, when should I set the parameter renormalize=True in function scv.pp.moments() ? namesly, scv.pp.moments(adata,  renormalize=True). Maybe it's better to have a detailed documents.

**Comment by VolkerBergen** [comment]
Once the paper is out, it will shed light on yet unclear statements/attributes.

The `renormalize` attr just indicates whether to renormalize the first-order moments as explained here: https://scvelo.readthedocs.io/en/latest/api/docs.source.api.pp.moments.html#docs.source.api.pp.moments

It's recommended to use its default value (`False`). The option is only available as I tried out a couple methodological things. I might even drop this attr later.

**Comment by VolkerBergen** [comment]
If I understood you correctly (w.r.t equalizing read depth), you can just create an AnnData object for each library, normalize them individually and then concatenate.  When having all in one object it does not take difference in libraries into account.

**Comment by fanxylab** [comment]
> Good point! Neighbors get only updated if..
> 
> * not computed yet
> * or `n_neighbors` attribute (default: 30) in `scv.pp.moments` is larger than the current one given in `adata.uns['neighbors']['params']['n_neighbors']`
> 
> If it got recomputed in your case, it prob traces back to your `n_neighbors` being less than 30. Just set it to a lower value in `scv.pp.moments`.

Scanpy neighbors  use all matrix data (unspliced + spliced + ambiguous) as input data to get neighbor matrixes. 
I confuse whether it`s correct If  I don`t use the spliced matrix to get neighbor matrixes and  return 'Ms' and 'Mu' .

**Comment by WeilerP** [comment]
@fanxylab, both Scanpy and scvelo use whatever data is stored in `.X`, _i.e._, if you store all counts (spliced + unspliced + ambiguous) in `.X`, scvelo will not calculate the neighbor graph using spliced counts but all instead.
Given that we usually have many more spliced than unspliced reads, I do not expect major differences between the two approaches. This is also what I observed on one or two datasets where the latent space was computed one time using the original count matrix and one time only spliced counts.

**Comment by brainfo** [comment]
Hi, could we specify "neighbors_key" to where in the anndata.uns to look at by scvelo.pp.moments?
