### ISSUE TITLE
gene likelihood

### ISSUE THREAD

**Issue by andreariba** [theislab/scvelo#120]
Hi,
is it possible to extract the gene likelihood values in some way?
Thanks

**Comment by VolkerBergen** [comment]
Hi, after running the dynamical model, they're stored in `adata.var` and you can simply access them via `top_genes = adata.var_names[adata.var.fit_likelihood.argsort()[::-1]]` (in descending order). Also see  the [tutorial](https://scvelo-notebooks.readthedocs.io/Pancreas.html).
