### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'str' and 'str'

### ISSUE THREAD

**Issue by suhuanhou** [theislab/scvelo#1209]
*>>> scv.pp.filter_and_normalize(adata)
/share/home/shh/miniconda3/envs/scVelo/lib/python3.9/site-packages/scvelo/preprocessing/utils.py:705: DeprecationWarning: `log1p` is deprecated since scVelo v0.3.0 and will be removed in a future version. Please use `log1p` from `scanpy.pp` instead.
  log1p(adata)
Normalized count data: X, spliced, unspliced.
Logarithmized X.
*>>> scv.pp.moments(adata)
computing neighbors
    finished (0:00:37) --> added 
    'distances' and 'connectivities', weighted adjacency matrices (adata.obsp)
computing moments based on connectivities
    finished (0:00:34) --> added 
    'Ms' and 'Mu', moments of un/spliced abundances (adata.layers)
*>>> scv.tl.velocity(adata, mode = "stochastic")
computing velocities
    finished (0:04:46) --> added 
    'velocity', velocity vectors for each individual cell (adata.layers)
*>>> scv.tl.velocity_graph(adata)
computing velocity graph (using 1/144 cores)
  0%|          | 0/54272 [00:00<?, ?cells/s]
    finished (0:01:21) --> added 
    'velocity_graph', sparse matrix with cosine correlations (adata.uns)
*>>> scv.pl.velocity_embedding_stream(adata, basis="umap")
TypeError: unsupported operand type(s) for -: 'str' and 'str'
computing velocity embedding

*>>>

**Comment by WeilerP** [comment]
I cannot reproduce the error. Please use the provided issue templates for bugs and all relevant information.
