### ISSUE TITLE
Need help with the parsing of stream plot result

### ISSUE THREAD

**Issue by NikTuzov** [theislab/scvelo#1215]
Hello:

I'm working with scvelo and my goal is to extract the lines and arrows information displayed by velocity_embedding_stream(). I want to get those coordinates to reuse them elsewhere. 

velocity_embedding_stream() is essentially a wrapper for matplotlib.streamplot(). I attached a Jupyter notebook with some data that are fed to matplotlib.streamplot(). The latter generates the lines and arrows as LineCollection and PatchCollection objects, but they end up being on different scales. I tried some hacking to make them agree, all to no avail.

I am sorry for asking a question that is more about matplotlib than scvelo, but matplotlib experts are scarce.

[lines_and_arrows.zip](https://github.com/theislab/scvelo/files/14578202/lines_and_arrows.zip)

**Comment by WeilerP** [comment]
You can check the code to generate the figure [here](https://github.com/theislab/scvelo/blob/ffe2cd3c437fd385f80fed9e6abc6dc3013eff82/scvelo/plotting/velocity_embedding_stream.py#L26) and extract the code generating the needed info.
