### ISSUE TITLE
cannot use module of scvelo after import in Spyder

### ISSUE THREAD

**Issue by yulchen810** [theislab/scvelo#1227]
I installed scvelo (version 0.3.2) in conda scVelo environment, I can import scvelo in Spyder but cannot use module of it.

```Spyder
import scvelo as scv

scv.set_figure_params()
Traceback (most recent call last):

  Cell In[18], line 1
    scv.set_figure_params()

AttributeError: module 'scvelo' has no attribute 'set_figure_params'


scv.settings.verbosity = 3
Traceback (most recent call last):

  Cell In[19], line 1
    scv.settings.verbosity = 3

AttributeError: module 'scvelo' has no attribute 'settings'

```
Does anyone know what's the problem?

Thank you!

**Comment by WeilerP** [comment]
@yulchen810, looks like something is wrong with your conda environment or something went wrong when you installed scvelo. I just checked pip installing scvelo in a clean environment and everything works.
