### ISSUE TITLE
AttributeError: module 'scvelo' has no attribute 'DataFrame'

### ISSUE THREAD

**Issue by jwalewski** [theislab/scvelo#1232]
When attempting to run the line ``` df_name = scv.DataFrame(adata.uns["rank_velocity_genes"]["names"]) ``` (like any of the tutorials) I now get the error that is the title. Why would this be? I've tried this previously and it worked before, but I have upgraded versions of things:
...

<details> <summary> Versions </summary>
```pytb
cellrank==2.0.3 scanpy==1.10.0 anndata==0.10.6 numpy==1.26.4 numba==0.59.1 scipy==1.12.0 pandas==2.2.1 pygpcca==1.0.4 scikit-learn==1.1.3 statsmodels==0.14.1 scvelo==0.0.0 pygam==0.9.1 matplotlib==3.8.3 seaborn==0.13.2
```
</details>

I attempted to look through the source code to find where the DataFrame function is defined (so I could explicity import it), but I couldn't find it with the github search. Do you know where it is?

Many thanks (as always),

Joe

**Comment by WeilerP** [comment]
`scv.DataFrame` was removed in the past. Please use `pandas.DataFrame`, instead.
