### ISSUE TITLE
High-dimensional extrapolated cell state vector

### ISSUE THREAD

**Issue by jvikkula** [theislab/scvelo#124]
Hi,

After performing the scVelo analysis, I would like to save the extrapolated cell states matrix and the corresponding "current cell state" matrix. In RNA Velocyto, these matrices would be Sx_sz_t and Sx_sz, respectively. Do some of the AnnData object's matrices correspond to these matrices directly? 

Thanks!

-Johanna

**Comment by VolkerBergen** [comment]
Hi Johanna, 
Extrapolating the cell state is simply adding the velocity vector scaled by extrapolation time, i.e. `adata.layers['Ms'] + adata.layers['velocity'] * deltaT`, where `deltaT` is arbitrary and can be set to 1.

**Comment by jvikkula** [comment]
Perfect, thank you!
