### ISSUE TITLE
scv.read(adata.h5ad) does not load spliced and unspliced layers

### ISSUE THREAD

**Issue by mdu4003** [theislab/scvelo#1242]
Hello, 

I am trying to do scvelo analysis on snRNAseq. I prepared the adata.h5ad using kb-python with a index built with the --workflow nucleus. I used that workflow also in kb count. The log shows that both matrixes are generated and combined in the adata.h5ad file. But when I read it with scv.read, the object shows 0 Layers. 
...
This is the log for the counting: 
[TCD_sn_KB.out.8877564.txt](https://github.com/theislab/scvelo/files/15142366/TCD_sn_KB.out.8877564.txt)

This is the command in scvelo: 
adata_Epi_TCD35_P = scv.read("/Users/diazmeco/Desktop/SCU/TCD35kb_P/counts_unfiltered/adata.h5ad", chunk_size=100000)
adata_Epi_TCD35_
AnnData object with n_obs × n_vars = 182745 × 33696
    obs: 'n_genes'

This is my scvelo:
[scvelo.txt](https://github.com/theislab/scvelo/files/15142368/scvelo.txt)

Thank you very much!
Best regards, 
Angeles

**Comment by mdu4003** [comment]
I started from scratch with new version of kb-python and workflow=nac. 
The only issue now is that I have nascent (unspliced) and mature (spliced) which are not recognized by scv.pp.filter_and_normalize. 
scv.pp.filter_and_normalize(adata_Epi_TCD35_P_filt, min_shared_counts=20, n_top_genes=2000)
WARNING: Could not find spliced / unspliced counts.

Do you have any solution? Should we re-name the layers somehow? Thanks!

**Comment by mdu4003** [comment]
I copied the layers with a new name: 
adata_filt.layers["unspliced"] = adata_filt.layers["nascent"]
adata_filt.layers["spliced"] = adata_filt.layers["mature"]
It seems to be solved. 
Can you add a modification for scvelo to recognize this new nomenclature?

**Comment by WeilerP** [comment]
Won't be implemented for now.
