### ISSUE TITLE
'dynamical' vs 'stochastic' mode

### ISSUE THREAD

**Issue by jfouyang** [theislab/scvelo#125]
I am wondering why the default mode in `scvelo.tl.velocity` being set to `mode='stochastic'` when the majority of the biorxiv paper seems to focus on the "dynamical" model. Is the "dynamical" model still under development?

Also, from the paper, it seems to me that the "dynamical" model is superior to the "stochastic" model. Thus, should I always try to run scVelo in "dynamical" model instead?

Finally, thanks so much for this awesome work!

**Comment by VolkerBergen** [comment]
Thanks! As you mentioned the dynamical model is superior and also yields many additional insights beyond velocities such as latent time, top-likelihood genes (putative drivers), kinetic rates etc.
It requires to first run `tl.recover_dynamics` and - depending on the number of genes - usually takes around 20-30 min.

If you're only interested in velocities, the stochastic model does a fairly good job yielding results approximating those from the dynamical model and usually runs within a minute.

**Comment by jfouyang** [comment]
Thanks for the explanation! It really helps in choosing between the "dynamical" and "stochastic" mode. An additional suggestion, is it possible to implement some form of parallelism in the "dynamical" model to speed up the calculation? Like perhaps parallelise the EM calculation for each gene?

**Comment by VolkerBergen** [comment]
Definitely, needs to be parallelized! That's on our list of todos. We will try to speed up the dyn. model just like we did for the other models. In terms of efficiency there's indeed room for improvement.

**Comment by WeilerP** [comment]
@jfouyang, I'll close the issue as the parallelisation is implemented as of `scvelo==0.2.3`.
