### ISSUE TITLE
Shape of phase plot(U-S) changes after scv.pp.moments(adata)

### ISSUE THREAD

**Issue by yuzzini** [theislab/scvelo#1253]
Hi, thank you for developing this tool.
I have a question about the shape of a phase plot

Before calculating scv.pp.moments,
scv.pp.normalize_per_cell(adata)
scv.pl.scatter(adata, basis=['FTL'])

results in 
![image](https://github.com/theislab/scvelo/assets/46211018/949aff08-6e4d-40c9-9994-ea4e826c4f8c)

and this is consistent which I checked through my own code doing total count normalization
![image](https://github.com/theislab/scvelo/assets/46211018/7a8a8d09-53a5-47a5-8478-5c9b58af76da)

but, after doing 
scv.pp.moments(adata)

phase plot dramatically change, like below, 
![image](https://github.com/theislab/scvelo/assets/46211018/6a03edd0-e7b2-473d-8c1e-e91d23a6ac11)

why is this happening? 
and which is a correct phase plot?

Sorry if this is a question lacking an understanding of scVelo's essense, 
but I would appreciate it if you could explain why this is happening.

Thank you,

**Comment by WeilerP** [comment]
Please check the docs for these sort of questions. If moments exist, `scatter` plots them by default.
