### ISSUE TITLE
Dependency problem on packages optax & chex

### ISSUE THREAD

**Issue by jasonleongbio** [theislab/scvelo#1255]
I recently newly installed `scVelo` in my virtual environment. 
However, loading `scvelo` was not successful
```python
import scvelo as scv
```
which showed the following the error message:
```
module 'chex' has no attribute 'warn_deprecated_function'
```

This error has been reported in another single-cell tool `cellrank`, but it seems that this has not been reported here in `scVelo`
https://github.com/theislab/cellrank/issues/1186

and a solution suggested by the post was that to downgrade the package `optax` from `0.2.2` (current ver) to `0.2.0`. I tried it with my virtual environment for `scVelo` and it worked.
```
mamba install optax=0.2.0
```

Hope this will help the community to solve the problem. 

Best,
Jason.

...

```python
# paste your code here, if applicable
# see above
```

<details>

<summary> Error output </summary>

```pytb
# paste the error output here, if applicable
# see above
```

</details>

<details> <summary> Versions </summary>

```pytb
# paste the ouput of scv.logging.print_versions() here

# This actually generated another error message but it seems the code using `scvelo` works fine
Running scvelo 0.0.0 (python 3.11.4) on 2024-06-26 15:55.
ERROR: XMLRPC request failed [code: -32500]
RuntimeError: PyPI no longer supports 'pip search' (or XML-RPC search). Please use https://pypi.org/search (via a browser) instead. See https://warehouse.pypa.io/api-reference/xml-rpc.html#deprecated-methods for more information.

# pacakge info from mamba
# scvelo                    0.3.2              pyhd8ed1ab_1    conda-forge
```

</details>

**Comment by WeilerP** [comment]
Thanks, @jasonleongbio! The jax dependecies will be removed in the future s.t. this issue should no longer occur.
