### ISSUE TITLE
Blocked by scv.settings.set_figure_params('scvelo')

### ISSUE THREAD

**Issue by iaconogi** [theislab/scvelo#126]
At the very beginning I am stuck with scv.settings.set_figure_params('scvelo').
It asks me In : as expecting me to give some further input and whatever I trie does not work.

>>> import scvelo as scv
>>> scv.logging.print_version()
Running scvelo 0.1.25.dev44+gf6280eb (python 3.7.3) on 2019-12-13 14:12.
>>>
>>> scv.settings.set_figure_params('scvelo')
In : 'scvelo'
'scvelo'
In : /home/trippa
  File "<stdin>", line 1
    /home/trippa
    ^
SyntaxError: invalid syntax
In : '/home/trippa'
'/home/trippa'
In :
KeyboardInterrupt

**Comment by VolkerBergen** [comment]
See if you can `import IPython` and `import matplotlib`.

**Comment by iaconogi** [comment]
It seems so. 
After it asks again 'In :'

>>> import IPython
>>> import matplotlib
>>> scv.settings.set_figure_params('scvelo')
In :

**Comment by VolkerBergen** [comment]
That's odd. What about `scv.settings.set_figure_params(style=None)`?

**Comment by iaconogi** [comment]
Same

Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scvelo as scv
>>>
>>>
>>> scv.settings.set_figure_params(style=None)
In :

**Comment by VolkerBergen** [comment]
I don't see what can possibly go wrong in there; and I am also missing any error message. Whatsoever, that is just setting some matplotlib params for beautified visualization. Try continue without these. I assume it'll also break at other modules for you; in that case you may need to reinstall; maybe also update IPython, jupyter and matplotlib.

**Comment by vickyrev** [comment]
I had the same issue with python3.7. Updating to python3.8 did the trick for me, hope it helps!
