### ISSUE TITLE
error from scv.pp.moments(adata)

### ISSUE THREAD

**Issue by QiqiGuo1996** [theislab/scvelo#1260]
Hi Team,

I plan to run scv.pp.moments(adata) using example data (scv.datasets.pancreas()), but I got the error pasted below, (Python version 3.10, scvelo version: 0.3.2), do you know how to fix it? please feel free to let me know if you need to see any other information from the attempted run. Thank you so much.

scv.pp.moments(adata)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/guoqq/.local/lib/python3.10/site-packages/scvelo/preprocessing/moments.py", line 63, in moments
    neighbors(
  File "/home/guoqq/.local/lib/python3.10/site-packages/scvelo/preprocessing/neighbors.py", line 223, in neighbors
    n_duplicate_cells = len(get_duplicate_cells(adata))
  File "/home/guoqq/.local/lib/python3.10/site-packages/scvelo/preprocessing/neighbors.py", line 555, in get_duplicate_cells
    X_new = np.array(X[idx_dup].A if issparse(X) else X[idx_dup])
AttributeError: 'csr_matrix' object has no attribute 'A'

**Comment by WeilerP** [comment]
You can either install scvelo from source or downgrade scipy.

**Comment by matthieuheitz** [comment]
Which version of scipy should it work with?

**Comment by pdemko** [comment]
Making a fresh conda environment and installing scvelo from source fixed the issue.

**Comment by TTTPOB** [comment]
tried scipy 1.13.1, works.

**Comment by stela2502** [comment]
Has that been fixed by now?!
I still get the same error.

scanpy==1.10.3
scvi==1.2.0
torch==2.5.1+cu124
scvelo==0.3.2
loompy==3.0.7
scanpy==1.10.3
igraph==0.11.6
pandas==2.2.3
re==2.2.1
numpy==1.26.4
h5py==3.12.1

**Comment by WeilerP** [comment]
It's fixed on `main` but I have not yet released a new version.

**Comment by stela2502** [comment]
Thank you.
Installing from git worked for me.
