### ISSUE TITLE
Possible to embed on one-dimensional embedding?

### ISSUE THREAD

**Issue by dpcook** [theislab/scvelo#127]
Hey! Thanks for developing the package--it's fantastic

I'm wondering if there's a way to map velocity along an arbitrary one-dimensional embedding (eg. cells ordered by diffusion distance to a root cell, or some other measure)? The purpose would be to measure magnitude/speed and direction (ie. forward or backwards) along a pre-defined trajectory. I tried running the pl.velocity_embedding giving it a one-dimensional basis parameter, but it threw an error.

Ultimately, I'd be hoping to access the mapped values similar to getting values for other embeddings from adata.obsm

Thanks!

**Comment by VolkerBergen** [comment]
Thanks, and interesting question. You could something along these lines.

Define an arbitrary embedding:
`adata.obsm['X_lmap'] = np.stack([adata.obs['latent_time'], adata.obs['latent_time']]).T`

and visualize the arrows on that line
`scv.pl.velocity_embedding(ldat, basis='lmap', arrow_size=3, arrow_length=2, dpi=120, size=0)`

and color by magnitude of the velocity vector
`scv.pl.velocity_embedding(ldat, basis='lmap', color=ldat.obsm['velocity_lmap'][:, 0], vmid=0,
                          arrow_size=3, arrow_length=2, dpi=120, size=0, color_map='RdBu')`

where the red-colored ones are inconsistent with latent time.

That yields sth like that:
![image](https://user-images.githubusercontent.com/31883718/70840479-d4ffcd00-1e12-11ea-9a00-5da5d77cc5f8.png)

![image](https://user-images.githubusercontent.com/31883718/70840481-dc26db00-1e12-11ea-8eb6-da80c48e4775.png)

**Comment by dpcook** [comment]
Perfect! This will work great. Thank you!

**Comment by VolkerBergen** [comment]
To get a better idea of the magnitudes, you could also do something along these lines:

```
adata.obsm['X_lmap'] = np.stack([adata.obs['latent_time'], adata.obs['latent_time']]).T
scv.tl.velocity_embedding(adata, basis='lmap', retain_scale=True)

scv.pl.velocity_embedding(adata, X=np.stack([adata.obs['latent_time'], np.zeros(adata.n_obs)]).T,
                          basis='lmap', color=adata.obsm['velocity_lmap'][:, 0], vmid=0,
                          arrow_size=3, arrow_length=1, dpi=120, size=0, color_map='RdBu')
```
![image](https://user-images.githubusercontent.com/31883718/70854613-4cd70180-1ebe-11ea-907a-c29614622dbe.png)

**Comment by dpcook** [comment]
Ah good to know! Yeah, I ended up trying it out on some cells ordered along PC1 and visualized it in a similar way. 
![image](https://user-images.githubusercontent.com/18197806/70854674-e4236100-1e8c-11ea-8da8-761c6cccf4bd.png)
