### ISSUE TITLE
scv.settings.figdir

### ISSUE THREAD

**Issue by michalk8** [theislab/scvelo#128]
Hey @VolkerBergen ,
when running this,
```python
import scvelo as scv
scv.settings.figdir = 'bar'

adata = scv.datasets.toy_data(10)
scv.pl.scatter(adata, basis='umap', save='foo')
```
the figure is saved as `barscvelo_foo.pdf`, not as `bar/scvelo_foo.pdf` (specifying the trailing `/` fixes the problem).

My version is `0.1.25.dev19+g3e75071.d20191116`.

**Comment by VolkerBergen** [comment]
Fixed, thanks.
