### ISSUE TITLE
Question on dependencies

### ISSUE THREAD

**Issue by dawe** [theislab/scvelo#1284]
Hello all, I am populating a clean conda environment and `scvelo` is (obviously) a dependency. As I don't want to mess with libraries, I've noticed that the package toml file specifies "scikit-learn>=0.21.2", whereas the recipe file on conda-forge scvelo-feedstock adds a maximal version scikit-learn >=0.21.2,<1.2.0. Since other packages are requesting more recent versions of scikit-learn, I'd like to know if it is ok to override scvelo dependency and install v1.5.2

**Comment by WeilerP** [comment]
Yes, you can. Should also be solved by now.
