### ISSUE TITLE
Velocyto question

### ISSUE THREAD

**Issue by Liripo** [theislab/scvelo#1285]
When I use the parameter `--soloFeatures GeneFull_Ex50pAS Velocyto`, the result is only three lines.
for example: `Velocyto/raw/spliced.mtx`:
```R
%%MatrixMarket matrix coordinate integer general
%
38606 2359296 0
```

Should I use parameters `--soloFeatures GeneFull GeneFull_Ex50pAS Velocyto` ?

**Comment by WeilerP** [comment]
Sorry, your question concers velocyto, not scvelo. Please open an issue on the correct repo or contact the maintainers of velocyto. It's also not a bug. Please use the corresponding issues to reduce overhead on the maintainer side.

**Comment by Liripo** [comment]
I'm really sorry, I asked in the wrong place.
