### ISSUE TITLE
The inferred RNA velocity direction is not as expected

### ISSUE THREAD

**Issue by smallfishcui** [theislab/scvelo#1286]
Hi,

I am working with plant species, and lately I have been trying to use scevelo to infer the cell transition state for the annotated cell types. Scevelo gave very nice result with clear and strong signals of RNA flows, however, the results are very different from my expectations.
![Image](https://github.com/user-attachments/assets/eaf4b7b9-2b14-45f0-bb09-4bbbc41e247d) For example, in this picture, the source of the center is annotated to be mesophyll cells, but it acts as a meristematic cell with flow to every other tissues. 
I have spatial data, and quite sure the cell annotation is not too absurd, and I have other clusters annotated to be the meristemnatic tissues. 
Can anyone tell how accurate this analysis is?

Thanks for your help,
Cui

**Comment by smallfishcui** [comment]
I meant cluster 3 and 9.

**Comment by WeilerP** [comment]
CLassical issue. Please check the multiple issues and discussions here on GitHub; there are also numerous papers fundamental limitations of RNA velocity, _i.e._, why it may fail, and why you should not plot/rely on stream embeddings.
