### ISSUE TITLE
AttributeError in scvelo.read() following update to 12.9

### ISSUE THREAD

**Issue by LCGaoZzz** [theislab/scvelo#1288]
I recently updated to the latest release of scvelo (12.9), and I've encountered a new bug that wasn't present in previous versions. When attempting to use the read() function, I receive an AttributeError indicating that the module 'scvelo' does not have an attribute 'read'. This issue occurs even when trying to use basic functionality as demonstrated below:

```python
import scvelo as scv

# Error occurs on the following line
ldata = scv.read("file_path.loom", cache=True)
```

<details>

<summary> Error output </summary>

```pytb
AttributeError Traceback (most recent call last)
<ipython-input-#> in <cell line: #>()
      ldata = scv.read("file_path.loom", cache=True)
AttributeError: module 'scvelo' has no attribute 'read'
```

**Comment by LCGaoZzz** [comment]
Issue resolved! It seems that the new scvelo release has removed the .read method. As an alternative, you can import scanpy as sc and use sc.read instead:

```python
import scanpy as sc
ldata = sc.read("file_path.loom", cache=True)

**Comment by WeiQin2001** [comment]
Thank you for your work!!!

**Comment by 18520964064** [comment]
Thanks a lot
