### ISSUE TITLE
figure cannot be saved as pdf, using png instead (can only output finite numbers in pdf).

### ISSUE THREAD

**Issue by Quianter** [theislab/scvelo#1289]
I'm confused that my scvelo script program cannot export .pdf format figures.
...

```python
scv.pl.velocity_embedding_stream(adata1, basis='X_umap', color=var_name, arrow_size=1, alpha=0.4, show=False,
                                 save='scVelo.pdf',
                                 palette = colors, size = 250,fontsize=10)

```

<details>
velocity_embedding_stream error messages: figure cannot be saved as pdf, using png instead (can only output finite numbers in pdf)
matplotlib.pyplot.figsave error messages: ValueError: Can only output finite numbers in PDF
<summary> Error output </summary>

```pytb
# paste the error output here, if applicable
```

</details>

<details> <summary> Versions </summary>
0.3.3
```pytb
# paste the ouput of scv.logging.print_versions() here
```

</details>

**Comment by WeilerP** [comment]
I think the different levels and transparency are the problem if I remember correctly. It's not a problem with scVelo.
