### ISSUE TITLE
Sorting genes by latent_time does not return the same order as scv.pl.heatmap(adata, tkey='latent_time', sort=True)

### ISSUE THREAD

**Issue by Appren893** [theislab/scvelo#130]
Hi,

For my data, I am trying to plot the transcriptional progression of genes similar to the heatmap shown here (https://scvelo-notebooks.readthedocs.io/Pancreas.html), ie:

    top_genes = adata.var_names[adata.var.fit_likelihood.argsort()[::-1]][:300]
    scv.pl.heatmap(adata, var_names=top_genes, tkey='latent_time', n_convolve=100, col_color='clusters')

This works just fine. However, I would then like to further analyse the genes in the same order as they appear in the heatmap. Unfortunately, there doesn't seem to be any documentation surrounding scv.pl.heatmap, so in order to do so, I checked the actual code and followed the sorting steps as follows:

    var_names = [name for name in top_genes if name in adata.var_names]
    df = pd.DataFrame(adata[:, var_names].layers[xkey][np.argsort(time)], columns=var_names)
    max_sort = np.argsort(np.argmax(df.values, axis=0))
    df = pd.DataFrame(df.values[:, max_sort], columns=df.columns[max_sort])

Since there doesn't seem to be any other sorting step, I thought the order of df.columns would be the same as the order of the top_genes, ordered by latent time in the heatmap. However, that doesn't seem to be the case. Could you explain why it's different? And any way to extract the genes in the same order as in the heatmap?

Thanks!

**Comment by VolkerBergen** [comment]
Hi,
the default ordering is per maximum expression. If you don't want to order them, you can simply set `sort=False`. And to extract the ordered gene names, follow the same code as in `pl.heatmap`:

```
import pandas as pd
xkey = 'Ms'
tkey = 'latent_time'
n_convolve = 30

var_names = top_genes[:100]

time = adata.obs[tkey].values
time = time[np.isfinite(time)]

df = pd.DataFrame(adata[:, var_names].layers[xkey][np.argsort(time)], columns=var_names)

if n_convolve is not None:
    weights = np.ones(n_convolve) / n_convolve
    for i, gene in enumerate(var_names):
        df[gene] = np.convolve(df[gene].values, weights, mode='same')

max_sort = np.argsort(np.argmax(df.values, axis=0))
top_genes[max_sort]
```

**Comment by Appren893** [comment]
I must have gotten a wrong order due to not uisng the weights as well, didn't realize that they affected it. Thanks!
