### ISSUE TITLE
Estimate effect gene perturbation

### ISSUE THREAD

**Issue by jipeifeng** [theislab/scvelo#132]
Hi:
   Thank you for the helpful tool.
   I have sequenced two data sets (WT vs KO) using 10 x genomics. My question is can I estimate the effect of gene  perturbation in the KO data set. My previous observation is that after gene knockdown, the ratio of some  cell type decreased, while other cell type increased. Therefore, I want to use the RNA velocity tool to investigate the effect the gene perturbation. My expectation is that we can observe the changes of cell fate of some cell types.
   Thank you very much!
   Looking forward to your response!

Peiefeng

**Comment by VolkerBergen** [comment]
Following the conservation in https://github.com/theislab/scvelo/issues/142 you can apply a DE test on velocity expression to then quantify e.g. scaled difference in expression for DE genes that characterize the temporal dynamics in a particular group. Further gene likelihoods obtained from the dynamical model can be used to assess their significance w.r.t. splicing dynamics.

For further research, it'd be exciting to have a model (e.g. VAE) that learns to generalize the response in stimulation in terms of splicing dynamics / velocities.

**Comment by jipeifeng** [comment]
Thank you for the response! I'll have a try!
