### ISSUE TITLE
Gene Names

### ISSUE THREAD

**Issue by iaconogi** [theislab/scvelo#138]
Dear Volker,
I have transferred from R to python my data and now I have an AnnData object which works for all the analysis and plots.

AnnData object with n_obs × n_vars = 5649 × 31053
    obs: 'fake', 'clusters', 'initial_size_unspliced', 'initial_size_spliced', 'initial_size', 'n_counts', 'velocity_self_transition'
    var: 'velocity_gamma', 'velocity_r2', 'velocity_genes'
    uns: 'pca', 'neighbors', 'velocity_settings', 'velocity_graph', 'velocity_graph_neg', 'clusters_colors'
    obsm: 'X_umap', 'X_pca', 'velocity_umap'
    varm: 'PCs'
    layers: 'spliced', 'unspliced', 'ambiguous', 'Ms', 'Mu', 'velocity', 'variance_velocity'

However when I try to plot specific gene names I get the error "ValueError: color key is invalid! pass valid observation annotation or a gene name".
I do not know how to check if AnnData has any gene names or during my transferring I lost them.

To load the data from R I run these lines:

import anndata as ad
import pandas as pd
import os
import scvelo as scv

os.chdir('/scratch/devel/giacono/scvelo')

sdata = ad.read_mtx("combined.emat.mtx")
sdata.layers['spliced'] = sdata.X
ndata = ad.read_mtx("combined.nmat.mtx")
sdata.layers['unspliced'] = ndata.X
mdata = ad.read_mtx("combined.smat.mtx")
sdata.layers['ambiguous'] = mdata.X

pd_obs = pd.read_csv("combined.obs.csv")
pd_obsm = pd.read_csv("combined.obsm.csv")
sdata.obs = pd_obs
sdata.obsm["X_umap"] = pd_obsm.values
sdata
AnnData object with n_obs × n_vars = 17829 × 14152 
    obs: 'orig.ident', 'clusters'
    obsm: 'X_umap'
    layers: 'spliced', 'unspliced', 'ambiguous'

**Comment by iaconogi** [comment]
Never mind, I solved the problem on my own.
Best

**Comment by JBreunig** [comment]
How did you end up solving this?
