### ISSUE TITLE
Plotting expression in log

### ISSUE THREAD

**Issue by iaconogi** [theislab/scvelo#139]
Dear Volker,
I am plotting my data with

scv.pl.velocity_embedding_stream(sdata,save='plot.png',basis='umap',color='Cd4',layer=['spliced'])

Is the color on the plot in log-scale? It does not seem so. Is it possible to plot in log scale?
Best
Giovanni

**Comment by VolkerBergen** [comment]
Hi Giovanni,
the color is not in log-scale. You can plot it manually with log or any transformation via 
```
log_color = np.log1p(adata.obs_vector('Cd4', layer='spliced'))
scv.pl.velocity_embedding_stream(sdata, color=log_color)
```

**Comment by VolkerBergen** [comment]
This can now be done with `scv.pl.velocity_embedding_stream(sdata, color='Cd4', layer='log1p(spliced)')`.
