### ISSUE TITLE
clean up object

### ISSUE THREAD

**Issue by wangjiawen2013** [theislab/scvelo#14]
Dear,
I cannot find any documents about the parameter cleanup in sc.read(), so I don't know whether I should set cleanup=True or cleanup=False, could you explain this parameter for me ?

**Comment by VolkerBergen** [comment]
Very good that you mention it. I'll have to include it in the documentation.

cleanup simply removes all attributes that store only one unique value. Say, you have `adata.obs['age(days)']` with all elements being '12'. That column would be removed from your object as it doesn't provide any valuable information about an individual observation. It is just for memory considerations and does not affect any downstream analysis.
