### ISSUE TITLE
Error running pancreatic endocrinogenesis example

### ISSUE THREAD

**Issue by ilyakorsunsky** [theislab/scvelo#140]
I am having trouble plotting individual gene dynamics after computing velocity with the dynamical mode. I followed the pancreatic endocrinogenesis tutorial through. I am using scanpy v1.4.3 and scVelo v0.1.24. The offending command and error message are reproduced below. 

Really wonderful concept, method, and implementation! 

scv.pl.scatter(adata, basis=top_genes[:10], legend_loc='none',
               size=80, frameon=False, ncols=5, fontsize=20)

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-25-d80b816da3a2> in <module>
      1 scv.pl.scatter(adata, basis=top_genes[:10], legend_loc='none',
----> 2                size=80, frameon=False, ncols=5, fontsize=20)

~/anaconda3/lib/python3.7/site-packages/scvelo/plotting/scatter.py in scatter(adata, x, y, basis, vkey, color, use_raw, layer, color_map, colorbar, palette, size, alpha, linewidth, perc, sort_order, groups, components, projection, legend_loc, legend_fontsize, legend_fontweight, right_margin, left_margin, xlabel, ylabel, title, fontsize, figsize, xlim, ylim, show_density, show_assignments, show_linear_fit, show_polyfit, rug, n_convolve, smooth, rescale_color, dpi, frameon, show, save, ax, zorder, ncols, **kwargs)
     76                                   basis=bases[i] if len(bases) > 1 else basis,
     77                                   title=title[i] if isinstance(title, (list, tuple)) else title,
---> 78                                   **scatter_kwargs, **ext_kwargs, **kwargs))
     79         savefig_or_show(dpi=dpi, save=save, show=show)
     80         if not show: return ax

~/anaconda3/lib/python3.7/site-packages/scvelo/plotting/scatter.py in scatter(adata, x, y, basis, vkey, color, use_raw, layer, color_map, colorbar, palette, size, alpha, linewidth, perc, sort_order, groups, components, projection, legend_loc, legend_fontsize, legend_fontweight, right_margin, left_margin, xlabel, ylabel, title, fontsize, figsize, xlim, ylim, show_density, show_assignments, show_linear_fit, show_polyfit, rug, n_convolve, smooth, rescale_color, dpi, frameon, show, save, ax, zorder, ncols, **kwargs)
    216                         lines.append(line)
    217                     if 'fit_alpha' in adata.var.keys() and (vkey is None or 'dynamics' in vkey):
--> 218                         line, fit = show_full_dynamics(adata, basis, 'fit', use_raw, linewidth, show_assignments=show_assignments, ax=ax)
    219                         fits.append(fit)
    220                         lines.append(line)

~/anaconda3/lib/python3.7/site-packages/scvelo/plotting/simulation.py in show_full_dynamics(adata, basis, key, use_raw, linewidth, show_assignments, ax)
     55 
     56     if key is not 'true':
---> 57         _, ut, st = compute_dynamics(adata, basis, key, extrapolate=False, sort=False, t=show_assignments)
     58         if show_assignments is not 'only':
     59             ax.scatter(st, ut, color=color, s=1)

~/anaconda3/lib/python3.7/site-packages/scvelo/plotting/simulation.py in compute_dynamics(adata, basis, key, extrapolate, sort, t_, t)
     25     idx = np.where(adata.var_names == basis)[0][0] if isinstance(basis, str) else basis
     26     key = 'fit' if key + '_gamma' not in adata.var_keys() else key
---> 27     alpha, beta, gamma, scaling, t_ = get_vars(adata[:, idx], key=key)
     28 
     29     if 'fit_u0' in adata.var.keys():

~/anaconda3/lib/python3.7/site-packages/anndata/base.py in __getitem__(self, index)
   1291     def __getitem__(self, index: Index) -> 'AnnData':
   1292         """Returns a sliced view of the object."""
-> 1293         return self._getitem_view(index)
   1294 
   1295     def _getitem_view(self, index: Index) -> 'AnnData':

~/anaconda3/lib/python3.7/site-packages/anndata/base.py in _getitem_view(self, index)
   1294 
   1295     def _getitem_view(self, index: Index) -> 'AnnData':
-> 1296         oidx, vidx = self._normalize_indices(index)
   1297         return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
   1298 

~/anaconda3/lib/python3.7/site-packages/anndata/base.py in _normalize_indices(self, index)
   1271         obs, var = super()._unpack_index(index)
   1272         obs = _normalize_index(obs, self.obs_names)
-> 1273         var = _normalize_index(var, self.var_names)
   1274         return obs, var
   1275 

~/anaconda3/lib/python3.7/site-packages/anndata/base.py in _normalize_index(index, names)
    266     else:
    267         raise IndexError('Unknown index {!r} of type {}'
--> 268                          .format(index, type(index)))
    269 
    270 

IndexError: Unknown index 1065 of type <class 'numpy.int64'>

**Comment by VolkerBergen** [comment]
You seem to be working on an older version of anndata which is raising the error here. 

Could you send me your version number of anndata, e.g. via `scv.logging.print_versions()` and try rerun with anndata updated, `pip install -U anndata`.

**Comment by ilyakorsunsky** [comment]
That was it! I had anndata 0.6.18 and updating it bumped it up to 0.6.22. 

Thanks @VolkerBergen!
