### ISSUE TITLE
Compare two different conditions

### ISSUE THREAD

**Issue by ChaDuss** [theislab/scvelo#142]
Hello scvelo team, thank you for your nice tool.

How would you process to compare two different conditions like normal vs pathological samples ?
Is it right to run scvelo on the two samples separately and then compare  the two results ?
Is it possible to run velocyto on the merge samples ?

Thank you for your advices.

Bests.

Charles

**Comment by VolkerBergen** [comment]
Thanks. If you expect the samples to have distinct dynamic behavior (perhaps also resulting in differential kinetics), it'd be important to run velocity estimation separately.

You can then merge the samples to apply a DE test on velocity expression (e.g. using t-test) between two groups / conditions to identify genes sets that characterize the temporal dynamics in a particular group. That can be done using `tl.rank_velocity_genes`.

**Comment by Flu09** [comment]
How after merging the  different conditions how to find the top spliced or the top genes of importance for each celltype in each condition? as comparing conditions would result into velocity genes for each condition regardless of the celltype. I hope you reply. Thanks.
