### ISSUE TITLE
Coloring phase portait with velocities

### ISSUE THREAD

**Issue by juhaa** [theislab/scvelo#147]
Hi,

I've noticed that when using `scv.pl.velocity` with `color='velocity'`, the colorbar scales in the phase portrait and the embedding with velocity colored do not seem match.
Example:
![image](https://user-images.githubusercontent.com/10233157/73522563-5d611e00-4411-11ea-9f56-7e4c5fbd11a8.png)
Further digging into this, I found out that the parameter `perc` is not passed on when creating the phase plot:
https://github.com/theislab/scvelo/blob/f389c38c38251accaa6bbdb42a0dd2eb7493f979/scvelo/plotting/velocity.py#L110-L114
So, if I understood correctly, setting `perc=None` would give me the same scale on both plots, but still the colorbars/ticks don't match:
![image](https://user-images.githubusercontent.com/10233157/73523599-e8dbae80-4413-11ea-9817-791f63c1d7ac.png)

I would appreciate if this could be double checked and perhaps fixed so that things are consistent between the plots.

BR,
Juha

**Comment by VolkerBergen** [comment]
Thanks. Missing attributes (perc and color_map) are now passed to scatter as well.

**Comment by juhaa** [comment]
Thank you! Confirmed fixed.

![image](https://user-images.githubusercontent.com/10233157/73646864-f8acfa00-4682-11ea-9ee7-b2a250eb7664.png)
![image](https://user-images.githubusercontent.com/10233157/73646879-03678f00-4683-11ea-8ddd-08f48ba5d57d.png)
