### ISSUE TITLE
Bug in recurse neighbors

### ISSUE THREAD

**Issue by Marius1311** [theislab/scvelo#149]
I think there is a bug in `get_iterative_indices`. Let's consider the following example of a simple, undirected KNN graph given by matrix A,  where
```python
A = np.array([[0, 1, 0, 1, 1, 0, 0, 0],
             [1, 0, 1, 0, 1, 1, 1, 0],
             [0, 1, 0, 0, 0, 0, 1, 1],
             [1, 0 ,0, 0, 1, 1, 0, 0],
              [1, 1, 0, 1, 0, 0, 0, 0],
              [0, 1, 0, 1, 0, 0, 0, 1],
              [0, 1, 1, 0, 0, 0, 0, 1],
              [0, 0, 1, 0, 0, 1, 1, 0]])
```
This graph looks as follows:
![image](https://user-images.githubusercontent.com/24494650/73570928-b068be80-446d-11ea-92b6-219c5fc5d415.png)

If I convert this to a sparse matrix, I can run `get_indices_from_csr` to get the indices:
```python
array([[ 1.,  3.,  4., nan, nan],
       [ 0.,  2.,  4.,  5.,  6.],
       [ 1.,  6.,  7., nan, nan],
       [ 0.,  4.,  5., nan, nan],
       [ 0.,  1.,  3., nan, nan],
       [ 1.,  3.,  7., nan, nan],
       [ 1.,  2.,  7., nan, nan],
       [ 2.,  5.,  6., nan, nan]])
```
 Now, let's run `get_iterative_indices` for node `1`:
`get_iterative_indices(ixs, 1)`. 
This returns `array([0, 1, 2, 3, 4, 6, 7])`.

What happened to node number 5?

**Comment by VolkerBergen** [comment]
Thanks for spotting this. It only accounts for indirect neighbors. Direct neighbors are accounted for only implicitly (not explicitly) via indirect neighbors. In practice (endocrinogenesis example) this leaves out around 0.1% of cell-to-cell affinities (such as the node 5 in your example), which does not affect any results for velocity projection. However, I will modify accordingly s.t. direct neighbors are certainly included as well.

**Comment by Marius1311** [comment]
I think the easiest way to fix this would be to use idea I pointed out in [this issue](https://github.com/theislab/cellrank/issues/75) - that should also improve efficiency.

**Comment by VolkerBergen** [comment]
It's fixed with the latest commit. Obtaining 'recursive' indices is not an efficiency bottleneck. Moreover, the current implementation is even more efficient than matrix multiplication, which you can test with

```
indices = scv.utils.get_indices(dist=adata.uns['neighbors']['connectivities'])[0]
for i in range(adata.n_obs):
    idx = scv.utils.get_iterative_indices(indices, i, n_recurse_neighbors=2)
```
vs. 
```
A = adata.uns['neighbors']['connectivities'].dot(adata.uns['neighbors']['connectivities']) > 0
for i in range(adata.n_obs):
    idx = A[i].indices
```

**Comment by Marius1311** [comment]
Tested it, agreed about the efficiency aspect!
