### ISSUE TITLE
Add custom colour palette

### ISSUE THREAD

**Issue by MikeDMorgan** [theislab/scvelo#153]
Thanks for developing and maintaining this package - somewhat related to  #150, would it be possible for users to provide their own custom mapping to colours? For instance, I have a set of annotations and a custom colour palette mapping a single colour to each label. For consistency across figure panels these should be the same. However, currently it is not possible to alter the default colour palette for qualitative variables.

Thanks.

**Comment by VolkerBergen** [comment]
That's exactly the purpose of the palette attribute. Given a categorical variable stored e.g. in `adata.obs["annotations"]`, you can simply pass a palette via
`scv.pl.scatter(adata, color="annotations", palette=["color1", "color 2", "color 3" ])`.

**Comment by MikeDMorgan** [comment]
Any value passed to the `palette` argument is currently ignored in the stable release however. Furthermore, a list structure does not guarantee that the correct colour is mapped to the appropriate label; a `dict` would be a natural way to allow a consistent mapping in the case either the labels or colour definitions ordering changes. Could I also suggest making this explicitly clear in the documentation - this is most certainly not the case at the moment. Thx.

**Comment by VolkerBergen** [comment]
It would need to be ordered according to `adata.obs["annotations"].cat.categories`. Allowing palette to be a dict is a great idea. Would you like to do a PR? Otherwise I'd add that to the list of todos.

**Comment by MikeDMorgan** [comment]
I need to familiarise myself with the code base - but I'm happy to find a fix using a dict.

**Comment by VolkerBergen** [comment]
Was essentially a one-liner to allow a dict for palette. Let me know if it works for you.

**Comment by VolkerBergen** [comment]
A `dict` can now be passed to map colors to categories. 
`scv.pl.scatter(adata, color="clusters", palette={'cluster1: 'color1', 'cluster2': 'color2', 'cluster3': 'color3'})`.
