### ISSUE TITLE
Explanation of genes associated with latent time

### ISSUE THREAD

**Issue by fbrundu** [theislab/scvelo#155]
Hi @VolkerBergen,
I am following the tutorial on Pancreatic endocrinogenesis.

I am interested in the plot of the top genes associated with latent time. The code used to generate the gene heatmap is the following.

```python
top_genes = adata.var_names[adata.var.fit_likelihood.argsort()[::-1]][:300]
scv.pl.heatmap(adata, var_names=top_genes, tkey='latent_time', n_convolve=100, col_color='clusters')
```

I was looking for an explanation of how these genes are computed but I couldn't find it. Can you elaborate/point me to some documentation of this plot? I understand the main aim of having this plot but I would like to understand the details.

Thanks

**Comment by VolkerBergen** [comment]
Hi @fbrundu,
pardon the delayed response. These genes are the top 300 likelihood genes, i.e. they yield a good phase trajectory fit, thus constitute putative driver genes. The heatmap internally additionally orders those genes by when they are active during the developmental process. By looking at the cascades you may also find which genes are relevant at which developmental stages. Can you follow the explanation? Let me know if there are any further queries.

**Comment by fbrundu** [comment]
Hi @VolkerBergen . Thanks, I have a minor follow-up question: in the heatmap do you look for simple estimates to order genes (i.e. you order depending on max value)?

Thanks

**Comment by VolkerBergen** [comment]
Screening through the issues I found your open question - my apologies.
As you mentioned correctly, the genes are simply ordered by max expression.

**Comment by fbrundu** [comment]
No worries, thanks!
