### ISSUE TITLE
Using latent time to infer switching points

### ISSUE THREAD

**Issue by riguyer** [theislab/scvelo#159]
### 
Apologies if this is too simple of a question or if it is addressed elsewhere, but I have not found a straightforward explanation. How does one use the functions of scvelo and/or scanpy to identify cell fate switching points, and then to plot inferred trajectories? I cannot find code or a good tutorial for generating images such as this, which is Fig 3e in the bioRxiv preprint. 
![Fig3e](https://user-images.githubusercontent.com/15082058/74964209-0aabce00-53e1-11ea-930f-3d278dc89f38.png)
It would be very useful to order cells and assess for driver genes along each of the inferred trajectories, rather than simply along latent time or pseudotime within the whole population.

Many thanks for any help!

**Comment by VolkerBergen** [comment]
Hi,
the code snippets to produce that figure should be somewhere in the reproducibility notebooks. That together with identification of driver genes in regions of interest will be made much more accessible soon. It is already possible, yet not straightforward to obtain. Will get back to you soon.
The "trajectories" are simple splines fit between cell cycle exit to the end points, nothing fancy. Also to that end, colleagues are currently working on some probabilistic trajectory inference method based on scvelo. Should be out in a couple weeks. Then you should be able to address your queries.

**Comment by riguyer** [comment]
Thanks a lot for the reply. I'll look out for this functionality to be added. It will be very useful.
