### ISSUE TITLE
removal batch effects

### ISSUE THREAD

**Issue by wangjiawen2013** [theislab/scvelo#163]
Dear,
Thera always are some batch effects among different single cell experiments. We need to remove batch effects with some tools like COMBAT, MNN, CCA and so on. Is scvelo robust to batch effects or we need to remove batch effects with other tools ?

**Comment by VolkerBergen** [comment]
Hi,
there is currently no clear consensus on how to best deal with batch effects in the context of RNA velocity. If you observe evident tech. variation, you'd need to correct for that, e.g. via `scanpy.external.pp.bbknn`, also combat, mnn and cca may be suitable, which yields a corrected neighbor graph (usually not corrected high dim. expression). For velocity analysis I'd just try running velocity estimation, check upon the top likelihood genes, whether you observe any gene-specific tech. variation. If that is so, you'd need to fit each batch separately. I hope, there will be a more systematic strategy in the near future.

**Comment by wangjiawen2013** [comment]
A start on correcting for batch effects in RNA velocity.
https://www.hansenlab.org/velocity_batch
hope it helps

**Comment by wangjiawen2013** [comment]
Monocle3 tries to remove batch effects using MNN. https://cole-trapnell-lab.github.io/monocle3/docs/clustering/#batch-effects
But I don't think it works well for both monocle and RNA velocity, because it's hard to tell batch effects from true biological variation. In this case, it's better to call it "data integration" rather than "batch effects removal".

**Comment by zhanglab2008** [comment]
> Monocle3 tries to remove batch effects using MNN. https://cole-trapnell-lab.github.io/monocle3/docs/clustering/#batch-effects
> But I don't think it works well for both monocle and RNA velocity, because it's hard to tell batch effects from true biological variation. In this case, it's better to call it "data integration" rather than "batch effects removal".

@wangjiawen2013  I totally agree. The data integration tools seem to overcorrect the batch effects. I have tried applying mnn, cca, liger on my dataset, it works very well to correct the batch effect but the biological variance is also being corrected. For example, cells from healthy and disease samples are totally overlaid, which makes it impossible to do velocity prediction or pseudo time trajectory analysis. desc is designed to overcome this problem. https://www.nature.com/articles/s41467-020-15851-3
But desc only works for me sometimes. I think it still needs a lot of work to address the batch effect issue.

**Comment by ajs1029** [comment]
@zhanglab2008 

I've used DESC to correct for batch effect in clustering. But as far as I'm aware, DESC doesn't return a corrected matrix, which I believe is necessary for velocity prediction and differential gene expression analysis (?). 

Have you found a way around this using DESC? If so, could you please explain your process?
