### ISSUE TITLE
Integrating imputation and velocity?

### ISSUE THREAD

**Issue by smgroves** [theislab/scvelo#167]
I am wondering what the best way to integrate imputation, such as with MAGIC, with calculation of RNA velocity. I know scanpy has an implementation of MAGIC that works well on AnnData objects, but I'm not sure if it would work (or is ill-advised) to first impute on both spliced and unspliced counts layers and then calculate velocity on this data. Any suggestions?

**Comment by VolkerBergen** [comment]
Generally yes. If you do a graph-based method, you'd need to ensure to use the same graph on both count matrices. In knn-imputation, for instance, this is straightforward. I haven't read on MAGIC in depth, but I believe it is quite similar to the moment computation. I just run it on the dentate gyrus and got the following result, when comparing it against moments on Tmsb10 as an example. 
![image](https://user-images.githubusercontent.com/31883718/75927817-665c6980-5e6d-11ea-9839-3e2571f72155.png)

After all, I'm not sure, whether any fancy imputation method would add much for velocity estimation. Conversely, I believe using unspliced-spliced relation could considerably improve imputation methods.

**Comment by smgroves** [comment]
Great, thanks. To make sure the same graph is used for both spliced and unspliced counts, would I need to run MAGIC on X and then rescale spliced and unspliced, or is running MAGIC on each layer separately sufficient?

**Comment by VolkerBergen** [comment]
It's not that easy. You'd have to adjust their code or try to get the graph returned, when computing on spliced or X, then use that graph to apply imputation likewise on unspliced. Maybe ask [here](https://github.com/KrishnaswamyLab/MAGIC), whether that is easily doable.

**Comment by smgroves** [comment]
okay thank you!
