### ISSUE TITLE
recovering all genes for subsets

### ISSUE THREAD

**Issue by notimenocall** [theislab/scvelo#168]
Hi,
Thanks for the great package!
I would like to perform scvelo on a subset. To do that, I clustered my data with highly variable genes and subset the cluster of interest. At this point, the vars only contain the hvgs, and so I usually do the following to recover all the genes for reclustering:
`T_cells = adata[adata.obs.louvain.str.contains('T cells')]
T_cells=sc.AnnData(T_cells.raw.X,obs=T_cells.obs,var=T_cells.raw.var)`
However, this approach does not recover the 'layers' (spliced/unspliced). Is there an easy way to do this that I missed?
Thanks again!

**Comment by VolkerBergen** [comment]
Why not just `T_cells = adata[adata.obs.louvain.str.contains('T cells')].copy()` without the second command. Or is there a reason for creating a new anndata?

**Comment by notimenocall** [comment]
Thanks for your quick response!
Because the adata only contains hvg and I was trying to recover all the genes with the 2nd line from the T_cells.raw, so I can re-select hvg again just from the T cells cluster. However, this approach does not recover the 'layers' (spliced/unspliced).

**Comment by VolkerBergen** [comment]
`.raw` has no layers, because it is only meant to store `.X` for DE testing, so the layers are not restorable anymore for all genes at this point. You would have to re-read the data and then subset to the T_cells. The pre-computed (on hvg) cluster annotations, embeddings etc. can then be load into the anndata object.

**Comment by notimenocall** [comment]
Okay. It makes sense to me. I just want to make sure I didn't miss any magical function to could accomplish this. Thank you very much again!
