### ISSUE TITLE
invalid value encountered in double_scalars

### ISSUE THREAD

**Issue by wangjiawen2013** [theislab/scvelo#17]
Dear,
when I run scv.tl.velocity_embedding(adata,basis='draw_graph_fa') and scv.pl.velocity_embedding_grid(adata,legend_loc='on data',size=10,basis='draw_graph_fa'), an error occurs:
invalid value encountered in double_scalars, there are no velocity arrows on the FA plot. But when I use umap instead, everything is OK.

**Comment by stefanpeidli** [comment]
Hi,
it seems like I can not replicate that Error.
Could you please kindly copy your full error code here if you still have that issue?

**Comment by wangjiawen2013** [comment]
here it is:
scv.pl.velocity_embedding_grid(adata,legend_loc='on data',size=10,basis='draw_graph_fa')
/home/wangjw/bin/miniconda3/lib/python3.6/site-packages/matplotlib/quiver.py:649: RuntimeWarning: Mean of empty slice. amean = a.mean()
/home/wangjw/bin/miniconda3/lib/python3.6/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars ret = ret.dtype.type(ret / rcount)

**Comment by wangjiawen2013** [comment]
I don't know about the parameters "dashed_edges" and "Solid_edges" in function sc.pl.paga. 
Does the solid edge means the pair of nodes share at least two triangles in the summary graph, while the dashed line shows they share at most one triangle in the paga abstract graph?

**Comment by stefanpeidli** [comment]
Thanks a lot.
It seems like the X_embedding (in your case X_draw_graph_fa) used for the plotting contains empty or NaN values. This indicates that the computation of the embedding was erroneous.
What line of code did you run to compute the embedding? Which arguments did you use?

'solid_edges' can be a key in adata .uns[‘paga’] reffering to a matrix to be used for deciding if a line should be solid or not. So for example if you use the default 'paga_connectivity' and default threshold=0.01, a line will be drawn as solid if the corresponding paga_connectivity value of that connection is higher than that treshold. Same goes for the 'dashed_edges'. The information from the abstract graph is visualized by the colors of the lines.

**Comment by wangjiawen2013** [comment]
I find that both solid and dashed lines are decreasing with the increasing threshold, So I am still confused about. In my opinion, the sum of solid and dashed lines should keep the same, no matter what the threshold is

**Comment by wangjiawen2013** [comment]
The embedding code is: scv.tl.velocity_embedding(adata,basis='draw_graph_fa')

**Comment by wangjiawen2013** [comment]
Now I know the reason. I should use "adata.obs['Clusters'] = adata.obs['louvain']" first to assign a cluster to each cell, then run "scv.tl.velocity_embedding(adata,basis='draw_graph_fa')", now everything is OK!

**Comment by stefanpeidli** [comment]
Good point! I misunderstood it, sorry.
The same threshold is used for both the solid and the dashed lines. A connection with a paga connectivity value below that will not be drawn at all. So **increasing the threshold will result in less lines overall**. The arguments for solid/dashed lines determine the partition of the connectivities to be drawn solid/dashed. By default, all lines are drawn solid (except for those below the threshold).

As for your other problem:
Could you please run the lines of code:
```
print((adata.obsm['X_draw_graph_fa'] == 0).any())
print((adata.obsm['X_draw_graph_fa'] != adata.obsm['X_draw_graph_fa']).any())
```
They should both be False. If not, X_draw_graph_fa contains "bad" values.

**Comment by wangjiawen2013** [comment]
I have tried these code, both the result are False.
print((adata.obsm['X_draw_graph_fa'] == 0).any())
print((adata.obsm['X_draw_graph_fa'] != adata.obsm['X_draw_graph_fa']).any())

**Comment by wangjiawen2013** [comment]
The solid lines have arrows, but dashed lines have no arrows. So what's the difference ? In which situation the lines will be solid and in which situation the lines will be dashed ? Sorry I am not familiar with graph theory and I cannot find enough information to figure it out.

**Comment by wangjiawen2013** [comment]
I have exported adata.obsm['X_draw_graph_fa'] to csv. All the values are good. And, I have tried to subset the data, use less cells (5000 cells, 20000 cells, 40000 cells). All these attempts are failed. perhaps draw_graph_fa is not compatible well with RNA velocity (while Umap works well).

In /miniconda3/lib/python3.6/site-packages/matplotlib/quiver.py line 649:
644         if self.scale is None:
 645             sn = max(10, math.sqrt(self.N))
 646             if self.Umask is not ma.nomask:
 647                 amean = a[~self.Umask].mean()
 648             else:
 649                 amean = a.mean()
Perhaps the reason is that the length of a is 0. An empty numpy array was passed to mean(). However, I don't know why umap works well. Could you check quiver.py ?

By the way, when using K-means algorithm, the same things could be happen ( empty array) vary occasionally. It is a reported bug.

**Comment by stefanpeidli** [comment]
This could be happening due to our rather "weird" way of utilizing matplotlibs internal automatic quiver scaling:
`V_grid /= 3 * quiver_autoscale(X_grid[:, 0], X_grid[:, 1], V_grid[:, 0], V_grid[:, 1])`
Usually our quiver_autoscale gives reasonable values for Umap values. But as you mentioned, `X_draw_graph_fa ` has bigger values possibly resulting in a value of 0, NaN or inf in our quiver_autoscale function, which in turn leads to empty or NaN values in `V_grid`.
As a provisional workaround you could either rescale `X_draw_graph_fa ` to lower values or use u_map instead.
We will catch that bug, thanks a lot for helping!

**Comment by wangjiawen2013** [comment]
I cannot recreate this bug today. Now scv.pl.velocity_embedding_grid(adata,legend_loc='on data',size=10,basis='draw_graph_fa') works well. I don't know what happened the day before yesterday ( when I report this issue). The only thing that have been changed is that I upgrade my matplotlib. However, it's the best ends, nothing troubles you and me now!

**Comment by wangjiawen2013** [comment]
Is it possible that two distinct clusters far away from each on FA(or Umap) plot while have a strong directed link on paga graph ?

**Comment by stefanpeidli** [comment]
That's good news. Still, I get the error if I artificially scale up the embedded velocities before plotting
`adata.obsm['X_draw_graph_fa']*=1000`
This needs to be fixed, as some `draw_graph` emdeddings might actually lead to such big values that crash the quiver plot.

As for the paga: In theory this should not happen. Paga is constructed in such a way that tries to minimize the occurence of assigning high connectivities between clusters far away in the embedding space. For more details on this I can highly recommend reading the chapter "Faithfulness of embeddings to global topology" in the [preprint paga paper](https://rawgit.com/falexwolf/paga_paper/master/paga.pdf).

**Comment by wangjiawen2013** [comment]
I don't know much about the difference between sc.tl.paga(adata) and sc.tl.paga(adata, use_rna_velocity=True). Is it necessary to run sc.tl.paga(adata, groups='clusters') first before sc.tl.paga(adata, groups='clusters', use_rna_velocity=True) ? I find that the results of sc.pl.paga_compare (adata) and sc.pl.paga_compare (adata, transitions='transitions_confidence') differ a lot. Some directed links would appear between clusters far away in the embedding space in the results of sc.pl.paga_compare (adata, transitions='transitions_confidence'), while there is no links between these clusters in the results of sc.pl.paga_compare (adata). It seems that transitions='transitions_confidence' replace the original thick and thin lines among the clusters with totally different arrows.

here is the results of sc.pl.paga_compare(adata):
![2](https://user-images.githubusercontent.com/29703450/48265295-21861580-e467-11e8-83c6-320754cc5c0d.png)
and here is the results of sc.pl.paga_compare(adata,transitions='transitions_confidence')
![1](https://user-images.githubusercontent.com/29703450/48265330-35ca1280-e467-11e8-942c-b0e5ab312b1a.png)

Notice the relationship between cluster5 and cluster0. They are totally different.

**Comment by wangjiawen2013** [comment]
> That is weird. I am sorry to bother you so much with it, but could you please also check if `adata.obsm['X_draw_graph_fa']` is empty?
> You could also try and run `sc.tl.draw_graph(adata)` (after importing scanpy.api as sc) to recompute X_draw_graph_fa.
> 
> As for the arrows and lines: Unfortunately I am not an expert in scanpy. I will ask someone who is one and understands the transitions better, if you like.

I think dashed lines represent the link in sc.pl.paga(adata), while arrows represent the link in sc.pl.paga(adata, transitions='transitions_confidence'). If they are overlapped, then only the arrows would be displayed. In a word, they show the similarities and difference between sc.pl.paga(adata) and sc.pl.paga(adata, transitions='transitions_confidence')
