### ISSUE TITLE
X_umap not found

### ISSUE THREAD

**Issue by haoyang-insitro** [theislab/scvelo#170]
Dear scvelo authors,

Thank you for this great software. I was trying to apply scvelo on a scRNA-data of my own using the following code:

```
    adata = scv.read('data.loom', cache=False)
    scv.utils.show_proportions(adata)
    scv.pp.filter_and_normalize(adata, min_shared_counts=20, n_top_genes=2000)
    scv.pp.moments(adata, n_pcs=25, n_neighbors=30, method='umap')
    scv.tl.velocity(adata)
    scv.tl.velocity_graph(adata)
    
    ax = scv.pl.velocity_embedding(adata, basis='pca', color=['Clusters'], show=False)
    ax.legend(bbox_to_anchor=(1.1, 1.05))
    plt.show()
```

However, I can only use `basis='pca'` in the plotting step, not `basis=umap`. And I found `X_umap` doesn't exist in my anndata object. I wonder if you could advise what I should do to use `basic='umap'` when plotting? The toydata sets seem to already have `X_umap` in the anndata object.

**Comment by VolkerBergen** [comment]
On exemplary data, we have already pre-computed umap coordinates. On your data, you would have to compute it via `scv.tl.umap` before running `velocity_embedding`.

**Comment by haoyang-insitro** [comment]
@VolkerBergen thanks! To clarify, I should call `scv.tl.umap` **after** I have calculated velocity and velocity graph? I tried and the plot seems quite disjoint so wanted to make sure

**Comment by VolkerBergen** [comment]
It simply computes the embedding coordinates and is completely independent of the modules `velocity` and `velocity_graph`. So you can call it in any order you like. Disjoint clusters may suggest that you have multiple distinct clusters without any dynamic flow between those. You can play around with the `min_dist` and `spread` parameters, see the [UMAP docs](https://umap-learn.readthedocs.io/en/latest/parameters.html) for more details.
