### ISSUE TITLE
Using imputed expression for velocity estimation?

### ISSUE THREAD

**Issue by chansigit** [theislab/scvelo#175]
As my data suffers from severe dropouts, I used imputed data for dimensionality reduction /clustering and got fairly good results. 
I stored the imputed value in the adata.layer["imputed"]  

Can I use the imputed value for velocity estimation instead of the heavily noised raw expressions.

**Comment by VolkerBergen** [comment]
Depends on what method you use for imputation. It requires the same transformation of the data on both spliced and unspliced, which is not feasible with all existing methods. Running e.g. @gokceneraslan's DCA could be doable and would be worth a try. 

However, scvelo internally obtains velocities from first- and second-order moments (essentially means and uncentered variances across nearest neighboring cells), which can be regarded as a simple knn-imputation.

If you want to try your imputation method, you can store the imputed values of spliced and unspliced in `.layers['Ms']` and `.layers['Mu']`, respectively, and then go ahead with computing `tl.velocity`.
