### ISSUE TITLE
why my adata.obs including Clusters, _X and _Y ?

### ISSUE THREAD

**Issue by Jenny-Jason** [theislab/scvelo#176]
Hi, Thank you for creating scvelo. That is a very great tool. 

I am a novice for single cell analysis. So my problem may be ridiculous. But it really perplexed me.

I ran Cellranger count to get matrix and I used velocyto to align. And finally, I got a .loom
file. I checked this file and found out there  are columns such Clusters, _X ,_Y in my adata.obs.

I feel puzzled. I didn't do cluster and why there are Clusters, _X, _Y ?

My code is displayed as following:

`houruiyan@GPU:~/10genomic$ nohup cellranger count --id=run_count_1kpbmcs --fastqs=./pbmc_1k_v3_fastqs --sample=pbmc_1k_v3 --transcriptome=./refdata-cellranger-GRCh38-3.0.0 &
`
`(velocyto) houruiyan@GPU:~/10genomic$ nohup velocyto run10x ~/10genomic/run_count_1kpbmcs/  /home/houruiyan/10genomic/Homo_sapiens.GRCh38.93.gtf &
`

**Comment by VolkerBergen** [comment]
Cellranger can optionally produce automated analysis results, see [here](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/analysis). However, since that corresponds e.g. to outdated k-means clustering, I'd ignore these outputs and do all processing from within scvelo/scanpy.

**Comment by Jenny-Jason** [comment]
Thanks very much for your reply! And I am still puzzled about the results. When I delete the Cluster，_X and _Y, I still can get a clustering outcome graph. My codes are displaying as follow:
`adata=sc.read_loom('/home/houruiyan/10genomic/run_count_1kpbmcs/velocyto/newrun_count_1kpbmcs.loom')
del adata.obs['Clusters']
del adata.obs['_X']
del adata.obs['_Y']
print(adata)
scv.pp.filter_and_normalize(adata,min_shared_counts=20,n_top_genes=2000)
scv.tl.velocity_graph(adata)
scv.pl.velocity_embedding_stream(adata)`
Even if I delete the cluster,_X and _Y, I still get the graph. I don't know which step does this work?
![image](https://user-images.githubusercontent.com/56068158/78001619-8a29a700-7368-11ea-9b09-410dd4671ee6.png)

**Comment by VolkerBergen** [comment]
scvelo internally computes PCA, which is needed to obtain the neighbor graph. If no `basis` is specified, it uses whatever is available in the following order (umap, tsne, diffmap, pca). When printing adata, you should also see that `adata.obsm['X_pca']` has been stored.

**Comment by Jenny-Jason** [comment]
Thanks for your reply. And now I have another problem. When I write these code, I found they can not meet my exception.
print(adata.uns['neighbors']['indices'])
print(adata.uns['neighbors']['connectivities'])
I think adata.uns[neighbors']['indices'] reflects that  every cell and which are their neighbors.
And the adata.uns['neighbors']['connectivities'] reflects the weight of every cell and their neighbors that are found above. However, when I look at the data, I found they are not unonimous.
I feel puzzled. Looking forward to your reply!

**Comment by VolkerBergen** [comment]
Distances are unanimous with indices. 

Connectivities are computed with adaptive kernel width as proposed in Haghverdi et al. 2016 (doi:10.1038/nmeth.3971) thus not having a fixed number of connections.

**Comment by Jenny-Jason** [comment]
Oh , thanks for your reply! I still have another question. If I compute velocity in 'steady_state' model, I found all genes have β value. When I compute velocity in 'dynamical' model, I found some genes have γ and β. Some genes don't have these two value. I don't know why ?  How can I get all genes‘ β and γ value.

My code is display as follow:
import scvelo as scv
import pandas as pd

pd.set_option('display.max_rows',None)

adata=scv.read_loom('/home/houruiyan/10genomic/run_count_1kpbmcs/velocyto/newrun_count_1kpbmcs.loom')
del adata.obs['Clusters']
del adata.obs['_X']
del adata.obs['_Y']
# print(adata)

scv.pp.filter_and_normalize(adata,min_shared_counts=10,n_top_genes=3000)
# print(adata)
# print(adata.X)

scv.pp.moments(adata,n_pcs=30,n_neighbors=30)
# print(adata)

scv.tl.recover_dynamics(adata)
scv.tl.velocity(adata,mode='dynamical')
print(adata)
dynamgammadf=adata.var['fit_gamma']
dynamgammadf.to_csv('~/dynamgammadf.csv')
dynambetadf=adata.var['fit_beta']
dynambetadf.to_csv('~/dynambetadf.csv')

**Comment by VolkerBergen** [comment]
From the deterministic/steady-state model, you only obtain one value of gamma denoted as 'velocity_gamma', which is the relative steady-state ratio, not the degradation rate. 

The dynamical model provides many estimates all starting with 'fit_', including the rates of transcription ('fit_alpha'), splicing ('fit_beta') and degradation ('fit_gamma'). 

In the latest source version, you can fetch all anndata keys that start with 'fit_' by path search via `scv.get_df(adata, 'fit_*')`.

Per default, the dynamical only fits phase trajectories for those genes, that can be reliably fitted. You can force it to fit all genes by setting `var_names='all'` in `tl.recover_dynamics`.

**Comment by Jenny-Jason** [comment]
Thank you very much !!!  Thank you for your patient explanation!
