### ISSUE TITLE
Plot without gridlines

### ISSUE THREAD

**Issue by JBreunig** [theislab/scvelo#177]
Great package--currently using it in several projects!

Is there any way to plot velocity_embeddings without grid lines?  I've tried all of the kwargs that seemed to be related (V_grid, frameon, etc.).

Thanks in advance!

**Comment by VolkerBergen** [comment]
Thanks. The grid lines are drawn by matplotlib per default, which is turned off by running `scv.set_figure_params()`, making several changes in the default settings for beautified visualization, as also done in the [tutorial](https://scvelo-notebooks.readthedocs.io/Pancreas.html).

**Comment by JBreunig** [comment]
Perfect, thanks!
