### ISSUE TITLE
Velocity/pseudotime inconsistencies

### ISSUE THREAD

**Issue by alitinet** [theislab/scvelo#180]
Hi Volker,

First, thanks for the package and a lot of interesting discussions here! We are working with a dataset of about 700 cells, after filtering we have about 600 genes, 70 of which are then picked as velocity genes. We calculated diffusion pseudotime for some previous analysis so we compare it to velocity pseudotime and latent time (with the root specified to be the same as in DPT). Also we use diffusion components 1 and 2 for plotting. Both stochastic and dynamical model yield similar results. 
![scvelo_report_custer_skin](https://user-images.githubusercontent.com/20745228/78662819-67037800-78d1-11ea-88c5-99fa15759150.png)
It seems like based on velocity analysis we have cells in clusters 5 that act as root cells. At the same time, velocity pseudotime and latent time look similar to DPT, apart from the direction in velocity pseudotime which as far as I understand is a known issues and we shouldn't worry about it. My question is then, don't these two analyses contradict each other? Shouldn't pseudo times be consistent with the arrows?
![Screenshot 2020-04-07 at 13 13 48](https://user-images.githubusercontent.com/20745228/78662964-a16d1500-78d1-11ea-9d92-3a317f811ce7.png)

**Comment by VolkerBergen** [comment]
I just found your unsettled issue - many apologies for that!

Could you send me / go through the phase portraits as explained in the [tutorials](https://scvelo-notebooks.readthedocs.io/VelocityBasics.html), which help to understand which genes are supporting the inferred directionality.

**Comment by alitinet** [comment]
Hi Volker, no worries, and thank you for your reply! Here's the phase portraits (113 out of 540 genes are velocity genes):
![scvelo__report_skin_velogenes](https://user-images.githubusercontent.com/20745228/81737004-bb34e580-9497-11ea-80e9-dcdffd7670e2.png)
![scvelo__report_skin_phase_profiles](https://user-images.githubusercontent.com/20745228/81737642-b290df00-9498-11ea-942f-df1774dc9b8e.png)

I noticed that a lot of velocity genes are ribosomal genes. Do you think that might be an issue? 

Also I looked at the fraction of unspliced counts as you suggested in #173.
![scvelo__report_skin_fraction](https://user-images.githubusercontent.com/20745228/81737696-cb00f980-9498-11ea-9e28-f134dfac7c6b.png)
It looks like the difference is not that dramatic but it follows exactly the pattern that the velocity pseudotime picks up.

**Comment by VolkerBergen** [comment]
Thanks, the gene-wise dynamics support directionality from 0 to 1 (whatever the coloring is referring to?), which seems consistent across genes (except for the ambiguous dynamics in _UBC_ which got falsely picked as up-reg. while it prob. should have been down-reg.).

As I'm reading your comment "after filtering we have about 600 genes, 70 of which are then picked as velocity genes", I am wondering why are there so few genes, since the signal in the  above-presented genes is fairly strong.. The histogram of `.var['velocity_r2']` and/or `.var['fit_likelihood']` must display most genes with very low values then. 

The dyn. changing fraction in unspliced counts might have an impact indeed, yet the change doesn't seem to be too dramatic.

**Comment by alitinet** [comment]
Indeed, here's the histogram of `.var['fit_likelihood']`. I guess in the end it's not clear whether the directionality of the velocities or the pseudotime is more to telling about the underlying dynamics. But thanks a lot for your comments! I'm closing the question.
![Screenshot 2020-05-19 at 10 42 29](https://user-images.githubusercontent.com/20745228/82305239-ad162600-99bd-11ea-9ba8-84f937069465.png)
