### ISSUE TITLE
choices of matrix input from Seurat

### ISSUE THREAD

**Issue by zehualilab** [theislab/scvelo#181]
Thanks for the great tools! I was able to use scvelo after modifying the as.loom() function in Seurat. Here is my question: My Seurat object has 5 assays: RNA, SCT, spliced, unspliced, ambiguous. If I would like to use SCT assay, then I have these plans:
Plan A: import SCT assay into  .X matrix and spliced, unspliced, ambiguous into layers. (I need to keep only the same features as SCT's in spliced, unspliced and ambiguous assay first)
Plan B: import spliced assay into .X and spliced, unspliced, ambiguous into layers.
Plan C: import spliced assay into .X and unspliced, ambiguous into layers.
I was wondering which is the correct or the best plan of importing matrix input from Seurat? Or are they all wrong?
Thanks so much for any help!

**Comment by zehualilab** [comment]
Oh, btw, it seems that the workflow of Seurat's wrapper function of Velocyto.R suggests Plan B.

**Comment by VolkerBergen** [comment]
Generally, that would be X=spliced, and layers=spliced/unspliced, exactly. For X, you can also use a preprocessed matrix such as sctransform data. Just try to retain as many genes as possible, and not to constrain the analysis to too few features obtained from sct.

**Comment by zehualilab** [comment]
Thanks so much for help!
