### ISSUE TITLE
saving plots

### ISSUE THREAD

**Issue by ForestCA** [theislab/scvelo#183]
Naive thoughts -- I'm wondering: (1) how do I modify the plots (e.g. colors for clusters, aspect ratio, etc), and (2) how do I save the plots?   Perhaps there is a quick answer?

**Comment by VolkerBergen** [comment]
You can set the corresponding parameters, e.g. 
`scv.pl.scatter(adata, color='clusters', figsize=(7,5), save='umap.pdf')`.
See https://scvelo.readthedocs.io/scvelo.pl.scatter.html for details.

**Comment by ForestCA** [comment]
Thanks - got the figure saved now. However, to clarify my other question - I'm not sure how to change the colors assigned to each cluster? I can do this in R with a given set of colors that would correspond to each cluster as defined by the order set with factor() --  just not sure how to implement here?

**Comment by VolkerBergen** [comment]
You can set the colors via `palette`, either passed as dict or as list with the same order as `adata.obs['clusters'].cat.categories`.

**Comment by VolkerBergen** [comment]
Let me know, if that works - otherwise I can provide more details.

**Comment by ForestCA** [comment]
working - thanks!!
