### ISSUE TITLE
Transition Matrix function definition unclear

### ISSUE THREAD

**Issue by gouinK** [theislab/scvelo#184]
Hi all, I really appreciate your package as it has helped speed up my velocity analysis by quite a bit. I use the transition matrix to look at probabilities of specific cells transitioning into others and noticed something about the documentation of the scvelo.tl.transition_matrix function. In the ReadtheDocs site the parameters state that the self_transitions parameter is default set to False, but then when I look at the function definition on Github it seems like the default is set to True. Maybe I am misreading something, but just wanted to bring this up. Thanks!

**Comment by VolkerBergen** [comment]
Thanks for raising this. Corrected the docs (default: `self_transitions=True`).
