### ISSUE TITLE
Neighbors being recalculated with neighbors_to_be_recomputed

### ISSUE THREAD

**Issue by d93espinoza** [theislab/scvelo#187]
Hi!
Thank you for providing this very useful package. I was interested in using the `scv.pp.moments` function with a nearest neighbors graph computed outside of scvelo. The neighbor graph appears to be loaded appropriately (shown below). 
```
{'params': {'n_neighbors': 30,
  'method': 'annoy',
  'metric': 'cosine',
  'use_rep': 'harmony'},
 'distances': <37452x37452 sparse matrix of type '<class 'numpy.float64'>'
 	with 1123560 stored elements in Compressed Sparse Row format>,
 'connectivities': <37452x37452 sparse matrix of type '<class 'numpy.float64'>'
 	with 1760748 stored elements in Compressed Sparse Row format>}
```

However, when running `scv.pp.moments` or `scv.tl.velocity_graph`, the `neighbors_to_be_recomputed` function is called and re-calculates the neighbors graph because the following lines lead to an evaluation of the function as `True`:
https://github.com/theislab/scvelo/blob/fe295e252f34cf5b701ca161561cd329abecd299/scvelo/preprocessing/neighbors.py#L226-L227

What is the rationale for using the `n_neighs.max() * .1 > n_neighs.min()` condition? Is there a way around this when using a custom neighbors graph or is this condition necessary and perhaps there is an issue with my neighbors graph? Thanks!

**Comment by VolkerBergen** [comment]
This is a (admittedly hacky) way of testing whether the neighbor graph is corrupted. For instance, when subsetting the data, the graph is distorted and needs to be recomputed. I think it'd be more appropriate to add a warning instead of forcing it to recompute the neighbor graph.

**Comment by d93espinoza** [comment]
got it! that makes sense in regards to the subsetting. I do subset my data prior to this and that is likely why this is happening, thank you!
