### ISSUE TITLE
Trouble loading loom files 

### ISSUE THREAD

**Issue by amunzur** [theislab/scvelo#188]
My apologies if this counts as something other than a bug. 

**Description**: 
I have a Seurat object that I converted to a loom file to be able to use it in scanpy. I also another loom file that I got from the velocyto run (10X).  I tried to load both, then merge them into one object and continue my RNA velocity analysis using scVelo. I have trouble loading file converted from Seurat. 

**Minimal reproducible example**: 
I attached the files here. "velocyto_output.loom" is the loom file that contains spliced and unspliced counts I got from the velocyto run. "seurat_to_loom.loom" is the loom file I converted from a Seurat object. I tried to execute the following: 

```
import scvelo as scv
adata = scv.read('velocyto_output.loom', cache=True)
adata2 = scv.read('seurat_to_loom.loom', cache=True)
adata = scv.utils.merge(adata, adata2)
```
scvelo can load the velocyto output with no problem, but it fails to load the loom object converted from seurat. My system freezes and crashes eventually. I checked if loompy can load the object; it looks like it can: 

```
import loompy
adata3 = loompy.connect('seurat_to_loom.loom')
adata3
```

Output looks like this: 
```
32738 rows, 2132 columns, 3 layers
(showing up to 10x10)
DH17existing.loom
name: ['2.0.1']
name: ['RNA']
name: ['(2132, 7072)']
name: ['20200508T195659.204898Z']
name: ['0.2.1.9000']
```
**Error message**
I get this message when I interrupt the code. It's same every time: 

```
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-7-838647feb173> in <module>
      1 adata = scv.read('DH15.loom', cache=True)
----> 2 adata2 = scv.read('DH15existing.loom', cache=True)
      3 # adata2 = loompy.connect('DH17new.loom')
      4 
      5 adata = scv.utils.merge(adata, adata2)

~/miniconda3/lib/python3.7/site-packages/scanpy/readwrite.py in read(filename, backed, sheet, ext, delimiter, first_column_names, backup_url, cache, cache_compression, **kwargs)
    120             cache=cache,
    121             cache_compression=cache_compression,
--> 122             **kwargs,
    123         )
    124     # generate filename and read to dict

~/miniconda3/lib/python3.7/site-packages/scanpy/readwrite.py in _read(filename, backed, sheet, ext, delimiter, first_column_names, backup_url, cache, cache_compression, suppress_cache_warning, **kwargs)
    689         adata = _read_softgz(filename)
    690     elif ext == 'loom':
--> 691         adata = read_loom(filename=filename, **kwargs)
    692     else:
    693         raise ValueError(f'Unknown extension {ext}.')

~/miniconda3/lib/python3.7/site-packages/anndata/_io/read.py in read_loom(filename, sparse, cleanup, X_name, obs_names, obsm_names, var_names, varm_names, dtype, **kwargs)
    203                 layers[key] = (
    204                     lc.layers[key].sparse().T.tocsr()
--> 205                     if sparse
    206                     else lc.layers[key][()].T
    207                 )

~/miniconda3/lib/python3.7/site-packages/loompy/loom_layer.py in sparse(self, rows, cols)
    116                 col: List[np.ndarray] = []
    117                 i = 0
--> 118                 for (ix, selection, view) in self.ds.scan(items=cols, axis=1, layers=[self.name], what=["layers"]):
    119                         if rows is not None:
    120                                 vals = view.layers[self.name][rows, :]

~/miniconda3/lib/python3.7/site-packages/loompy/loompy.py in scan(self, items, axis, layers, key, batch_size, what)
    610                                 # Load the whole chunk from the file, then extract genes and cells using fancy indexing
    611                                 for layer in layers:
--> 612                                         temp = self.layers[layer][:, ix:ix + cols_per_chunk]
    613                                         temp = temp[ordering, :]
    614                                         if selection is not None:

~/miniconda3/lib/python3.7/site-packages/loompy/loom_layer.py in __getitem__(self, slice)
     87                 if self.name == "":
     88                         return self.ds._file['/matrix'].__getitem__(slice)
---> 89                 return self.ds._file['/layers/' + self.name].__getitem__(slice)
     90 
     91         def __setitem__(self, slice: Tuple[Union[int, slice], Union[int, slice]], data: np.ndarray) -> None:

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

~/miniconda3/lib/python3.7/site-packages/h5py/_hl/dataset.py in __getitem__(self, args)
    571         mspace = h5s.create_simple(mshape)
    572         fspace = selection.id
--> 573         self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
    574 
    575         # Patch up the output for NumPy

KeyboardInterrupt: 
```
**Versions**: 
```
scvelo==0.1.25  scanpy==1.4.6  anndata==0.7.1  loompy==3.0.6  numpy==1.18.1  scipy==1.4.1  matplotlib==3.1.3  sklearn==0.22.1  pandas==1.0.3  
```

I am using a conda environment, and I used Jupyter Notebooks to execute my code. If you need it I can add the versions of packages I have installed. 

Can you please help me? 

Do you think this issue could have risen while converting the Seurat object to a loom file? 

Thank you for a great package!

**Comment by VolkerBergen** [comment]
Downloaded your files for testing and removed the links (for data confidentiality reasons). Will let you know once I found the culprit.

**Comment by VolkerBergen** [comment]
For some reason, the layers are corrupted. Just displaying one of the layers is already extremely slow. 
```
lc = connect( 'data/seurat_to_loom.loom', "r")
lc.layers['norm_data'][:, :]
```
Deleting the layers solves the issue.

**Comment by amunzur** [comment]
Thank you for helping out! So I guess this is rather a Seurat issue. This morning I generated more loom file using Seurat from other datasets I have, and I had the same issue with all of them. I'll let them know. 

I could delete the layers, but my data is in one of them, as explained by Seurat: 
"data will be stored in `layers/norm_data`"

Can you think of a way to salvage this situation?

**Comment by VolkerBergen** [comment]
Yes, that would prob have sth to do with Seurat. Would have to dig into Seurat, which I am certainly not an expert at. Maybe updating helps, otherwise I'd ask you to directly raise an [issue](https://github.com/satijalab/seurat/issues/new), which may also be useful for others.

**Comment by amunzur** [comment]
I'll do that! 

Many thanks for taking the time.

**Comment by VolkerBergen** [comment]
You're welcome. Keep me posted. Would be keen to understand what could have caused this - maybe I can adapt the `read` module accordingly.

**Comment by amunzur** [comment]
Hello Volker, 

I opened an issue with Seurat team about this matter, link to the issue is [here](https://github.com/satijalab/seurat/issues/3010). 

They suggested that I look at a document they wrote. 

Apparently we can't directly use Seurat objects in velocity analysis. However, we can still convert them to loom objects and read bits and pieces from them in Python using loompy. Another option is converting Seurat object to sce object, then finally to loom.

**Comment by fidelram** [comment]
As a workaround, and since the problem is the layers, why don’t you save each layer as a separate loom file and combine them afterwards in a single AnnData file?

**Comment by VolkerBergen** [comment]
Thanks! Yes, reading each layer separately would be the quickest way around. Yet, I am a surprised why Seurat's output stored with loomR cannot be read via loompy. Would need to investigate this further, as that is quite a fundamental issue.. @spalit, @Mesh09, @LuckyMD has anyone of you encountered this issue when going from Seurat to scanpy/scvelo?

**Comment by amunzur** [comment]
Loompy requires both column and row attributes while creating a new loom file, so I tried this: 

```
# import the seurat object converted via loomR 
import loompy
adata = loompy.connect('seurat_to_loom.loom')

# generate a new loom file 
loompy.create('sample.loom', adata['norm_data'], adata.ca, adata.ra)
```
When I execute this, same thing I mentioned above happens again, my browser freezes. Did you think of a different way to generate the loom file?

**Comment by VolkerBergen** [comment]
I think what @fidelram was referring to, is creating a separate loom file for each layer to then read them individually
`adata = scv.read('file_name.loom')`
`adata_norm = scv.read('file_name_norm.loom')`
for merging into `adata.layers['X_norm'] = adata_norm.X`.

**Comment by LuckyMD** [comment]
> @LuckyMD has anyone of you encountered this issue when going from Seurat to scanpy/scvelo?

Nope, I go between the two via `anndata2ri` normally. Don't really use `loompy` much.
