### ISSUE TITLE
Velocity and Diffmap

### ISSUE THREAD

**Issue by lenaschneehas** [theislab/scvelo#19]
Hi!

I have an issue plotting the velocity on the diffusion map. The arrows and the diffusion maps are both plotted, but the arrow are all one below the other on the right or left side of the plot and don't actually show the velocity of each cell. There is no error message when I call the function.

Thank you!
Best, 
Lena

**Comment by juugii** [comment]
I have the same issue here, I only have been able to successfully use tSNE or UMAP as embedding.

**Comment by stefanpeidli** [comment]
Hi,

I could also recreate that situation. Thanks a lot for pointing it out.
I think the problem has to do with the way scanpy plots the diffusion map embedding (scvelo uses that scanpy plot method), which in this case seems to be different to the way we plot the arrows in scvelo. I will figure out how to fix this.

In the meantime a **very** provisionary workaround would be:
`import numpy as np`
`import matplotlib.pyplot as pl`
`from scvelo.plotting.utils import get_components`
`from scvelo.plotting.scatter import scatter`
`ix_choice = np.random.choice(adata.n_obs, size=int(1 * adata.n_obs), replace=False)`
`X = adata.obsm['X_' + 'diffmap'][:, get_components(None)][ix_choice]`
`V = adata.obsm['velocity' + '_' + 'diffmap'][ix_choice]`
`pl.scatter(X[:, 0], X[:, 1])`
`pl.quiver(X[:, 0], X[:, 1], V[:, 0], V[:, 1])`
`pl.show()`

**Comment by VolkerBergen** [comment]
It was using the wrong diffmap coord per default. Fixed now. Thanks for pointing out.
