### ISSUE TITLE
Question about normalization

### ISSUE THREAD

**Issue by csoneson** [theislab/scvelo#190]
Hi, and thanks for a great software package! I have a couple of questions related to the normalization procedure in `scVelo`.

* When determining whether the data should be normalized: https://github.com/theislab/scvelo/blob/dea2f64c0eec4566ecfacef928c21dbed77316ec/scvelo/preprocessing/utils.py#L295-L296 the logic is different for dense and sparse matrices (and sometimes gives different conclusions). What is the reason behind this choice? 

* I'm using counts estimated by `alevin` as input to `scVelo`. These are not necessarily integers, and thus in some cases `scVelo` concludes that the data is already normalized. My solution was to run the four filtering/normalization steps separately, and enforce the normalization. I was wondering if the `enforce` argument of `normalize_per_cell()` perhaps could be propagated to `filter_and_normalize()`, to allow running all steps in one. 

Thanks!

**Comment by VolkerBergen** [comment]
Hi, it's a very simple proxy to check efficiently (thus only on the first 10 entries) whether the matrix consists of integers or floats (hence, whether it's already normalized/preprocessed or not). May I ask you what is the reason for getting non-integers from alevin?

With latest commit you can now pass `enforce` to `filter_and_normalize`.

**Comment by csoneson** [comment]
Thank you! `alevin` is providing _expected_ counts (from an EM algorithm), which don't have to be integers (if reads map to multiple genes). Many of the counts are integers though, which can lead to a difference in the decision to normalize for the sparse and dense representation since they check different subsets of the matrix.

**Comment by VolkerBergen** [comment]
Equivalence now guaranteed. Does the same apply for spliced/unspliced counts (non-integers due to EM)?

**Comment by csoneson** [comment]
Awesome, thank you! Yes, I am running the spliced/unspliced quantification in the same way as for the 'regular' gene expression (just with a different reference index), so it can happen also there.

**Comment by VolkerBergen** [comment]
And `X = spliced` or different?

**Comment by csoneson** [comment]
For me, it depends. In general I would define `X` as the 'regular' gene expression estimates (which would typically not be the same as `spliced`).

**Comment by VolkerBergen** [comment]
Raising a warning now. Let me know, if you can think of a better solution. And thanks for raising this!

**Comment by csoneson** [comment]
Thank you! That sounds great. I think it's hard to detect by just looking at the counts (there could be many or few non-integer values). Perhaps one could imagine something similar to the `log` argument of `filter_and_normalize`, allowing the user to specify whether the data has been normalized or not, which would override the internal checks?

**Comment by VolkerBergen** [comment]
You can now specify that with `layers_normalize={'X', 'spliced', 'unspliced'}` which has the same effect as `enforce=True`, but specified for particular layers.

**Comment by csoneson** [comment]
Yes, this seems like a good solution. Thank you!
