### ISSUE TITLE
get_cell_transitions output does make description

### ISSUE THREAD

**Issue by gitbuckley** [theislab/scvelo#191]
Hi, great tool! One issue: 

scv.utils.get_cell_transitions(adata, basis='umap', starting_cell=70)

is supposed to return "embedding coordinates (if basis is specified), else indices of simulated cell transitions."

However, even though I've  specified a basis this method call returns a list of indices:
[ 70 1464 4407 2674  ... ]

Is there a way to force return of coordinates?

If not, how can I make a cell transition scatter plot with cell indices instead of coordinates?

Much thanks!

**Comment by gitbuckley** [comment]
Running scvelo 0.2.1.dev18+g95e2679 (python 3.7.4)

**Comment by VolkerBergen** [comment]
Hi @gitbuckley,
please verify whether you have the coordinates stored at `adata.obsm['X_umap']`. 
Otherwise you obtain the coordinates manually with `x, y = adata.obsm['X_umap'][indices].T`

**Comment by gitbuckley** [comment]
adata.obsm['X_umap'] was empty. I filled it with sct.tl.umap(adata). 
Somehow I missed this going through the tutorials. Much appreciation for the quick reply.
