### ISSUE TITLE
Importing UMAP embeddings from Seurat into scvelo

### ISSUE THREAD

**Issue by kathirij** [theislab/scvelo#192]
Hello guys.. Thanks for a great package and overall support. I am primarily a biologist.. and I have selftaught a bit of R but just starting out in python... I have a rather naive question. I am very familiar with Seuart and wanted to run scvelo on an integrated seurat object (or at least via umap). 

This is the general flow I have used:

1. loom files generated from 10x of four different samples were combined using loompy.combine
2. subsetted the merged adata file based on the cell IDs from final Seurat object (e.g., adata = adata[cellnames])
3. processed the merged adata object in scvelo as per your tutorial.

The seurat object projection, based on the integration features (not SCT), seem very much like the biology I am expecting. Question is: once I export the UMAP embedding and cluster identities, how do I import that into python. I think I have to use numpy to format them in a specific manner, but due to my lack of knowledge, I am stuck there!

I am using Jupyter notebook to run all the python code.

Thanks in advance!

**Comment by VolkerBergen** [comment]
Hi @kathirij, sounds perfectly right so far. 

If you save the coordinates as `.npy` or `.csv`, you can load them into python with 
`X_umap = scv.load('filename')`. If you have each coordinate as an array, i.e. UMAP1 and UMAP2, you can stack them together with `X_umap = np.stack([UMAP1, UMAP2]).T`. The embedding coordinates are then stored at `adata.obsm['X_umap'] = X_umap`.

**Comment by kathirij** [comment]
Thanks so much for the super fast response! I think I am doing something wrong... what should the format of my coordinates csv file? Currently, it reads it as:

UMAP_1,UMAP_2
-10.52492045,2.959003479
-9.554694163,-2.914408654
-8.53956412,-2.044721573

But loading it through scv.load does not work nor does  splitting it into two text files and then stacking them using np.stack.

Thoughts?

**Comment by VolkerBergen** [comment]
Would be easier, if you could send the me csv file to mail@scvelo.org.

**Comment by kathirij** [comment]
Thanks! Just did.

**Comment by VolkerBergen** [comment]
Alright, so you can load via
`X_umap = scv.load('data/org_int_umap.csv', index_col=0)`
where `X_umap` is now a dataframe, then write as
`adata.obsm['X_umap'] = X_umap.loc[adata.obs_names].values`
where `.loc[adata.obs_names]` is to make sure, you put it in the right order, otherwise you can remove that part and simply do `adata.obsm['X_umap'] = X_umap.values`.

**Comment by kathirij** [comment]
It worked out perfectly! I was also able to import seurat cluster identities to place the cells appropriately... thank you so much!

**Comment by xie186** [comment]
> Alright, so you can load via
> `X_umap = scv.load('data/org_int_umap.csv', index_col=0)`
> where `X_umap` is now a dataframe, then write as
> `adata.obsm['X_umap'] = X_umap.loc[adata.obs_names].values`
> where `.loc[adata.obs_names]` is to make sure, you put it in the right order, otherwise you can remove that part and simply do `adata.obsm['X_umap'] = X_umap.values`.

Can you please tell me what information should be included in `data/org_int_umap.csv`? I want to do the same thing. Thanks in advance.

**Comment by AAA-3** [comment]
> Alright, so you can load via
> `X_umap = scv.load('data/org_int_umap.csv', index_col=0)`
> where `X_umap` is now a dataframe, then write as
> `adata.obsm['X_umap'] = X_umap.loc[adata.obs_names].values`
> where `.loc[adata.obs_names]` is to make sure, you put it in the right order, otherwise you can remove that part and simply do `adata.obsm['X_umap'] = X_umap.values`.

Hello @VolkerBergen -

I ran this code and successfully imported my tSNE coordinates from Seurat but when I load my saved loom file with the `obsm_mapping` parametre I get an error:
`adata = scv.read_loom("/home/ali/Dokumente/RPractise/Velocity/PythonCodes/adata.loom", obs_names="CellID", var_names="Gene", obsm_mapping="X_tsne")`
![image](https://user-images.githubusercontent.com/68068335/130209166-3b1126fd-529a-4026-a36a-1b3f3f149562.png)

Without setting the `obsm_mapping` parametre, the file loads normally and one can even see the tsne coordinates:
![image](https://user-images.githubusercontent.com/68068335/130209483-da0b29dc-82d9-4d16-ac4e-34250417f568.png)

Seeing as the information is available in the loom file, I assume that it is in an incorrect format...would it have something to do with it being an array? I notice that there is no `["tsne_1", "tsne_2"]`  headers, as listed in the [scvelo.read_loom API page](https://scvelo.readthedocs.io/scvelo.read_loom/)

**Comment by WeilerP** [comment]
@AAA-3, as already mentioned in #648, this is **not** an scVelo but Scanpy/anndata issue. Please open an issue/discussion there.

**Comment by denvercal1234GitHub** [comment]
@kathirij - Would you mind posting the format/example of the "org_int_umap.csv", and what did you do after running `adata.obsm['X_umap'] = X_umap.values`?

**Comment by denvercal1234GitHub** [comment]
@kathirij - Thanks for your response. Since the original answer above, there is now a `scv.utils.merge` function to merge the Seurat object and the loom objects. Did you try that instead of manually importing the embeddings etc as above?

**Comment by chklee30** [comment]
> [@kathirij](https://github.com/kathirij) - Thanks for your response. Since the original answer above, there is now a `scv.utils.merge` function to merge the Seurat object and the loom objects. Did you try that instead of manually importing the embeddings etc as above?

@denvercal1234GitHub , have you tried using the scv.utils.merge() function? I'm not sure what its purpose is or how to use it. 

I have a processed and integrated single seurat object, and I've also ran velocyto separately on my samples individually. I was going to do what @kathirij originally wrote, but wondering if the scv.utils.merge() function is supposed to make this easier?
