### ISSUE TITLE
Question regarding low proportion of unspliced counts

### ISSUE THREAD

**Issue by pavlin-policar** [theislab/scvelo#193]
Hi guys, thanks for the great package, it's really been super simple to work with!

I have a somewhat general question regarding velocity estimation. I am working with an organism that has a fairly poor genome and when I check the proportions of spliced/unspliced counts I get around 6% unspliced counts. This is quite a big step down from what you guys have in your docs, where you get around 20% unspliced counts. And this isn't some ultra-deep sequencing, this is a straight-up 10X/cellranger type data. On average, I get 65 UMI unspliced counts compared to 690 spliced UMI counts.

So my question is basically, how reliable is the velocity estimation here? I get some plots that appear to make sense, but I am skeptical due to the low numbers I stated above. And are there any guidelines for this?

**Comment by VolkerBergen** [comment]
Thanks. In the dentate gyrus we also only have a fraction of 10%, which is noticeable when comparing against the pancreas example, as there are fewer genes that yields interpretable signal.  However, the dentate gyrus example still yielded meaningful results and there were ~10 genes, that gave good support to the velocity directions.

So generally, I'd also advice to go into phase portraits of individual genes (those with high likelihood or differential or marker genes -> see tutorials), to see whether you have any signal and whether those genes support the inferred directionality. It always unravels through individual gene dynamics.

**Comment by pavlin-policar** [comment]
I see, I'll dig further into it. Thanks for your quick reply!
