### ISSUE TITLE
high proportion of unspliced

### ISSUE THREAD

**Issue by vickyrev** [theislab/scvelo#194]
Hi! Thanks for the great package, I'm beginning to explore with my own data, so looking for some benchmarks to understand what I'm seeing. In 10X data (sc) I'm getting 50/60% unspliced for PBMCs (monocytes in this case). Have you tested any similar datasets? I see that the docs are around 20%, but substantially different cells, so not sure if comparable. I've checked the phase plots for the top genes and they look very nice, and I also see differences for specific genes comparing different datasets (control/treated), but the global is always high. I used the cellranger output bams with velocyto (might try kallisto now instead). 
 
Any comment/opinion is highly appreciated!

**Comment by vickyrev** [comment]
Here's an example, 4 samples, rows 1 and 3 are control, and 2 and 4 a treatment condition in a paired design for one gene
![Screenshot from 2020-05-22 18-02-38](https://user-images.githubusercontent.com/7387990/82712673-87f01480-9c56-11ea-9d5b-644ba425a945.png)

**Comment by WeilerP** [comment]
@vickyrev, your phase portraits are really noisy s.t. the fitted kinetic is not very informative. In general, it seems that RNA velocity fails when applied to blood datasets. This will also be addressed in a soon to be published review by @VolkerBergen.

**Comment by asif7adil** [comment]
Hi, I am facing the same situation in my dataset of peripheral blood. I just wanted to know was this ever addressed?
Thanks!
