### ISSUE TITLE
Can't specify which genes velocity is calculated on

### ISSUE THREAD

**Issue by EvanLemire** [theislab/scvelo#200]
Hi there, 

I've noticed that when running velocity only a subset of the genes which are fed to the function actually have velocity calculated on them, and this seems somewhat dependent on how many genes are fed in the first place. I would like to be able to give the function a set of genes to calculate velocity on, but when I set the two filtering parameters min_likelihood and min_r2 to 0, it still seems to further filter the set of genes and only calculates velocity on a subset. Am I misunderstanding how "velocity genes" are chosen, and is there any way to specify exactly which genes you want velocity calculated on?

Thanks so much

**Comment by VolkerBergen** [comment]
Hi Evan,
`scv.tl.velocity` is generally computes velocities for all genes. The `velocity_genes` taken into account for all downstream analysis (incl. velocity graph, projection etc.) are obtained by thresholding on R2 and likelihood. You can enforce it to use all genes by setting `adata.var['velocity_genes'] = True`, or setting `min_r2` and `min_likelihood` to zero. For the dynamical model that'd be `scv.tl.recover_dynamics(adata, var_names='all')` if velocity_genes isn't set yet.
