### ISSUE TITLE
add_outline in scv.pl.scatter does not work with commas in group name

### ISSUE THREAD

**Issue by le-ander** [theislab/scvelo#201]
Hey Volker, I just tried to plot a umap with scv.pl.scatter and wanted to add an outline to a cluster. I realised that the outline is not drawn when the cluster name contains a comma (as it does when you have used louvain with the restrict_to=... option. one I convert the comma to another character, the outline gets drawn without problems.

**Comment by VolkerBergen** [comment]
True, a list of clusters can be passed as an actual list ['c1', 'c2', 'c3'] or as comma separated string 'c1, c2, c3'. That's why it understands it as a list of clusters. It's very uncommon to have commas in cluster names. However, I could add another test to verify whether it's meant to be a list or a comma separated cluster.

**Comment by le-ander** [comment]
Makes sense. I guess given that `sc.tl.louvain(adata, restrict_to=...)` puts commas in the split louvain groups by default it's actually not that uncommon to have them in there.

**Comment by le-ander** [comment]
Do you need the comma separated string functionality for anything in scvelo? Not sure a user would expect this functionality.

**Comment by VolkerBergen** [comment]
Was a relatively quick fix. Both is possible now. Let me know if that works. 

We initially enabled plotting multiple groups by comma-separated str just for diff kinetic plotting, as the test stores a list of clusters describing by a secondary kinetic for each gene in adata.var, which only hosts str and not list.

**Comment by le-ander** [comment]
Awesome, thanks a lot!
