### ISSUE TITLE
Problem with UMAP

### ISSUE THREAD

**Issue by ogandril** [theislab/scvelo#203]
I am experiencing a problem with the UAMP function

>>> scv.tl.umap(adata)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/lib/python3.7/site-packages/scanpy/tools/_umap.py", line 147, in umap
    adata.uns['neighbors']['connectivities'].tocoo(),
KeyError: 'connectivities'

I have run the scv.pp.neighbors(adata)function and it went well.

When looking at the adata object, I see the connectivities matrix in the obsp and not in the uns category.
I therefore tried 
>>> adata.uns['connectivities']=adata.obsp['connectivities']

Now connectivities also appears in the uns category but the 
>>> scv.tl.umap(adata)
command generates the exact same error.

```python
...
```

<details>
<summary> Error </summary>
python
import scvelo as scv
scv.settings.verbosity = 3  # show errors(0), warnings(1), info(2), hints(3)
scv.settings.presenter_view = True  # set max width size for presenter view
scv.set_figure_params('scvelo')  # for beautified visualization
adata_pos = scv.read('/Users/olivier_2/Documents/En_cours/Labo/Manipes/OG3287/BCRpos.counts_unfiltered/adata.loom', cache=True)
adata_neg = scv.read('/Users/olivier_2/Documents/En_cours/Labo/Manipes/OG3287/BCRneg.counts_unfiltered/adata.loom', cache=True)
adata_pos.obs['run'] = 'pos'
adata_neg.obs['run'] = 'neg'
adata_pos.obs['bcs'] = adata_pos.obs.index
adata_neg.obs['bcs'] = adata_neg.obs.index
adata_pos.obs.index = adata_pos.obs['bcs'] + '.' + adata_pos.obs['run']
adata_neg.obs.index = adata_neg.obs['bcs'] + '.' + adata_neg.obs['run']
adata_pos_neg = adata_pos.concatenate(adata_neg, batch_key='batch')
adata_pos_neg.obs.index = adata_pos_neg.obs.index.str.split('-').str[0]
#adata_pos_neg.obs.head()
adata_pos_neg.var.index = adata_pos_neg.var.index.str.split('.').str[0]
#adata_pos_neg.var.head()
adata_pos_neg.write('pos_neg.h5ad')
adata = scv.read('pos_neg.h5ad')
scv.pl.proportions(adata)
scv.pp.filter_and_normalize(adata, min_shared_counts=20, n_top_genes=2000)
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
adata.obs["Clusters"] =adata.obs.run
scv.pp.neighbors(adata)
scv.tl.umap(adata)

#### Versions:

>>> scv.logging.print_version()
Running scvelo 0.2.0 (python 3.7.6) on 2020-05-28 11:10.

**Comment by VolkerBergen** [comment]
You'll need to update scanpy, `pip install -U scanpy`.

**Comment by ogandril** [comment]
That was FAST!
Thank’s

I’ll try that ASAP.

Olivier

**Comment by ogandril** [comment]
Ant it worked like a charm!!! Thank’s AGAIN
