### ISSUE TITLE
Can I merge my single cell analysis?

### ISSUE THREAD

**Issue by Vyoming** [theislab/scvelo#205]
Hello,
Everything in this package has been working great for me!
However I was wondering that if I were to have a filtered, normalized, Annotated data object with clusters from my single cell analysis will I be able to merge it with my velocyto based adata object and keep all of the clusters and filtering?

I'm still very new to velocyto and don't really understand it all too well

Any help would be much appreciated!!!

**Comment by VolkerBergen** [comment]
Sure, you can use `adata = scv.merge(adata_processed, adata_loom)` to merge the velocyto/loom file into a preprocessed adata object - along shared `obs_names/cellIDs`. It internally takes care of cleaning up the obs_names wrt different prefixes. After merging, you just need to check whether all observations are retained.

**Comment by Vyoming** [comment]
Wow that really cool and super useful

Great package!
