### ISSUE TITLE
I'm using LSTM model and in that when i use scaler.inverse_transform method then below error occurred.

### ISSUE THREAD

**Issue by pranjalsharma26** [theislab/scvelo#206]
non-broadcastable output operand with shape (61286,1,1) doesn't match the broadcast shape (61286,1,6)

**Comment by VolkerBergen** [comment]
How's that related to scvelo?

**Comment by pranjalsharma26** [comment]
I found a similar issue related to my problem so I posted it here. I would be glad if you tell me what to do next.

**Comment by VolkerBergen** [comment]
Don't understand your issue. scvelo has nothing to do with LSTM nor any inverse_transform. Which scvelo module exactly yields that error?

**Comment by pranjalsharma26** [comment]
I have not worked in scvelo module, this is my separate project and issue I posted here because when I search for my issue google provides me this link.

**Comment by VolkerBergen** [comment]
Can't help you with that, sorry. You'd need to post the issue at the relevant repository. If it is your own script, you can ask for help at stackoverflow.
