### ISSUE TITLE
Pressing the github button in a tutorial on readthedocs

### ISSUE THREAD

**Issue by Marius1311** [theislab/scvelo#209]
When I press the "Edit on Github" button on any tutorial page other than the "Getting started tutorial", I get to a page like this: https://github.com/theislab/scvelo/blob/master/docs/source/DynamicalModeling.ipynb, 
which just says "page not found". Is this intended?

**Comment by VolkerBergen** [comment]
Yes, I am aware of that and didn't manage to modify the "edit on github" links specifically for the notebook urls, which should be ref. to https://github.com/theislab/scvelo_notebooks/blob/master/DynamicalModeling.ipynb

**Comment by VolkerBergen** [comment]
or even ref to the nbviewer https://nbviewer.jupyter.org/github/theislab/scvelo_notebooks/blob/master/DynamicalModeling.ipynb

I'd be highly interested, if you have any idea how to modify specific "edit on github" links.

**Comment by Marius1311** [comment]
I must confess I don't know, but maybe @michalk8 has an idea...?

**Comment by VolkerBergen** [comment]
Solved by @michalk8. Thanks a lot!

**Comment by Marius1311** [comment]
Fantastic, thanks!
