### ISSUE TITLE
Scatterplot ignoring numeric titles for `'0'` and `'1'`

### ISSUE THREAD

**Issue by michalk8** [theislab/scvelo#212]
Hey @VolkerBergen ,

When passing e.g. `title='0'`, `scv.pl.scatter` ignores it (and in the case below, uses the column name).
This only happens for numbers `'0'` and `'1'`, other numbers seems to be fine.
 

```python
import scvelo as scv
import numpy as np
np.random.seed(42)
adata = scv.datasets.toy_data(50)
adata.obs['0'] = np.random.normal(size=(50,))

adata.obs['foo'] = np.random.normal(size=(50,))

scv.pl.scatter(adata, color=['foo'] * 5, title=list(map(str, range(5))))
```

![img](https://user-images.githubusercontent.com/46717574/83981207-21d4e400-a91c-11ea-9e18-0e0738b8de45.png)

#### Versions:
```scvelo==0.2.2.dev11+g6dfb8aa  scanpy==1.5.1  anndata==0.7.3  loompy==3.0.6  numpy==1.18.4  scipy==1.4.1  matplotlib==3.2.1  sklearn==0.23.1  pandas==1.0.4```

**Comment by VolkerBergen** [comment]
Thanks for spotting this. '0' and '1' were interpreted as color codes (corresponding to black and white), thus title was not set. It should be fixed now.

**Comment by michalk8** [comment]
Works perfectly, thanks!
