### ISSUE TITLE
Plot velocity 3D UMAP

### ISSUE THREAD

**Issue by ccruizm** [theislab/scvelo#220]
Good day! 

I would like to know whether there is an option to plot RNA velocities on a 3D UMAP. I saw from `scanpy` would be possible to do it but I am not sure whether it is feasible to get the arrows embedded into a 3D projection. 

Thanks in advance

**Comment by VolkerBergen** [comment]
That's not fully integrated as there were some matplotlib issues with 3d plotting and we removed the functionality. But I think @Marius1311 you got it working now, right? Would you mind sharing the code or making a PR for such?

**Comment by Marius1311** [comment]
Hi all, happy to contribute my solution, it's quick and dirty though: 
```
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D 

umap = adata.obsm['X_umap']
velocity = adata.obsm['velocity_umap']
# color = adata.obs['global_time']
color = scv.utils.interpret_colorkey(adata, c="lineage")

fig = plt.figure(dpi=400)
ax = fig.add_subplot(111, projection='3d')
ax.scatter(umap[:, 0], umap[:, 1], umap[:, 2], c=color, cmap='viridis')

# prepare colors for the arrows
c = scv.utils.interpret_colorkey(adata, c="lineage")
c = list(c) + [element for element in list(c) for _ in range(2)]

# Plot the velocity projection
ax.quiver(umap[:, 0], umap[:, 1], umap[:, 2], velocity[:, 0], velocity[:, 1], velocity[:, 2], color='k',
          normalize=True, length=0.4, arrow_length_ratio=0.3, linewidth = 0.5)
ax.set_title('phenotypic manifold in high dimensions')
ax.view_init(None, 10)

# turn off the axis ticks
ax.set_xticklabels([])
ax.set_yticklabels([])
ax.set_zticklabels([])

# ax.set_xlabel('20k dimensions')
plt.savefig(f"{figdir}/high_dim_projection.pdf")
plt.show()
```

**Comment by JBreunig** [comment]
I look forward to trying this?
Where is "lineage" set?  
And do I need to calculate the 3rd dimensional coordinate prior to this somewhere? 

> ax.scatter(umap[:, 0], umap[:, 1], umap[:, 2], c=color, cmap='viridis')

**Comment by Marius1311** [comment]
Hi @JBreunig , the `lineage` is just the name of a key in `.obs` to color in my cells. You can leave that out, or provide an alternative key like `clusters`, depending on what you would like to color in. 

And yes, you need to compute a 3D umap, see the docstring of `sc.tl.umap` in the scanpy documentation for that.

**Comment by JBreunig** [comment]
Got it working, thanks!  I think my big stumble was not realizing that the velocity_umap needs more steps to plot the 3d coordinates.

**Comment by ccruizm** [comment]
Thank you so much for sharing the code! It also worked for me! If you want to move interactively the UMAP 3D projection, use `%matplotlib notebook`

**Comment by Marius1311** [comment]
Thanks @ccruizm , I will check this out!

**Comment by wupeng2** [comment]
hi,@Marius1311 As in your script, there are 3 element in velocity:velocity[:, 0], velocity[:, 1], velocity[:, 2],but I can only get 2 ,how can I get 3d velocity_umap?thanks

**Comment by Marius1311** [comment]
Hi @wupeng2 , you have to compute a 3D UMAP first, i.e. set `n_components` (may have a similar name, you have to look this up) to `3`, then compute umap. When you project velocities, this should project onto all computed UMAP components.

**Comment by wupeng2** [comment]
hi,@Marius1311 thank you for your reply. in my case ,I've computed a 3D UMAP ,but I don't know how to get 3d velocity(as the arrow).below is how I get velocity based on Dynamical Model.
scv.pp.filter_and_normalize(adata, min_shared_counts=20, n_top_genes=2000)
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
scv.tl.recover_dynamics(adata)
scv.tl.velocity(adata, mode='dynamical')
scv.tl.velocity_graph(adata)
in my data: adata.obsm['X_umap'] is 3 element, but adata.obsm['velocity_umap'] only have 2 element.
thanks

**Comment by wupeng2** [comment]
hi,@Marius1311 thank you for your reply. in my case ,I've computed a 3D UMAP ,but I don't know how to get 3d velocity(as the arrow).below is how I get velocity based on Dynamical Model.
scv.pp.filter_and_normalize(adata, min_shared_counts=20, n_top_genes=2000)
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
scv.tl.recover_dynamics(adata)
scv.tl.velocity(adata, mode='dynamical')
scv.tl.velocity_graph(adata)
in my data: adata.obsm['X_umap'] is 3 element, but adata.obsm['velocity_umap'] only have 2 element.
thanks

**Comment by wupeng2** [comment]
hi,@Marius1311 thank you for your reply. in my case ,I've computed a 3D UMAP ,but I don't know how to get 3d velocity(as the arrow).below is how I get velocity based on Dynamical Model.
scv.pp.filter_and_normalize(adata, min_shared_counts=20, n_top_genes=2000)
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
scv.tl.recover_dynamics(adata)
scv.tl.velocity(adata, mode='dynamical')
scv.tl.velocity_graph(adata)
in my data: adata.obsm['X_umap'] is 3 element, but adata.obsm['velocity_umap'] only have 2 element.
thanks

**Comment by wupeng2** [comment]
@Marius1311 hi, this time,i get 3d velocity by using  scv.tl.velocity_embedding(adata,basis='umap'),as there are 3 element in both adata.obsm['X_umap'] and adata.obsm['velocity_umap'].but I've meet a new problem whether there is an option to plot RNA velocities in other form such as  grid or stream instead of arrow on a 3D UMAP.thanks a lot!

**Comment by Marius1311** [comment]
Hi @wupeng2 , I haven't experiment with that yet, sorry!

**Comment by mayurdoke6** [comment]
> %matplotlib notebook



> Hi all, happy to contribute my solution, it's quick and dirty though:
> 
> ```python
> import matplotlib.pyplot as plt
> from mpl_toolkits.mplot3d import Axes3D 
> 
> umap = adata.obsm['X_umap']
> velocity = adata.obsm['velocity_umap']
> # color = adata.obs['global_time']
> color = scv.utils.interpret_colorkey(adata, c="lineage")
> 
> fig = plt.figure(dpi=400)
> ax = fig.add_subplot(111, projection='3d')
> ax.scatter(umap[:, 0], umap[:, 1], umap[:, 2], c=color, cmap='viridis')
> 
> # prepare colors for the arrows
> c = scv.utils.interpret_colorkey(adata, c="lineage")
> c = list(c) + [element for element in list(c) for _ in range(2)]
> 
> # Plot the velocity projection
> ax.quiver(umap[:, 0], umap[:, 1], umap[:, 2], velocity[:, 0], velocity[:, 1], velocity[:, 2], color='k',
>           normalize=True, length=0.4, arrow_length_ratio=0.3, linewidth = 0.5)
> ax.set_title('phenotypic manifold in high dimensions')
> ax.view_init(None, 10)
> 
> # turn off the axis ticks
> ax.set_xticklabels([])
> ax.set_yticklabels([])
> ax.set_zticklabels([])
> 
> # ax.set_xlabel('20k dimensions')
> plt.savefig(f"{figdir}/high_dim_projection.pdf")
> plt.show()
> `

Hello @Marius1311 

Thank you so much for the code. I have computed 3d velocity by using scv.tl.velocity_embedding(adata,basis='umap'),as there are 3 element in both adata.obsm['X_umap'] and adata.obsm['velocity_umap']. I was able to make 3D UMAP. However, I am not able to make velocity arrows on 3d UMAP. Is that possible? I am using your code. It's working however it does not produce any output at the end. Could you please help me with this issue?

**Comment by cetinsz** [comment]
Were you able to find a solution for velocity arrows?
