### ISSUE TITLE
More Clarity on Velocity Arrows

### ISSUE THREAD

**Issue by oswaldbra12** [theislab/scvelo#222]
Thank you for the awesome program, very helpful! 

I do have a question regarding the velocities imposed on the cell clustering. One of the cool downstream applications of the programs is identifying the top genes driving the velocity. You can see in a chart, rank-ordered, the genes that contribute most to the velocity estimates. Is that rank-order of genes true for arrows going from cluster to cluster or all the clusters as a whole? 

The heart of my question is this: If I wanted to identify a gene or gene-set that drives cluster 1 to cluster 2, is the chart helpful in identifying that? Or is the chart more generic to all the clusters as a whole?

Code I am talking about:
scv.tl.rank_velocity_genes(adata, groupby='seurat_clusters.refined', min_corr=.3)
df = scv.DataFrame(adata.uns['rank_velocity_genes']['names'])
print(df.shape)
df.head(30)

I hope that makes sense if not, I can elaborate.

**Comment by WeilerP** [comment]
@oswaldbra12, sorry for the super late reply. The likelihood is calculated on all observations used to infer dynamics. In your case, this seems to be all clusters.

If you are interested in scoring genes based on likelihood in a subset of the data you can either

1. fit the model on all clusters and recalculate likelihoods with observations from cluster one and two
2. fit a dynamical model on only cluster one and two.

I believe option 1 to be preferable as you use all data available and focus on the overall dynamic. Subsetting the data may be accompanied by loss in signal in the phase portraits.
