### ISSUE TITLE
how to compute latetn time?

### ISSUE THREAD

**Issue by hahia** [theislab/scvelo#223]
Hello, 
I have some doubts about the calculation of latent time.
If I understand correctly, compute latent time need root cell. But I find no root cell, there still have latent time

![image](https://user-images.githubusercontent.com/49113803/85378949-bfabee00-b56d-11ea-80fd-92120f1b9e7b.png)
![image](https://user-images.githubusercontent.com/49113803/85378971-c5a1cf00-b56d-11ea-9373-c192e7577dff.png)

Why？
Can anyone explain in detail the calculation of latent time？
how the root cell latent time compute?

Thank any comment!!!

**Comment by VolkerBergen** [comment]
Latent time just needs one reference point which can also be terminal end points. Given the continuity of latent time and its concordance with the end points, it looks good to me. The reason for not having detected a confident root cell population might be that there are multiple distinct ones (we've had similar results in the dentate gyrus example). You could try https://github.com/theislab/cellrank which has an improved implementation of computing root states, if you are interested in those specifically.

**Comment by hahia** [comment]
> Thanks for sharing. Latent time just needs one reference point which can also be terminal end points. Given the continuity of latent time and its concordance with the end points, it looks good to me. The reason for not having detected a confident root cell population might be that there are multiple distinct ones (we've had similar results in the dentate gyrus example). You could try https://github.com/theislab/cellrank which has an improved implementation of computing root states, if you are interested in those specifically.

Thanks for your reply!!!!
I use different cutoff to filter gene, the results seems hard to explain for me. Maybe you have some comments.
min_shared_counts=10, n_top_gene=2000
![image](https://user-images.githubusercontent.com/49113803/85398750-440b6a80-b588-11ea-9e3e-a37b754a5b80.png)
![image](https://user-images.githubusercontent.com/49113803/85398763-48d01e80-b588-11ea-8aca-aa2da94c27e6.png)

min_shared_counts=20, n_top_gene=2000
![image](https://user-images.githubusercontent.com/49113803/85398793-51c0f000-b588-11ea-88c1-b71b65cc74bd.png)
![image](https://user-images.githubusercontent.com/49113803/85398802-538ab380-b588-11ea-85b8-314dddfbf527.png)

the second cutoff can identify root cells and cell latent time have some differences. Why?



I still confuse about computation of latent time.
Latent time of cell i is the latent time of genes of cell i minus each root cells genes latent time, and take 20−30% quantile of t, then Gene shared time of cell i is obtained as mean across all root cells. Am I understanding it correctly? 
But how to compute root cell latent time? just mean the genes latent time of root cell? or minus themselves gene latent time?

**Comment by VolkerBergen** [comment]
You should go with a higher cutoff `min_shared_counts=20`, as 10 is really low. It makes sense to me that it is now better at picking up root cells because you have a higher chance of retaining only those genes that potentially have good signal in splicing kinetics, thus it will not so much be masked by noise. 

The difference I see is among the progenitors, not so much among the more differentiated cells - which again makes sense as it now uses the roots as prior. The more priors the better.

Latent time is - first for each gene the time it takes to go along the inferred kinetics from the root cell towards a cell of interest - then this is coupled across genes by the assumption that all genes share the same overall timescale in their transient states (so whenever a gene is changing, its time is progressing along the same cell-to-cell graph as for the other genes) - and finally it takes the "pseudo"-average of all timescale-aligned genes. (pseudo-average as in 20-30% quantile chosen such that it maximizes the correlation between latent time and its convolution with neighbors - it also works with a simple average, this is just to adapt to a non-uniform density of cells along the time-course as cells often tend to accumulate in later time points, thereby making it more robust).

**Comment by hahia** [comment]
> You should go with a higher cutoff `min_shared_counts=20`, as 10 is really low. It makes sense to me that it is now better at picking up root cells because you have a higher chance of retaining only those genes that potentially have good signal in splicing kinetics, thus it will not so much be masked by noise.
> 
> The difference I see is among the progenitors, not so much among the more differentiated cells - which again makes sense as it now uses the roots as prior. The more priors the better.
> 
> Latent time is - first for each gene the time it takes to go along the inferred kinetics from the root cell towards a cell of interest - then this is coupled across genes by the assumption that all genes share the same overall timescale in their transient states (so whenever a gene is changing, its time is progressing along the same cell-to-cell graph as for the other genes) - and finally it takes the "pseudo"-average of all timescale-aligned genes. (pseudo-average as in 20-30% quantile chosen such that it maximizes the correlation between latent time and its convolution with neighbors - it also works with a simple average, this is just to adapt to a non-uniform density of cells along the time-course as cells often tend to accumulate in later time points, thereby making it more robust).



I also use min_shared_counts=30, n_top_gene=2000
![image](https://user-images.githubusercontent.com/49113803/85401650-f04f5000-b58c-11ea-8796-897a93e68da7.png)
![image](https://user-images.githubusercontent.com/49113803/85401656-f2b1aa00-b58c-11ea-87a1-036980ff0f88.png)
It can't identify root cells. what's the reason cause this?

**Comment by VolkerBergen** [comment]
Alright, that's a good point. It just has to do with the initialization (not with what I mentioned earlier). You can adjust the `random_state` parameter in `terminal_states()`. It's defaulted to 0, so you can set it to any other integer number. It breaks down to running a Markov chain backwards for an 'infinite' time, converging in the root progenitors. Depending on the initialization however, it may happen that it would not converge and the underlying eigenvalue problem cannot be solved. Could you try with different `random_states`? If that solves it, I'll add multiple runs with diff. initializations to the eigenvalue problem in `terminal_states`. There's a whole literature on solvability conditions for such, which is currently studied in https://github.com/theislab/cellrank to come up with an improved implementation for identifying terminal states.

**Comment by hahia** [comment]
> Alright, that's a good point. It just has to do with the initialization (not with what I mentioned earlier). You can adjust the `random_state` parameter in `terminal_states()`. It's defaulted to 0, so you can set it to any other integer number. It breaks down to running a Markov chain backwards for an 'infinite' time, converging in the root progenitors. Depending on the initialization however, it may happen that it would not converge and the underlying eigenvalue problem cannot be solved. Could you try with different `random_states`? If that solves it, I'll add multiple runs with diff. initializations to the eigenvalue problem in `terminal_states`. There's a whole literature on solvability conditions for such, which is currently studied in https://github.com/theislab/cellrank to come up with an improved implementation for identifying terminal states.

OK, I will try different random_states. It need some time. keep in touch.

I'm new to Markov chain and Linear algebra. I am very interested in these.
The egienvalue problem is that default eigenvalue is 1, sometimes use this egienvalue, the left eigenvectors would not converge? (The eigenvectors are the probability of cell be root or end state?)

**Comment by hahia** [comment]
> Alright, that's a good point. It just has to do with the initialization (not with what I mentioned earlier). You can adjust the `random_state` parameter in `terminal_states()`. It's defaulted to 0, so you can set it to any other integer number. It breaks down to running a Markov chain backwards for an 'infinite' time, converging in the root progenitors. Depending on the initialization however, it may happen that it would not converge and the underlying eigenvalue problem cannot be solved. Could you try with different `random_states`? If that solves it, I'll add multiple runs with diff. initializations to the eigenvalue problem in `terminal_states`. There's a whole literature on solvability conditions for such, which is currently studied in https://github.com/theislab/cellrank to come up with an improved implementation for identifying terminal states.

Hi, I try different random_states, but still can't identify root cells

random_state=1
![image](https://user-images.githubusercontent.com/49113803/85492377-a6578000-b607-11ea-841a-3c3d03dff4be.png)
![image](https://user-images.githubusercontent.com/49113803/85492412-b5d6c900-b607-11ea-8c6c-b11e31d2200b.png)


random_state=2
![image](https://user-images.githubusercontent.com/49113803/85492455-c71fd580-b607-11ea-99b9-d377200d2206.png)
![image](https://user-images.githubusercontent.com/49113803/85492475-ce46e380-b607-11ea-94f6-3096ae57cffa.png)

random_state=6
![image](https://user-images.githubusercontent.com/49113803/85492514-e0288680-b607-11ea-8922-c0329e60ef25.png)
![image](https://user-images.githubusercontent.com/49113803/85492543-e9195800-b607-11ea-8c97-01207b91afb6.png)

**Comment by VolkerBergen** [comment]
ok, what if you apply `scv.tl.velocity_graph(adata, mode_neighbors='connectivities')` before computing terminal states?

**Comment by hahia** [comment]
> ok, what if you apply `scv.tl.velocity_graph(adata, mode_neighbors='connectivities')` before computing terminal states?

I use this, can identify root cells
scv.tl.velocity_graph(adata, mode_neighbors='connectivities')
scv.tl.terminal_states(adata)
scv.tl.latent_time(adata)
scv.pl.scatter(adata, color=[ 'root_cells', 'end_points'])
scv.pl.scatter(adata, color='latent_time',color_map='gnuplot', size=80)

![image](https://user-images.githubusercontent.com/49113803/85494046-93927a80-b60a-11ea-98e9-cdceb53a874a.png)
![image](https://user-images.githubusercontent.com/49113803/85494064-9b521f00-b60a-11ea-9239-ce15784acb3c.png)

what's the rational behind this?

**Comment by VolkerBergen** [comment]
By setting it to `connectivities`, it uses a symmetric neighbor/transition graph (if cell i is neighboring cell j, then also vice versa), which guarantees that there are always outgoing as well as incoming edges equally captured for each cell. That eventually improves root cell identification, which would suffer otherwise because many parts of the progenitor would be 'disconnected' otherwise. 

Your example is a though one, with multiple root/end states. So I'm happy that it worked out fairly well. Does it coincide with what you'd be expecting biologically?

**Comment by hahia** [comment]
> By setting it to `connectivities`, it uses a symmetric neighbor/transition graph (if cell i is neighboring cell j, then also vice versa), which guarantees that there are always outgoing as well as incoming edges equally captured for each cell. That eventually improves root cell identification, which would suffer otherwise because many parts of the progenitor would be 'disconnected' otherwise.
> 
> Your example is a though one, with multiple root/end states. So I'm happy that it worked out fairly well. Does it coincide with what you'd be expecting biologically?

Yes, thank you for your help!!!!!!
