### ISSUE TITLE
pl.heatmap with the gene list we interesting

### ISSUE THREAD

**Issue by hahia** [theislab/scvelo#224]
Hi,
After compute latent time, how to plot a heatmap with a gene list we interesting, not the top300 high likelihood genes. and show all the rownames of heatmap (we care abount which gene express in which cell)?

![image](https://user-images.githubusercontent.com/49113803/85517126-8c329780-b631-11ea-8658-4638420b9575.png)

**Comment by VolkerBergen** [comment]
That can be done with `scv.pl.heatmap(adata, var_names, yticklabels=True)` where `var_names` specifies the gene names to be plotted, and `yticklabels` is set to display all row labels. See the [api-docs](https://scvelo.readthedocs.io/scvelo.pl.heatmap.html)  for more details.

**Comment by hahia** [comment]
> That can be done with `scv.pl.heatmap(adata, var_names, yticklabels=True)` where `var_names` specifies the gene names to be plotted, and `yticklabels` is set to display all row labels. See the [api-docs](https://scvelo.readthedocs.io/scvelo.pl.heatmap.html) for more details.

Thank you very much
