### ISSUE TITLE
Using externally-normalized data and batch effects

### ISSUE THREAD

**Issue by rfarouni** [theislab/scvelo#227]
Hi Volker,

I have an issue similar to this one https://github.com/theislab/scvelo/issues/163. Basically I am running scVelo on a dataset consisting of several samples (i.e. batches) across two conditions and I get different output when I use the built in normalization vs when I skip this step and provide already normalized data.  For this dataset, I have already clustered the cells with MNN  using the combined spliced and unspliced counts and I have also lognormalized the combined counts using [multiBatchNorm ](https://rdrr.io/github/LTLA/batchelor/man/multiBatchNorm.html). I used the adjusted size factors for the combined counts to log-normalize the spliced and unspliced counts.  

Do the lognormalized spliced/unspliced counts need to be exponentiated in order to estimate the RNA velocities correctly? What about the matrix X? How is it used in downstream steps?

Also, I see the  scVelo https://github.com/theislab/scvelo/blob/master/scvelo/preprocessing/utils.py#L666 centers the total counts of all the cells to the median. Is that an essential step? 

Thanks in advance,
Rick Farouni

**Comment by WeilerP** [comment]
@rfarouni, sorry for the late reply.

> Do the lognormalized spliced/unspliced counts need to be exponentiated in order to estimate the RNA velocities correctly? What about the matrix X? How is it used in downstream steps?

Yes, `spliced` and `unspliced` need to be exponentiated. Otherwise, you would have to transform the ODE.

> Also, I see the scVelo https://github.com/theislab/scvelo/blob/master/scvelo/preprocessing/utils.py#L666 centers the total counts of all the cells to the median. Is that an essential step?

The median is just one possible target.
