### ISSUE TITLE
velocity_embedding graphs don't follow autoshow=False?

### ISSUE THREAD

**Issue by blin100** [theislab/scvelo#228]
Hi, I'm quite a novice at python, so forgive the simple question. I set at the beginning of my script  scv.settings.autoshow=false, as well as sc.settings.autoshow=false (for scvelo and scanpy), and yet the velocity embedding graphs still pop up and I must close them for the script to continue running. However, many of the other graphs do follow it properly and are just auto-saved and moved on. I must be missing something?
Thanks for any help!

**Comment by VolkerBergen** [comment]
Thanks for raising - show be solved now.

**Comment by blin100** [comment]
Works like a charm, thanks very much!
