### ISSUE TITLE
About tl.velocity

### ISSUE THREAD

**Issue by hahia** [theislab/scvelo#229]
Hi

After
```
scv.pp.filter_and_normalize(adata, min_shared_counts=15, n_top_genes=500)
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
scv.tl.recover_dynamics(adata)
scv.tl.velocity(adata, mode='dynamical')
print(adata.var.velocity_genes.sum())
```

there have 128 genes for velocity

But when I look for likelihood and fit_r2 of genes

```
top_genes = adata.var['fit_likelihood'].sort_values(ascending=False)
top_genes.to_csv('gene_count15_n500.csv')
adata.var.fit_r2.to_csv('gene_count15_n500_r2.csv')
```

and use R to look which genes for velocity

`length(intersect(gene_count15_n500$X1[gene_count15_n500$fit_likelihood>0.001],gene_count15_n500_r2$X1[gene_count15_n500_r2$fit_r2>0.01]))`

there have 138 genes for velocity

I use the default min_likelihood 0.001 and min_fit_r2 0.01 
![image](https://user-images.githubusercontent.com/49113803/85912317-3e4ea700-b85e-11ea-83c6-3edc74c89601.png)

why they are different?

**Comment by hahia** [comment]
Can anyone help me to figure out the problem?

**Comment by VolkerBergen** [comment]
There's another gene selection step [here](https://github.com/theislab/scvelo/blob/a7de78ae974b251c366f208aab2e685b23bc101e/scvelo/tools/velocity.py#L337), by a 'reliable' ratio of unspliced-to-spliced counts (essentially unselecting genes that have e.g. less than 3 unspliced counts per 100 spliced counts and thus might induce unreliable signal - it shouldn't have much influence though).

**Comment by hahia** [comment]
> There's another gene selection step [here](https://github.com/theislab/scvelo/blob/a7de78ae974b251c366f208aab2e685b23bc101e/scvelo/tools/velocity.py#L337), by a 'reliable' ratio of unspliced-to-spliced counts (essentially unselecting genes that have e.g. less than 3 unspliced counts per 100 spliced counts and thus might induce unreliable signal - it shouldn't have much influence though).

Thank you very much!!!!!
