### ISSUE TITLE
About min_shared_counts

### ISSUE THREAD

**Issue by hahia** [theislab/scvelo#230]
Hi, when I use 
`scv.pp.filter_and_normalize(adata, min_shared_counts=10, n_top_genes=500)`

Filtered out 55848 genes that are detected 10 counts (shared).

But when I use R to look shared_counts

```
spliced_counts = colSums(spliced)
unspliced_counts = colSums(unspliced)
share_data = data.frame(spliced=spliced_counts,unspliced=unspliced_counts)
share_data$shared_counts = NA
share_data$shared_counts = ifelse(share_data$spliced>= share_data$unspliced,share_data$unspliced,share_data$spliced)
table(share_data$shared_counts>10)
```

![image](https://user-images.githubusercontent.com/49113803/85940236-d6778980-b94d-11ea-9409-6c7bcd0fe32b.png)

it just filter 53018 genes

Are there any other filter steps here I miss?

**Comment by WeilerP** [comment]
Shared counts are defined as the sum of spliced and unspliced counts provided that both modalities are positive. See [here](https://github.com/theislab/scvelo/blob/f740f28e554ef91447c9a53447eb01096e3bb4c4/scvelo/preprocessing/utils.py#L234) for the respective part of the code.

**Comment by agnese-re** [comment]
I have the same problem. We just need to change the condition in the ifelse statement or we have to add something more specific?
