### ISSUE TITLE
Which genes use for compute latent time?

### ISSUE THREAD

**Issue by hahia** [theislab/scvelo#231]
Hi, I fell confuse about which genes use for compute latent time

After 
```
scv.pp.filter_and_normalize(adata, min_shared_counts=20, n_top_genes=3000)
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
scv.tl.recover_dynamics(adata)
scv.tl.velocity(adata, mode='dynamical')
print(adata.var.velocity_genes.sum())
```

I can get the velocity gene in the adata.var.velocity_genes

Is `scv.tl.latent_time(adata, min_likelihood=0.1)` select genes likelihood more than 0.1 (likelihood of genes come from tl.recoer_dynamics), and these genes intersect with velocity genes, then I get the final gene for latent time computation. 
Am I understanding it right？

**Comment by WeilerP** [comment]
Yes, that is correct.
