### ISSUE TITLE
Should latent time consistent with velocity flow？

### ISSUE THREAD

**Issue by hahia** [theislab/scvelo#232]
Hello, I have a naive question.

I use `min_shared_counts=15,n_top_gene=500`
![image](https://user-images.githubusercontent.com/49113803/85964060-d4afd380-b9ea-11ea-9094-6e0a610f60ee.png)
![image](https://user-images.githubusercontent.com/49113803/85964063-d7122d80-b9ea-11ea-904c-173a3f81fe45.png)

and use `min_shared_counts=10, n_top_gene=500`
![image](https://user-images.githubusercontent.com/49113803/85964097-ee511b00-b9ea-11ea-9701-157789c82f00.png)
![image](https://user-images.githubusercontent.com/49113803/85964100-f315cf00-b9ea-11ea-82dc-6525b68407ea.png)

the latent time look different.
So if base on latent time should consistent with velocity flow, the second parameters is right?
Can I make this conclusion?

**Comment by WeilerP** [comment]
Yes, latent time and velocity should be consistent. Not sure what's going wrong in your first example.
