### ISSUE TITLE
Gene selection

### ISSUE THREAD

**Issue by Marius1311** [theislab/scvelo#236]
Hi guys, I'm experimenting with some simulated data of a simple bifurcation. I used to get the results of Fig 1 when applying the fairly standard scvelo pipeline. However, when I re-run my notebook today, I got the results of Fig 2. I was mildly confused and went through the commits to pinpoint the one where the change occured. I realised the changes are caused by

https://github.com/theislab/scvelo/commit/b79bbef3aaf988646e17df55404d55f2129a537e

which dealt with reformating the `filter_genes_dispersion` function and a utility. Up to this commit, I get results of Fig 1, after and including that commit, Figure 2. I tried to pinpoint the source of the changes within that commit but I was unsucessful. Can you guys help me with this please?

This highlights to me that we **really** need tests for scvelo, at least some pipeline tests that go through a standard workflow and compare results with a set of hard-coded results. I think for a standard workflow with default parameter settings, we should post a warning in the docs in case results are changing. It costs me a ton of time to catch these bugs and I think it could easily be prevented with some basic testing. 

## Fig 1
![image](https://user-images.githubusercontent.com/24494650/86371511-3d17e280-bc81-11ea-9cdc-d3c58b6a3e05.png)

## Fig 2
![image](https://user-images.githubusercontent.com/24494650/86371524-40ab6980-bc81-11ea-9edd-4c9693d485b1.png)

**Comment by VolkerBergen** [comment]
@Marius1311 I could not reproduce it and obtain the exact same genes in both versions. Would appreciate if you could send me your notebook for reproducing the plots.

**Comment by Marius1311** [comment]
sure, will send via seafile and ping you in mattermost.

**Comment by VolkerBergen** [comment]
Pipeline test run successfully. The diff is due to a particular gene that got previously filtered out (upon fixing a scanpy bug in filtering for n_top_genes, https://github.com/theislab/scvelo/commit/b79bbef3aaf988646e17df55404d55f2129a537e).
