### ISSUE TITLE
quantify scvelo to measure dynamics

### ISSUE THREAD

**Issue by manarai** [theislab/scvelo#24]
Hi,

I tested scvelo on inflammed inmmune cells between different aged  mice and I see a nice trend. The arrows going from normal to inflammed cells become smaller with age correlating with reduce immune function in this particular tissue and assay. I want to quantify this. How can I extract the values of the vectors for each cells so I can make an average or plot these on a boxplot?  

Thanks for your help!

**Comment by VolkerBergen** [comment]
Hi manarai,

The length of the embedded velocities mainly reflect two quantities: 
- The actual length in the high dimensional space
- The confidence of how well the embedded velocities (obtained from the velocity graph) represent the actual high dimensional velocity vectors. 

You can access the velocity vectors with `adata.layers['velocity']` and, for instance, compute the lengths for each cell in high dimensional space via `scv.utils.norm(adata.layers['velocity'])`. 

The confidences are obtained and visualized with 
```
scv.tl.velocity_confidence(adata)
scv.tl.velocity_confidence_transition(adata)
scv.pl.scatter(adata, color=['velocity_confidence', 'velocity_confidence_transition'], perc=[2,98], colorbar=True)
```

Further, it might be worth looking at a direct PCA projection of the velocities (which skips the velocity graph) with 
```
scv.tl.velocity_embedding(adata, basis='pca', pca_transform=True)
scv.pl.velocity_embedding(adata, basis='pca')
```

**Comment by manarai** [comment]
Great! Quick look with a box plot and I already see nice correlations between decreasing immune activation of some immune cells with the average lengths of their corresponding velocities, with age. That's very interesting.  Thanks!
