### ISSUE TITLE
gene_count_corr

### ISSUE THREAD

**Issue by ogandril** [theislab/scvelo#240]
Hello

During the normalization stem (scv.pp.filter_and_normalize()) a new .var appears named "gene_count_corr" . 
The description as to what the function returns is somewhat succinct (Returns: | Returns or updates adata depending on copy.).
Can you let me know what this "gene_count_corr" correspond to?

Thank's!

Olivier

**Comment by WeilerP** [comment]
Should be the correlation between counts per gene and the number of non-negative counts per observation. See [here](https://github.com/theislab/scvelo/blob/1659cc8e00a45fcf87cd80a7013aae5531744613/scvelo/preprocessing/utils.py#L681) and [here](https://github.com/theislab/scvelo/blob/1659cc8e00a45fcf87cd80a7013aae5531744613/scvelo/preprocessing/utils.py#L541).
