### ISSUE TITLE
Reverse the trajectories

### ISSUE THREAD

**Issue by MalteMederacke** [theislab/scvelo#245]
Hi,

great tool! I am wondering if its possible to reverse the trajectories of the velocities, as they show exactly the opposite of what we would expect. This appears not only to be the case with scVelo. but with other pseudotime analysis tools as well. Is there maybe a technical reason why we observe such a pattern?

Best, 

Malte

**Comment by WeilerP** [comment]
No, this is not possible. For a possible reason see e.g. #216 and #459.
