### ISSUE TITLE
Runtime of tl.recover_dynamics

### ISSUE THREAD

**Issue by michalk8** [theislab/scvelo#247]
Hi @VolkerBergen ,
I'm running scvelo on a data of size `104679 x 1500` (after preprocessing) on the ICB's servers, but I think `scv.tl.recover_dynamics(adata)` is taking too long (32 cores, 64GB of RAM, job cancelled after 14h). The core usage is at minimum (on in a while it uses all of them, but I think that's one of the `scipy` or numpy`'s optimization routines`) and I don't think this is a server issue.

Questions:
- How long would you expect to run it with the default parameters?
- Would scvelo benefit from parallelization, either using joblib or numba (it still doesn't support sparse matrices, so there will be issues)? And if so, any plans for it?

**Comment by plath997** [comment]
I ran on a dataset of a larger size (~192k cells x ~15k genes) and it took 55 hours to complete using 500GB RAM on 4 cores.

**Comment by preetida** [comment]
Hi, 
I. have a similar problem, I am running after filter marix which is big. ` n_obs × n_vars = 96344 × 36601`
I am running on local on Mac  (12 cores, 64GB of RAM), got into memory error. 
I am now running on cluster, and can ask more core, What is the best way to ask more resources 

`scv.tl.recover_dynamics(adata, n_jobs=32)`

**Comment by dawe** [comment]
I don't want to make this a RAM-usage challenge, but I have a ~12k x 50k matrix and I had RAM peaks > 240Gb. Also, I found that running in jupyter multiple velocity estimations on the same object (in chain, one after the other) is not memory-friendly (blame python, I guess), and eventually crashes.

**Comment by WeilerP** [comment]
@preetida , @dawe the recovery of the underlying dynamics is currently being refactored s.t. it is, amongst other things, memory efficient. Hope to merge a first prototype in the coming days.
I'll already close this issue, though, as it was focused on improving the runtime of `tl.recover_dynamics` which was solved by #342. I'll open a new issue specifically for the memory issue. Feel free to repost your problems/experience there.
