### ISSUE TITLE
what is the range of splicing rate (β）

### ISSUE THREAD

**Issue by houruiyan** [theislab/scvelo#248]
Hi Dr Bergen,

I got splicing rate (β） through scv.tl.velocity(adata,mode='dynamical').
I found some β values were more than 1 and the most β values were less than 1 and more than 0. 
And I found there was a picture about β in your thesis.
 
<img width="247" alt="屏幕快照 2020-07-13 下午8 26 17" src="https://user-images.githubusercontent.com/56068158/87304261-21e18880-c547-11ea-8496-7473c628cb34.png">

I find your β seems in a range of 0 and 1. So I am confused about the distribution of splicing rate. Could you help me to solve this problem? 

Thank you in advanced!

Ruiyan Hou

**Comment by VolkerBergen** [comment]
It depends on the units - say we're talking about hours. Then, rate of splicing corresponds to the amount that is spliced in 1h. We usually have halflifes of few up to around 20 hours. Thus, the overall time-scale is per default set to 20h. Given that halflife = ln(2) / degradation rate, and assuming that degradation rates and splicing rates (usually log-normally distributed) are partly correlated (not generally true), than the rates could go from 0.03 (corresponding to a halflife of 20h) to anywhere like 1.5 (halflife of 30min). So, none of the rates necessarily need to be below 1.

**Comment by houruiyan** [comment]
Thank you very much! You are really kind!

**Comment by houruiyan** [comment]
Dear Dr Bergen,

That means that the beta and the gamma value I get from scvelo corresponding to a half-life whose unit is hour. Is that right?
In addition, I did the correlation between the fit_gamma in dynamic model and velocity_gamma in stochastic model. I found that they do not have a good correlation. But when I did the correlation between fit_beta from dynamic model and velocity_gamma from stochastic model, I found the correlation is really high. Could you tell me the reason? Thank you!

**Comment by WeilerP** [comment]
@houruiyan, you are comparing two different things here: In both steady state and stochastic model, the estimated splicing degradation rate `gamma` is measured in terms of the splicing rate `beta`. For the dynamical system we infer both `beta` and `gamma`. Comparing the fitted values as you do on the pancreas data, for example, you will see that the correlation is not significant. I'd say the correlation is merely a coincident in your case.
