### ISSUE TITLE
How are cosine correlations being computed?

### ISSUE THREAD

**Issue by Marius1311** [theislab/scvelo#250]
So I'm trying to figure out how precisely the cosine correlations are being computed. I compute them using scvelo by running
```python
scv.tl.velocity(adata)
sc.pp.neighbors(adata, n_neighbors=100)
scv.tl.velocity_graph(adata, mode_neighbors='connectivities', sqrt_transform=False)

# get the computed velocity graph values
vgraph = adata.uns['velocity_graph'] + adata.uns['velocity_graph_neg']
```

Then I try to reproduce this for a single cell by running
```python
from scvelo.utils import  cosine_correlation, norm

subset = np.array(adata.var['velocity_genes'].values, dtype=bool)
adata_ = adata[:, subset].copy()

X = np.array(adata_.layers['Ms'], dtype=np.float32)
V = np.array(adata_.layers['velocity'], dtype=np.float32)

# get indices of the neighbors of a reference cell
ref_ix = 7
C = adata.obsp['connectivities']
neighbors_ix = C[ref_ix, :].indices

# compute cosine correlations
dX = X[neighbors_ix] - X[ref_ix, None]
dX /= norm(dX)[:, None]
v = V[ref_ix, :]

# check whether all of these are finite
assert(np.isfinite(dX).all()), "Some elements in dX were not finite"
assert(np.isfinite(v).all()), "Some elements in v were not finite"

val = cosine_correlation(dX, v)[0]
```

This gets me quite close. Running `print(vgraph[ref_ix, :].data[:10])` gives
```
array([0.00324127, 0.17267656, 0.02051987, 0.09439137, 0.07927924,
       0.06423732, 0.01564388, 0.0598949 , 0.08274952, 0.01046317],
      dtype=float32)
```
while running `print(val[:10])` gives
```
array([0.00315533, 0.1680978 , 0.01997568, 0.09188831, 0.07717688,
       0.06253388, 0.01522904, 0.05830675, 0.08055514, 0.01018569],
      dtype=float32)
```

Conceptually, I'm just wondering where the remaining deviations come from?

**Comment by Marius1311** [comment]
Okay, so the trick is mean-centering the velocities as well, `V -= np.nanmean(V, axis=1)[:, None]`. Having done that, the two arrays match exactly, as expected.

**Comment by suragnair** [comment]
Hey Marius, thanks for this analysis. Note that in addition to mean-centering `V`, `dX` is also mean-centered internally in `cosine_correlation`. 

I was wondering what the logic behind the mean-centering is. In general, if a large number of genes are used, the mean is usually pretty close to zero.

I foresee issues when the method is run on a smaller number of genes:
- Mean-centering would potentially flip signs for some genes, which is not ideal since the sign of velocities is important
- When `scv.tl.velocity_graph` is run on a small subset of genes, potentially genes with highly similar velocities across cells (for interpreting a group of marker genes, say), such that velocities of the genes have the same signs in a given cell, mean-centering will force half genes to have the opposite sign which would likely lead to unexpected results.

**Comment by Marius1311** [comment]
@suragnair, this is really a question of what measure to use to compare velocity vectors with state-change vectors. If you mean-center before computing cosine-correlation, you end up with Pearson's correlation. See the below preprint for a discussion of the implications: 

https://www.biorxiv.org/content/10.1101/2020.09.19.304584v1

**Comment by suragnair** [comment]
Thanks for the pointer, I'll check it out. As I mentioned, the results would likely be identical when many genes are considered. I ran a few small checks with and without mean-centering for smaller sets of genes. 

Specifically, I commented out 
https://github.com/theislab/scvelo/blob/8351f46922903f20eee61def96e7cc7af47a0475/scvelo/tools/velocity_graph.py#L90
and replaced this 
https://github.com/theislab/scvelo/blob/8351f46922903f20eee61def96e7cc7af47a0475/scvelo/tools/utils.py#L96
with `dx = dX`.

For the Dentate Gyrus dataset, consider top 3 genes for Granule immature cluster on running `scv.pl.rank_velocity_genes` (Shisa9, Jph1, Sphkap):
![GIGenes](https://user-images.githubusercontent.com/10693069/95736001-43b3ee00-0ca3-11eb-9e5e-b4d3dafa46e9.png)

When `scv.tl.velocity_graph` is run with `gene_subset=['Shisa9', 'Jph1', 'Sphkap']`, the outputs:
![MC](https://user-images.githubusercontent.com/10693069/95736557-06039500-0ca4-11eb-95a4-5eb9a0ed19e3.png)

Moreover, by just making the two changes above, the error when running `scv.tl.velocity_graph` with just a single gene as input to `gene_subset` goes away. Running `scv.tl.velocity_graph` without mean entering for each of the 3 genes gives:
![Unknown-4](https://user-images.githubusercontent.com/10693069/95737330-22ec9800-0ca5-11eb-9f57-142f6534e331.png)

Results seem to make more sense without mean centering. Can share more such examples if required.

**Comment by Marius1311** [comment]
Thanks for this analysis @suragnair !

**Comment by Marius1311** [comment]
Btw, @suragnair , feel free to checkout our new software package called CellRank at https://cellrank.org where build onto the scvelo-estimated velocities to look into fate probabilities and the like. I think this would be a better place to include different metrics for velocity graph estimation as CellRank is made to quantitatively analyse velocities. It consists of `kernels` and `estimators`, where the former build transition matrices based on vector fields and the latter perform inference based on kernels. We could think of adding extra similarity metrics to our `VelocityKernel` class. Feel free to open an issue in CellRank so we can discuss this further!
