### ISSUE TITLE
About  retain_genes in filter_and_normalize

### ISSUE THREAD

**Issue by hahia** [theislab/scvelo#253]
Hello

I try to use retain_genes parameter to retain the gene we are interested in. 
but there don't have this parameter. 
![image](https://user-images.githubusercontent.com/49113803/88050445-74dfbf00-cb89-11ea-92b7-fab700e8738f.png)

But I see this in here
![image](https://user-images.githubusercontent.com/49113803/88050245-0b5fb080-cb89-11ea-89d5-90f628266534.png)

I fell little confuse.
So how can I retain the gene we interested in? 
Thanks any comments!!!!!

**Comment by VolkerBergen** [comment]
You're probably working on an outdated version. Consider upgrading scvelo, it should be available from v0.2.2.
