### ISSUE TITLE
How to get transition matrix?

### ISSUE THREAD

**Issue by hahia** [theislab/scvelo#258]
Hello

I'm new to python and scVelo,

I want to get cell-cell transition matrix, how can I get it? and how to save this matrix as csv or other format, so I can deal with is use R?

**Comment by noorisotoudeh** [comment]
as tutorial https://scvelo.readthedocs.io/VelocityBasics.html says use 
scv.utils.get_transition_matrix

by using print() of the above command you can see what is included in transition matrix. In my case, the transition matrix is a sparse matrix and it doesn't make sense to me to convert it to CSV file.

**Comment by hahia** [comment]
> as tutorial https://scvelo.readthedocs.io/VelocityBasics.html says use
> scv.utils.get_transition_matrix
> 
> by using print() of the above command you can see what is included in transition matrix. In my case, the transition matrix is a sparse matrix and it doesn't make sense to me to convert it to CSV file.

Hello, thank you for your comment!!
I use .toarray convert the sparse matrix into numpy array then save it as csv use np.savetxt. It seems work.
