### ISSUE TITLE
Logarithmization message

### ISSUE THREAD

**Issue by SamueleSoraggi** [theislab/scvelo#26]
Hej,
I noticed a small thing that has created a little bit of confusion in me :)

I have been using `scvelo.pp.filter_and_normalize(all_data, min_counts=20, min_counts_u=10)` when playing around on my data, that has been merged with a dataset on which I applied the scanpy clustering tools (louvain, umap, tsne and paga). The matrix X has been logarithmized during the analysis.

Nonetheless I get the following message when running `scvelo.pp.moments(all_data, n_pcs=15, n_neighbors=30)`:

```
Consider to logarithmize adata.X with `scv.pp.log1p` for better results.
```

The same happens even when I first apply `scvelo.pp.log1p(all_data_loom)`. However, such a message disappears when using a dataset not merged with another one handled with scanpy. Is it possible that scanpy and scvelo check in a different way if the data has been logarithmized?

**Comment by VolkerBergen** [comment]
Hi Samuele,
I admit that's indeed confusing. The verification check appears to be too naive, as it roughly compares `X` with the log of `adata.layers['spliced']`. That would always return a warning message, when the data is (besides log-normalization) further preprocessed (e.g. batch-corrected). You can ignore that for now. I'll adjust it for the next release. 

Just keep in mind to set `log=False` in `scv.pp.filter_and_normalize(adata, **params, log=False)` when your data is already logarithmized.

**Comment by SamueleSoraggi** [comment]
Super,

thanks for the hint.

**Comment by VolkerBergen** [comment]
Logging should be less confusing now. Thanks for addressing this! 

The auto-detection of already preprocessed data (e.g. when X is preprocessed, but spliced/unspliced are not yet) has also been substantially improved.
