### ISSUE TITLE
Merging multiple loom files: adata + ldata

### ISSUE THREAD

**Issue by whitleyo** [theislab/scvelo#263]
Expect scvelo.merge to merge cells from two scvelo AnnData objects (i.e. barcode observations).

Instead, merged object has ~7 cells. Looking through source code, it appears that  [scvelo.merge](https://github.com/theislab/scvelo/blob/master/scvelo/read_load.py#L138-L221)  instead subsets adata input for common observations with ldata input.

...

```python
import scvelo as scv
import os
import re
import numpy as np
import pandas as pd
# set figure parameters
scv.set_figure_params()

# directory names renamed from original code as it deals with work currently underway
top_dir = '/home/asdf/projects/asdf/'
data_dir = os.path.join(top_dir, 'asdf')

# load data
file_names = os.listdir(data_dir)
# file_names = [x for x in file_names if re.match('.loom$', x)]
print(file_names[0:2])

def rename_scv_obj(scv_obj, prefix):
    scv_obj.var_names_make_unique()
    rename_idx = {}
    for x in scv_obj.obs.index.values:
        barcode = re.search('[ACTG]+x$', str(x)).group(0)
        barcode = re.search('[ACTG]+', barcode).group(0)
        rename_idx[x] = prefix + barcode
    df_new = scv_obj.obs.rename(index = rename_idx)
    scv_obj.obs = df_new
    return(scv_obj)

# cell_name_regex = '(G|BT)[0-9]+-*[A-Z]*_[TL]_[ATCG]*$'
sample_name_regex = '(G|BT)[0-9]+-*[A-Z]*_[TL]'

for i in range(2):
    fname = file_names[i]
    sample_name_match = re.search(sample_name_regex, fname)
    if sample_name_match:
        sample_name = sample_name_match.group(0)
        sample_prefix = sample_name + '_'
    else:
        raise ValueError('more than 1 match for sample_name_regex in file ' + fname)
    fpath = os.path.join(data_dir, fname)
    loaded_obj = scv.read(fpath, cache=True) 
    loaded_obj = rename_scv_obj(loaded_obj, sample_prefix)
    print('## Number of observations in sample:')
    print(len(loaded_obj.obs.index))
    if i == 0:
        adata = loaded_obj
    else:
        ldata = loaded_obj
        adata = scv.utils.merge(adata, ldata, copy = True)

print('## observations in merged object')
len(adata.obs.index)

...
```

<details>
<summary> Error </summary>
```pytb


['G885_L.loom', 'G1003-D_T.loom']

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

\## Number of observations in sample:
1048
\## Number of observations in sample:
1701
\## observations in merged object
7

...
```
</details>

#### Versions:

scvelo==0.2.2  scanpy==1.5.1  anndata==0.7.4  loompy==3.0.6  numpy==1.19.1  scipy==1.5.2  matplotlib==3.3.0  sklearn==0.23.2  pandas==1.0.5  

>

**Comment by VolkerBergen** [comment]
(sorry for the late response - I've been out of office for a while)

I think what you're looking for is concatenating, not merging, i.e. `adata = adata.concatenate(adata2)1`.

**Comment by whitleyo** [comment]
Looks like this should work, but I ended up circumventing the problem using the [loompy package](http://linnarssonlab.org/loompy/index.html), specifically the [combine](http://linnarssonlab.org/loompy/fullapi/combine.html?highlight=combine) function to make a unified loom file prior to running the standard scvelo pipeline as outlined in the [tutorial](https://scvelo.readthedocs.io/VelocityBasics.html). Will close for now

**Comment by denvercal1234GitHub** [comment]
Hi @whitleyo -- Would you mind sharing the R codes you used to merge the several loom objects? Thank you for your help.
