### ISSUE TITLE
Velocity pseudotime "group by" returns a column with NaN when it used to work days ago

### ISSUE THREAD

**Issue by Ngort** [theislab/scvelo#264]
Velocity pseudotime grouped by obs column "state" used to work; for unknown reason it only produces NaN now. Either ungrouped or grouped by other variables works.

```python
scv.pp.moments(ldata)
scv.tl.velocity(ldata, mode='deterministic')
scv.tl.velocity_graph(ldata)
scv.tl.score_genes_cell_cycle(ldata)

scv.tl.velocity_pseudotime(ldata) # produces normal array
scv.tl.velocity_pseudotime(ldata, groupby='state') #produces array of NaN


```

<details>
Array of NaN
<summary> Error </summary>
```pytb
WARNING: Only set groupby, when you have evident distinct clusters/lineages, each with an own root and end point.
computing terminal states
WARNING: Only set groupby, when you have evident distinct clusters/lineages, each with an own root and end point.
    identified 1 region of root cells and 2 regions of end points  (24hpf-differentiating neurons)
    finished (0:00:00) --> added
    'root_cells', root cells of Markov diffusion process (adata.obs)
    'end_points', end points of Markov diffusion process (adata.obs)

```
</details>

#### Versions:

scvelo==0.2.1  scanpy==1.5.1  anndata==0.7.1  loompy==3.0.6  numpy==1.19.1  scipy==1.5.1  matplotlib==3.3.0  sklearn==0.23.1  pandas==1.0.3  WARNING: There is a newer scvelo version available on PyPI:

>

**Comment by VolkerBergen** [comment]
(sorry for the late response - I've been out of office for a while) 

Would you please let me know what your `adata.obs['state']` is?
`scv.pl.scatter(adata, c='state')` and `print(adata.obs['state'])`.

**Comment by WeilerP** [comment]
@Ngort, were you able to resolve the issue by now?

**Comment by WeilerP** [comment]
I am closing this since substantial time has passed since the last exchange. @Ngort, happy to reopen should you still encounter the problem.

**Comment by yingyonghui** [comment]
Hi @Ngort were you able to resolve the issue now? 
I've just met the same issue and any suggestions would be appreciated!

Thanks!
Yonghui
