### ISSUE TITLE
Generating imput file

### ISSUE THREAD

**Issue by eynullazada** [theislab/scvelo#266]
Hi

I am very new to computational biology. I am trying to apply your script to my scRNA-seq data, but I am not able to figure out what should be the format of input files? I have fastq files. Where can I find instruction on generating scVelo compatible input format from the fastq files I have?

looking forward to hearing from you.

Best

Khagani

**Comment by MalteMederacke** [comment]
In the paper they state, that they use the formatting tools of velocyto to preprocess the drop-seq data.

**Comment by VolkerBergen** [comment]
The alignment is done with [velocyto](https://velocyto.org/velocyto.py/tutorial/cli.html) to generate the loom file, which then is used in scvelo downstream to do velocity analysis.
