### ISSUE TITLE
Plot smoothed velocities

### ISSUE THREAD

**Issue by SamueleSoraggi** [theislab/scvelo#27]
Hello,

I have opened the github page of scvelo and noticed that there is a plot where the velocities are smoothed instead of being over each single cell. That seems a bit of a more clear view of the cell dynamics.

I cannot find the way of recreating something with my data by checking in the documentation. Could you please provide which command and options are to be used? Or is it something that has been implemented by the author of the picture out of the scvelo tool?

Thanks for the great job with scvelo,
Samuele

**Comment by VolkerBergen** [comment]
Hi Samuele,

It's simply `scv.pl.velocity_embedding_stream(adata)`.

I haven't put it in the docs yet, as I'm still preparing a couple novelties for the next release. Will be updated within the next days.

**Comment by SamueleSoraggi** [comment]
Many thanks, 

I will just wait for the finalization and the update.

**Comment by VolkerBergen** [comment]
It's now included in the docs and exemplary at https://github.com/theislab/scvelo_notebooks/blob/master/DentateGyrus.ipynb
