### ISSUE TITLE
Splicing proportions incorrect / Duplicated cells?

### ISSUE THREAD

**Issue by andrewni4313** [theislab/scvelo#276]
I have been struggling with this issue for quite a while and have not stumbled across a solution. I am working with two runs of 10x data that I have analyzed in Seurat and wish to perform velocity analysis on a subset of the cells. I counted spliced/unspliced RNA using velocyto using the same commands for both batches (_old, new_) generating two loom files.

The splicing proportions seems semi-correct for _new_ but is wildly wrong for _old_.
Also not sure if this is relevant but I got a warning that `Variable names are not unique. To make them unique, call .var_names_make_unique.` when reading both files. I made them unique so I could concatenate the loom files.

Old:
```
View of AnnData object with n_obs × n_vars = 2297 × 32285
    var: 'Accession', 'Chromosome', 'End', 'Start', 'Strand'
    layers: 'ambiguous', 'matrix', 'spliced', 'unspliced'
```
`scv.pl.proportions(old)`
![image](https://user-images.githubusercontent.com/45903831/92317083-86aae380-efca-11ea-81bb-ee482c9efc64.png)
New:
```
View of AnnData object with n_obs × n_vars = 1193 × 32285
    var: 'Accession', 'Chromosome', 'End', 'Start', 'Strand'
    layers: 'ambiguous', 'matrix', 'spliced', 'unspliced'
```
`scv.pl.proportions(new)`
![image](https://user-images.githubusercontent.com/45903831/92317086-8ad70100-efca-11ea-92da-9387d8f74b37.png)

I did an integrated analysis and Seurat so I combined the loom files using `velo = old.concatenate(new, index_unique = None)` 
Running the analysis simply gave `WARNING: You seem to have 2296 duplicate cells in your data. Consider removing these via pp.remove_duplicate_cells` and then errored out with `ValueError: Your neighbor graph seems to be corrupted. Consider recomputing via pp.neighbors.`

Using the _new_ batch only, however, yielded results with no issues:
![image](https://user-images.githubusercontent.com/45903831/92317114-0f298400-efcb-11ea-84ae-e0911cac9dd3.png)

I am not sure what went wrong. It might be an issue with velocyto but I used the same commands to generate the two files and I have run the pipeline multiple times to check.
If needed I can provide the command log from velocyto.

Any help would be greatly appreciated!

**Comment by VolkerBergen** [comment]
Seems that sth definitely went wrong  (these proportion of un/spliced is unexpected in either way). 

Could you check the proportions in your raw loom file (before passing to Seurat)? 

Also check how `adata.obs_names` look like.
