### ISSUE TITLE
error while running velocyto

### ISSUE THREAD

**Issue by eynullazada** [theislab/scvelo#282]
Hi

When I try to run velocyto on bam file to generate  a loom file, it generates the following error:
IOError("The bam file does not contain cell and umi barcodes appropriatelly formatted. If you are runnin UMI-less data you should use the -U flag.")

The way I am running the velocyto is:

>> velocyto run -o out A2S_Day6_sorted.bam Mus_musculus.GRCm38.100.abinitio.gtf

I tried to run with -U option as well, but it did not help.

How can I resolve this issue?

Best

**Comment by VolkerBergen** [comment]
Could also try the `-t` flag for sorting the bam files. Otherwise, you'd need to raise the issue [here](https://github.com/velocyto-team/velocyto.py).
