### ISSUE TITLE
Negative control for RNA velocity results

### ISSUE THREAD

**Issue by jonathan-f** [theislab/scvelo#285]
Hi @VolkerBergen, is there a negative control for the RNA velocity results already implemented in scvelo? I mean a randomisation procedure as in velocyto (option "calculate_randomized" in the function "estimate_transition_prob" or something like the binomial randomisation that they describe in Supplementary Note 2 in the RNA velocity paper).

Thank you,
Best,
Jonathan

**Comment by VolkerBergen** [comment]
Yes, you'd find it [here](https://github.com/theislab/scvelo/blob/1ff51ba53f7fcedadb9ee147aac81383926dd9f6/scvelo/tools/utils.py#L216) and running 
```
scv.utils.randomized_velocity(adata)
scv.pl.velocity_embedding_stream(adata, vkey=['velocity', 'velocity_random'])
``` 
on pancreas yields sth. like that
![image](https://user-images.githubusercontent.com/31883718/95124486-cabd0f80-0753-11eb-8090-acc14fb15a07.png)
