### ISSUE TITLE
scvelo.tl.recover_dynamics ignores var_names param, calculates velocity for all genes

### ISSUE THREAD

**Issue by mtvector** [theislab/scvelo#286]
Hi there,
Beautiful code, great work! My issue is that scvelo.tl.velocity seems to ignore what I give to var_names and always recovers dynamics for all genes, which takes a very long time.

I run the preprocessing steps:
```
ncells=20
mgenes=(adata.layers['unspliced']>0).sum(0) > ncells
adata.var['velocity_genes']=mgenes.A1&adata.var['highly_variable']
print(list(adata.var['velocity_genes']))
scv.pp.normalize_per_cell(adata)
scv.pp.log1p(adata)
scv.pp.remove_duplicate_cells(adata)
scv.pp.moments(adata, n_neighbors=20)
```
Which shows that the var column 'velocity_genes' I have added is about 1/5 of the total genes:
```
[False, True, True, True, True, False, False, False, False, False, False, True ... ]
```
And then when I run:
```
scv.tl.recover_dynamics(adata,var_names='velocity_genes',use_raw=False)
```
It goes and calculates the dynamics for every gene!

Indeed, the above takes 5X as long as it takes to run if, during preprocessing, I've simply subset out all the genes I don't want with:
```
adata=adata[:,mgenes.A1]
adata=adata[:,adata.var['highly_variable']]
```
However I'd like to not subset, as I want to analyze expression of all genes along the trajectories scvelo calculates.

Thanks for any help you can provide!

M

#### Versions:

scvelo==0.2.1  scanpy==1.6.0  anndata==0.7.4  loompy==2.0.17  numpy==1.19.1  scipy==1.5.0  matplotlib==3.3.1  sklearn==0.23.1  pandas==1.0.5

**Comment by WeilerP** [comment]
Could you provide a working examples including data where the described problem occurs? I just ran the following code and only velocity genes are recovered:

```python
>>> import numpy as np
>>> import pandas as pd
>>>
>>> from anndata import AnnData
>>>
>>> import scvelo as scv
>>>
>>> N_GENES = 500
>>> N_SAMPLES = 10
>>>
>>> adata = AnnData(
...     pd.DataFrame(
...         np.random.randint(0, 100, (N_GENES, N_GENES)),
...         columns=[f"gene_{id}" for id in range(N_GENES)],
...         index=[f"cell_{id}" for id in range(N_GENES)]
...     ),
...     layers={
...         "spliced": np.random.randint(0, 100, (N_GENES, N_GENES)),
...         "unspliced": np.random.randint(0, 100, (N_GENES, N_GENES)),
...     }
... )
>>> adata.var["velocity_genes"] = np.random.choice([True, False], size=N_GENES)
>>> adata
AnnData object with n_obs × n_vars = 500 × 500
    var: 'velocity_genes'
    layers: 'spliced', 'unspliced'
>>>
>>> print(f"Velocity genes: {adata.var['velocity_genes'].head()}")
Velocity genes: gene_0    False
gene_1     True
gene_2    False
gene_3    False
gene_4     True
Name: velocity_genes, dtype: bool
>>>
>>> scv.pp.normalize_per_cell(adata)
Normalized count data: X, spliced, unspliced.
>>> scv.pp.log1p(adata)
>>> scv.pp.remove_duplicate_cells(adata)
>>> scv.pp.moments(adata, n_neighbors=5)
computing neighbors
    finished (0:00:02) --> added
    'distances' and 'connectivities', weighted adjacency matrices (adata.obsp)
computing moments based on connectivities
    finished (0:00:00) --> added
    'Ms' and 'Mu', moments of un/spliced abundances (adata.layers)
>>>
>>> scv.tl.recover_dynamics(adata, var_names="velocity_genes", use_raw=False)
    finished (0:00:22) --> added
    'fit_pars', fitted parameters for splicing dynamics (adata.var)
>>>
adata.var.head()
        velocity_genes  fit_alpha  fit_beta  fit_gamma     fit_t_  fit_scaling  fit_std_u  ...  fit_u0  fit_s0  fit_pval_steady  fit_steady_u  fit_steady_s  fit_variance  fit_alignment_scaling
gene_0           False        NaN       NaN        NaN        NaN          NaN        NaN  ...     NaN     NaN              NaN           NaN           NaN           NaN                    NaN
gene_1            True  17.951180  0.287439   0.200470  13.720991     0.460678  10.921831  ...     0.0     0.0         0.494431     46.284691     52.580421      1.129440               3.525793
gene_2           False        NaN       NaN        NaN        NaN          NaN        NaN  ...     NaN     NaN              NaN           NaN           NaN           NaN                    NaN
gene_3           False        NaN       NaN        NaN        NaN          NaN        NaN  ...     NaN     NaN              NaN           NaN           NaN           NaN                    NaN
gene_4            True   6.972778  0.126378   0.068622  29.336434     1.712362  11.171745  ...     0.0     0.0         0.493290     47.403840     48.823949      1.226796               7.624588

[5 rows x 16 columns]
```

If the problem is indeed that the velocity is recovered for every gene, there shouldn't be `NaN` values for non-velocity genes.

**Comment by mtvector** [comment]
Hi there,
Thanks for your response! So you're right, it isn't recovering the velocity for the genes not labeled 'velocity_genes', as your test code demonstrates. However I'm wondering why the genes that aren't having velocity recovered still have 'fit_r2' values and are affecting the computation time... 

```
scv.tl.recover_dynamics(adata,var_names='velocity_genes',use_raw=False)
```
The time to run is as below, and all genes have 'fit_r2' values.
```
recovering dynamics
    finished (0:57:48) --> added 
    'fit_pars', fitted parameters for splicing dynamics (adata.var)
```
However completely discarding the non 'velocity_genes', it is way faster.
```
adata=adata[:,adata.var['velocity_genes']]
scv.tl.recover_dynamics(adata,var_names='velocity_genes',use_raw=False)
```
The output:
```
recovering dynamics
    finished (0:04:29) --> added 
    'fit_pars', fitted parameters for splicing dynamics (adata.var)
```

Is there a reason that it would be doing calculations on genes it isn't using for the velocity model? Does this extra computation have any benefit to the recovered velocities?

Thanks for the clarification!

M

P.S. I'm sorry I can't share my data, but I don't think it's necessary to answer this more clarified question :)

**Comment by WeilerP** [comment]
Hm, I am unsure why there is such a big discrepancy between the two runtimes. It might simply be due to the different size of the annotated data objects (in terms of memory). Also, did you run the two experiments independently of one another or after one another? Definitely worth investigating either way.

___

When running the above example, the resulting column names of `adata.var` do not include `"fit_r2"`

```python
>>> adata.var.columns
Index(['velocity_genes', 'gene_count_corr', 'fit_alpha', 'fit_beta',
       'fit_gamma', 'fit_t_', 'fit_scaling', 'fit_std_u', 'fit_std_s',
       'fit_likelihood', 'fit_u0', 'fit_s0', 'fit_pval_steady', 'fit_steady_u',
       'fit_steady_s', 'fit_variance', 'fit_alignment_scaling'],
      dtype='object')
```

The `R2` score is only determined when calculating the velocity based on the steady state model introduced by [LaManno et al.](https://www.nature.com/articles/s41586-018-0414-6). This happens when passing `var_names="velocity_genes"` but `"velocity_genes"` is not yet a column in `adata.var`. This is happening in `recover_dynamics` [here](https://github.com/theislab/scvelo/blob/1ff51ba53f7fcedadb9ee147aac81383926dd9f6/scvelo/tools/dynamical_model.py#L432). Alternatively, the column `"fit_r2"` is added when running the function `velocity` [here](https://github.com/theislab/scvelo/blob/1ff51ba53f7fcedadb9ee147aac81383926dd9f6/scvelo/tools/velocity.py#L184).
Could this be an explanation for why the column `"fit_r2"` exists, i.e. the column `"fit_r2"` is only an artefact of a previous run?

**Comment by mtvector** [comment]
Right so that makes sense, it does seem to be calculating the velocity during `recover dynamics` and I think the great speed bump after I've subset is simply that it has already calculated the velocity in the subset, since I'm running them in serial.

I'm not sure I understand why it might bypass `if var_names in adata.var.keys():` to hit `elif "_genes" in var_names:` which runs the velocity. I'll look into it.

**Comment by WeilerP** [comment]
Did you manage identifying the problem?

**Comment by VolkerBergen** [comment]
hi @mtvector, interesting and needs to investigated. Yet, I could not reproduce these runtime differences.

Minimal code example
``` 
adata = scv.datasets.toy_data(n_obs=100)
scv.pp.moments(adata)

adata.var['velocity_genes']=((adata.layers['unspliced']>0).sum(0) > 30).A1
print(adata.var['velocity_genes'].sum())
scv.tl.recover_dynamics(adata)

adata = adata[:, adata.var.velocity_genes].copy()
scv.tl.recover_dynamics(adata)
``` 

that yields the exact same runtime.

**Comment by mtvector** [comment]
Hi there,
I can't replicate the issue anymore, and I haven't been able say for sure what initially caused it. My guess is that I had either incorrectly set 'velocity_genes' or there were RAM issues with the machine I had been using. 
I believe this isn't an issue on your end and the issue can be closed.
Thanks for your help, sorry for the trouble!
M

**Comment by yjgeno** [comment]
Great question! I was still wondering if we will get 'NaN' for the velocity of genes that are not 'velocity_genes'?
