### ISSUE TITLE
Getting spliced and unspliced vector information

### ISSUE THREAD

**Issue by sidrahmaryam** [theislab/scvelo#291]
Hello,

I want to have spliced and unspliced vector information for each cell, with respect to every gene, using scvelo pipeline.
How can I get that information? 

Please help, any help would be highly appreciated.
Thank you.

**Comment by VolkerBergen** [comment]
You'd need to run the counting pipeline via [velocyto](http://velocyto.org/velocyto.py/tutorial/index.html#running-the-cli), then read the loom file into scvelo, there you'd find the counts in `adata.layers['spliced'], adata.layers['unspliced']`.

**Comment by sidrahmaryam** [comment]
Thank you so much for your prompt response. Also highly grateful for this complete workflow. It is really very nice.

I have one more query. Actually, what I want to get is:  Suppose I have 5 past cells, and 2 future cells, and I want to know which of the past cells are converted to the future ones, with time. 

Is there any inbuilt function in scVelo to get the possible cell transformation giving the probability that which cell is derived from which one, not on a cluster basis, but on an individual cell basis?

**Comment by VolkerBergen** [comment]
thank you! 

sure, a rather ad-hoc way would be to simply run the Markov chain forward/backward to identify potential descendants/ancestors. See line 20 [here](https://scvelo.readthedocs.io/VelocityBasics.html). 

A more elegant and compatible framework is given by the recent implementation of cellrank.org, where you can get a fate map, i.e. assigning each cell its probability of ending up in a particular fate (which I believe can also be done backwards to identify ancestors).

**Comment by sidrahmaryam** [comment]
Thank you so much for that. 
I will follow the suggested pipeline. 

And also to mention, scVelo has been a great help for my master's thesis. Thank you for developing it. :)
