### ISSUE TITLE
Velocity Streams for Single/Group of Genes

### ISSUE THREAD

**Issue by suragnair** [theislab/scvelo#292]
Hi, thanks for this great tool! I'm new to RNA velocity so might be off the mark. I was wondering if it would help to have velocity embeddings/streams for a single or group of genes. Currently for interpretation, `scv.pl.velocity` plots the spliced vs unspliced phase plots, velocity and expression, but (at least for me) it doesn't seem to intuitively convey the velocity streams based on that gene. Is there a cheap way to recompute streams for a gene or set of genes? Any alternatives? Would it even be meaningful to look at streams for a single/group of genes?

**Comment by VolkerBergen** [comment]
Yes, you can recompute the projection on a subset of genes with
``` 
scv.tl.velocity_graph(adata, gene_subset=list_of_genes)
scv.tl.velocity_embedding(adata)
scv.pl.velocity_embedding_stream(adata)
```

**Comment by suragnair** [comment]
Thanks for the quick response, this should work!

**Comment by suragnair** [comment]
This requires at least 2 genes otherwise it fails on the `hstack`:

```python
~/anaconda3/envs/r36_cran/lib/python3.8/site-packages/scvelo/tools/velocity_graph.py in compute_cosines(self)
    198             progress.finish()
    199 
--> 200         vals = np.hstack(vals)
    201         vals[np.isnan(vals)] = 0
    202 ```

**Comment by VolkerBergen** [comment]
right, you'd need at least two genes to project into two dimensions.

**Comment by suragnair** [comment]
I noticed that removing mean centering before computing cosine correlations resolves this issue and makes it possible to visualise velocities even for single genes. More in #250.
