### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'tocsr'

### ISSUE THREAD

**Issue by andreariba** [theislab/scvelo#293]
Hi,

running

scv.pp.moments 

I get
"AttributeError: 'tuple' object has no attribute 'tocsr'".

I'm using scanpy=1.6.0, scvelo=0.2.2, numpy=1.19.1

Any idea why?
Thanks
Andrea

**Comment by VolkerBergen** [comment]
Could you please send the full error message to trace it to its origin? It might have to do with scipy, thus upgrading` pip install -U scipy` might already solve it.

**Comment by andreariba** [comment]
Thanks for the fast reply

I have scipy 1.5.2 the full error is the following
I 'm trying to update scipy

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-daa836e40472> in <module>
----> 1 scv.pp.moments(adata, n_pcs=20)

/shared/space2/molina/ribaa/conda_envs/scanpy_scvelo/lib/python3.7/site-packages/scvelo/preprocessing/moments.py in moments(data, n_neighbors, n_pcs, mode, method, use_rep, copy)
     62             use_rep = "X_pca"
     63         neighbors(
---> 64             adata, n_neighbors=n_neighbors, use_rep=use_rep, n_pcs=n_pcs, method=method
     65         )
     66     verify_neighbors(adata)

/shared/space2/molina/ribaa/conda_envs/scanpy_scvelo/lib/python3.7/site-packages/scvelo/preprocessing/neighbors.py in neighbors(adata, n_neighbors, n_pcs, use_rep, knn, random_state, method, metric, metric_kwds, num_threads, copy)
    157                 metric=metric,
    158                 metric_kwds=metric_kwds,
--> 159                 write_knn_indices=True,
    160             )
    161         logg.switch_verbosity("on", module="scanpy")

/shared/space2/molina/ribaa/conda_envs/scanpy_scvelo/lib/python3.7/site-packages/scanpy/neighbors/__init__.py in compute_neighbors(self, n_neighbors, knn, n_pcs, use_rep, method, random_state, write_knn_indices, metric, metric_kwds)
    681         {n_pcs}
    682         {use_rep}
--> 683 
    684         Returns
    685         -------

/shared/space2/molina/ribaa/conda_envs/scanpy_scvelo/lib/python3.7/site-packages/scanpy/neighbors/__init__.py in compute_connectivities_umap(knn_indices, knn_dists, n_obs, n_neighbors, set_op_mix_ratio, local_connectivity)
    322             rows[i * n_neighbors + j] = i
    323             cols[i * n_neighbors + j] = knn_indices[i, j]
--> 324             vals[i * n_neighbors + j] = val
    325 
    326     result = coo_matrix((vals, (rows, cols)),

AttributeError: 'tuple' object has no attribute 'tocsr'
-------------------------------------------------------

Andrea

**Comment by andreariba** [comment]
1.5.2 is already the lastest version of scipy

**Comment by VolkerBergen** [comment]
Alright, you'd probably need to upgrade umap, with `pip install -U umap-learn`.

**Comment by andreariba** [comment]
same for umap-learn I installed already the version 0.4.6

**Comment by VolkerBergen** [comment]
Do you get the same error, if you apply another metric? For instance, after installing `pip install hnswlib`, run `scv.pp.moments(adata, method='hnsw')`. (yields the same neighbor graph, just differs in runtime).

**Comment by andreariba** [comment]
ok thanks that solves the issue i managed to run it with hnsw

**Comment by VolkerBergen** [comment]
Great, hnsw yields the exact same result and is good to go, even with around 3-fold speedup. The issue is then perhaps related to scanpy, maybe https://github.com/theislab/scanpy/issues/1154 even though that should be solved with the latest release.
