### ISSUE TITLE
ValueError in scv.tl.rank_dynamical_genes

### ISSUE THREAD

**Issue by plath997** [theislab/scvelo#294]
I am trying to use the rank dynamical genes function using 'groupby' and I keep getting this error. Any advice would be appreciated.

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.local/lib/python3.6/site-packages/scvelo/tools/dynamical_model.py", line 1074, in rank_dynamical_genes
    [n for n in rankings_gene_names], dtype=[(f"{rn}", "U50") for rn in groups],
  File "/home/data1/miniconda3/lib/python3.6/site-packages/numpy/core/records.py", line 667, in fromarrays
    raise ValueError("mismatch between the number of fields "
ValueError: mismatch between the number of fields and the number of arrays
```

</details>

#### Versions:

scvelo==0.2.2  scanpy==1.6.0  anndata==0.7.4  loompy==2.0.17  numpy==1.19.2  scipy==1.5.2  matplotlib==3.3.1  sklearn==0.23.2  pandas==0.24.2 
>

**Comment by qoiopipq** [comment]
same problem

**Comment by yunkaizhang** [comment]
same here, even with the demo data

**Comment by yunkaizhang** [comment]
previously I was using 0.2.2 and it happens with the demo pancreas dataset, after I upgrade to 0.2.3 the issue seemed to be gone now
