### ISSUE TITLE
WARNING: Did not modify X as it looks preprocessed already.

### ISSUE THREAD

**Issue by YubinXie** [theislab/scvelo#300]
Hi so I input my raw data to the analysis but what I got is:

WARNING: Did not modify X as it looks preprocessed already.

All the downstream analysis is wrong since the data is not logged. Any idea why this is happening?

**Comment by WeilerP** [comment]
Sorry for picking up on this only now. Could you please provide a minimum working example where the problem occurred?

Seems like the entries in `adata.X` and `adata.layers["spliced"]` are not similar (checked [here](https://github.com/theislab/scvelo/blob/1659cc8e00a45fcf87cd80a7013aae5531744613/scvelo/preprocessing/utils.py#L826)) which is interpreted as `X` already being log-transformed.
You can always manually log transform the modalities using the `log1p` function from scanpy.

**Comment by WeilerP** [comment]
@YubinXie, I am closing this issue. Feel free to reopen it should you have further questions.
