### ISSUE TITLE
"Top" velocity genes (by "fit_likelihood") that are false for the "velocity_gene" attribute

### ISSUE THREAD

**Issue by Marcus-NEXUS** [theislab/scvelo#303]
This might be more of a conceptual misunderstanding on my part that I am trying to clarify.

To my knowledge, it is possible to get the top putative driver genes by looking at the genes with the highest `fit_likelihood` values: 
`top_genes = adata.var['fit_likelihood'].sort_values(ascending=False).index`

What I do not completely understand is why some of the genes at the top of the list here are not necessarily true for the `velocity_gene` attribute. (Indeed, they seemed to be sprinkled throughout the top 300 genes I looked at.)

What I am trying to understand is why some of the top putative driver genes would not be classified and used as a "velocity gene" for the purpose of estimating the overall velocity, and what the distinction is.

**Comment by WeilerP** [comment]
@Marcus-NEXUS, sorry for getting to this only now. Could you possibly provide a code snippet of the relevant code you are running as well as figures of genes where the entry in `adata.var.loc[GENE_NAME, "velocity_gene']` is `False` but `fit_likelihood` exists?
By default, only `velocity_genes` are fitted. You can, however, manually specify variables for which to fit a model.

If `"velocity_gene"` is not yet a column in `adata.var`, it is added by fitting the original steady state model. Genes with a sufficiently good fit are estimated to contain information useful when fitting the dynamical model. These genes are assinged `True` in the column `"velocity_genes"`. All other variable are excluded to improve the fit and decrease runtime.

**Comment by WeilerP** [comment]
Closing for now. Happy to reopen.
