### ISSUE TITLE
An error of PAGA velocity graph 

### ISSUE THREAD

**Issue by JingleW** [theislab/scvelo#304]
I am using scVelo for my data. Everything worked until the PAGA velocity graph. 

After running the script: 
adata.uns['neighbors']['distances'] = adata.obsp['distances']
adata.uns['neighbors']['connectivities'] = adata.obsp['connectivities']

scv.tl.paga(adata, groups='clusters')
df = scv.get_df(adata, 'paga/transitions_confidence', precision=2).T
df.style.background_gradient(cmap='Blues').format('{:.2g}')

A table looking likes the example was produced. 

However, when running the script: 
scv.pl.paga(adata, basis='umap', size=50, alpha=.1, min_edge_width=2, node_size_scale=1.5)

An error occurred.
AttributeError                            Traceback (most recent call last)
<ipython-input-217-45a24c1a299b> in <module>
----> 1 scv.pl.paga(adata, basis='umap', size=50, alpha=.1, min_edge_width=2, node_size_scale=1.5)

~/anaconda3/lib/python3.7/site-packages/scvelo/plotting/paga.py in paga(adata, basis, vkey, color, layer, title, threshold, layout, layout_kwds, init_pos, root, labels, single_component, dashed_edges, solid_edges, transitions, node_size_scale, node_size_power, edge_width_scale, min_edge_width, max_edge_width, arrowsize, random_state, pos, node_colors, normalize_to_color, cmap, cax, cb_kwds, add_pos, export_to_gexf, plot, use_raw, size, groups, components, figsize, dpi, show, save, ax, ncols, scatter_flag, **kwargs)
    352             ax = scatter(adata, x=x, y=y, zorder=0, **kwargs)
    353         text_kwds = {"zorder": 1000, "alpha": legend_loc == "on data"}
--> 354         _paga(adata, ax=ax, show=False, text_kwds=text_kwds, **paga_kwargs)
    355 
    356         savefig_or_show(dpi=dpi, save=save, show=show)

~/anaconda3/lib/python3.7/site-packages/scvelo/plotting/paga.py in _paga(adata, threshold, color, layout, layout_kwds, init_pos, root, labels, single_component, solid_edges, dashed_edges, transitions, fontsize, fontweight, fontoutline, text_kwds, node_size_scale, node_size_power, edge_width_scale, min_edge_width, max_edge_width, arrowsize, title, random_state, pos, normalize_to_color, cmap, cax, colorbar, cb_kwds, frameon, add_pos, export_to_gexf, use_raw, colors, groups, plot, show, save, ax, **scatter_kwargs)
    659                 single_component=single_component,
    660                 arrowsize=arrowsize,
--> 661                 pos=pos,
    662             )
    663             if colorbars[icolor]:

~/anaconda3/lib/python3.7/site-packages/scvelo/plotting/paga.py in _paga_graph(adata, ax, solid_edges, dashed_edges, adjacency_solid, adjacency_dashed, transitions, threshold, root, colors, labels, fontsize, fontweight, fontoutline, text_kwds, node_size_scale, node_size_power, edge_width_scale, normalize_to_color, title, pos, cmap, frameon, min_edge_width, max_edge_width, export_to_gexf, colorbar, use_raw, cb_kwds, single_component, arrowsize)
    895             edge_color="grey",
    896             style="dashed",
--> 897             alpha=0.5,
    898         )
    899 

~/anaconda3/lib/python3.7/site-packages/networkx/drawing/nx_pylab.py in draw_networkx_edges(G, pos, edgelist, width, edge_color, style, alpha, arrowstyle, arrowsize, edge_cmap, edge_vmin, edge_vmax, ax, arrows, label, node_size, nodelist, node_shape, connectionstyle, **kwds)
    577     edge_pos = np.asarray([(pos[e[0]], pos[e[1]]) for e in edgelist])
    578 
--> 579     if not cb.iterable(width):
    580         lw = (width,)
    581     else:

AttributeError: module 'matplotlib.cbook' has no attribute 'iterable'
</details>

#### Versions:

> scvelo==0.2.2  scanpy==1.6.0  anndata==0.7.4  loompy==3.0.6  numpy==1.17.2  scipy==1.5.2  matplotlib==3.3.2  sklearn==0.21.3  pandas==1.1.2  

Thanks very much.

**Comment by semir2** [comment]
Maybe something wrong with matplotlib version, should be  2.2.1

**Comment by JingleW** [comment]
Thanks very much. It worked when downgrade the matplotlib.

**Comment by WeilerP** [comment]
Could not replicate the issue. Worked fine for me using `matplotlib>=3.3.2`.
