### ISSUE TITLE
scv.pl.heatmap does not show colorbar

### ISSUE THREAD

**Issue by haozhaozhe** [theislab/scvelo#305]
Hello,

This package works great and gave me a very nice heatmap.

However,when I am trying plot the heatmap, I could not get the color bar... 

Below is the code I am using....

```python
...scv.pl.heatmap(ad_wk, var_names=top_genes, sortby='latent_time', col_color='subclass_diff', n_convolve=30, colorbar = True)

```
Did I do something wrong?

Thank you! 

<details>
<summary> Error </summary>
```pytb
...
```
</details>

#### Versions:

>

**Comment by mzhibo** [comment]
having the same issue

**Comment by mehrankr** [comment]
Same issue here

**Comment by haozhaozhe** [comment]
I had a very awkward work around it....

Since still people need it, I will share mine and hopefully intriguing other people's better solutions!

I simply dig into the scv package and took out the scv.pl.heatmap function and write it out like this 🙂

adata = ad_wk.copy()
var_names=top_genes
sortby ='latent_time'
col_color = 'subclass'
colorbar = True

layer='Ms'
color_map='viridis'
#col_color=None
palette='viridis',
n_convolve=30
standard_scale=0
sort=True
#colorbar=None
col_cluster=False
row_cluster=False,
#figsize=(8, 4)
font_scale=None
show=True
save=None



import seaborn as sns
var_names = [name for name in var_names if name in adata.var_names]

#tkey, xkey = kwargs.pop('tkey', sortby), kwargs.pop('xkey', layer)
tkey = sortby
xkey = layer
time = adata.obs[tkey].values
time = time[np.isfinite(time)]

X = adata[:, var_names].layers[xkey] if xkey in adata.layers.keys() else adata[:, var_names].X
if issparse(X): X = X.A
df = pd.DataFrame(X[np.argsort(time)], columns=var_names)

if n_convolve is not None:
        weights = np.ones(n_convolve) / n_convolve
        for i, gene in enumerate(var_names):
            try:
                df[gene] = np.convolve(df[gene].values, weights, mode='same')
            except: pass  # some extreme cases may not be convolved e.g. due to all-zero counts or nans

if sort:
        max_sort = np.argsort(np.argmax(df.values, axis=0))
        df = pd.DataFrame(df.values[:, max_sort], columns=df.columns[max_sort])
#strings_to_categoricals(adata)
'''
if col_color is not None:
        #col_colors = to_list(col_color)
        col_colors = col_color
        col_color = []
        for i, col in enumerate(col_colors):
            #if not is_categorical(adata, col):
            #    obs_col = adata.obs[col]
            #    adata.obs[col + '_categorical'] = pd.Categorical(np.round(obs_col / np.max(obs_col), 2) * np.max(obs_col))
            #    col += '_categorical'
            #    set_colors_for_categorical_obs(adata, col, palette)
            col_color.append(interpret_colorkey(adata, col)[np.argsort(time)])
'''
if font_scale is not None:
        sns.set(font_scale=font_scale)
#if 'dendrogram_ratio' not in kwargs:
#        kwargs['dendrogram_ratio'] = (.1 if row_cluster else 0, .2 if col_cluster else 0)
#if 'cbar_pos' not in kwargs or not colorbar:
#        kwargs['cbar_pos'] = None

plt.figure()
cm = sns.clustermap(df.T,  col_cluster=col_cluster, row_cluster=row_cluster, cmap=color_map,
                        xticklabels=False, standard_scale=standard_scale, figsize=figsize)
plt.savefig('Figure/Fig_scv/ColorBar.pdf')


This way it generates figures with color bars.

I admit this is not the best solution (nor the second best....) but it works for me.

Hope this helps.

Zhe
________________________________

**Comment by michael-kotliar** [comment]
Based on these two lines, we need to set both `cbar_pos` and `colorbar` parameters to make the color bar appear.
```
    if "cbar_pos" not in kwargs or not colorbar:
        kwargs["cbar_pos"] = None
```

**Comment by WeilerP** [comment]
Thanks @michael-kotliar!
