### ISSUE TITLE
scvelo missed some genes compared to Seurat v3 results

### ISSUE THREAD

**Issue by lijiacd985** [theislab/scvelo#309]
Hi there,

I was using the standard workflow to do scvelo analysis, everything is ok, except that there is a marker gene can be detected by Seurat v3, but failed to detect in scvelo. scvelo can detect another marker gene, but not this one:

scv.pp.filter_genes(data, min_shared_counts=5)
scv.pp.normalize_per_cell(data)
scv.pp.filter_genes_dispersion(data, n_top_genes=6000)
scv.pp.log1p(data)
scv.pp.filter_and_normalize(data, min_shared_counts=5, n_top_genes=6000)
scv.pp.moments(data, n_pcs=30, n_neighbors=30)
scv.tl.velocity(data)
scv.tl.velocity_graph(data)
scv.tl.umap(data)
scv.tl.louvain(data,resolution=0.8)

scv.pl.umap(data, color=['Sox4'],nrows=1,size=8)

ValueError: color key is invalid! pass valid observation annotation or a gene name

Thanks,

Jia

**Comment by WeilerP** [comment]
Sorry, not sure what the question is exactly. You can prevent `scvelo` from filtering out specific genes by specifying them via the argument `retain_genes`. Seems like Seurat v3 and scvelo (with your current settings) use different filter masks. Not sure where the difference is, though.
