### ISSUE TITLE
Plotting several heatmaps in the same figure

### ISSUE THREAD

**Issue by rgranit** [theislab/scvelo#310]
This is a bit of general question, but how does one plot several `scv.pl.heatmap` objects in a single figure?

The function returns `seaborn.matrix.ClusterGrid` and does not accept 'ax' in kwargs 

Thanks!

**Comment by rgranit** [comment]
So far I have yet to come up with a proper solution, but for now I'm exporting the plots as PNG and reloading them as subplots.
e.g. 

    plt.figure(figsize=(30, 15))
    plt.suptitle("Title", fontsize=22)

    plt.subplot(133)
    plt.imshow(mpimg.imread('./figures/heatmap_2.png',format="png"))
    plt.title("expression")
    plt.axis('off')

    plt.subplot(132)
    plt.imshow(mpimg.imread('./figures/heatmap_1.png'), format="png"))
    plt.grid(None) 
    plt.axis('off')

    plt.subplot(131)
    plt.imshow(mpimg.imread('./figures/3.png',format="png"))
    plt.grid(None) 
    plt.axis('off')

    plt.show()

**Comment by WeilerP** [comment]
Seems like [this](https://stackoverflow.com/a/51813562) and ultimately [this](https://stackoverflow.com/questions/35042255/how-to-plot-multiple-seaborn-jointplot-in-subplot/47664533#47664533) should help. From skimming through it, the solution isn't straight forward and a bit tricky.
