### ISSUE TITLE
Clearer remove_duplicate_cells warning message

### ISSUE THREAD

**Issue by danielee0707** [theislab/scvelo#311]
In the pp.neighbors function, sometimes it prompts to remove duplicate cells. But to a user, it's not clear whether it's an error or a warning or just a suggestion, and whether the function should be called before the pp.neighbors function or after. I thought it was a warning that may affects pp.moments function, and put it well before calling the pp.moments, but it turned out that was not correct because PCA was called while removing duplicates well ahead of any other preprecessing functions. And because of how moments checks for existing X_pca, the correct PCA (e.g. n_pcs=40) during neighbors finding never got called again. Thus in the end my plot looked very strange. It would be a good idea to specify when to call the remove duplicates function (e.g. "Consider removing these via pp.remove_duplicate_cells right before or after pp.moments"). Thank you.

**Comment by coolmak32** [comment]
Hi Danielee0707, 
Could you please show to use the command, I am having the same message generated. 
I tried calling it as following: 

scv.pp.filter_genes(adata, min_shared_counts=20).remove_duplicate_cells

But this generated an error, "object has no attribute 'remove_duplicate_cells". 

Thank you

**Comment by danielee0707** [comment]
You should call sc.pp.remove_duplicate_cells(adata) directly.

**Comment by WeilerP** [comment]
@danielee0707, the `scv.pp.neighbors` is (or should be) called immediately prior to `scv.pp.moments`. As such, their shouldn't be any problems IMO.
