### ISSUE TITLE
Discrepancy results in velocity and expression plots using dynamical model 

### ISSUE THREAD

**Issue by qoiopipq** [theislab/scvelo#316]
Great package to use! 

I tried both stochastic and dynamical models for my data. But I observed discrepancy in velocity and expression plots under dynamical model. My understanding is it doesn't matter a gene shows positive or negative velocity, the gene must be expressed first.
 
Clustering plot:
![image](https://user-images.githubusercontent.com/16911467/100697705-d1ca6c00-33ea-11eb-9183-d660cc2cd07e.png)

Under dynamical model, these two genes showing as up-regulated in almost all clusters in velocity plots. But in the expression plots, the first gene was only expressed in the bottom clusters while the second gene was only expressed in the top clusters.

Dynamical model:
![image](https://user-images.githubusercontent.com/16911467/100696304-5915e080-33e7-11eb-8af5-e8b55c144cf3.png)

Similar results were observed in the top10 likelihood genes (these two genes were among top10 genes). 
When I checked these two genes under stochastic model, velocity and expression plots correlated with each other pretty well. 

Stochastic model:
![image](https://user-images.githubusercontent.com/16911467/100697389-fa059b00-33e9-11eb-8fdc-5e1a00183df8.png)

I don't understand why in dynamical model, those genes showing positive velocity while they were not expressed?

**Comment by lb15** [comment]
Hi, I was wondering if you had any more thoughts on this. I see something similar with my data and I'm trying to figure out how to interpret the areas with velocity but no expression. Generally, I usually see positive velocity appearing where there is no expression. Could this be an indication that the gene has not yet been spliced, and so not picked up in expression, but that there are unspliced transcripts?

**Comment by QqQss** [comment]
same issue here!

**Comment by WeilerP** [comment]
I'm moving this to discussions as it is an issue related to the code base.
