### ISSUE TITLE
paper_simulation notebook does not work: highly variable genes

### ISSUE THREAD

**Issue by yannikschaelte** [theislab/scvelo#322]
Not sure whether the scvelo_notebooks repository is being monitored, therefore re-posting here: https://github.com/theislab/scvelo_notebooks/issues/3

**Comment by WeilerP** [comment]
I was able to run the notebook using

> scvelo==0.2.3  scanpy==1.7.0  anndata==0.7.5  loompy==3.0.6  numpy==1.20.1  scipy==1.6.0  matplotlib==3.3.4  sklearn==0.24.1  pandas==1.2.2

Which version of scanpy did you use?

**Comment by yannikschaelte** [comment]
Thanks for checking! It seems to work now, maybe it was the scanpy update.
