### ISSUE TITLE
High proportion of unspliced counts

### ISSUE THREAD

**Issue by dsg03** [theislab/scvelo#323]
Hello,

Thank you for making this great package!

I have a question about the proportion of unspliced counts. The tutorial states that 10-25% of counts should be unspliced. In addition, the tutorial extracted 2000 highly variable genes after filtering, when the minimum number of shared counts is set at 20. For our data, the proportion of unspliced counts is about 60% - very high. In addition, there are only 23 highly variable genes after the filtering - very low. The cells for our data are Tregs.

Do you have any suggestions?

**Comment by sarajimenez** [comment]
Hi, 

Thank you for the great tool :)

I have a similar issue. I happen to have in my data set ~ 30% of unspliced counts, this is the case for two data sets (one sequenced with 10X and the other one with inDrops). They come from a differentiation protocol (hiPSC to beta-like cells) I don't know if this is a coincidence. 

My question is, what are the implications of having a higher proportion of unspliced counts in the estimation of the velocities? 

I'd highly appreciate any comment on this!
