### ISSUE TITLE
Switch to GitHub Actions for CI

### ISSUE THREAD

**Issue by WeilerP** [theislab/scvelo#340]
## Description

As the original [Travis](https://travis-ci.org) website will be shutting down in several weeks which entails a change in plans and pricing, we should switch to GitHub Actions to run CI.

**Comment by yannikschaelte** [comment]
I'm not aware of it shutting down completely? -- migration to travis-ci.com should be straightforward. However, there are plenty reasons for switching to GHA completely.

See https://github.com/yannikschaelte/scvelo/blob/master/.github/workflows/ci_push.yml for an exemplary setup.

**Comment by WeilerP** [comment]
Sorry, bad phrasing. You are, of course, right. I meant the website `https://travis-ci.org` will be shutting down. This entails changes in plans and pricing.
