### ISSUE TITLE
Latent time is opposite to what I have expected

### ISSUE THREAD

**Issue by mal7** [theislab/scvelo#348]
Dear scvelo developers,

Thanks for developing such a fantastic tool. 

Recently, I applied scvelo in analyzing single-cell data from several samples, and found that latent time is consistent to what I have expected in most of the samples expect one. For that sample, the latent time seems completely opposite. I am wondering if I can manually reverse the latent time to fit the biological process and whether this operation violates the hypothesis in your paper.

Thanks so much.
Lisa

**Comment by yxiaobme** [comment]
I have this question, too! The latent time plots showed the opposite trend to pseudotime plots and streamline plots.

**Comment by WeilerP** [comment]
@mal7, @yxiaobme could you please provide code snippets leading to the problem as well as figures visualising it?

**Comment by WeilerP** [comment]
I'll close this for now. Happy to reopen.
