### ISSUE TITLE
Unable to install and use scvelo

### ISSUE THREAD

**Issue by aditisk** [theislab/scvelo#35]
I tried to install scvelo using pip install scvelo and I got no error. But when I try to import scvelo I am getting this error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-fd6280dc6695> in <module>()
----> 1 import scvelo as scv
      2 scv.logging.print_version()

/anaconda3/lib/python3.6/site-packages/scvelo/__init__.py in <module>()
      1 """scvelo - stochastic single cell RNA velocity"""
      2 
----> 3 from . import preprocessing as pp
      4 from . import tools as tl
      5 from . import plotting as pl

/anaconda3/lib/python3.6/site-packages/scvelo/preprocessing/__init__.py in <module>()
----> 1 from .utils import show_proportions, cleanup
      2 from .moments import moments
      3 from .recipes import recipe_velocity

/anaconda3/lib/python3.6/site-packages/scvelo/preprocessing/utils.py in <module>()
----> 1 import numpy as np
      2 
      3 
      4 def show_proportions(adata, copy=False):
      5     """Fraction of spliced/unspliced/ambiguous abundances

/anaconda3/lib/python3.6/site-packages/numpy/__init__.py in <module>()
    140     from . import _distributor_init
    141 
--> 142     from . import core
    143     from .core import *
    144     from . import compat

/anaconda3/lib/python3.6/site-packages/numpy/core/__init__.py in <module>()
     55 from . import umath
     56 from . import _internal  # for freeze programs
---> 57 from . import numerictypes as nt
     58 multiarray.set_typeDict(nt.sctypeDict)
     59 from . import numeric

/anaconda3/lib/python3.6/site-packages/numpy/core/numerictypes.py in <module>()
    109 )
    110 
--> 111 from ._type_aliases import (
    112     sctypeDict,
    113     sctypeNA,

/anaconda3/lib/python3.6/site-packages/numpy/core/_type_aliases.py in <module>()
     61         _concrete_typeinfo[k] = v
     62 
---> 63 _concrete_types = {v.type for k, v in _concrete_typeinfo.items()}
     64 
     65 

/anaconda3/lib/python3.6/site-packages/numpy/core/_type_aliases.py in <setcomp>(.0)
     61         _concrete_typeinfo[k] = v
     62 
---> 63 _concrete_types = {v.type for k, v in _concrete_typeinfo.items()}
     64 
     65 

AttributeError: 'tuple' object has no attribute 'type'

Any help on how to fix this would be great. I also tried the Git clone install and that gives me a similar error.

**Comment by VolkerBergen** [comment]
Could you check your numpy version `import numpy; print(numpy.__version__)`,
and try upgrading via `pip install --upgrade numpy`?

If you have v1.16.0, there might be something broken with numpy. In that case, try downgrading to 
you might try downgrading to numpy v.1.15.4.

**Comment by VolkerBergen** [comment]
Any updates on this?

**Comment by aditisk** [comment]
Hi, sorry I haven't tried doing anything since the past 2 days because when I installed scvelo the last time I could not use scanpy on my computer due to version conflicts of some packages including numpy. I am afraid that this will mess up my scanpy installation and I have a deadline this Friday. 

I will try what you suggested over the weekend and get back to you at the earliest. Thanks,

**Comment by VolkerBergen** [comment]
Sure, no worries. Good luck! :)

side note: scanpy and scvelo should not have any conflicting dependencies. scvelo's main dependencies are basically scanpy and anndata.

**Comment by aditisk** [comment]
Thanks a lot. I am sure I got some version conflict messages and everything stopped working after that. I will re-try the installation and post the messages/errors here and we can go from there :)

**Comment by VolkerBergen** [comment]
Any updates on the installation?
