### ISSUE TITLE
Key contributions section in the docs

### ISSUE THREAD

**Issue by Marius1311** [theislab/scvelo#352]
I think it would be important to have a [scanpy-style](https://scanpy.readthedocs.io/en/latest/) "Key contributions" section in the docs to highlight contributions by e.g. @WeilerP, @stefanpeidli and @michalk8 - especially if the perspective is to drive scVelo in the community direction.

**Comment by Marius1311** [comment]
Any comments/opinions on this @VolkerBergen ?

**Comment by VolkerBergen** [comment]
For now, it's only Philipp. But will consider for the future to list those that contribute more regularly.

**Comment by WeilerP** [comment]
Closed via #930.
