### ISSUE TITLE
Stream embeddings for 3D plots

### ISSUE THREAD

**Issue by maddemaddi** [theislab/scvelo#357]
Hi!

I am currently generating different types of 3D plots for our sc-data and I managed to plot the velocity arrows for single cells thanks to this former discussion [https://github.com/theislab/scvelo/issues/220]. However, the arrows are very small and abundant and it is therefore quite hard to interpret what is going on. Would there be any chance to extract coordinates for the stream embeddings so that the velocities could be visualized more clearly in a 3D plot? :)

Thanks!
Madeleine

**Comment by VolkerBergen** [comment]
Hi Madeleine, 

there are a couple parameters such as `scale` that you can play around with to adjust the size of the arrows as described [here](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.quiver.html).

**Comment by kobeho24** [comment]
> Hi!
> 
> I am currently generating different types of 3D plots for our sc-data and I managed to plot the velocity arrows for single cells thanks to this former discussion [https://github.com/[/issues/220](https://github.com/theislab/scvelo/issues/220)]. However, the arrows are very small and abundant and it is therefore quite hard to interpret what is going on. Would there be any chance to extract coordinates for the stream embeddings so that the velocities could be visualized more clearly in a 3D plot? :)
> 
> Thanks! Madeleine
Hi,

Just wondering if you have come up with an idea of how to alter the arrow abundance on the 3d velocity plot
