### ISSUE TITLE
Support for external kNN approaches

### ISSUE THREAD

**Issue by dawe** [theislab/scvelo#358]
Hi, I'm using `scvelo` for some data spanning multiple experiments. I perform standard scRNA analysis using `sc.external.pp.bbknn`, whereas `scvelo` computes its own kNN graph using standard `scanpy`'s method (based on UMAP). Would it be possible (or maybe it is already and I don't know) to calculate moments using any provided kNN graph (possibly passing `neighbors_key` to `scv.pp.moments`)?

```
scv.__version__
'0.2.2'
```

**Comment by dawe** [comment]
Wait, is it `scv.pp.moments(adata, method=None)` after I have a knn graph built with the alternative tool (e.g. `bbknn`)?

**Comment by WeilerP** [comment]
Moments can be calculated on a custom pre-computed knn graph. To prevent calculating a new knn graph [here](https://github.com/theislab/scvelo/blob/1659cc8e00a45fcf87cd80a7013aae5531744613/scvelo/preprocessing/moments.py#L64), you can simply set `n_neighbors=None`. `scvelo` will retrieve the knn graph from either `adata.obsp[mode]` or `adata.uns["neighbors"][mode]` (mode is e.g. distances or connectivities). The corresponding function can be found [here](https://github.com/theislab/scvelo/blob/1659cc8e00a45fcf87cd80a7013aae5531744613/scvelo/preprocessing/neighbors.py#L300).
We're currently working on making the handling of cases such as yours easier and (potentially) more intuitive.
