### ISSUE TITLE
remove labels from clusters on plot

### ISSUE THREAD

**Issue by hartlama** [theislab/scvelo#363]
Hello,

I'm sure this is a simple fix, but I'm not familiar with matplotlib. I have my velocity plot colored by Seurat cluster numbers. The plot includes text on the plot labeling each cluster. How do I get rid of these?
![Run2961_TumorB1B2_scvelo_velocity](https://user-images.githubusercontent.com/74679498/108271719-3ae69380-713f-11eb-8994-d999f75a78ce.png)

**Comment by VolkerBergen** [comment]
You can specify the absence/location of the legend via `legend_loc='none' `, `legend_loc='right' `.

**Comment by williamwuyulu** [comment]
> 

That's really helpful!

Thanks!
