### ISSUE TITLE
Lose cells when merge two anndata with `scv.utils.merge`

### ISSUE THREAD

**Issue by quan-xu** [theislab/scvelo#366]
When I merge two anndata to run velocity analysis with `scv.utils.merge(adata, adata1)`, I lose some of the cells.
I have 12 samples. When I merge the top 10 samples, it will not lose cells. When I merge the last 2 samples, it will also not lose cells. However, when I merge all 12 samples, it will only inclued a few cells from the last 2 samples. Do you have any suggestions? Thanks!

#### Versions:
scvelo==0.2.2  scanpy==1.7.0  anndata==0.7.5  loompy==3.0.6  numpy==1.19.5  scipy==1.5.3  matplotlib==3.3.4  sklearn==0.24.1  pandas==1.1.5
>

**Comment by WeilerP** [comment]
Sorry not quite sure what you mean by samples. Would you mind clarifying?
Do your two AnnData objects share the same cells? `scvelo.utils.merge` performs an inner join i.e., only cells common across both AnnData are retained:

```zsh
>>> import numpy as np
>>> import pandas as pd
>>>
>>> from anndata import AnnData
>>> import scvelo as dcv
>>>
>>> adata_1 = AnnData(
...     np.random.randn(3, 3),
...     obs=pd.DataFrame(index=['cell_1', 'cell_2', 'cell_3']),
...     var=pd.DataFrame(index=['a', 'b', 'c'])
... )
>>> adata_2 = AnnData(
...     np.random.randn(2, 3),
...     obs=pd.DataFrame(index=['cell_1', 'cell_2']),
...     var=pd.DataFrame(index=['a', 'b', 'c'])
... )
>>> adata = merge(adata_1, adata_2)
>>> adata
AnnData object with n_obs × n_vars = 2 × 3
>>> adata.obs
Empty DataFrame
Columns: []
Index: [cell_1, cell_2]
```

Does this help?

**Comment by quan-xu** [comment]
> Sorry not quite sure what you mean by samples. Would you mind clarifying?
> Do your two AnnData objects share the same cells? `scvelo.utils.merge` performs an inner join i.e., only cells common across both AnnData are retained:
> 
> ```shell
> >>> import numpy as np
> >>> import pandas as pd
> >>>
> >>> from anndata import AnnData
> >>> import scvelo as dcv
> >>>
> >>> adata_1 = AnnData(
> ...     np.random.randn(3, 3),
> ...     obs=pd.DataFrame(index=['cell_1', 'cell_2', 'cell_3']),
> ...     var=pd.DataFrame(index=['a', 'b', 'c'])
> ... )
> >>> adata_2 = AnnData(
> ...     np.random.randn(2, 3),
> ...     obs=pd.DataFrame(index=['cell_1', 'cell_2']),
> ...     var=pd.DataFrame(index=['a', 'b', 'c'])
> ... )
> >>> adata = merge(adata_1, adata_2)
> >>> adata
> AnnData object with n_obs × n_vars = 2 × 3
> >>> adata.obs
> Empty DataFrame
> Columns: []
> Index: [cell_1, cell_2]
> ```
> 
> Does this help?

**Comment by quan-xu** [comment]
I am doing `velocity analysis`, so all 12 samples are paired. 
It will retained cells if I merge the first 10 pairs of sample, and it will retained cells if I merge the last 2 pairs of sample. But if I merge all 12 pairs of samples, it will retain the first 10 samples, and only retain a few cells from the last 2 samples.

**Comment by VolkerBergen** [comment]
Check the `adata.obs_names` and the overlap `pd.unique(adata.obs_names.intersection(ldata.obs_names))` to understand what kind of discrepancies there may be between cell IDs in the different samples.

**Comment by quan-xu** [comment]
> Check the `adata.obs_names` and the overlap `pd.unique(adata.obs_names.intersection(ldata.obs_names))` to understand what kind of discrepancies there may be between cell IDs in the different samples.

Hi, thanks for your help, this is the output of cell name intersection.

```
adata.obs_names
```
Index(['F49-W06-B1-S1-P_lib1:AAAGATGTCATCGATGx',
       'F49-W06-B1-S1-P_lib1:AACCGCGCAAAGGTGCx',
       'F49-W06-B1-S1-P_lib1:AAACCTGGTGCCTGTGx',
       'F49-W06-B1-S1-P_lib1:AAACCTGCACTGAAGGx',
       'F49-W06-B1-S1-P_lib1:AACACGTTCAATCTCTx',
       'F49-W06-B1-S1-P_lib1:AAAGTAGTCTTACCGCx',
       'F49-W06-B1-S1-P_lib1:AAAGCAAAGATCCCATx',
       'F49-W06-B1-S1-P_lib1:AAAGCAATCTTGAGACx',
       'F49-W06-B1-S1-P_lib1:AACCATGAGCTGTTCAx',
       'F49-W06-B1-S1-P_lib1:AAAGCAACAGTTTACGx',
       ...
       'F49-W30-B1-S1-I_lib2:TTTGGTTAGATGGGTCx',
       'F49-W30-B1-S1-I_lib2:TTTGCGCCATGTAAGAx',
       'F49-W30-B1-S1-I_lib2:TTTGCGCTCTTCAACTx',
       'F49-W30-B1-S1-I_lib2:TTTGCGCAGTGGAGAAx',
       'F49-W30-B1-S1-I_lib2:TTTGGTTCACACAGAGx',
       'F49-W30-B1-S1-I_lib2:TTTATGCAGTCCATACx',
       'F49-W30-B1-S1-I_lib2:TTTGGTTCAGGGATTGx',
       'F49-W30-B1-S1-I_lib2:TTTCCTCGTAGCGCTCx',
       'F49-W30-B1-S1-I_lib2:TTTGCGCAGCTATGCTx',
       'F49-W30-B1-S1-I_lib2:TTTGCGCGTCCGACGTx'],
      dtype='object', length=29922)

```
mdata.obs_names
```
Index(['AAACCTGAGAGACTTA', 'AAACCTGAGGCATGTG', 'AAACCTGAGTTGAGAT',
       'AAACCTGCACTGAAGG', 'AAACCTGCATCCGCGA', 'AAACCTGGTATCTGCA',
       'AAACCTGGTGCCTGTG', 'AAACCTGGTTAGTGGG', 'AAACCTGTCCCAACGG',
       'AAACCTGTCCGCTGTT',
       ...
       'GCGGGTTCACCTCGGA-1', 'GCTTCCATCCTACAGA', 'GGCTCGACAGCCACCA',
       'GTGTGCGTCATTGCCC', 'TACTCATAGCGAAGGG', 'TAGGCATCAATCCGAT',
       'TCCACACAGCGGCTTC', 'TGACTTTGTTAGAACA', 'TGGTTAGCACTGCCAG',
       'TTGAACGAGACGCACA'],
      dtype='object', length=23294)

```
mdata = scv.utils.merge(adata, ldata)
mdata.obs_names
```
Index(['AAACCTGAGAGACTTA', 'AAACCTGAGGCATGTG', 'AAACCTGAGTTGAGAT',
       'AAACCTGCACTGAAGG', 'AAACCTGCATCCGCGA', 'AAACCTGGTATCTGCA',
       'AAACCTGGTGCCTGTG', 'AAACCTGGTTAGTGGG', 'AAACCTGTCCCAACGG',
       'AAACCTGTCCGCTGTT',
       ...
       'GCGGGTTCACCTCGGA-1', 'GCTTCCATCCTACAGA', 'GGCTCGACAGCCACCA',
       'GTGTGCGTCATTGCCC', 'TACTCATAGCGAAGGG', 'TAGGCATCAATCCGAT',
       'TCCACACAGCGGCTTC', 'TGACTTTGTTAGAACA', 'TGGTTAGCACTGCCAG',
       'TTGAACGAGACGCACA'],
      dtype='object', length=23294)

```
a=[i.split("-")[0] for i in adata.obs_names.tolist()]
b=[i.split(":")[1][:-1] for i in ldata.obs_names.tolist()]
c=[i.split("-")[0] for i in mdata.obs_names.tolist()]
print(len(set(a).intersection(set(b))))
print(len(set(a).intersection(set(c))))
print(len(set(b).intersection(set(c))))
```
22945
22945
22945

**Comment by VolkerBergen** [comment]
That's almost maximal overlap after cleaning the names. You can finally check what's missing `[i for i in mdata.obs_names if i not in a]`.

**Comment by quan-xu** [comment]
Thanks! I solved my problem. It is because I add `cache=True` when I run `scv.read()`. It will load my previous `loom` file that didn't include my new samples.
