### ISSUE TITLE
Using precomputed UMAP coordinates

### ISSUE THREAD

**Issue by ashwinikumarkulkarni** [theislab/scvelo#37]
Hello! I have a dataset for which I have already performed clustering using UMAP (Seurat). I want to use the same coordinates and compute velocity. For some reason "velocity.R" keeps failing. Is it possible to use scvelo with pre-computed UMAP coordinates? Thanks!

**Comment by VolkerBergen** [comment]
Sure. What format does your file with the UMAP coordinates have? Do the observations have the same order as in the loom file. If so, you can proceed as follows:
```
adata = scv.read(loom_file_name)
adata.obsm['X_umap'] = scv.load(umap_file_name)
```

If your observations for the UMAP have a different order, you can read your data with the UMAP coord., read the loom file and merge them:
```
adata = scv.read(file_name)
adata_loom = scv.read(file_name.loom)
adata = scv.utils.merge(adata, adata_loom)
```

**Comment by VolkerBergen** [comment]
`scv.load` understands npy (saved with numpy), csv and txt.

**Comment by ashwinikumarkulkarni** [comment]
Thanks for the reply! I can save UMAP coordinates in a loom file using loomR. It will have same observations to that of scvelo data. Let me try what you suggested! Thanks again!

**Comment by VolkerBergen** [comment]
Did you manage to merge the embedding coord?

**Comment by PedroRaposo** [comment]
I'm trying to do this. However after I do the `scv.pp.moments(adata, **params)` line, I only have the analysis regarding "pca" and not "umap". I found out when I saw in the observations:

`adata.obsm.keys()`
`('X_pca',)`

Do you know how to proceed to obtain the "umap" analysis? Thank you.

**Comment by VolkerBergen** [comment]
PCA is computed for the neighbor graph that is used within `pp.moments`, therefore available without actually computing it. UMAP needs to be computed via `scv.tl.umap(adata)`.

**Comment by PedroRaposo** [comment]
Thank you!

**Comment by PedroRaposo** [comment]
I don't know if it's pertinent to ask here or in another thread, but I think this is a natural continuation of this pipeline.
After I successfully merged the objects, I ran `adata.obsm.keys()` and it outputted `('pca_cell_embeddings', 'umap_cell_embeddings')`. It seems that it managed to import my UMAP embedding data from the Seurat object.

However, I don't know at what point, and how do I input the embedding to calculate the velocities. Sorry, I couldn't not find on the Guideline.

Thank you

**Comment by VolkerBergen** [comment]
Hi Pedro,
velocity (as well as velocity graph) computation does not depend on any embedding. It is only needed for the actual embedment of the velocities, which is automatically done when specifying the embedding coordinates as
`scv.pl.velocity_embedding(adata, basis='umap_cell_embeddings')`

**Comment by VolkerBergen** [comment]
Or rename it to the canonical name 'umap', then it'll find it itself without specifying the basis.

**Comment by PedroRaposo** [comment]
I tried to do that but it gave me an error. I'll try to rename to the canonical name then.

```
>>> scv.pl.velocity_embedding(adata, basis='umap_cell_embeddings')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/scvelo/plotting/velocity_embedding.py", line 52, in velocity_embedding
    compute_velocity_embedding(adata, basis=basis, vkey=key)
  File "/opt/conda/lib/python3.7/site-packages/scvelo/tools/velocity_embedding.py", line 68, in velocity_embedding
    raise ValueError('You need compute the embedding first.')
ValueError: You need compute the embedding first.

```

**Comment by VolkerBergen** [comment]
Ah, one piece missing:
Embedding are assumed to start with 'X_', else they won't be recognized. Simply store it as `adata.obsm['X_umap'] = adata.obsm['umap_cell_embeddings']`

**Comment by PedroRaposo** [comment]
Perfect! Thank you very much for all your assistance.

**Comment by hmassalha** [comment]
Hi @VolkerBergen, 
I have two questions related to this point. 

a. I used the merge function that was suggested above `scv.utils.merge` to add the embeddings to my working file. But when I try to make the phase diagrams using `scv.pl.velocity` function, I got scatter plots without the colors of the clusters. How I can fix this? 

b. I have a large file (genes by cells not filtered, resulted by merging several loom files of separated experiments).  I have another loom file that includes only two clusters that I am interested in and contains the selected cells by the variable genes (~2000). 
My question is which file to use to run the velocity pipeline? or do I have to let scvelo select the genes that will be required to a downstream analysis by filtering the large file and keeping the cells that I am interested in or it is enough to use the 2000 variable genes? 
(I ran the analysis in both ways and do see slight changes in the number of retained genes at the end of the process!) 

Best, HM

**Comment by VolkerBergen** [comment]
Hi @hmassalha 

a. you can color the cells in the embedding with the `color` attribute, e.g. setting it to `scv.pl.velocity(adata, color='clusters')`. 

b. The more cells you include, the better the captured steady states, thus the more accurate the velocities. Hence, I'd rather go with the larger dataset for velocity estimation and then subset to the clusters that you are interested in. The number of selected hvg (2000) should be fine. Including all genes should, in general, not change resulting velocities much. For the velocity embedding genes are automatically selected that pass a certain R-squared threshold.

**Comment by hmassalha** [comment]
Thanks a lot for your quick reply. 

Regarding (b). Assuming I have VERY different cell types in the large dataset, in each I have two subclusters. Do you still recommend to calculate the velocities on all cells rather than to calculate velocities on a select two subclusters that I am interested in? 

Thanks, HM

**Comment by VolkerBergen** [comment]
As long as the method is based on quantifying a steady-state equilibrium (this will soon change with a new dynamical model), it is usually better to include as many cells as possible. Of course, the cell types have to be related to share a common steady-state ratio. You can check in the phase portraits whether the observations from the two cell types indicate a common or two distinct slopes for the steady-state ratio.

**Comment by hmassalha** [comment]
How I could estimate if I have two distinct slopes between my two clusters? I assume the output slope in `scv.pl.velocity` is calculated based on all cells in the axis. If this is the case and I have two distinct slopes, what should I do? 
Thanks, 

Attached are genes I get from `scv.tl.rank_velocity_genes` function
![download (1)](https://user-images.githubusercontent.com/10478803/62543647-fbab6700-b866-11e9-9fad-d198a1c980fd.png)

**Comment by VolkerBergen** [comment]
One does not learn anything from those genes; very low count number and not indication of dynamics. You'd have to manually screen through your marker genes and find some indicative ones (such as the ones in [this example](https://scvelo-notebooks.readthedocs.io/en/latest/DentateGyrus.html)).

**Comment by hmassalha** [comment]
Hi @VolkerBergen, 
I spent a few days trying to understand why I have the result above without any success! The first thing I did is to compare the retained exonic reads in the 'spliced' layer with the Seurat retained exons. I found that they are very different from each other. The number of the exonic reads from the loom file is very shallow for the majority of the genes! Why is that? 

To test this I went back from the final merged loom file (or 6 experiments) to the original BAM file for each experiment separately. My BAM file is obtained from the zUMIs pipeline, where I have a checkbox in the YAML file for velocity. That file was the input for `velocyto run` command using the default logic (i.e. permissive 10X although my data was generated using MARSseq, still UMI based chemistry as 10X). Again I found differences in the exonic reads between the 'untreated loom file' and the Seurat data.

Here is the log file of the one sample (out of the 6). This file is the output of `velocyto run` command. I am copying a few lines that I think it has some information that I don't know how to interpret: 

2019-08-13 12:45:39,130 - DEBUG - Generated 2199352 features corresponding to 200310 transcript models from /home/labs/shalev/NGS/indexes/GRCh38.91/Homo_sapiens.GRCh38.91.gtf

2019-08-13 13:09:20,045 - DEBUG - Validated 44662 introns (of which unique intervals 17008) out of 999521 total possible introns (considering each possible transcript models).

2019-08-13 13:25:26,611 - WARNING - More than 20% (25.0%) of molitems trashed, of those:
2019-08-13 13:25:26,612 - WARNING - A situation where many genes were compatible with the observation in 0.0 cases
2019-08-13 13:25:26,612 - WARNING - No gene is compatible with the observation in 18.5 cases
2019-08-13 13:25:26,612 - WARNING - Observation compatible with more genes 6.5 of the cases
2019-08-13 13:25:26,612 - WARNING - Situation that were not described by the logic in the 0.0 of the cases

[h3o.log](https://github.com/theislab/scvelo/files/3513098/h3o.log)

I am not sure if I did the correct thing? dose the selected 'logic' is correct? How I can test my resulted files and what the sanity check you would recommend? 

Your input is much appreciated, I am straggling with this already for a long time.
Thanks a lot,
HM

**Comment by VolkerBergen** [comment]
I'd have to ask colleagues about velocyto/alignment-related questions, which are currently all on vacation. Yet, these kind of issues would rather belong [here](https://github.com/velocyto-team/velocyto.py).

**Comment by Slakky** [comment]
Dear @theislab,

First of all sorry if this is not the right place to ask this type of questions.

I'm trying to import my own UMAP coordinates from previous analysis into my AnnData object. I understand that using `utils.merge` I can incorporate these coordinates into the `['X_umap']` slot and use those for plotting. The problem is that I don't have the same number of observations between my coordinates and `mydata.obs_names`. 

Is there any way I can filter the observations prior to any steps with a given list/vector of cells to keep? (skipping the `scv.pp` pre-processing)

Thanks in advance

**Comment by rohan19250** [comment]
I want to see UMAP clustering on RNA velocity of a sample. here are the steps I took and I wanted to make sure if this is the correct way to do to achieve this : https://scvelo.readthedocs.io/VelocityBasics.html#Project-the-velocities?

 - Read 10X counts data from cell ranger, do filtering, normalization etc and compute UMAP as well as leiden clustering.(adata) based on scanpy (https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html)
 
 - Read loom files which contains output from velocyto with spliced and unspliced counts.(adata_loom)
 - Merge both the above files: 
 
       adata = scv.utils.merge(adata, adata_loom)

 - Do normalization on the merged data : 
 
       scv.pp.normalize_per_cell(adata,enforce=True)

       scv.pp.log1p(adata)

-Calculate moments and then velocity : 

       scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
       scv.tl.velocity(adata)
       scv.tl.velocity_graph(adata)
       scv.pl.velocity_embedding_stream(adata)


- For seeing clusters: 
     
      
      scv.pl.velocity_embedding_stream(adata,basis='umap',color='leiden')

Is this the correct way to go about this?I was confused about the above since after the merged adata, how the velocity is being computed? whether its on the velocyto output or the 10X output only.Also UMAP has to be computed on 10X counts data and not loom files?
