### ISSUE TITLE
Please, port Scvelo to R 

### ISSUE THREAD

**Issue by akhst7** [theislab/scvelo#378]
Hi, 

Converting Seurat or SingleCellExperiment obj to loom or Ann to import in Python environment has been excruciatingly painful.  I'd really appreciate if you could port scvelo to R much like Velocyte.R 

Thanks.

**Comment by kanefos** [comment]
I'm not an author but this is a pretty large request lol. Can't you just use [SeuratDisk](https://github.com/mojaveazure/seurat-disk) or [zellkonverter](https://bioconductor.org/packages/release/bioc/html/zellkonverter.html)

**Comment by ThomasCarroll** [comment]
Or velociraptor
https://bioconductor.org/packages/release/bioc/html/velociraptor.html

**Comment by akhst7** [comment]
Velocyto.R and velociraptor are basically a wrapper for Velocyto.py, and it should not take a lot of effort to write a scvelro wrapper for R.  Also, SeuratDIsk is not prime time yet.  It misses a key conversion of Seurat obj to anndata (e.g. assay to layer conversion).    What has worked for me is to use two R packages, Sceasy and Anndata to convert Seurat obj  to  ann  and manipulate ann in R environment.  I could use Reticulate to run Scvelo in R but for me Jupiter lab is much easier.

**Comment by AAA-3** [comment]
> Velocyto.R and velociraptor are basically a wrapper for Velocyto.py, and it should not take a lot of effort to write a scvelro wrapper for R. Also, SeuratDIsk is not prime time yet. It misses a key conversion of Seurat obj to anndata (e.g. assay to layer conversion). What has worked for me is to use two R packages, Sceasy and Anndata to convert Seurat obj to ann and manipulate ann in R environment. I could use Reticulate to run Scvelo in R but for me Jupiter lab is much easier.

Hello! 

I am new to bioinformatics but I wanted to know if you used [this vignette](http://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/scvelo.html)? How would you know the conversion method loses some data and would this impact heavily on the analysis?

I plan on sing this vignette for RNA velocity analysis and wanted to know if it is compromising my findings in any way.

**Comment by akhst7** [comment]
@AAA-3,  Computationally speaking, there is no data corruption.   SeuratDisk at that time did not add `spliced` and `non-spliced` into the var of ann file.  They may have been fixed this issue already in the newer version.

**Comment by AAA-3** [comment]
@andrewwbutler is this still the case?

**Comment by akhst7** [comment]
@AAA-3,   You can check it out yourself.  Because of  Sceasy and Anndata,  I have a reliable pipeline now that I don't need really SeuratDisk.

**Comment by Shamzar** [comment]
Have you tried reticulating scvelo in R? [check](https://statbiomed.github.io/SingleCell-Workshop-2021/RNA-velocity.html#:~:text=3.3.1%20Getting-,started,-First%2C%20let%E2%80%99s%20use) this tutorial.
