### ISSUE TITLE
Okay, so there are only ~20 cells containing expressed genes? Not sure if I understood correctly, but cells containing only zero counts should be removed during quality control.

### ISSUE THREAD

**Issue by alexmascension** [theislab/scvelo#394]
Okay, so there are only ~20 cells containing expressed genes? Not sure if I understood correctly, but cells containing only zero counts should be removed during quality control.
Also, as part of the preprocessing, genes expressed in only a small number of cells should be excluded from any downstream analysis as well. You can do so via `scv.pp.filter_genes`. Alternatively, you can also use `scv.pp.filter_and_normalize` which simply combines filtering and normalizing.

_Originally posted by @WeilerP in https://github.com/theislab/scvelo/issues/386#issuecomment-800387679_

No, those cells have expression 0 for that gene in particular, but > 0 for others. In that case, the gene might be filtered out, but still I am interested in knowing if it would be feasible to lower the k value.

I think the issue is not closed yet because we are having some miscommunication.

**Comment by WeilerP** [comment]
Sorry, moved the issue to discussions [here](https://github.com/theislab/scvelo/discussions/393) as this isn't an issue related to the code base but a discussion on the general methodology. Please repost your comment there.
