### ISSUE TITLE
how to save all layers to loom file?

### ISSUE THREAD

**Issue by zacharylau10** [theislab/scvelo#4]
Hi,
     when finished scvlo pipeline, is there anyway saving all layers in adata to Loom file like velocyto loom file?

**Comment by VolkerBergen** [comment]
Hi zacharylau10,

the easiest way is just `adata.write(filepath)`, which writes a hdf5 file. Writing loom files is not available yet, but I should be able to implement that by tomorrow.

**Comment by zacharylau10** [comment]
I see, thank you~

**Comment by VolkerBergen** [comment]
In the latest version you can now save loom files simply via `adata.write_loom('filename.loom')`.

To read, use `adata = sc.read('filename.loom', X_name='')`. 
`X_name=''` indicates that `adata.X` becomes the main layer of the loom file. If not specified, it becomes the spliced counts.
