### ISSUE TITLE
Mathematical formula for scvelo velocity estimation

### ISSUE THREAD

**Issue by bioinformaticss** [theislab/scvelo#40]
thanks for this nice package! It works pretty well in my hands. I am pretty curious about the method you used to estimate velocity, in comparison to the original RNA velocity paper. Is there any plans that you will publish or post to biorxiv this soon?

**Comment by VolkerBergen** [comment]
Thanks for asking. I'll post a summary including some explanations on the stochastic part within the next few days. The reason for having the publication postponed yet is that the actually aspired model (inferring the full dynamics of splicing kinetics; much more powerful than the current state) is still in progress. Posting to biorxiv and releasing the full model is expected soon.

**Comment by VolkerBergen** [comment]
Expanded the Readme with some more details, only intuitions yet, the math comes with biorxiv. You could read up on 'moment closure techniques' to get a broad idea of the stochastic approach.
