### ISSUE TITLE
scv.tl.velocity_pseudotime setting "groupby" produces NaN pseudotime values

### ISSUE THREAD

**Issue by 14lwt1** [theislab/scvelo#409]
Hi,
When computing pseudotime, I set the "groupby" argument to the variable "lineage", which groups clusters into respective lineages.
However, when I extracted the pseudotime associated with each cell, I found a total of 10 cells with NaN values out of 4378 cells in the dataset. These cells seem to locate toward the end of the trajectory.
Not entirely sure how to interpret this.

scv.tl.velocity_pseudotime(adata, groupby = "lineage")
scv.pl.scatter(adata, color='velocity_pseudotime', cmap='gnuplot')
![Pseudotime](https://user-images.githubusercontent.com/59578221/112530631-e9e04580-8d63-11eb-902d-245be60f4674.png)

sum(np.isnan(adata.obs.velocity_pseudotime))
10
![Missing pseudotime](https://user-images.githubusercontent.com/59578221/112530660-f06ebd00-8d63-11eb-9189-e118905d3072.png)

Note:
- I opted to the stochastic model
- UMAP embedding was imported from the same data processed in Seurat

**Comment by WeilerP** [comment]
Did you receive a warning when running `scv.tl.velocity_pseudotime(adata, groupby = "lineage")` (This requires `scv.settings.verbosity = 1`)? Could you please share the logs of `scv.tl.velocity_pseudotime(adata, groupby = "lineage")` when using `scv.settings.verbosity = 3`?

**Comment by WeilerP** [comment]
Closing this for now. Happy to reopen.
