### ISSUE TITLE
Question about modes in velocity function

### ISSUE THREAD

**Issue by bharris12** [theislab/scvelo#41]
Could you explain the difference between the modes in the tl.velocity() function? 

Through a cursory look at your code and readme it looks like Deterministic is the original La Manno velocity, stochastic is your new one and I have no clue what bayes is?

Just wanted clarification.

**Comment by VolkerBergen** [comment]
`deterministic` reproduces the velocities as described by La Manno et al.

`stochastic` as explained (detailed math behind it will be posted with publishing on biorxiv).

`bayes` was just an attempt for another approach, which you can forget for now.

**Comment by bharris12** [comment]
Great thanks for the clarification.
