### ISSUE TITLE
What do you mean by fit_t_, fit_tau_, fit_tau, and fit_t_ in the parameters of the inference ?

### ISSUE THREAD

**Issue by yujinmath** [theislab/scvelo#411]
Hi,everyone!
There is a problem that bothers me recently. What do you mean by fit_t_, fit_tau_, fit_tau, and fit_t_ in the parameters of the inference output of the dynamics model?
Thanks in advance for your help!

**Comment by VolkerBergen** [comment]
That's bit cryptic indeed - will update the docs. It's only being used internally, thus a full description if yet missing. Hope this helps for now:

- `fit_t` corresponds to the gene-wise latent times. 
- `fit_t_` are the swicthing timepoints.
- `fit_tau_` are the timepoints of assigning observatins to the off-state (necessary to generate likelihoods after the fitting)
- `fit_tau` same as above, but for the on-state.
