### ISSUE TITLE
the scvelo adata object adata.obs['seurat_clusters'] =  cell_clusters_ordered.values occurred error

### ISSUE THREAD

**Issue by honghh2018** [theislab/scvelo#416]
Hi @All,
     I want to add the seurat cluster into scvelo adata object but it show me error the key error 'seurat_clusters'.
     But when i perform the same procedure in hand using python shell interaction, it can work well on below command,
adata.obs['seurat_clusters'] =  cell_clusters_ordered.values
      the 'cell_clusters_ordered' was DataFrame including  one column of seurat clusters.
      cell_clusters_ordered.values showed like below:
![image](https://user-images.githubusercontent.com/41668708/113142143-28429c80-925d-11eb-9228-388035efaa46.png)
    How can i fix this issue, any advice would be appreciated.
    hanhuihong

**Comment by VolkerBergen** [comment]
Try `adata.obs['seurat_clusters'] = np.ravel(cell_clusters_ordered.values)`. 

What exactly is the error message?

**Comment by honghh2018** [comment]
Thanks the reply,
I guess i had figure out what go on this issue. 
I had found the variable  cell_clusters_ordered.values was empty without any value, so it trigger error.
