### ISSUE TITLE
Best practices on data integration and analysis of stimulated sample

### ISSUE THREAD

**Issue by GabrielBaldissera** [theislab/scvelo#417]
Hello,

I am using scvelo to investigate possible differences in two samples (WT and KO) related to hematopoiesis. For that, I have created an anndata file merging the information of my loom files with the following comand:

```
mir128_merged = anndata.concat({"WT":sample_JG12_WT,"MT":sample_JG13_MT},join="outer", axis=1,label="Orig.Ident") 
mir128_merged.var_names_make_unique() 
mir128_merged.var_names.is_unique
```
I applied the required normalizations and selected HVG genes. Then, I have estimated the velocities for each sample separetly using the _groupby_ argument.
`scv.tl.velocity(mir128_merged, mode = "dynamical", groupby="Orig.Ident")`

This is my current object:
> AnnData object with n_obs × n_vars = 6171 × 1800
>     obs: 'Clusters', 'Orig.Ident', 'initial_size_spliced', 'initial_size_unspliced', 'initial_size', 'n_counts', 'velocity_self_transition', 'root_cells', 'end_points', 'velocity_pseudotime', 'latent_time'
>     var: 'Accession', 'Chromosome', 'End', 'Start', 'Strand', 'Orig.Ident', 'gene_count_corr', 'means', 'dispersions', 'dispersions_norm', 'highly_variable', 'fit_r2', 'fit_alpha', 'fit_beta', 'fit_gamma', 'fit_t_', 'fit_scaling', 'fit_std_u', 'fit_std_s', 'fit_likelihood', 'fit_u0', 'fit_s0', 'fit_pval_steady', 'fit_steady_u', 'fit_steady_s', 'fit_variance', 'fit_alignment_scaling', 'velocity_genes'
>     uns: 'Cluster_colors', 'Clusters_colors', 'Orig.Ident_colors', 'neighbors', 'pca', 'recover_dynamics', 'velocity_graph', 'velocity_graph_neg', 'velocity_params'
>     obsm: 'X_pca', 'X_umap', 'velocity_umap'
>     varm: 'PCs', 'loss'
>     layers: 'Ms', 'Mu', 'ambiguous', 'fit_t', 'fit_tau', 'fit_tau_', 'matrix', 'spliced', 'unspliced', 'velocity', 'velocity_u'
>     obsp: 'connectivities', 'distances'
> 

I have noticed that I have two variations of the same gene, eg "myb" and "myb-1". These variations belong each to one of the samples. This was added to make variable names unique inside the anndata object and was suggested as a warning during the analysis.
I am wondering whether this is correct or a bug, as I would expect that the cell (observations) for both samples would have the same gene names so that they can be compared if necessary. I also wonder how this would impact analysis like cv.tl.rank_velocity_genes. I wonder if the function would be able to recognize that one gene has a correpondent in another sample in case of comparing both of them.

I have calculated the latent time as follows and plotted a heatmap. I can see that the plot gets separated in four parts. That is because cells from one sample will not have any value for genes with the name finishing in -1 and vice-versa.

scv.tl.latent_time(mir128_merged)
![image](https://user-images.githubusercontent.com/47226253/113173344-4685a980-9217-11eb-9daa-2d11295020c1.png)

I am wondering whether this is something expected in this pipeline or if it's some sort of mistake in the integration of my samples.
If that is expected, I suppose I will have to subset my anndata to have only data from one sample to then plot this sort of heatmap.

Ideally, I would like to do something as @VolkerBergen suggested on #142  and #132  to see diferences in velocities in clusters/samples.

Thanks for developing this amazing tool. I watched your lecture on SIB last year and I really liked it!!
I appreciate all the help!
Best,
Gabriel

**Comment by VolkerBergen** [comment]
Hi @GabrielBaldissera, 

I think the answer is relatively short: What you would want is an 'inner' join using an intersection of genes, i.e., `anndata.concate(..., join='inner')`. Let me know, if that works.

**Comment by GabrielBaldissera** [comment]
Hello! It worked beautifully. I was able to move on with my analysis.
Thanks!
