### ISSUE TITLE
how to save the plot into specific path in scv.pl.velocity_embedding_stream

### ISSUE THREAD

**Issue by honghh2018** [theislab/scvelo#418]
Hi @All，
     Thanks to develop the great tools.
      I got a question that i am going to save the plot into specific path like below:
      scv.pl.velocity_embedding_stream(samples, basis='X_seurat', color=['seurat_clusters','initial_size_spliced','initial_size_unspliced'],save= os.path.join(outdir,'02.rna_velocyto','embedding_stream','velocity_embedding_stream.png'))
      It was unsuccessful, because it would automately save the plot into local path with 'figures' directory.
      So, i hope the function can be save into the path that i appointed not the local 'figure' that function default.
      How can i do for this question and fix it.
       Thanks, any advice would be appreciated
       hanhuihong

**Comment by honghh2018** [comment]
Can anyone could help?

**Comment by VolkerBergen** [comment]
Generally passing the directory directly through `save` should work. Otherwise, you can also set the `scv.settings.figdir` to the desired path.

**Comment by honghh2018** [comment]
Thanks  @VolkerBergen  the advices, i try the save parameter and give it the absolute path '/share/nas1/Data/PipeLine/Other/RNA_Velocity/analysis/test88888.png', it display below error:

![image](https://user-images.githubusercontent.com/41668708/113287929-d06d6980-9320-11eb-9a66-46ef82bb4f9d.png)

'FileNotFoundError: [Errno 2] No such file or directory: './figures/scvelo_/share/nas1/Data/PipeLine/Other/RNA_Velocity/analysest88888.png
The code post below:
scv.pl.velocity_embedding_stream(t1, basis='X_seurat', color=['seurat_clusters','initial_size_spliced','initial_size_unspliced'],ax = ax1,save = '/share/nas1/Data/PipeLine/Other/RNA_Velocity/analysis/test88888.png')

**Comment by VolkerBergen** [comment]
Ok, I understand. That is due to the 'scvelo_' prefix, which you can remove with `scv.settings.plot_prefix = ''`.

**Comment by honghh2018** [comment]
Excellent,  @VolkerBergen  it worked. thanks

**Comment by VolkerBergen** [comment]
You can now also directly pass a filepath.
