### ISSUE TITLE
The latent time heatmap displaying confused result 

### ISSUE THREAD

**Issue by honghh2018** [theislab/scvelo#419]
Hi @All,
     It was so weird that when draw the heatmap using latent time columns selectting 300 genes in scv object.
     The picture showing the gene PRKY duplication just posted below: 
![image](https://user-images.githubusercontent.com/41668708/113377096-e83b0100-93a5-11eb-8701-42713bc9d6a8.png)
     The code lying below:
      top_genes = samples.var_names[samples.var.fit_likelihood.argsort()[::-1]][:300]
      scv.pl.heatmap(samples, var_names=top_genes, tkey='latent_time', n_convolve=100, col_color='seurat_clusters',save = 'latent_time_heatmap.png',figsize = (15,12))
      what happen in my case ? any kindly help would be appreciated.
       hanhuihong

**Comment by WeilerP** [comment]
@honghh2018, is the gene already duplicated in `top_genes` or only in the plot?

**Comment by WeilerP** [comment]
@honghh2018, any update on this? I'm closing this issue for now. Happy to reopen.
