### ISSUE TITLE
Filter in velocity_length

### ISSUE THREAD

**Issue by yjgeno** [theislab/scvelo#420]
Hi there, excellent work! My issue is that I wanted to test the difference of velocity length, which is simply the norm of computed velocity vectors, between two groups. Basically, I just called

```
scv.tl.velocity_confidence(adata)
scv.pl.scatter(adata, c='velocity_length', cmap='coolwarm', perc=[5, 95])
```

However, it looks there is a filter defined in the raw code of velocity_length, which filtered out genes with velocity 'NaN' and genes that are not 'velocity_genes'.

I have two questions regarding this flow:
1. Does this difference test make sense, given the vector length after being filtered might be different?
2. It turns out if I passed var_names="velocity_genes" but "velocity_genes" is not yet a column in adata.var, 'velocity_genes' will be determined in [this way](https://github.com/theislab/scvelo/blob/1ff51ba53f7fcedadb9ee147aac81383926dd9f6/scvelo/tools/dynamical_model.py#L432) 
    But should the velocity of genes that are NOT defined as 'velocity_genes' be 'NaN' as well? In my case, velocities for some genes that are NOT 'velocity_genes' were also computed.
Should I manually define 'velocity_genes' before dynamic recovery?

Thanks for any help you can provide!

Version:
scvelo==0.2.2  scanpy==1.7.0  anndata==0.7.5  loompy==3.0.6  numpy==1.20.1  scipy==1.6.0  matplotlib==3.3.4  sklearn==0.24.1  pandas==1.1.4

**Comment by yjgeno** [comment]
Hi, any insights or comments?

**Comment by WeilerP** [comment]
By default, parameters are only fitted for genes identified as  (potential) velocity genes. To identify these genes, we run the original RNA velocity model using extreme quantile linear regression. Following, there should not be any velocity calculated w.r.t. genes not identified during this process. Can you provide a reproducible example where a gene is not labeled as a velocity gene but its corresponding ODE is still being fitted?

Regarding your first question: I am not sure I fully understand the question / problem. The filtering simply removes NaN columns, i.e., genes for which no model has been fitted. How would you calculate the length of a vector with NaN entries?

**Comment by yjgeno** [comment]
Hi Weiler, thanks for the comments.
I referred to your velocity_confidence.py and it turns out there are 3 filters before it computes the velocity length:
https://github.com/theislab/scvelo/blob/1659cc8e00a45fcf87cd80a7013aae5531744613/scvelo/tools/velocity_confidence.py#L44

I listed the top 2 of them:
```
tmp_filter = np.invert(np.isnan(np.sum(V, axis=0))) 
tmp_filter &= np.array(ada.var['velocity_genes'], dtype=bool)
```
My question was simply about the necessity of the second filter, as the first one will filter out all the genes that are NOT identified as 'velocity_genes' (cannot be fitted and thus return NaN).
Why we still need the second one?

**Comment by WeilerP** [comment]
Ah, I see. You can always fit genes not identified as velocity genes by passing their names to `recover_dynamics` through the argument `var_names`. The second step to set up the filter ensure that such genes are ignored.

**Comment by yjgeno** [comment]
I see, this helps! 
May you also specify your conditions to identify genes as 'velocity genes'? 
It turns out if I define velocity genes manually before dynamic recovery, for some genes it gives me WARNING: GeneXX not recoverable due to insufficient samples.
Do you tell from the info of linear regression for stable states?

**Comment by WeilerP** [comment]
No, the model is defined as recoverable if there are at least two cells with non-trivial counts in the unspliced **and** spliced data. See [here](https://github.com/theislab/scvelo/blob/1659cc8e00a45fcf87cd80a7013aae5531744613/scvelo/tools/dynamical_model_utils.py#L761).

**Comment by yjgeno** [comment]
That helps! thank you so much
