### ISSUE TITLE
Velocity on hematopoiesis: is it advisable at all?

### ISSUE THREAD

**Issue by GabrielBaldissera** [theislab/scvelo#429]
Hello!

I am working in the velocity analysis and I am wondering wether I should trust my results or not. My dataset is composed of cells involved in zebrafish hematopoiesis at 26hpf. The overall directions I see are not according to what I would expect for this process.

The following is the visualization for my WT sample. 
Clusters 0, 1, 2, and 7  are all artery cells. Cluster 3 is a group of endothelial cells called HemECs (Hemogenic endothelial cells); cluster 4 and 6 are nHSPCs (Nascent Hemogenic stem and progenitor cells) and clusters 5, 8 and 9 are groups of progenitor cells (Erytroid, neutrophils and macrophages respectvely).
Therefore, as the endothelial-to-hematopoietic transition (EHT) is going on, we would expect the summarized velocities to be in the other direction (0,2->1->3->4,6->5,8,9).
I have tried running the analysis with different models and the results were very similar (Dynamic worked better to visualize phase portraits).

![image](https://user-images.githubusercontent.com/47226253/115313653-aa79fe80-a141-11eb-984a-47ac1828b3a3.png)

The directions 4,6->5,8,9 are according to what I would expect but not the rest.

I have read  #173 and therefore I did some of the check-up plots mentioned. Here is the  fragment ratio plot as suggested by @VolkerBergen:
![image](https://user-images.githubusercontent.com/47226253/115319946-e5366380-a14e-11eb-9c75-79931079b1f8.png)

Here is the confidence plot:
![image](https://user-images.githubusercontent.com/47226253/115318044-df3e8380-a14a-11eb-8a3b-c4da1783398e.png)

Here is the scvelo proportion plot:
![image](https://user-images.githubusercontent.com/47226253/115312985-74884a80-a140-11eb-8356-01da48d63ee6.png)

Based on the above plots, I could not identify any issue with the data.

Next thing I did was to look to phase portraits of individual genes. I have plotted 3 markers that we use to identify EHT cells. Myb is the marker of nHSPCs (Cluster 4 and 6), runx1 is the marker of HemECs (Cluster 3) and gata2b is the marker for artery cells that will give rise to HemECs (Cluster 1). Based on the following immage, the velocities are according to expected. That makes me wonder if there is another biological process that is "masking" EHT or if the fact that this process takes a long time is responsible for not capturing it in the trajectory directions.
![scvelo_EHT_genes_velocity](https://user-images.githubusercontent.com/47226253/115311866-5f122100-a13e-11eb-86a7-b4ba85ed9d60.png)

The two things that I am considering before taking a decision about using this data or not is 1) If it would be possible to bias the HVG calculation to use EHT markers and if that would change my directionality 2) If it would be useful to do an imputation on unspliced counts based on similarity computed on spliced counts with a software like MAGIC and recalculate my velocities.

Thank you for putting together this amazing tool and sorry for the long message! I would really appreciate if you could give me your oppinion about this data  before I take a final conclusion as I am considering that maybe the nature of my dataset will make it not possible to use these results.

Please, let me know if there is any further information I could provide.
Thank you!

Best, 
Gabriel

**Comment by VolkerBergen** [comment]
Hi Gabriel, 

good timing to ask that Q as we're currently wrapping a perspectives paper highlighting some of the limitations in RNA velocity estimation, particularly in hematop. 

Generally, I'd advise to be extra careful with conclusions in hematop., as we've observed all kinds of interesting effects, including transcriptional boost, time-dependent decay rates etc. (e.g. in erythroids) that are not correctly captured by current velocity models. 

After all, you'd have to make sure you got some informative genes for each cell type that are supporting the inferred directionality. Hence, if you send me phase portraits of top likelihood genes (say top20) I can tell you more about applicability.
