### ISSUE TITLE
pp.neighbors vs pp.moments

### ISSUE THREAD

**Issue by JonasMir** [theislab/scvelo#43]
Hi Volker,
I noticed that computing the neighbourhood graph with scanpy before computing the moments makes a difference. I would have thought doing so would simply be redundant (of course for same parameters as number of principal components and neighbours) but it seems to matter: The UMAP looks different, the number of Louvain clusters for fixed resolution differs and the velocity flows change. So how does pp.moments actually compute the neighbourhood graph?
Best, Jonas

**Comment by VolkerBergen** [comment]
The neighbor graph should be the same in scvelo and scanpy. Did `pp.moments` recompute your neighbor graph?

**Comment by JonasMir** [comment]
No, pp.moments does not recompute the graph. But going directly for pp.moments, instead of applying pp.neighbors, somehow matters. My current versions are scanpy 1.3.7 and scvelo 0.1.15.

**Comment by VolkerBergen** [comment]
Could you check the difference by printing in each case `adata.uns['neighbors'].

Btw, there is already scanpy 1.4 and scvelo 0.1.16.

**Comment by JonasMir** [comment]
Cool, I will check out the new versions...
Regarding my "neighbourhood graph problem": The graphs differ, for example I compared the adata.uns['neighbors']['distances'] matrices. I suspect the pca to be the reason. Because if you call scanpy.pp.neighbors with n_pcs without having precomputed the pca before, then (as I see it) pp.neighbors internally computes the pca and evaluates the first n_pcs for the computation of the neighbourhood graph. scvelo.pp.moments does not the identical thing, or? However, if I compute the pca before calling either pp.neighbors or pp.moments, it approximately leads to the same downstream results. 'Approximately', because for example instead of 7 Louvain clusters, I get 6 for same resolution.

**Comment by VolkerBergen** [comment]
Should be the same in `pp.moments`. It only recomputes pca if more pcs are required. Hence, you could first of all check whether you have the same number of components used.

Further, to make pca exactly reproducible, you'd need to set the attribute `svd_solver='arpack'` in scanpy.
