### ISSUE TITLE
velocity_embedding_stream does not honor 'color_map' argument

### ISSUE THREAD

**Issue by therealgenna** [theislab/scvelo#432]
Setting/changing `color_map` has no effect - same colors are shown on the plot. I think this is because `cmap` and `color_map` are used interchangeably. While in `velocity_embedding_stream` color_map is obtained via `kwargs.pop("cmap", color_map)` and should be set right, it's then passed to `scatter` via `**scatter_kwargs` as `color_map`.  BUT in `scatter` its `color_map` is defaulted to `None`, and it only looks for `cmap` in its `kwargs` (which are `scatter_kwargs` passed to it). So it never looks for `color_map` in `kwargs` and hence `color_map` stays the default `None`.

The fix would be either adding the `"cmap": color_map` to `scatter_kwargs` in `velocity_embedding_stream` or checking not only for `cmap` but for `color_map` in `kwargs` in `scatter`.

Probably similar things go for `c` and `color`, but I haven't checked, and for other plotting scripts, like `velocity_embedding_grid` etc.

Thank you

#### Versions:

> 
scvelo==0.2.3  scanpy==1.6.0  anndata==0.7.5  loompy==3.0.6  numpy==1.19.4  scipy==1.5.3  matplotlib==3.3.3  sklearn==0.23.2  pandas==1.1.5

**Comment by VolkerBergen** [comment]
Works now. If you install from source `pip install git+https://github.com/theislab/scvelo`, it should be available.

**Comment by therealgenna** [comment]
Thanks very much!

**Comment by wes-lewis** [comment]
I installed scvelo from source as you mentioned, yielding version 0.2.4. However, this issue still persists, with different color map choices eliciting no difference in the displayed color map (at least for categorical variables).
![clusters_scvelo_cmaps](https://user-images.githubusercontent.com/59123674/135916218-fa6cc6f2-b6fe-4e79-9f81-40d8ab346d7b.PNG)
)
