### ISSUE TITLE
Goodness of fit for velocity based Markov Chain model 

### ISSUE THREAD

**Issue by smgroves** [theislab/scvelo#433]
Is there a suggested way to test the goodness of fit of the markov chain model (i.e. the transition matrix) that is derived from the velocity graph? Since single cell data can be very noisy, it would be nice to have some kind of measure to determine how confident we can be in the transition matrix, similar to the velocity confidence metric, that allows us to understand how much variability should be expected in the transition matrix probabilities fit to the data.

**Comment by VolkerBergen** [comment]
hi @smgroves, that is available through `scv.tl.velocity_confidence_transition`. (correlation of displacement from expected transition with actual velocity).
