### ISSUE TITLE
Deployment error id django on heroku, i dont seem to find solution. i am stuck

### ISSUE THREAD

**Issue by EdwardDanu** [theislab/scvelo#436]
remote:        Collecting toml==0.10.1
remote:          Downloading toml-0.10.1-py2.py3-none-any.whl (19 kB)
remote:        Collecting touch==0.0.0
remote:          Downloading touch-0.0.0.tar.gz (4.5 kB)
remote:            ERROR: Command errored out with exit status 1:
remote:             command: /app/.heroku/python/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kn92l973/touch/setup.py'"'"'; __file__='"'"'/tmp/pip-insta
ll-kn92l973/touch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
 egg_info --egg-base /tmp/pip-pip-egg-info-bafq9pld
remote:                 cwd: /tmp/pip-install-kn92l973/touch/
remote:            Complete output (5 lines):
remote:            Traceback (most recent call last):
remote:              File "<string>", line 1, in <module>
remote:              File "/app/.heroku/python/lib/python3.9/tokenize.py", line 392, in open
remote:                buffer = _builtin_open(filename, 'rb')
remote:            IsADirectoryError: [Errno 21] Is a directory: '/tmp/pip-install-kn92l973/touch/setup.py'
remote:            ----------------------------------------
remote:        ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to quickloaner.
remote:
To https://git.heroku.com/quickloaner.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/quickloaner.git'

**Comment by WeilerP** [comment]
@EdwardDanu could you please rephrase the issue title to something more descriptive and outline what you are trying to achieve?

**Comment by WeilerP** [comment]
I'll close this for now. Happy to reopen once you provided some additional info @EdwardDanu.
