### ISSUE TITLE
Setting figure params launches IPython kernel

### ISSUE THREAD

**Issue by michalk8** [theislab/scvelo#437]
Setting figure parameters launches IPython kernel when using normal Python interpreter.
Culprit line: https://github.com/theislab/scvelo/blob/master/scvelo/settings.py#L300
Possible solution: setting `ipython_format=None`, which will raise an exception, which is then caught.

```python
# launch this in normal Python interpreter
import scvelo as scv
scv.settings.set_figure_params('scvelo', ipython_format=None)
```

<details>
<summary> Error </summary>

![2021-05-01T18:27:20+02:00](https://user-images.githubusercontent.com/46717574/116788619-e484c200-aaaa-11eb-893e-6d31582ad829.png)

</details>

#### Versions:

> scvelo==0.2.3  scanpy==1.8.0.dev78+gc488909a  anndata==0.7.5  loompy==2.0.16  numpy==1.19.5  scipy==1.6.2  matplotlib==3.4.1  sklearn==0.24.1  pandas==1.2.3

**Comment by VolkerBergen** [comment]
Thanks @michalk8. Important point! The solution in scanpy ([check if running in ipython](https://github.com/theislab/scanpy/blob/525f08f64ded1cda165f376d18721d5200108e10/scanpy/_settings.py#L471)) seems elegant, but doesn't work for me. Any idea how to resolve this internally without the explicit `ipython_format=None` workaround, @WeilerP?
