### ISSUE TITLE
typing_extensions not installed in Python 3.8

### ISSUE THREAD

**Issue by WeilerP** [theislab/scvelo#443]
The issue was first reported [here](https://github.com/theislab/scanpy/issues/1799#issuecomment-830137752):

> When using **python 3.8** in a fresh new virtual environment, I get, installation of the development version works fine, but when importing scvelo.
> 
> `Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/home/mischko/test/python_virtual/lib/python3.8/site-packages/scvelo/__init__.py", line 5, in <module> from scvelo import datasets, logging, pl, pp, settings, tl, utils File "/home/mischko/test/python_virtual/lib/python3.8/site-packages/scvelo/datasets.py", line 10, in <module> from scvelo.core import cleanup, SplicingDynamics File "/home/mischko/test/python_virtual/lib/python3.8/site-packages/scvelo/core/__init__.py", line 1, in <module> from ._anndata import ( File "/home/mischko/test/python_virtual/lib/python3.8/site-packages/scvelo/core/_anndata.py", line 4, in <module> from typing_extensions import Literal ModuleNotFoundError: No module named 'typing_extensions'`
> 
> `pip install typing_extensions` resolves the issue, so @WeilerP you might consider adding this to the setup.py.

**Comment by VolkerBergen** [comment]
Sure, let's declare it as dependency. Same for `anndata`?

**Comment by VolkerBergen** [comment]
Can you check scanpy's definition of [Literal](https://github.com/theislab/scanpy/blob/525f08f64ded1cda165f376d18721d5200108e10/scanpy/_compat.py#L3)? Perhaps, we don't need to specify it as requirement then.
