### ISSUE TITLE
Colorbar of the learned dynamics

### ISSUE THREAD

**Issue by yjgeno** [theislab/scvelo#444]
Hi, thanks for your package. I was generating the learned dynamics graph of certain genes like this

![image](https://user-images.githubusercontent.com/77600778/117546305-66b34000-afef-11eb-8911-52fb6c37f8ff.png)

I was wondering 
1. the learned curve could be turned off?
2. Once I set color='velocity', which is a gene-long vector for each cell, what does the colorbar value stand for? Is the L1 or L2 norm of the vectors? I was confused

Appreciate it if any help could be given!

**Comment by VolkerBergen** [comment]
1. You can turn it off with `vkey='none'`. 
2. It's showing the velocity values for this particular gene that is shown here.

**Comment by yjgeno** [comment]
@VolkerBergen Thanks!
Concerning my question 2, if the values assigned to each point are the velocity w.r.t a certain gene, I realized in my example there were points below the steady-state were coated with red instead of blue. 
I believe they are expected to be blue as their velocities should be negative. 

Please let me know if I made anything wrong

**Comment by WeilerP** [comment]
@yjgeno, sorry for the late reply: It i

> 2. Once I set color='velocity', which is a gene-long vector for each cell, what does the colorbar value stand for? Is the L1 or L2 norm of the vectors? I was confused

It is neither. Setting `color='velocity'` colours observations by their velocity in the gene for which the phase portrait is plotted. The extracted velocities are an array of length `n_obs`.

**Comment by yjgeno** [comment]
> @yjgeno, sorry for the late reply.
> 
> > 1. Once I set color='velocity', which is a gene-long vector for each cell, what does the colorbar value stand for? Is the L1 or L2 norm of the vectors? I was confused
> 
> It is neither. Setting `color='velocity'` colours observations by their velocity in the gene for which the phase portrait is plotted. The extracted velocities are an array of length `n_obs`.

Hi, @WeilerP Thank you! It makes sense but I was wondering why my points below the steady-state were not colored in blue?
The residuals of those used as velocities were low and negative I believe.
