### ISSUE TITLE
heatmap doesn't sort custom ytick labels properly

### ISSUE THREAD

**Issue by jbliton** [theislab/scvelo#445]
Hi, when I'm trying to add specific annotations for the yticklabels for a large gene list (~2100 genes) I'm not able to specify the labels in the way that I expected. When I add specific genes that I want to highlight in the graph, it pulls them out to the top of the list, rather than highlight where they are in the existing list. 

```
kwargs = dict(cbar_pos = (1.0, 0.025, 0.02, 0.9), yticklabels=['OLFM4','APOA4'])

axis = scv.pl.heatmap(adata, gene_list, sortby='velocity_pseudotime', col_color='lineage', n_convolve= 70,
                      figsize = (8,8), standard_scale = 0, colorbar = True,show = False, **kwargs)
```

</details>

![image](https://user-images.githubusercontent.com/54275184/117689341-a319a400-b187-11eb-9ae6-cf1c6926c5cf.png)

#### Versions:
scvelo==0.2.2  scanpy==1.7.1  anndata==0.7.4  loompy==3.0.6  numpy==1.19.2  scipy==1.6.2  matplotlib==3.3.4  sklearn==0.24.1  pandas==1.1.5

**Comment by WeilerP** [comment]
@jbliton, can you try passing the index of the genes for `yticklabels`? As I understand Seaborn's docs for `seaborn.heatmap` [here](https://seaborn.pydata.org/generated/seaborn.heatmap.html#seaborn.heatmap), this should give you the desired result.

**Comment by WeilerP** [comment]
@jbliton, I'll close this for now. Fell free to reopen if my suggestion did not resolve the problem.

**Comment by jbliton** [comment]
Do you mean the index in the gene list? or the index in the adata object? Or some other index? 

I'm trying both and I find the same results, just with numbers instead of the gene symbols

`print(np.where(subset.var_names=='REG1A')[0][0])
print(np.where(subset.var_names=='APOA4')[0][0])
    
print(gene_list.index('REG1A'))
print(gene_list.index('APOA4'))

kwargs = dict(cbar_pos = (1.0, 0.025, 0.02, 0.9), yticklabels = [0,1459])

scv.pl.heatmap(subset, gene_list, sortby='latent_time', col_color='lineage', color_map = blue_cmap, 
               n_convolve= 70,figsize = (5,5),standard_scale=0, sort = True, colorbar = False, **kwargs)#, save = 'CDS014_DE_genes')

kwargs = dict(cbar_pos = (1.0, 0.025, 0.02, 0.9), yticklabels = [2650,12044])

scv.pl.heatmap(subset, gene_list, sortby='latent_time', col_color='lineage', color_map = blue_cmap, 
               n_convolve= 70,figsize = (5,5),standard_scale=0, sort = True, colorbar = False, **kwargs)#, save = 'CDS014_DE_genes')
`
![image](https://user-images.githubusercontent.com/54275184/126809671-219d6f43-e0bb-4d44-ad09-be602d4f68ca.png)

![image](https://user-images.githubusercontent.com/54275184/126809694-aa17c8c8-c106-44e9-84b6-3e01c6f654c3.png)

**Comment by WeilerP** [comment]
@jbliton, you are only setting the labels for the first two. Does [this](https://stackoverflow.com/questions/47784215/seaborn-heatmap-custom-tick-values) help/give you the desired result?

A dirty hack that also works is passing a list of `None`s except for the position where you want a specific label. For example if you want to label the first and 5th tick but nothing in between:

```python
svc.heatmap(..., yticklabels=['gene 1', None, None, None, 'gene 5'])
```

This will, however, plot all ticks and only annotated the not `None` ones.

**Comment by lohrmanf** [comment]
Hi,
@jbliton and @WeilerP, have you solved the issue yet? I am looking for the exact same thing and have not found a solution so far. @WeilerP, the "dirty hack" you suggest works just fine but is very impractical for large heatmaps. The link provides a solution for regular ticking but not for displaying hand-picked genes. I would be grateful for any help.
