### ISSUE TITLE
I'm trying to run the DentateGyrus.ipynb example and facing this error

### ISSUE THREAD

**Issue by saksham219** [theislab/scvelo#45]
`adata = scv.read("data/DentateGyrus/10X43_1.loom", sparse=True, cache=True, 
                 backup_url="http://pklab.med.harvard.edu/velocyto/DG1/10X43_1.loom")`

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-f0cda60772a0> in <module>()
      1 adata = scv.read("data/DentateGyrus/10X43_1.loom", sparse=True, cache=True, 
----> 2                  backup_url="http://pklab.med.harvard.edu/velocyto/DG1/10X43_1.loom")

~/anaconda3/lib/python3.6/site-packages/scanpy/readwrite.py in read(filename, backed, sheet, ext, delimiter, first_column_names, backup_url, cache, **kwargs)
     76         return _read(filename, backed=backed, sheet=sheet, ext=ext,
     77                      delimiter=delimiter, first_column_names=first_column_names,
---> 78                      backup_url=backup_url, cache=cache, **kwargs)
     79     # generate filename and read to dict
     80     filekey = filename

~/anaconda3/lib/python3.6/site-packages/scanpy/readwrite.py in _read(filename, backed, sheet, ext, delimiter, first_column_names, backup_url, cache, suppress_cache_warning, **kwargs)
    472             adata = _read_softgz(filename)
    473         elif ext == 'loom':
--> 474             adata = read_loom(filename=filename, **kwargs)
    475         else:
    476             raise ValueError('Unkown extension {}.'.format(ext))

~/anaconda3/lib/python3.6/site-packages/anndata/readwrite/read.py in read_loom(filename, sparse, cleanup, X_name, obs_names, var_names, dtype)
    182             var=var,
    183             layers=layers,
--> 184             dtype=dtype)
    185     return adata
    186 

~/anaconda3/lib/python3.6/site-packages/anndata/base.py in __init__(self, X, obs, var, uns, obsm, varm, layers, raw, dtype, shape, filename, filemode, asview, oidx, vidx)
    664                 layers=layers,
    665                 dtype=dtype, shape=shape,
--> 666                 filename=filename, filemode=filemode)
    667 
    668     def _init_as_view(self, adata_ref: 'AnnData', oidx: Index, vidx: Index):

~/anaconda3/lib/python3.6/site-packages/anndata/base.py in _init_as_actual(self, X, obs, var, uns, obsm, varm, raw, layers, dtype, shape, filename, filemode)
    889 
    890         # layers
--> 891         self._layers = AnnDataLayers(self, layers, dtype)
    892 
    893     def __sizeof__(self) -> int:

~/anaconda3/lib/python3.6/site-packages/anndata/layers.py in __init__(self, adata, layers, dtype, adata_ref, oidx, vidx)
     35                 raise ValueError('Shape does not fit.')
     36             if layer.dtype != np.dtype(dtype):
---> 37                 self._layers[key] = layer.astype(dtype, copy=False)
     38             else:
     39                 self._layers[key] = layer

TypeError: astype() got an unexpected keyword argument 'copy'

scvelo==0.1.16.dev18+3f160f2  scanpy==1.4  anndata==0.6.18  loompy==2.0.16  numpy==1.13.1  scipy==0.19.1  matplotlib==2.1.2  sklearn==0.20.2  pandas==0.20.3

**Comment by VolkerBergen** [comment]
The problem is with your very old scipy version. See scVelo requirements.
Installing from PyPI installs all the requirements needed, which includes scipy >= 1.0.
