### ISSUE TITLE
Error in scv.pp.moments 

### ISSUE THREAD

**Issue by shexiaolu** [theislab/scvelo#453]
Recently , i use the scvelo again , but it has an error in scv.pp.moments that didn't happen before.Code is below

```
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)-->
```python
```
TypeError                                 Traceback (most recent call last)
TypeError: expected dtype object, got 'numpy.dtype[float64]'

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-39-057178b4a97c> in <module>
----> 1 scv.pp.moments(adata, n_pcs=30, n_neighbors=30)

~/anaconda3/lib/python3.8/site-packages/scvelo/preprocessing/moments.py in moments(data, n_neighbors, n_pcs, mode, method, use_rep, use_highly_variable, copy)
     62 
     63     if n_neighbors is not None and n_neighbors > get_n_neighs(adata):
---> 64         neighbors(
     65             adata,
     66             n_neighbors=n_neighbors,

~/anaconda3/lib/python3.8/site-packages/scvelo/preprocessing/neighbors.py in neighbors(adata, n_neighbors, n_pcs, use_rep, use_highly_variable, knn, random_state, method, metric, metric_kwds, num_threads, copy)
    103             n_comps = min(30 if n_pcs is None else n_pcs, n_vars - 1, adata.n_obs - 1)
    104             use_highly_variable &= "highly_variable" in adata.var.keys()
--> 105             pca(
    106                 adata,
    107                 n_comps=n_comps,

~/anaconda3/lib/python3.8/site-packages/scanpy/preprocessing/_pca.py in pca(data, n_comps, zero_center, svd_solver, random_state, return_info, use_highly_variable, dtype, copy, chunked, chunk_size)
    198             )
    199 
--> 200         output = _pca_with_sparse(
    201             X, n_comps, solver=svd_solver, random_state=random_state
    202         )

~/anaconda3/lib/python3.8/site-packages/scanpy/preprocessing/_pca.py in _pca_with_sparse(X, npcs, solver, mu, random_state)
    309     ev = s[idx] ** 2 / (X.shape[0] - 1)
    310 
--> 311     total_var = _get_mean_var(X)[1].sum()
    312     ev_ratio = ev / total_var
    313 

~/anaconda3/lib/python3.8/site-packages/scanpy/preprocessing/_utils.py in _get_mean_var(X, axis)
      6 def _get_mean_var(X, *, axis=0):
      7     if sparse.issparse(X):
----> 8         mean, var = sparse_mean_variance_axis(X, axis=axis)
      9     else:
     10         mean = np.mean(X, axis=axis, dtype=np.float64)

~/anaconda3/lib/python3.8/site-packages/scanpy/preprocessing/_utils.py in sparse_mean_variance_axis(mtx, axis)
     40         )
     41     else:
---> 42         return sparse_mean_var_minor_axis(mtx.data, mtx.indices, *shape, np.float64)
     43 
     44 

SystemError: CPUDispatcher(<function sparse_mean_var_minor_axis at 0x2b04269641f0>) returned a result with an error 
```

 scvelo==0.2.3  scanpy==1.6.1  anndata==0.7.5  loompy==3.0.6  numpy==1.20.1  scipy==1.6.1  matplotlib==3.2.2  sklearn==0.22  pandas==1.1.4  
 
any help?

**Comment by WeilerP** [comment]
This is an issue caused by `scanpy`. Please open an issue there for help and some potential insight.

**Comment by gav-sturm** [comment]
was scanpy able to help with this bug? i just ran into the same issue. Was working fine in December of 2020 but now have the same error message

**Comment by WeilerP** [comment]
@gav-sturm which versions are you using?

**Comment by WeilerP** [comment]
@syouligan, as mentioned before, this is a bug in Sccanpy. You'll need to check there/open an issue.

**Comment by syouligan** [comment]
No worries, resolved thanks @WeilerP. This issue was occurring due to an incompatibility between the python packages numpy and numba.
