### ISSUE TITLE
Re-arranging clusters (labels) - question

### ISSUE THREAD

**Issue by vim15** [theislab/scvelo#464]
I'm sorry if this is better asked somewhere else (like biostars), but thought you would be the ideal people to raise it to. 

Is there a straightforward way of re-arranging the clusters in the object (i.e the ordering on the key). I've assigned names to my clusters, but on the key they come out as "A, C, D, B". I've tried re-arranging them using the below code :

```
adata.obs['seurat_clusters'].cat.categories = ["a", "b", "c"]
order = [1, 0, 2]

adata.obs['seurat_clusters'].cat.categories = [adata.obs['seurat_clusters'].cat.categories[i] for i in order]
```

the above re-orders the labels in the proper order, but not the actual cells. So my key is shown as it should be, but the populations and the respective labels do not match. 
Just to clarify, C clusters contains cells C1, C2, C3 etc, by doing the above, the C cluster is renamed to "B" but it still contains C1,C2,C3...which is a problem as now the label does not match the cell type.  I hope it makes sense the way i've described the problem. 

Thank you :)

**Comment by dawe** [comment]
Take a look at the [official pandas docs](https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html#reordering) about reordering. Something like

```
adata.obs['seurat_clusters'].cat.reorder_categories(['b', 'a', 'c'], inplace=True)
```

should work

**Comment by vim15** [comment]
@dawe this has worked like a charm. Thank you, it is very much appreciated :)
