### ISSUE TITLE
pp.show_proportions cannot detect abundance of transcripts

### ISSUE THREAD

**Issue by plath997** [theislab/scvelo#47]
Hi, I am trying to run scVelo using a merged object (combination of 16 loom files). Unfortunately, when I run `scv.pp.show_proportions(adata)` I encounter this error `RuntimeWarning: invalid value encountered in true_divide
  [np.mean(tot_mol_cell / np.sum(tot_mol_cell_layers, 0)) for tot_mol_cell in tot_mol_cell_layers], 2)` This prevents me from later on running `scv.tl.velocity_graph(adata)`
When I run the same object using velocyto, I don't encounter an issue, which is why I am wondering what could be happening here. Any clarity would be appreciated.

**Comment by VolkerBergen** [comment]
Seems like you've got some cells that have neither any spliced nor unspliced counts. You can filter those out, e.g. using 
```
import scanpy as sc
sc.pp.filter_cells(adata, min_counts=200)
```

Usually those cells would already be filtered within the counting pipeline.

**Comment by plath997** [comment]
Thank you! It worked
