### ISSUE TITLE
Problem with arrow direction [Question] 

### ISSUE THREAD

**Issue by pabloatria18** [theislab/scvelo#487]
Hello. I am sorry I know there are some other issues open that are similar to mine but I have not been able to fix this. I am totally new to RNA velocity, this being my first analyzed dataset.
I have a dataset from bone, where the most differentiated group of cells (Cluster 6) and the intermediate state (Cluster 2) is pointing towards the progenitors (Cluster 0-1-3).
I followed the directions that I found in other issues such as #112 and #173 

Here I attach my outputs:
scv.pl.proportions(adata,groupby='Clusters')
<img width="599" alt="Prop" src="https://user-images.githubusercontent.com/54920011/120822235-33979a00-c524-11eb-8cb1-f0e36f8bb6cc.png">

UMAP
<img width="458" alt="UMAP" src="https://user-images.githubusercontent.com/54920011/120822453-6cd00a00-c524-11eb-995f-621bf9af4406.png">

scv.tl.velocity(adata, mode='stochastic')
<img width="400" alt="RNAVelStoch" src="https://user-images.githubusercontent.com/54920011/120822473-722d5480-c524-11eb-8c93-5ce83d1c53df.png">

scv.tl.velocity(adata, mode='steady_state')
<img width="403" alt="Steady" src="https://user-images.githubusercontent.com/54920011/120822494-76597200-c524-11eb-96a2-0d607b18285a.png">

scv.tl.recover_dynamics(adata)
scv.tl.velocity(adata, mode='dynamical')
<img width="397" alt="Dynamic" src="https://user-images.githubusercontent.com/54920011/120822519-7bb6bc80-c524-11eb-9c3e-9693b6b2655f.png">

print(adata.var['velocity_genes'].sum(), adata.n_vars)
379 2000

top_genes = adata.var.sort_values('fit_likelihood', ascending=False).index[:10]
<img width="659" alt="Top10" src="https://user-images.githubusercontent.com/54920011/120822531-7fe2da00-c524-11eb-884d-737288882357.png">

Color Pseudotime
<img width="416" alt="Pseudotime" src="https://user-images.githubusercontent.com/54920011/120823482-7a39c400-c525-11eb-9044-ff52f4ed3a46.png">

counts_s = scv.utils.sum_var(adata.layers['spliced'])
counts_u = scv.utils.sum_var(adata.layers['unspliced'])
fractions_u = counts_u / (counts_s + counts_u)
scv.pl.scatter(adata, color=fractions_u, smooth=True)
<img width="442" alt="Another" src="https://user-images.githubusercontent.com/54920011/120823546-8b82d080-c525-11eb-8d12-4aa80d375347.png">

I appreciate the help
Thank you very much!

**Comment by WeilerP** [comment]
@pabloatria18, please see #416 or #216. Happy to have a discussion there if something is still unclear.

**Comment by pabloatria18** [comment]
Thank you @WeilerP, Sorry for duplicating the issue!
I saw both issues you mentioned, and I noticed not all of my genes have the almond/football shape as mentioned.
I have 379 velocity genes and I was wondering if there is a way of selecting some of them and evaluate if the direction changes?
What would you recommend me to do in this case?
I really appreciate your time and advice!

**Comment by WeilerP** [comment]
@pabloatria18, can we please move the discussion to #462 to have the related problems in the same place? Just repost your question there. Thanks!

**Comment by pabloatria18** [comment]
Sure! Thank you @WeilerP!
