### ISSUE TITLE
`tl.recover_dynamics` calculation on a subset of cells depends on previous velocity calculations

### ISSUE THREAD

**Issue by therealgenna** [theislab/scvelo#497]
#### Description of the bug: 
Hi,
When I am running `tl.recover_dynamics` on a subset of cells from an obj for which `velocity` in `stochastic` mode has been previously run, the result depends on whether I run `velocity` in `stochastic` mode on this subset, before running `tl.recover_dynamics`.

I'd expect the `tl.recover_dynamics` mode to work the same on a subset irrespective of me running `velocity` prior to that (on that same subset.) There seems to be no reason to run `velocity` (in stochastic mode) in order to prepare for the calculation of the dynamical model.

My guess is that `tl.recover_dynamics` uses some pre-computed features which are computed in `stochastic velocity`, instead of forcing their re-computation. Since the values in the subset are initially inherited from the whole object (and some are likely incorrect for the subset as a standalone), they apparently change when I run `stochastic velocity` on the subset.

The first block gives different results from the next block below:
```
DS=obj[[bool(re.match('^AB',x)) for x in obj.obs.orig_ident], :] # get a subset of cells from obj
scv.pp.moments(DS, n_pcs=30, n_neighbors=30) # recalculates neighbors ...
scv.tl.velocity(DS)  # <-- THIS IS THE ONLY DIFFERENCE BETWEEN THE BLOCKS
scv.tl.recover_dynamics(DS, n_jobs=4)
Counter(DS.var.fit_likelihood.isna())  # Counter({True: 1841, False: 158}) - fit 158 genes
```

```
DS=obj[[bool(re.match('^AB',x)) for x in obj.obs.orig_ident], :] # get a subset of cells from obj
scv.pp.moments(DS, n_pcs=30, n_neighbors=30) # recalculates neighbors ...
scv.tl.recover_dynamics(DS, n_jobs=4)
Counter(DS.var.fit_likelihood.isna())  # Counter({True: 1998, False: 1}) - fit only 1 gene
```

#### Versions:
scvelo==0.2.3  scanpy==1.6.0  anndata==0.7.5  loompy==3.0.6  numpy==1.19.4  scipy==1.5.3  matplotlib==3.3.3  sklearn==0.23.2  pandas==1.1.5
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.

**Comment by therealgenna** [comment]
I looked a bit more and `tl.velocity` (re)calculates `var.velocity_genes`.

According to the documentation, `tl.recover_dynamics` by default uses `var_names='velocity_genes'` for dynamical model fitting, and then `tl.velocity` (in the dynamical mode) will again (re)calculate `var.velocity_genes`.

It looks like somewhat circular, at least with the default behavior: I need to use stochastic mode to define `velocity_genes` which will be used for dynamical model calculation needed to calculate dynamical mode velocity, which will define its own `velocity_genes`.

Could you please tell what am I doing wrong? 
Also, I could not find any description of how are the `velocity_genes` defined - could you please explain?

**Comment by WeilerP** [comment]
As already pointed out by you, passing `var_names="velocity_genes"` will trigger a recalculation of these genes using the steady state model. Velocity genes are defined [here](https://github.com/theislab/scvelo/blob/dc1a66a1c619e8d3d6b04d30644bf3f4171e0d72/scvelo/tools/velocity.py#L93). To prevent the recalculation, you need to pass the names of the velocity genes directly. You should be able to extract them via

```python
var_names = adata.var_names[adata.var['velocity_genes']].tolist()
```

**Comment by therealgenna** [comment]
Thank you for the quick response!

Are you saying that passing `var_names="velocity_genes"` to `tl.recover_dynamics` will trigger the recalculation of velocity genes? I was just saying that running `tl.velocity` (either in stochastic or dynamic, and probably in steady-state mode) calculates them.

It does not look like `tl.recover_dynamics` triggers calculation of velocity genes if I use `var_names="velocity_genes"` argument, and that is basically why I've opened this issue. As my initial two code blocks indicate I get different results in them, which wouldn't have happened if calculation of velocity genes was triggered inside `tl.recover_dynamics`, afaik. If there are predefined velocity genes `tl.recover_dynamics` seems to just use them, and if there are no velocity genes I guess it uses all genes (?); or maybe in that case it calculates velocity genes but it does not save them?

I just did this:
```
DS.var.drop('velocity_genes',axis=1,inplace=True)
scv.tl.recover_dynamics(DS, n_jobs=4) # var_names="velocity_genes" is the default
Counter(DS.var.velocity_genes) # AttributeError: 'DataFrame' object has no attribute 'velocity_genes'
scv.tl.velocity(DS, mode='dynamical') # THIS calculates/sets velocity genes
Counter(DS.var.velocity_genes) # Counter({False: 1819, True: 180})
```
Instead of deleting velocity_genes from `DS.var`, I also tried to use all genes:
```scv.tl.recover_dynamics(DS, n_jobs=4, var_names=DS.var_names)```
I get multiple warnings for genes "not recoverable due to insufficient samples", which is fine, but is different from the previous case when I deleted `DS.var.velocity_genes`, where there were no warnings. Here, after running `scv.tl.velocity(DS, mode='dynamical')` I get 185 velocity genes (vs. 180 above).

I am trying to understand what would be the right strategy for my case, when I subset an object which already had velocity genes calculated in it. There are three alternatives, and they all produce different results:
1.  The "naive" way: this seems to use pre-existing velocity genes and is definitely not good in general:
```
scv.tl.recover_dynamics(DS) # with var_names="velocity_genes" by default
```
2. Remove pre-existing velocity genes; not sure exactly what it does and which genes it uses, but it does NOT set `DS.var.velocity_genes`:
```
DS.var.drop('velocity_genes',axis=1,inplace=True)
scv.tl.recover_dynamics(DS) # with var_names="velocity_genes" by default
```
3. Force run on all genes:
```scv.tl.recover_dynamics(DS, n_jobs=4, var_names=DS.var_names)```

I'd say (2) and (3) both make sense, but they are not identical, and I am not sure what exactly (2) does.

If the default, naive approach (1) was recalculating the velocity genes inside `scv.tl.recover_dynamics(DS)`, I would not have noticed any problem and gone into the woods :-)

Thanks for your help!

**Comment by WeilerP** [comment]
Okay, sorry, I missed a step in the code. So let me reiterate what is happening in detail:

Running `scv.tl.recover_dynamics` using default arguments, infers model paramters for what we call *velocity genes*.

## Case 1 - Velocity genes have been computed beforehand

In this case, velocity genes are given via the column `velocity_genes` in `adata.var`. `scv.tl.recover_dynamics` will then infer the parameters for these genes. This is happening [here](https://github.com/theislab/scvelo/blob/1659cc8e00a45fcf87cd80a7013aae5531744613/scvelo/tools/dynamical_model.py#L445).

Here is your code snippet again:

```python
DS=obj[[bool(re.match('^AB',x)) for x in obj.obs.orig_ident], :] # get a subset of cells from obj
scv.pp.moments(DS, n_pcs=30, n_neighbors=30) # recalculates neighbors ...
scv.tl.velocity(DS)
scv.tl.recover_dynamics(DS, n_jobs=4)
```

So you are calculating `velocity_genes` using the **stochastic model** since it is the default for `scv.tl.velocity`.

## Case 2 - Velocity genes have **not** been computed beforehand

In this case, the column `velocity_genes` does not exist in `adata.var`. `scv.tl.recover_dynamics` identifies velocity genes automatically [here](https://github.com/theislab/scvelo/blob/1659cc8e00a45fcf87cd80a7013aae5531744613/scvelo/tools/dynamical_model.py#L449). In this case, we are using the **steady state model**.

> I just did this:
> 
> ```
> DS.var.drop('velocity_genes',axis=1,inplace=True)
> scv.tl.recover_dynamics(DS, n_jobs=4) # var_names="velocity_genes" is the default
> Counter(DS.var.velocity_genes) # AttributeError: 'DataFrame' object has no attribute 'velocity_genes'
> scv.tl.velocity(DS, mode='dynamical') # THIS calculates/sets velocity genes
> Counter(DS.var.velocity_genes) # Counter({False: 1819, True: 180})
> ```

The attribute error is thrown because `scv.tl.recover_dynamics` does not add a column `velocity_genes` to `adata.var`.

## Addressing your points/questions

> Instead of deleting velocity_genes from `DS.var`, I also tried to use all genes:
> `scv.tl.recover_dynamics(DS, n_jobs=4, var_names=DS.var_names)`
> I get multiple warnings for genes "not recoverable due to insufficient samples", which is fine, but is different from the previous case when I deleted `DS.var.velocity_genes`, where there were no warnings. Here, after running `scv.tl.velocity(DS, mode='dynamical')` I get 185 velocity genes (vs. 180 above).

As mentioned above: `scv.tl.velocity(DS, mode='dynamical')` determines velocity genes internally using the steady state model. Using `var_names=DS.var_names`, you'll infer the parameters for all genes (except those with insufficient samples).

> I am trying to understand what would be the right strategy for my case, when I subset an object which already had velocity genes calculated in it. There are three alternatives, and they all produce different results:
> 
> 1. The "naive" way: this seems to use pre-existing velocity genes and is definitely not good in general:
> 
> ```
> scv.tl.recover_dynamics(DS) # with var_names="velocity_genes" by default
> ```

Not sure why you consider it as "not good in general". If you want to infer model parameters for a custom set of genes, you can simply define a new column, let's say `custom_velocity_genes`, in `adata.var` and pass `var_names="custom_velocity_genes"` to `scv.tl.recover_dynamics`.

> 2. Remove pre-existing velocity genes; not sure exactly what it does and which genes it uses, but it does NOT set `DS.var.velocity_genes`:
> 
> ```
> DS.var.drop('velocity_genes',axis=1,inplace=True)
> scv.tl.recover_dynamics(DS) # with var_names="velocity_genes" by default
> ```

See above. This defines velocity genes using the steady state model.

> 3. Force run on all genes:
>    `scv.tl.recover_dynamics(DS, n_jobs=4, var_names=DS.var_names)`

I would not recommend this. This will infer parameters for a lot of genes which lack the relevant info and would be filtered out when identifying velocity genes. As such, runtime will increase unnecessarily and you may add unnecessary and unwanted noise.

Hope this helped and answered your question.

**Comment by therealgenna** [comment]
Thank you - that basically clarifies the issue. My last comment/explanation is on why I say the "naive" way, point (1) above, is not good in general. That's basically why I opened this whole issue. I say this because the velocity genes defined on the whole object might be bad / irrelevant to the selected subset (DS). However, as a simple user I am not aware that this bad choice (for my subset) of velocity genes will be silently used. I'd want the velocity genes be recalculated by default inside `recover_dynamics`. (Also, it might make sense to save them when it does so; it might be useful to have a record of which genes were used by `recover_dynamics`.)

Please look at my first posting on this issue: when I don't call `tl.velocity` in the 2nd code block there (which changes previously defined velocity genes), I only have very few (1 or 2) pre-existing velocity genes and dynamical model and plotting fail in the end. So I had to play with it to understand what's going on and you helped me in that. But a new user might hit the same difficulty. To me it still seems that the default behavior of `recover_dynamics` (point 1 above) is in general problematic (I know what to do now, but others might not).

Thanks again - your clarifications are very helpful!

**Comment by WeilerP** [comment]
Okay, gotcha. I don't think velocity genes should be recalculated by default TBH. I'll update the docs to clarify what's going on.
I do agree that it should be possible to enforce a recalculation of the velocity genes. Will open a separate issue with a feature request for this.

> Thank you - that basically clarifies the issue. My last comment/explanation is on why I say the "naive" way, point (1) above, is not good in general. That's basically why I opened this whole issue. I say this because the velocity genes defined on the whole object might be bad / irrelevant to the selected subset (DS). However, as a simple user I am not aware that this bad choice (for my subset) of velocity genes will be silently used. I'd want the velocity genes be recalculated by default inside `recover_dynamics`.

I see your point but don't think velocity genes should be recalculated by default. A lot of times (maybe most of them), this will lead to unnecessary computation and consequently increasing runtime. Gotta think a bit on whether or not to add an option to enforce the calculation of velocity genes.

> (Also, it might make sense to save them when it does so; it might be useful to have a record of which genes were used by `recover_dynamics`.)

This is already implicitly given by the columns `fit_alpha`, `fit_beta` and `fit_gamma` in `adata.var`. Genes used in `scv.tl.recover_dynamics` are assigned the inferred model parameters, all other `np.nan`.

> Please look at my first posting on this issue: when I don't call `tl.velocity` in the 2nd code block there (which changes previously defined velocity genes), I only have very few (1 or 2) pre-existing velocity genes and dynamical model and plotting fail in the end. So I had to play with it to understand what's going on and you helped me in that. But a new user might hit the same difficulty. To me it still seems that the default behavior of `recover_dynamics` (point 1 above) is in general problematic (I know what to do now, but others might not).

I'll update the docs to hopefully make it clearer.

**Comment by therealgenna** [comment]
That sounds great, thank you!
