### ISSUE TITLE
API considerations

### ISSUE THREAD

**Issue by flying-sheep** [theislab/scvelo#5]
Hi!

While scanpy is a toolbox with many independent parts, I think scvelo is unlikely to outgrow a certain size.

I think it would be sufficient to import everything directly in `scvelo/__init__.py`. I have the followining mind:

- Get rid of `scvelo.preprocessing`:

  - `show_proportions` is a debugging function that prints stuff and is for a weird reason also able to remove layers… something not reflected in the name. maybe put it in some internal `scvelo/_utils` module and split it into `print_proportions` and `clear_layers` functions
  - `moments` can be directly `scvelo.moments`. the function shouldn’t be named the same. maybe `add_moments`? then you can also import it directly in `scvelo` without shadowing the module name
  - `recipes` can also just be `scvelo.recipes`

- Get rid of `tools`:

  - `scvelo.tools.velocity`, `scvelo.velocity_embedding`, `scvelo.velocity_graph`, … can just be `scvelo.velocity`, `scvelo.velocity.embedding`, …
  - the main `velocity` function can also be named e.g. `add_velocity` and imported in `scvelo` directly.

- Rename `plotting.velocity` to `plotting.plot_velocity` and import it in scvelo.

Now we have a flat module and example code would be

```py
import scvelo  # no need to rename this, keep the short full name

adata = ...
scvelo.velocity_graph(adata, ...)
scvelo.plot_velocity(adata, ...)
```

or so.

**Comment by VolkerBergen** [comment]
Thanks for your comment. The main reason for these name conventions (`pp`, `tl`, `pl`):
Firstly, it should harmonize with scanpy, which also includes usage principles. For instance, after computing the embedding via `sc.tl.umap(adata)` you would just compute the velocities in that embedding via `sc.tl.velocity_embedding(adata, basis='umap')`. Both tools would be under `tl`. 
Secondly, many more tools will be added (this is just an alpha release with basic RNA velocity tools).
