### ISSUE TITLE
scVelo cell cycle score calculation

### ISSUE THREAD

**Issue by sidrahmaryam** [theislab/scvelo#502]
Hello! 
Firstly, Thank you so much for this wonderful tool for single cell analysis. 
I wanted to address an issue I am facing while implementing the code. I have two datasets. In one of it, the cell cycle score determination was done all correctly, while in the other one it gave an error.
I am mentioning the error below. Kindly suggest the possible reason for the same and any alternative to correct it. I will be grateful for your help. 
Thank you

Code line used:
`scv.tl.score_genes_cell_cycle()`

Error:

calculating cell cycle phase
WARNING: provided gene list has length 0, scores as 0
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
**IndexError: arrays used as indices must be of integer (or boolean) type**

Please help.

**Comment by WeilerP** [comment]
@sidrahmaryam, which versions are you using (output of `scv.logging.print_versions()`)?  Would you please also provide the **full** stack trace so that I can see which part exactly is causing the problem? Thanks!

On a general note: Please stick to the provided issue template as closely as possible. This simplifies and speeds up debugging these sort of issues.

**Comment by sidrahmaryam** [comment]
Thank you for your response. 

![image](https://user-images.githubusercontent.com/58388074/122196659-0bf5e980-ceb5-11eb-9e57-a686efb22de5.png)


The complete error is given as:


calculating cell cycle phase
WARNING: provided gene list has length 0, scores as 0
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-79-798330f5b529> in <module>
----> 1 scv.tl.score_genes_cell_cycle(f)
      2 scv.pl.scatter(f, color_gradients=['S_score', 'G2M_score' ], perc=[5, 95], save = 'cell-score.pdf')

~/anaconda3/lib/python3.8/site-packages/scvelo/tools/score_genes_cell_cycle.py in score_genes_cell_cycle(adata, s_genes, g2m_genes, copy, **kwargs)
     96     kwargs.update({"ctrl_size": ctrl_size})
     97     score_genes(adata, gene_list=s_genes, score_name="S_score", **kwargs)
---> 98     score_genes(adata, gene_list=g2m_genes, score_name="G2M_score", **kwargs)
     99     scores = adata.obs[["S_score", "G2M_score"]]
    100 

~/anaconda3/lib/python3.8/site-packages/scanpy/tools/_score_genes.py in score_genes(adata, gene_list, ctrl_size, gene_pool, n_bins, score_name, random_state, copy, use_raw)
    159         X_list = np.nanmean(X_list, axis=1)
    160 
--> 161     X_control = _adata[:, control_genes].X
    162     if issparse(X_control):
    163         X_control = np.array(_sparse_nanmean(X_control, axis=1)).flatten()

~/anaconda3/lib/python3.8/site-packages/anndata/_core/anndata.py in __getitem__(self, index)
   1086         """Returns a sliced view of the object."""
   1087         oidx, vidx = self._normalize_indices(index)
-> 1088         return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
   1089 
   1090     def _remove_unused_categories(self, df_full, df_sub, uns):

~/anaconda3/lib/python3.8/site-packages/anndata/_core/anndata.py in __init__(self, X, obs, var, uns, obsm, varm, layers, raw, dtype, shape, filename, filemode, asview, obsp, varp, oidx, vidx)
    303             if not isinstance(X, AnnData):
    304                 raise ValueError("`X` has to be an AnnData object.")
--> 305             self._init_as_view(X, oidx, vidx)
    306         else:
    307             self._init_as_actual(

~/anaconda3/lib/python3.8/site-packages/anndata/_core/anndata.py in _init_as_view(self, adata_ref, oidx, vidx)
    346         var_sub = adata_ref.var.iloc[vidx]
    347         self._obsm = adata_ref.obsm._view(self, (oidx,))
--> 348         self._varm = adata_ref.varm._view(self, (vidx,))
    349         self._layers = adata_ref.layers._view(self, (oidx, vidx))
    350         self._obsp = adata_ref.obsp._view(self, oidx)

~/anaconda3/lib/python3.8/site-packages/anndata/_core/aligned_mapping.py in _view(self, parent, subset_idx)
     90     def _view(self, parent: "anndata.AnnData", subset_idx: I):
     91         """Returns a subset copy-on-write view of the object."""
---> 92         return self._view_class(self, parent, subset_idx)
     93 
     94     @deprecated("dict(obj)")

~/anaconda3/lib/python3.8/site-packages/anndata/_core/aligned_mapping.py in __init__(self, parent_mapping, parent_view, subset_idx)
    244         self.subset_idx = subset_idx
    245         self._axis = parent_mapping._axis
--> 246         self.dim_names = parent_mapping.dim_names[subset_idx]
    247 
    248 

~/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py in __getitem__(self, key)
   4305             key = np.asarray(key, dtype=bool)
   4306 
-> 4307         result = getitem(key)
   4308         if not is_scalar(result):
   4309             if np.ndim(result) > 1:

IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by WeilerP** [comment]
Thanks @sidrahmaryam. I presume you are using `scv.tl. score_genes_cell_cycle(adata)`? Could you please provide the output of

```python
scv.utils.get_phase_marker_genes(adata)
```

Might be that your AnnData does not contain any G2M phase marker genes as defined [here](https://github.com/theislab/scvelo/blob/1659cc8e00a45fcf87cd80a7013aae5531744613/scvelo/tools/score_genes_cell_cycle.py#L15).

**Comment by sidrahmaryam** [comment]
yes I used `scv.tl.score_genes_cell_cycle(adata)` for the above issue.

For `scv.utils.get_phase_marker_genes(adata)` the output is as:

(array([], dtype=float64),
 array(['Birc5', 'Top2a', 'Cenpf', 'Ckap2', 'Hjurp', 'Cenpa'], dtype='<U5'))

**Comment by WeilerP** [comment]
Okay, so the warning message is thrown because non of your genes are part of the S phase marker genes as defined [here](https://github.com/theislab/scvelo/blob/1659cc8e00a45fcf87cd80a7013aae5531744613/scvelo/tools/score_genes_cell_cycle.py#L8).
Regarding the actual error, you'll have to open an issue in [Scanpy](https://github.com/theislab/scanpy) since the error is originating there when calling

```python
score_genes(adata, gene_list=['Birc5', 'Top2a', 'Cenpf', 'Ckap2', 'Hjurp', 'Cenpa'], score_name="G2M_score", **kwargs)
```
