### ISSUE TITLE
scv.pl.proportions show equal proportions for clusters

### ISSUE THREAD

**Issue by jinyoung5484** [theislab/scvelo#506]
Hello, 

I am trying to figure out the proportions of spliced and unspliced for each cluster, but when I run proportions code on anndata object, the figure shows that spliced and unspliced proportions of all clusters are equal. Are there any suggestions that I can fix or components I need to revisit? 

Thank you.

![proportion_error](https://user-images.githubusercontent.com/63210104/123133334-9db5a780-d41d-11eb-9b40-4a3deae9dd60.PNG)

...

 
scv.pl.proportions(sdata_transpose, groupby='leiden')
or
scv.pl.proportions(sdata_transpose, groupby='louvain')

**Comment by WeilerP** [comment]
@jinyoung5484, would you please provide the package versions you are using?

On a general: Please do **not** change the GitHub template if not absolutely necessary and provide all required (and applicable) info! This speeds up the debugging of these issues.

**Comment by WeilerP** [comment]
Just ran the notebook [here](https://scvelo.readthedocs.io/VelocityBasics/) using the latest developer version of `scvelo` and everything worked fine. Does this produce the expected output for you?

**Comment by jinyoung5484** [comment]
@WeilerP, I was able to solve this, it is working perfectly fine.

Thank you!

**Comment by WeilerP** [comment]
@jinyoung5484 please open a discussion regarding your question about `scv.pl.velocity`.

**Comment by JenniferWUSTL** [comment]
@jinyoung5484 What steps did you follow to fix the equal proportions in your dataset? 

Thanks!
