### ISSUE TITLE
TypeError with tl.rank_velocity_genes

### ISSUE THREAD

**Issue by plath997** [theislab/scvelo#52]
Hello, I am trying to use `scv.tl.rank_velocity_genes(adata, match_with='clusters')` but I keep encountering this Error: `TypeError: unsupported operand type(s) for +: 'int' and 'str'` The full Traceback is:
`File "<stdin>", line 1, in <module>`

  `File "/data1/lan/miniconda3/lib/python3.6/site-packages/scvelo/tools/rank_velocity_genes.py", line 151, in rank_velocity_genes
    velocity_clusters(adata, vkey=vkey, match_with=match_with, resolution=resolution)`

  `File "/data1/lan/miniconda3/lib/python3.6/site-packages/scvelo/tools/rank_velocity_genes.py", line 101, in velocity_clusters
    vc = vc.cat.rename_categories({cat: new_cat + ' ' + cat})`

`TypeError: unsupported operand type(s) for +: 'int' and 'str'`

**Comment by VolkerBergen** [comment]
Your clusters are of type 'int', as you have not annotated them yet. In that case you don't need `match_with='clusters'`. 

However, your use case is now fixed in https://github.com/theislab/scvelo/commit/74978ddef21b87717760a2e005658db0d36232d1

**Comment by plath997** [comment]
Thank you!
