### ISSUE TITLE
The heatmap draw error

### ISSUE THREAD

**Issue by honghh2018** [theislab/scvelo#542]
Hi @All,
When the step running on below step, it showing below error:
top_genes = adata.var['highly_variable'].sort_values(ascending=False).index[:300] ###
scv.pl.heatmap(adata, var_names=top_genes, sortby='velocity_pseudotime', col_color='louvain', n_convolve=100)
Error:
AssertionError: Don’t call _normalize_index with non-categorical/string names

scv.__version__
'0.2.3'
How to fix this issue?

**Comment by WeilerP** [comment]
@honghh2018, could you please provide the full stack trace? Also, please provide the output of `scv.logging.print_versions()`.

**Comment by honghh2018** [comment]
Hi,
The detail:
AssertionError                            Traceback (most recent call last)
<ipython-input-175-6624a5be6628> in <module>
      1 top_genes = adata.var['highly_variable'].sort_values(ascending=False).index[:300] ###挑选var中的改变基因
----> 2 scv.pl.heatmap(adata, var_names=top_genes, sortby='velocity_pseudotime', col_color='louvain', n_convolve=100)

~/miniconda3/envs/scvelo/lib/python3.8/site-packages/scvelo/plotting/heatmap.py in heatmap(adata, var_names, sortby, layer, color_map, col_color, palette, n_convolve, standard_scale, sort, colorbar, col_cluster, row_cluster, figsize, font_scale, show, save, **kwargs)
     86 
     87     X = (
---> 88         adata[:, var_names].layers[xkey]
     89         if xkey in adata.layers.keys()
     90         else adata[:, var_names].X

~/miniconda3/envs/scvelo/lib/python3.8/site-packages/anndata/_core/anndata.py in __getitem__(self, index)
   1085     def __getitem__(self, index: Index) -> "AnnData":
   1086         """Returns a sliced view of the object."""
-> 1087         oidx, vidx = self._normalize_indices(index)
   1088         return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
   1089 

~/miniconda3/envs/scvelo/lib/python3.8/site-packages/anndata/_core/anndata.py in _normalize_indices(self, index)
   1066 
   1067     def _normalize_indices(self, index: Optional[Index]) -> Tuple[slice, slice]:
-> 1068         return _normalize_indices(index, self.obs_names, self.var_names)
   1069 
   1070     # TODO: this is not quite complete...

~/miniconda3/envs/scvelo/lib/python3.8/site-packages/anndata/_core/index.py in _normalize_indices(index, names0, names1)
     32             index = index[0].values, index[1]
     33     ax0, ax1 = unpack_index(index)
---> 34     ax0 = _normalize_index(ax0, names0)
     35     ax1 = _normalize_index(ax1, names1)
     36     return ax0, ax1

~/miniconda3/envs/scvelo/lib/python3.8/site-packages/anndata/_core/index.py in _normalize_index(indexer, index)
     50 ) -> Union[slice, int, np.ndarray]:  # ndarray of int
     51     if not isinstance(index, pd.RangeIndex):
---> 52         assert (
     53             index.dtype != float and index.dtype != int
     54         ), "Don’t call _normalize_index with non-categorical/string names"

scv.logging.print_versions()
scvelo==0.2.3  scanpy==1.8.1  anndata==0.7.5  loompy==3.0.6  numpy==1.20.1  scipy==1.6.1  matplotlib==3.3.4  sklearn==0.24.1  pandas==1.2.2

**Comment by WeilerP** [comment]
@honghh2018, seems like an issue with `anndata`. @ivirshup, any idea what's causing the problem and how to fix it?

**Comment by ivirshup** [comment]
I recall seeing this error pop up in the past. I can look at it a bit, but first @honghh2018,  could you update your version of anndata to the latest release and see if the error still occurs?

**Comment by honghh2018** [comment]
Hi @ivirshup  and all,
     The anndata version that i work for was 0.7.5, i am going to upgrade the anndata and try it again.
 If without a  hitch, It was feedback soon.

**Comment by honghh2018** [comment]
Hi guy,
     As you said, it surely was the version of anndata, when i upgrade the anndata(v0.7.5) into 0.7.6, the error was drop,
     and the result showing below:
![image](https://user-images.githubusercontent.com/41668708/126631554-e2f4f907-ecc8-4122-bf76-30a9daf7d445.png)

Thanks again.
Best,
