### ISSUE TITLE
Discordance between arrows in different velocity embeddings.

### ISSUE THREAD

**Issue by romanhaa** [theislab/scvelo#55]
I started experimenting with scVelo and got some interesting results but also noticed some discordance between the different velocity embeddings.

Result of `scv.pl.velocity_embedding`:
![velocity_embedding](https://user-images.githubusercontent.com/18103560/55715591-5639d100-59f5-11e9-837e-7d66d07e462b.png)

Result of `scv.pl.velocity_embedding_grid`:
![velocity_embedding_grid](https://user-images.githubusercontent.com/18103560/55715646-77022680-59f5-11e9-8334-f4810260c889.png)

Result of `scv.pl.velocity_embedding_stream`:
![velocity_embedding_stream](https://user-images.githubusercontent.com/18103560/55715665-81bcbb80-59f5-11e9-8996-a1fae361939d.png)

Out of those 3 the grid representation seems a little off, inverting many of the thick arrows in the green and blue clusters.

Additionally, the arrows in the PAGA plot don't seem to correspond very well either:
![paga_compare](https://user-images.githubusercontent.com/18103560/55715795-c21c3980-59f5-11e9-93ab-7844b260f23b.png)

```python
sc.pl.paga_compare(
  adata, basis = "umap", threshold = .15, arrowsize = 10,
  edge_width_scale = .5, transitions = "transitions_confidence",
  dashed_edges = "connectivities"
)
```

Did I misunderstand the output of these representations?

**Comment by VolkerBergen** [comment]
Hi Roman,

`velocity_embedding` and `stream` appear to be in concordance, while `grid` and PAGA are very off, which is indeed not to be expected. Have you run any processing steps in between those plots?

`grid` simply summarizes the single velocities, which is clearly not true from looking at your plot.

**Comment by romanhaa** [comment]
No I haven't done any processing, the plots were all produced one after the other.

**Comment by VolkerBergen** [comment]
Something definitely went wrong in there.. grid and PAGA are pretty much the opposite direction as if the sign has been changed along the way..

Would you rerun `tl.velocity_embedding(adata)` and check the plots again? What's the type of embedding in here?

**Comment by romanhaa** [comment]
The embedding is a UMAP. That's what you meant, right?

I repeated the following steps:

```python
scv.tl.velocity_embedding(adata, basis = "umap")

scv.pl.velocity_embedding(adata, basis = "umap", color = "leiden")
scv.pl.velocity_embedding_grid(adata, basis = "umap", color = "leiden")
scv.pl.velocity_embedding_stream(adata, basis = "umap", color = "leiden")
```

The plots were the same as before so I also re-ran the steps before:

```python
scv.tl.velocity(adata, mode = "stochastic")
scv.tl.velocity_graph(adata)

scv.tl.velocity_embedding(adata, basis = "umap")

scv.pl.velocity_embedding(adata, basis = "umap", color = "leiden")
scv.pl.velocity_embedding_grid(adata, basis = "umap", color = "leiden")
scv.pl.velocity_embedding_stream(adata, basis = "umap", color = "leiden")
```

Still the grid plot shows the opposite arrows.

All the pre-processing I did was prior to those steps (following the steps described here: <https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html>). However, when I follow the minimal scVelo tutorial (as posted here: <https://github.com/theislab/scvelo>) with the same input data the plots are coherent.

**Comment by VolkerBergen** [comment]
If I understand correctly, the discordance only arises when running scanpy's preprocessing steps without running scvelo's pp steps.

It'd be important to normalize the spliced/unspliced count data, which is not done within the scanpy pp pipeline. That would be running `scv.pp.filter_and_normalize()` after all your pp steps, which then only touches your spliced/unspliced counts and leaves `adata.X` as is when already processed.

**Comment by romanhaa** [comment]
I confirm that running `scv.pp.filter_and_normalize()` solved the problem. Thank you for the prompt support!

Since we are already in touch I have a follow-up question regarding the arrows in the PAGA plot (first post): The arrows represent the data in `transitions_confidence` while the dashed lines (or rather their thickness) represent the data in `connectivities`. In the PAGA plot of my first post you see that cluster 5 (brown) and 4 (purple) are not connected by an arrow but instead by a relatively thick dashed line (which should indicate a connection between them, right?). When looking at the stream plots of the velocity embedding it makes sense because the arrows are pointing away from the intersection between those clusters. Would you trust the velocity result over the PAGA?

**Comment by VolkerBergen** [comment]
Great! Clusters 4 and 5 are transcriptomically similar, thus have a high connectivity. The velocities indicate that there is no flow between those clusters. So, trusting the neighbor graph and the velocities, we find them to be connected, but without any directional flows going from one cluster to another. 

You'd of course have to check if that makes sense biologically. That could be driven biologically as well as technically, e.g. due to batch effects, as two clusters might be mistakenly similar, while velocities enables us to disentangle them.

**Comment by romanhaa** [comment]
Ok, that makes sense. I'll close this thread then, no further questions for now :)

Thanks again and great work! I like the `dpi` option for plotting. Would be useful also in the `scanpy` plot APIs.
