### ISSUE TITLE
The pseudotime direction showing reverse

### ISSUE THREAD

**Issue by honghh2018** [theislab/scvelo#563]
Hi @All,
    Like most, The sperm development direction in contrary with common sense. like below picture.
![image](https://user-images.githubusercontent.com/41668708/127428623-d457afe7-2e6f-4829-a63e-a9f463b383b7.png)
![image](https://user-images.githubusercontent.com/41668708/127429399-0c7d39cf-08c7-4b9a-b047-73a148c36ecf.png)

    According  to the previous research the development show be like below:
    
![image](https://user-images.githubusercontent.com/41668708/127428828-a0dbd66e-4109-4dc0-940d-f8b87432a8cb.png)
 Had any advices for this?
Best,
Hanhuihong

**Comment by WeilerP** [comment]
@honghh2018 with the limited of information given, I cannot offer any advice. Also, this does not seem to be code base related so it's more appropriate to open a discussion for this.
Please have a look at e.g. #216 and #462 and open a discussion.
