### ISSUE TITLE
The ratio spliced and unspliced ratio showing weird

### ISSUE THREAD

**Issue by honghh2018** [theislab/scvelo#575]
Hi @all，
   It was largely confused that why the ratio number can beyond 100 percentage reach to 1604%.
   The plot showing below:
![image](https://user-images.githubusercontent.com/41668708/127613064-00d88e59-13d1-4dd5-89a5-339bb8f1b3a3.png)
   What happen to this issue?

   scv.logging.print_version()
  Running scvelo 0.2.3 (python 3.8.8) on 2021-07-30 14:57.
Best,
Hanhuihong

**Comment by WeilerP** [comment]
@honghh2018, this is weird, indeed, and should not happen. Please update your comment with all required info from the issue template, i.e. the code snippet used to generate the output as well as the output of `scv.logging.print_versions()`.

**Comment by honghh2018** [comment]
The logging:
scvelo==0.2.3  scanpy==1.8.1  anndata==0.7.6  loompy==3.0.6  numpy==1.20.1  scipy==1.6.1  matplotlib==3.3.4  sklearn==0.24.1  pandas==1.2.2 
The code was just one line: 
scv.pl.proportions(adata,groupby="anno")

**Comment by WeilerP** [comment]
@honghh2018, this is the very first step of your analysis pipeline, i.e. `adata` still only contains integer count matrices?

**Comment by honghh2018** [comment]
The adata was converted from seurat object that had already preprocessed. not the first step.

**Comment by WeilerP** [comment]
> The adata was converted from seurat object that had already preprocessed. not the first step.

@honghh2018, I guess this is the problem. I assume you do not have columns `initial_size_unspliced` and `initial_size_spliced` in your `adata.obs` s.t. there is probably a division by a total reference count smaller than 1. This leads to values larger than 100%.

**Comment by lcymcdnld** [comment]
@WeilerP How can we check for/create the columns initial_size_unspliced and initial_size_spliced in adata.obs?

**Comment by phoebee-h** [comment]
@lcymcdnld 

Hi, I am not from the development team. I happened to see this issue. You can try this. 
```
spliced_count = scv.core.get_initial_size(adata)
adata.obs['initial_size_spliced'] = spliced_count
unspliced_count = scv.core.get_initial_size(adata, layer = "unspliced")
adata.obs['initial_size_unspliced'] = unspliced_count
```

They should be the same as what had been converted from Seurat object.

![image](https://user-images.githubusercontent.com/28743573/147219003-e16782c9-e193-4d8b-acdb-7c319491b476.png)



Best regards,
Phoebe.
