### ISSUE TITLE
Loosing transcripts

### ISSUE THREAD

**Issue by kt6k** [theislab/scvelo#59]
Hi. I am new to RNA velocity analysis, and this may already have been discussed elsewhere...

It appears that I am loosing a bunch of genes/transcripts during the Velocyto analysis, and I am trying to figure out what is going on. After running Velocyto, there are approximately 5000 final filtered transcripts (presumably ones used for the vector calculation). However, several genes/transcripts of interest that should be highly expressed in most cells (seen using software like Seurat) are not listed in the final filtered genes. Thus, I am suspecting that many genes/transcripts are, for some reason, lost during Velocyto calculation.

Does Velocyto filter out genes that are not differentially expressed (namely, genes/transcripts that are not useful to plot vector)?

My cells are captured using Fluidigm.

Very much appreciated.

**Comment by VolkerBergen** [comment]
Do I understand correctly that from velocyto you used the CLI API to generate your loom file, which then only retains a subset of your genes. (I.e. up to here you haven't done any preprocessing on the AnnData/Loom object yet?). 

Are you using the -c flag as mentioned [here](https://github.com/velocyto-team/velocyto.py/issues/101).

**Comment by VolkerBergen** [comment]
Please follow these [guidelines](http://velocyto.org/velocyto.py/) for generating the loom file. If anything is unclear, feel free to reopen this issue.
