### ISSUE TITLE
adding the scvelo features to an other matrix

### ISSUE THREAD

**Issue by hawaiiki** [theislab/scvelo#6]
Hi,

Thank you very much for making this software, its great!
My question might seem easy but I am still new at this. I have run my data in two ways, the first one using scanpy with mnnpy for batch effect correction which I called adata, and a second time using scvelo from loomfiles, which I called bdata. My question is how can I add the bdata features onto the adata matrix or vice versa ( I don't know what it is best) so that when I run the scv.pl.velocity_embedding_grid cmd it runs on the umap (or tsne) generated from adata?

![screen shot 2018-08-28 at 13 14 10](https://user-images.githubusercontent.com/42487820/44700497-4c95d580-aac4-11e8-98bf-d869f57abe37.png)

![screen shot 2018-08-28 at 13 13 45](https://user-images.githubusercontent.com/42487820/44700488-3f78e680-aac4-11e8-90af-ef78377ac396.png)

**Comment by hawaiiki** [comment]
Maybe these information will help as well. 

![screen shot 2018-08-28 at 17 29 13](https://user-images.githubusercontent.com/42487820/44710861-0f433f00-aae8-11e8-8cee-f2ba261729ed.png)

![screen shot 2018-08-28 at 17 29 35](https://user-images.githubusercontent.com/42487820/44710905-297d1d00-aae8-11e8-89c5-22b7ac7c217e.png)


Many thanks!

**Comment by VolkerBergen** [comment]
Thanks, hawaiiki!

that would be most convenient before applying gene filtering. As long the IDs of obs and vars are the same in `adata` and `bdata`, you can just merge the layers into adata simply via
`adata.layers['spliced'] = bdata.layers['spliced']`.

Hence, I'd just merge them directly after reading (before any preprocessing). You would only need the spliced and unspliced count matrices. Then run velocity analysis on `adata`. You can do that without gene filtering if you want to keep them. Only normalization of the count matrices is crucial to get correct velocity estimates.

**Comment by hawaiiki** [comment]
Great, it worked. Thanks a lot!
