### ISSUE TITLE
error when running  exemplary DentateGyrus.ipynb

### ISSUE THREAD

**Issue by yuxuth** [theislab/scvelo#62]
Hi, I am try running DentateGyrus.ipynb. However, get stuck on `scv.tl.velocity_graph(adata)` 
any suggestions ?

All previous cells work well.

```python
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))
%matplotlib inline

import scvelo as scv
scv.logging.print_version()
```
    Running scvelo 0.1.17.dev4+95beed0 (python 3.6.8) on 2019-05-23 15:23.

```python
scv.settings.set_figure_params('scvelo')
```
```python
adata = scv.read("data/DentateGyrus/10X43_1.loom", sparse=True, cache=True,
                 backup_url="http://pklab.med.harvard.edu/velocyto/DG1/10X43_1.loom")

```
```python
scv.utils.show_proportions(adata)
scv.utils.cleanup(adata, clean='all')

adata
```

    Abundance of ['spliced', 'unspliced', 'ambiguous']: [0.68 0.08 0.24]

    AnnData object with n_obs × n_vars = 3396 × 25919 
        layers: 'spliced', 'unspliced'

```python
scv.pp.filter_and_normalize(adata, min_counts=20, min_counts_u=10, n_top_genes=3000)
```

    Filtered out 13864 genes that are detected in less than 20 counts (spliced).
    Filtered out 6520 genes that are detected in less than 10 counts (unspliced).
    Normalized count data: X, spliced, unspliced.
    Logarithmized X.

```python
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
```

    computing neighbors
        finished (0:00:07.31) --> added to `.uns['neighbors']`
        'distances', weighted adjacency matrix
        'connectivities', weighted adjacency matrix
    computing moments based on connectivities
        finished (0:00:00.63) --> added 
        'Ms' and 'Mu', moments of spliced/unspliced abundances (adata.layers)

```
scv.tl.velocity(adata)
```

    computing velocities
        finished (0:00:00.29) --> added 
        'velocity', velocity vectors for each individual cell (adata.layers)

```python
scv.tl.velocity_graph(adata)
```

    ---------------------------------------------------------------------------
    
    ValueError                                Traceback (most recent call last)
    
    <ipython-input-8-699687a77a69> in <module>
    ----> 1 scv.tl.velocity_graph(adata)

    /work/06032/tg853315/stampede2/software/miniconda3/lib/python3.6/site-packages/scvelo/tools/velocity_graph.py in velocity_graph(data, vkey, xkey, tkey, basis, n_neighbors, n_recurse_neighbors, random_neighbors_at_max, sqrt_transform, approx, copy)
        153     vgraph = VelocityGraph(adata, vkey=vkey, xkey=xkey, tkey=tkey, basis=basis, n_neighbors=n_neighbors, approx=approx,
        154                            n_recurse_neighbors=n_recurse_neighbors, random_neighbors_at_max=random_neighbors_at_max,
    --> 155                            sqrt_transform=sqrt_transform, report=True)
        156 
        157     logg.info('computing velocity graph', r=True)

    /work/06032/tg853315/stampede2/software/miniconda3/lib/python3.6/site-packages/scvelo/tools/velocity_graph.py in __init__(self, adata, vkey, xkey, tkey, basis, n_neighbors, sqrt_transform, n_recurse_neighbors, random_neighbors_at_max, approx, report)
         54         if 'neighbors' not in adata.uns.keys(): neighbors(adata)
         55         if n_neighbors is None or n_neighbors < adata.uns['neighbors']['params']['n_neighbors']:
    ---> 56             self.indices = get_indices(dist=adata.uns['neighbors']['distances'], n_neighbors=n_neighbors)[0]
         57         else:
         58             if basis is None: basis = [key for key in ['X_pca', 'X_tsne', 'X_umap'] if key in adata.obsm.keys()][-1]

    /work/06032/tg853315/stampede2/software/miniconda3/lib/python3.6/site-packages/scvelo/tools/utils.py in get_indices(dist, n_neighbors)
         92         dat[rm_idx] = 0
         93     D.eliminate_zeros()
    ---> 94     indices = D.indices.reshape((-1, n_neighbors))
         95     return indices, D
         96 

    ValueError: cannot reshape array of size 0 into shape (0)

**Comment by yuxuth** [comment]
I install the scvelo via `pip install git+https://github.com/theislab/scvelo`

**Comment by VolkerBergen** [comment]
I was not able to reproduce the error. Would you please print your neighbors

```
dist = adata.uns['neighbors']['distances']
n_neighs = (dist > 0).sum(1).A1
print(dist, n_neighs)
```

Further, you check the dependencies versions with `scv.logging.print_versions()`.

**Comment by yuxuth** [comment]
Thank you so much for your help! The information is as following.
 
`scv.logging.print_versions()`
> scvelo==0.1.17.dev4+95beed0  scanpy==1.3.8  anndata==0.6.19  loompy==2.0.17  numpy==1.16.3  scipy==1.2.1  matplotlib==3.0.2  sklearn==0.21.1  pandas==0.24.2

```
dist = adata.uns['neighbors']['distances']
n_neighs = (dist > 0).sum(1).A1
print(dist, n_neighs)
```
```
(0, 55)	2.766350269317627
  (0, 61)	2.9171249866485596
  (0, 103)	2.897191286087036
  (0, 314)	2.85616397857666
  (0, 323)	2.8995094299316406
  (0, 563)	2.747565746307373
  (0, 620)	2.8693785667419434
  (0, 722)	2.934455156326294
  (0, 1127)	2.7233963012695312
  (0, 1154)	2.6639938354492188
  (0, 1214)	2.952554225921631
  (0, 1455)	2.741056203842163
  (0, 1526)	2.6519339084625244
  (0, 1536)	2.741546869277954
  (0, 2052)	2.6210250854492188
  (0, 2223)	2.8848979473114014
  (0, 2527)	2.947450876235962
  (0, 2617)	2.9388716220855713
  (0, 2819)	2.838306188583374
  (0, 2824)	2.6633551120758057
  (0, 2849)	2.721888542175293
  (0, 2886)	2.5955352783203125
  (0, 2993)	2.827843427658081
  (0, 3019)	2.870811939239502
  (0, 3066)	2.404082775115967
  :	:
  (1114, 768)	3.480347156524658
  (1114, 1021)	3.4749486446380615
  (1114, 1161)	3.009150743484497
  (1114, 1202)	3.450887680053711
  (1114, 1206)	3.7488584518432617
  (1114, 1273)	3.627166271209717
  (1114, 1357)	3.3485937118530273
  (1114, 1400)	3.788331985473633
  (1114, 1565)	3.518092155456543
  (1114, 1672)	3.2474918365478516
  (1114, 1919)	3.6642651557922363
  (1114, 1985)	3.5745768547058105
  (1114, 2069)	3.849222183227539
  (1114, 2092)	3.7506277561187744
  (1114, 2139)	3.6346585750579834
  (1114, 2268)	3.6384048461914062
  (1114, 2299)	3.880396604537964
  (1114, 2321)	2.7973361015319824
  (1114, 2392)	3.6423850059509277
  (1114, 2542)	3.852964401245117
  (1114, 2808)	3.8910140991210938
  (1114, 2813)	3.52219295501709
  (1114, 2977)	3.5096569061279297
  (1114, 3167)	3.7945544719696045
  (1114, 3395)	3.8473329544067383 [29 29 29 ...  0  0  0]
```

**Comment by VolkerBergen** [comment]
Hmm.. For some reason, the neighbor graph misses all the neighbors for cells 1115 - 3395. 

Could you try again with the updated version (from source)?

If it still throws an error, it'd be interesting to see whether you get the same error with the in-built dataset `adata = scv.datasets.dentategyrus()`

**Comment by sbooeshaghi** [comment]
I am also getting this error on a different dataset. Here are the dependencies:

`scv.logging.print_versions()`
>scvelo==0.1.17.dev6+39a3ff5  scanpy==1.4.1  anndata==0.6.19  loompy==2.0.17  numpy==1.16.3  scipy==1.2.1  matplotlib==3.0.3  sklearn==0.20.3  pandas==0.24.2

Here are the neighbors:
```
dist = adata.uns['neighbors']['distances']
n_neighs = (dist > 0).sum(1).A1
print(dist, n_neighs)
```

```
  (0, 162)	1.99241821522695
  (0, 475)	2.018094613247957
  (0, 602)	2.3061423790067948
  (0, 833)	2.1095917777346105
  (0, 881)	2.2893890533410213
  (0, 1531)	2.317859310357659
  (0, 1587)	2.3466554930301813
  (0, 2165)	2.029874447678866
  (0, 2510)	2.1658920212052086
  (0, 2791)	2.336415481687932
  (0, 2818)	2.237531504578858
  (0, 2844)	2.306094251496077
  (0, 2885)	2.097154134986734
  (0, 3863)	2.1798154135903083
  (0, 4424)	1.8755556864364786
  (0, 4690)	1.9770977849431952
  (0, 4749)	2.2551045227973723
  (0, 5033)	2.3401563288915264
  (0, 5053)	2.2227109487971957
  (0, 6286)	2.2320324235673192
  (0, 6559)	2.369515520828979
  (0, 76811)	1.9151332420782716
  (0, 78534)	2.057325492145534
  (0, 80480)	2.307139319612072
  (0, 82935)	2.344900439119506
  :	:
  (112298, 20458)	5.139965406667381
  (112298, 20703)	6.340432676296969
  (112298, 22555)	6.252147878867913
  (112298, 22742)	5.15023680524036
  (112298, 23267)	5.978051281497999
  (112298, 25642)	6.373439380583437
  (112298, 37201)	5.776583005284154
  (112298, 41488)	5.858651107814942
  (112298, 44183)	6.662332579100779
  (112298, 61559)	6.629357746641156
  (112298, 101805)	6.346828912425935
  (112298, 102016)	5.919357600149979
  (112298, 102226)	6.28563133030635
  (112298, 102260)	6.3892473302616795
  (112298, 102565)	5.434222998150165
  (112298, 104692)	6.147624797996394
  (112298, 105087)	4.240357046046699
  (112298, 105707)	6.218681149252846
  (112298, 105893)	5.517506001376452
  (112298, 106601)	6.273584982685616
  (112298, 109727)	5.344008395442505
  (112298, 109999)	5.524193550868478
  (112298, 110560)	6.702585354207674
  (112298, 110770)	5.85583494496436
  (112298, 111516)	5.759890969763501 [29 29 29 ... 29 29 29]
```
Here is my adata:
```
AnnData object with n_obs × n_vars = 112299 × 5000 
    obs: 'sample', 'time', 'barcode', 'umap_cluster', 'umap_coord1', 'umap_coord2', 'umap_coord3', 'used_for_pseudotime', 'umap2_CellType', 'n_genes', 'initial_size_spliced', 'initial_size_unspliced', 'initial_size', 'n_counts'
    var: 'n_cells', 'means', 'dispersions', 'dispersions_norm', 'velocity_gamma', 'velocity_r2', 'velocity_genes'
    uns: 'neighbors'
    obsm: 'X_pca'
    layers: 'spliced', 'unspliced', 'Ms', 'Mu', 'velocity'
```

My intuition is that this may somehow be related to https://github.com/theislab/scvelo/issues/43. I tried running `scanpy.pp.neighbors(adata, n_neighbors=50, n_pcs=30)` in place of `scvelo.pp.moments(adata, n_neighbors=50, n_pcs=30)` but I still got the same error.

Thoughts?

**Comment by VolkerBergen** [comment]
I've done some editing on the neighbor graph, enabling it to handle some special cases. Could you please try again with the latest version from source?

If it still raises an error, it would be very helpful to know whether you also get the error when using sklearn's nearest neighbor computation, i.e.
`scv.pp.moments(adata, method='sklearn')`

**Comment by sbooeshaghi** [comment]
I installed scvelo from source 
>scvelo==0.1.17.dev10+38b9e3f  scanpy==1.4.1  anndata==0.6.19  loompy==2.0.17  numpy==1.16.3  scipy==1.2.1  matplotlib==3.0.3  sklearn==0.20.3  pandas==0.24.2 

and still got the same error ( using `scv.pp.moments(adata, n_neighbors=50, n_pcs=30`) ) when running `scv.tl.velocity_graph(adata)`.

Separately I ran `scv.pp.moments(adata, method='sklearn')` and still got the same error. 

Here are the results from 
```
dist = adata.uns['neighbors']['distances']
n_neighs = (dist > 0).sum(1).A1
print(dist, n_neighs)
```

```
  (0, 162)	1.9980447675114925
  (0, 475)	2.0257282826977843
  (0, 602)	2.2980064166119116
  (0, 833)	2.106290353928917
  (0, 881)	2.2962415941820473
  (0, 1531)	2.3047868463250536
  (0, 1587)	2.346378738520425
  (0, 2165)	2.0155806799073277
  (0, 2510)	2.1541113923292383
  (0, 2791)	2.344548629208393
  (0, 2818)	2.236240478945379
  (0, 2844)	2.318911833938334
  (0, 2885)	2.098959689202987
  (0, 3863)	2.18440899041591
  (0, 4424)	1.8785969300269143
  (0, 4690)	1.9788148343006162
  (0, 4749)	2.2604305594854197
  (0, 5033)	2.3253032239737403
  (0, 5053)	2.2168200458136735
  (0, 6286)	2.2448392808425996
  (0, 6559)	2.363877804523717
  (0, 76819)	1.930451295720954
  (0, 78542)	2.0605659975926143
  (0, 80488)	2.303768257353386
  (0, 82943)	2.3205775717394443
  :	:
  (112306, 20458)	5.193539421617805
  (112306, 20703)	6.351169704699518
  (112306, 22555)	6.245084189824771
  (112306, 22742)	5.160163815668472
  (112306, 23267)	6.022640162414275
  (112306, 25642)	6.359183041699013
  (112306, 37201)	5.794244681501777
  (112306, 41488)	5.867207158150357
  (112306, 44183)	6.674955715362824
  (112306, 61567)	6.658520594289489
  (112306, 101813)	6.266132148346639
  (112306, 102024)	5.896260258689357
  (112306, 102234)	6.184278289536772
  (112306, 102268)	6.464887026572806
  (112306, 102573)	5.399945030574889
  (112306, 104700)	6.078946930233254
  (112306, 105095)	4.248031508886222
  (112306, 105715)	6.255937444092278
  (112306, 105901)	5.524765467782726
  (112306, 106609)	6.2742959820387485
  (112306, 109735)	5.293411089301313
  (112306, 110007)	5.538308487486002
  (112306, 110568)	6.6802674515958484
  (112306, 110778)	5.8039240172088435
  (112306, 111524)	5.783192623929299 [29 29 29 ... 29 29 29]
```

For reference I am using `Python 3.7.1` on 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
```

**Comment by sbooeshaghi** [comment]
I've been playing around with the order of operations and got an interesting result:

If I run the following commands in succession
```
scanpy.pp.neighbors(adata, n_pcs=50, n_neighbors=40)

scvelo.pp.filter_genes(adata, min_counts=3, min_counts_u=2)
scvelo.pp.normalize_per_cell(adata)
scvelo.pp.filter_genes_dispersion(adata, n_top_genes=5000)
scvelo.pp.log1p(adata)

scvelo.pp.moments(adata, n_pcs=50, n_neighbors=40)
scvelo.tl.velocity(adata)
scvelo.tl.velocity_graph(adata)
```

Then I did not get `ValueError: cannot reshape array of size 0 into shape (0)`.

But this is a strange to me since intuitively, to me, `neighbors` should be computed after normalization and filtering.. Therefore my question is are the results of the aforementioned list of commands interpretable in the context of RNA velocity?

**Comment by VolkerBergen** [comment]
`neighbors` should be computed on log-transformed normalized data (+ pca space).

Would you do me another favor and compute
```
dist = adata.uns['neighbors']['distances'] 
print((dist > 0).sum(1).A1.min())
print(scv.utils.get_indices(dist))
```

once with `scv.pp.neighbors(adata, method='sklearn')` and once with `scv.pp.neighbors(adata, method='umap')`

**Comment by sbooeshaghi** [comment]
Running `scv.pp.neighbors(adata, method='sklearn')` and 
```
dist = adata.uns['neighbors']['distances'] 
print((dist > 0).sum(1).A1.min())
print(scv.utils.get_indices(dist))
```
I get:
```
0
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-75facd85b1c8> in <module>
      1 dist = adata.uns['neighbors']['distances']
      2 print((dist > 0).sum(1).A1.min())
----> 3 print(scv.utils.get_indices(dist))

~/tools/miniconda/lib/python3.7/site-packages/scvelo/tools/utils.py in get_indices(dist, n_neighbors)
     95 
     96     D.data -= 1e-6
---> 97     indices = D.indices.reshape((-1, n_neighbors))
     98     return indices, D
     99 

ValueError: cannot reshape array of size 0 into shape (0)
```

Running `scv.pp.neighbors(adata, method='umap')` and 
```
dist = adata.uns['neighbors']['distances'] 
print((dist > 0).sum(1).A1.min())
print(scv.utils.get_indices(dist))
```
I get the exact same as above.

**Comment by VolkerBergen** [comment]
imho that can only be explained by correputed data or pca.

Can you recompute pca via `scv.pp.pca(adata)`, run again and inspect those cells for which no neighbors have been found, i.e. `(dist > 0).sum(1).A1 == 0`.

**Comment by yuxuth** [comment]
Thank you very much for your help. Sorry for the late reply. 

I reinstall through source. 
`scv.logging.print_versions()`
> scvelo==0.1.17.dev17+7eef7c0  scanpy==1.3.8  anndata==0.6.19  loompy==2.0.17  numpy==1.16.3  scipy==1.2.1  matplotlib==3.0.2  sklearn==0.21.1  pandas==0.24.2

and rerun the same code. Still got the same error message. 
`ValueError: cannot reshape array of size 0 into shape (0)`

However, when I chage the `scv.pp.moments(adata, n_neighbors=50, n_pcs=30)`
`scv.pp.moments(adata, n_neighbors=50, n_pcs=30,method='sklearn')`

The problem solved. 

The default method is 'umap', shall I keep 'sklearn' in the future? 

Thank you again for your help!

**Comment by yuxuth** [comment]
By the way. Even when I use`adata = scv.datasets.dentategyrus()`
the `scv.pp.moments(adata, n_neighbors=50, n_pcs=30)` still lead to same error when run `scv.tl.velocity_graph(adata)`  

> ValueError: cannot reshape array of size 0 into shape (0)

and the problem solved when specific the 'sklearn' method.
`scv.pp.moments(adata, n_neighbors=50, n_pcs=30,method='sklearn')`

Hope this information is helpful. 
`scv.logging.print_versions()`
> scvelo==0.1.17.dev17+7eef7c0  scanpy==1.3.8  anndata==0.6.19  loompy==2.0.17  numpy==1.16.3  scipy==1.2.1  matplotlib==3.0.2  sklearn==0.21.1  pandas==0.24.2  

I'm using Python 3.6.8.

Thank you!

**Comment by VolkerBergen** [comment]
I guess that's it: a umap neighbor graph breakage due to a bug in scikit-learn 0.21.1. See https://github.com/theislab/scanpy/issues/654. I'll exclude the buggy versions of scikit-learn in the requirements.

**Comment by yuxuth** [comment]
Thank you again for your help! I think we can close this issue.

**Comment by VolkerBergen** [comment]
Great. Just one more comment : it does not matter which method (hnsw, umap, sklearn) you use for neighbors/moments. They only differ in the runtime.

**Comment by VolkerBergen** [comment]
@sbooeshaghi solved for you as well?

**Comment by AshleyFrans** [comment]
I am running into the same Value Error as discussed above, very similar to all the issues @sbooeshaghi was running into when running `scv.t1.velocity_graph(adata)`. I have reinstalled scvelo from source, and do not have the updated sklearn, and when running `scv.pp.moments(adata)` I use `method = 'sklearn'`.

`import scanpy as sc
import scanpy.external as sce
import scvelo as scv
scv.logging.print_versions()`

<img width="961" alt="Screen Shot 2019-08-16 at 11 27 42 AM" src="https://user-images.githubusercontent.com/25848661/63189461-e5489c80-c018-11e9-8f94-92279d9de666.png">

Any recommendations on how to proceed?

**Comment by VolkerBergen** [comment]
This all traced back to sklearn issues. Try running with one of their latest releases 0.20.4 or 0.21.3. We will check on other buggy version and exclude them in the requirements.

**Comment by GBeattie** [comment]
@VolkerBergen Apologies for resurrecting this but I am getting an identical error, even with trying the suggestions above. Confusingly, my script works with a different dataset, so there may be an issue with the dataset itself. Any ideas on how to address this would be greatly appreciated!

```
scv.logging.print_versions()
scvelo==0.1.23  scanpy==1.4.4.post1  anndata==0.6.22.post1  loompy==3.0.6  numpy==1.17.3  scipy==1.3.1  matplotlib==3.1.1  sklearn==0.21.3  pandas==0.25.2  
```
The script:
```
## Read velocyto generated loom file
adata_aCT = scv.read('./aCT/possorted_genome_bam_9NXRO.loom', cache=True)

## Read in seurat generated loom file
adata_aCT_seu = scv.read('./aCT/wt_aCT_combined.loom')

## Merge velocyto and seurat looms and make variable names unique
adata_aCT = scv.utils.merge(adata_aCT, adata_aCT_seu)
adata_aCT.var_names_make_unique()

## Display basic info on adata_aCT
scv.utils.show_proportions(adata_aCT)
adata_aCT

## Filtering and normalisation/log transformation > PCA
scv.pp.filter_genes(adata_aCT, min_shared_counts=10)
scv.pp.normalize_per_cell(adata_aCT)
scv.pp.filter_genes_dispersion(adata_aCT, n_top_genes=3000)
scv.pp.log1p(adata_aCT)
scv.pp.filter_and_normalize(adata_aCT, min_shared_counts=10, n_top_genes=3000)
scv.pp.moments(adata_aCT, n_neighbors=50, n_pcs=30,method='sklearn')

## Calculate velocities
scv.tl.velocity(adata_aCT)
scv.tl.velocity_graph(adata_aCT)
```
The error:
```
scv.tl.velocity_graph(adata_aCT)
computing neighbors
    finished (0:00:10) --> added to `.uns['neighbors']`
    'distances', weighted adjacency matrix
    'connectivities', weighted adjacency matrix
Traceback (most recent call last):

  File "<ipython-input-20-432f9fd195f0>", line 1, in <module>
    scv.tl.velocity_graph(adata_aCT)

  File "/opt/miniconda3/lib/python3.7/site-packages/scvelo/tools/velocity_graph.py", line 170, in velocity_graph
    sqrt_transform=sqrt_transform, gene_subset=gene_subset, report=True)

  File "/opt/miniconda3/lib/python3.7/site-packages/scvelo/tools/velocity_graph.py", line 67, in __init__
    self.indices = get_indices(dist=adata.uns['neighbors']['distances'], n_neighbors=n_neighbors)[0]

  File "/opt/miniconda3/lib/python3.7/site-packages/scvelo/tools/utils.py", line 105, in get_indices
    indices = D.indices.reshape((-1, n_neighbors))

ValueError: cannot reshape array of size 0 into shape (0)
```

**Comment by VolkerBergen** [comment]
Looks like having a corrupted neighbor graph.. Try first recomputing neighbors via `scv.pp.neighbors(adata, n_neighbors=50)` before computing the velocity graph. 

If still buggy, check `print((adata.uns['neighbors']['distances']  > 0).sum(1).A1.min())`.

**Comment by GBeattie** [comment]
No luck adding pp.neighbors before the tl.velocity_graph step. The print function returns "0" (which I'm guessing is not a good sign).

```
print((adata_aCT.uns['neighbors']['distances'] > 0).sum(1).A1.min())
0
```
The input data seems sensible just looking at the proportions, but maybe there is a more informative metric. 

```
scv.utils.show_proportions(adata_aCT)
Abundance of ['spliced', 'unspliced', 'ambiguous']: [0.5  0.39 0.05]
```

**Comment by VolkerBergen** [comment]
That issue was just posted again here https://github.com/theislab/scvelo/issues/107
would be very helpful if you could also follow those steps explained.
