### ISSUE TITLE
Warning about unexpected neighbors graph

### ISSUE THREAD

**Issue by adamgayoso** [theislab/scvelo#625]
I suspect this issue is here:

https://github.com/theislab/scvelo/blob/1659cc8e00a45fcf87cd80a7013aae5531744613/scvelo/preprocessing/neighbors.py#L313-L325

Doesn't scanpy now store neighbors in `.obsp`? This occurs if using scanpy to compute neighbors.

**Comment by WeilerP** [comment]
Thanks @adamgayoso. I'll have a look at it ASAP!

**Comment by WeilerP** [comment]
@adamgayoso, which version of scanpy are you using? The latest, i.e. `scanpy=1.8.1`? Or are you working with `scanpy@master`?
Could you also please provide a minimal working example for which the error is thrown? I presume it is `sc.pp.neighbors()` and them some scVelo function checking the neighbors graph?

**Comment by WeilerP** [comment]
Update after briefly discussing this offline: The error is thrown after running the standard pipeline, e.g.

```python
scv.pp.filter_and_normalize(adata)
scv.pp.moments(adata)
scv.tl.velocity(adata)
scv.tl.velocity_graph(adata)
```

The problem comes from supposed duplicate cells, which aren't actual duplicates but only appear to be after filtering.

**Comment by WeilerP** [comment]
Closing this since the current warning already points towards potential issues when subsetting data. Will circle back to it once the corresponding code is being unit tested and refactored.
