### ISSUE TITLE
problem running the scv.pp.moments

### ISSUE THREAD

**Issue by terooatt** [theislab/scvelo#63]
Hi,

scvelo used to run fine before with scanpy version 1.3 at least. But now with the new update I am having the following issue. Appreciate your help.
from os import path
import numpy as np
import matplotlib.pyplot as pl
import scvelo as scv
import scanpy.api as sc

scv.pp.filter_and_normalize(adata1)
scv.pp.moments(adata1)
scv.tl.velocity(adata1, mode='stochastic')# Estimating the velocities for each individual cell
scv.tl.velocity_graph(adata1)
scv.tl.velocity_embedding(adata1, basis='tsne')
scv.tl.velocity_embedding(adata1, basis='umap')
scv.tl.velocity_embedding(adata1, basis='phate')
scv.tl.velocity_embedding(adata1, basis='diffmap')

Did not modify X as it looks preprocessed already.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-34-3cb338a879a6> in <module>
      7 scv.pp.filter_and_normalize(adata1)
      8 
----> 9 scv.pp.moments(adata1)
     10 scv.tl.velocity(adata1, mode='stochastic')# Estimating the velocities for each individual cell
     11 scv.tl.velocity_graph(adata1)

~/miniconda3/envs/scanpy/lib/python3.6/site-packages/scvelo/preprocessing/moments.py in moments(data, n_neighbors, n_pcs, mode, method, metric, use_rep, recurse_neighbors, renormalize, copy)
     41     if any([not_yet_normalized(adata.layers[layer]) for layer in {'spliced', 'unspliced'}]):
     42         normalize_per_cell(adata)
---> 43     if 'neighbors' not in adata.uns.keys() or neighbors_to_be_recomputed(adata, n_neighbors=n_neighbors):
     44         if use_rep is None: use_rep = 'X_pca'
     45         neighbors(adata, n_neighbors=n_neighbors, use_rep=use_rep, n_pcs=n_pcs, method=method, metric=metric)

~/miniconda3/envs/scanpy/lib/python3.6/site-packages/scvelo/preprocessing/neighbors.py in neighbors_to_be_recomputed(adata, n_neighbors)
    129 
    130 
--> 131 def neighbors_to_be_recomputed(adata, n_neighbors=None):
    132     # check if neighbors graph is disrupted
    133     n_neighs = (adata.uns['neighbors']['distances'] > 0).sum(1)

KeyError: 'distances'

**Comment by VolkerBergen** [comment]
Ok, for some reason you have `adata.uns['neighbors']` stored, while `distances` are missing in here. 

Does it run through if you recompute the neighbor graph before calling `moments`?
`scv.pp.neighbors(adata)`

**Comment by terooatt** [comment]
Thanks, that did it!
