### ISSUE TITLE
scv.datasets.pancreas()   OSError: Unable to open file (truncated file: eof = 7340032, sblock->base_addr = 0, stored_eof = 52477898)

### ISSUE THREAD

**Issue by shijianasdf** [theislab/scvelo#631]
After running scv.datasets.pancreas() in the linux server, I got the following error:
![image](https://user-images.githubusercontent.com/39074222/129331728-7de79339-c68b-4034-9468-e2e2d2b049e2.png)

then i run scv.datasets.pancreas() in MAC, I got the following error:
![image](https://user-images.githubusercontent.com/39074222/129332192-a2c1a64f-a97d-423c-b001-50543339bf59.png)

**Comment by WeilerP** [comment]
@shijianasdf, looks like a Scanpy/AnnData problem. Please open an issue there.

**Comment by zhangliyin666** [comment]
I met the same error when run adata = scv.datasets.pancreas(), have you solved it please?

**Comment by WeilerP** [comment]
@zhangliyin666, I cannot reproduce the error and, as mentioned above, the issue seems to be in Scanpy or anndata. You can manually download the file from `https://github.com/theislab/scvelo_notebooks/raw/master/data/Pancreas/endocrinogenesis_day15.h5ad` and save the file in `/data/Pancreas/endocrinogenesis_day15.h5ad` - `scv.datasets.pancreas()` will then read this file. Maybe something is going or went wrong when downloading the file.

**Comment by zhangliyin666** [comment]
> @zhangliyin666, I cannot reproduce the error and, as mentioned above, the issue seems to be in Scanpy or anndata. You can manually download the file from `https://github.com/theislab/scvelo_notebooks/raw/master/data/Pancreas/endocrinogenesis_day15.h5ad` and save the file in `/data/Pancreas/endocrinogenesis_day15.h5ad` - `scv.datasets.pancreas()` will then read this file. Maybe something is going or went wrong when downloading the file.

Sorry to reply late and hanks a lot for your help! I tried your advice and downloaded the file successfully!

**Comment by EVARen2022** [comment]
> @zhangliyin666, I cannot reproduce the error and, as mentioned above, the issue seems to be in Scanpy or anndata. You can manually download the file from `https://github.com/theislab/scvelo_notebooks/raw/master/data/Pancreas/endocrinogenesis_day15.h5ad` and save the file in `/data/Pancreas/endocrinogenesis_day15.h5ad` - `scv.datasets.pancreas()` will then read this file. Maybe something is going or went wrong when downloading the file.


Hello, may I ask if there is a link to the dataset  “dentategyrus”  ? I cannot load it  when I run  “adata = scv.datasets.dentategyrus()”

**Comment by EVARen2022** [comment]
> > @zhangliyin666, I cannot reproduce the error and, as mentioned above, the issue seems to be in Scanpy or anndata. You can manually download the file from `https://github.com/theislab/scvelo_notebooks/raw/master/data/Pancreas/endocrinogenesis_day15.h5ad` and save the file in `/data/Pancreas/endocrinogenesis_day15.h5ad` - `scv.datasets.pancreas()` will then read this file. Maybe something is going or went wrong when downloading the file.
> 
> Hello, may I ask if there is a link to the dataset “dentategyrus” ? I cannot load it when I run “adata = scv.datasets.dentategyrus()”

I found the link   https://github.com/WeilerP/scvelo_notebooks/tree/master/data/DentateGyrus

**Comment by dsfefgffd** [comment]
> @zhangliyin666, I cannot reproduce the error and, as mentioned above, the issue seems to be in Scanpy or anndata. You can manually download the file from `https://github.com/theislab/scvelo_notebooks/raw/master/data/Pancreas/endocrinogenesis_day15.h5ad` and save the file in `/data/Pancreas/endocrinogenesis_day15.h5ad` - `scv.datasets.pancreas()` will then read this file. Maybe something is going or went wrong when downloading the file.

Good solution
