### ISSUE TITLE
scv.pl.velocity_embedding_stream(adata, basis='umap'). KeyError: 'X_umap'

### ISSUE THREAD

**Issue by shijianasdf** [theislab/scvelo#634]
I run scv.pl.velocity_embedding_stream() like below
```python
scv.pl.velocity_embedding_stream(adata, basis='umap')
```
and i got the following error:
```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/biofly/opt/miniconda3/lib/python3.9/site-packages/scvelo/plotting/velocity_embedding_stream.py", line 111, in velocity_embedding_stream
    X_emb = np.array(obsm[f"X_{basis}"][:, comps]) if X is None else X[:, :2]
  File "/Users/biofly/opt/miniconda3/lib/python3.9/site-packages/anndata/_core/aligned_mapping.py", line 148, in __getitem__
    return self._data[key]
KeyError: 'X_umap'
```

#### Versions:

scvelo==0.2.3  scanpy==1.8.1  anndata==0.7.6  loompy==3.0.6  numpy==1.20.3  scipy==1.7.1  matplotlib==3.4.2  sklearn==0.24.2  pandas==1.3.1  
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
ERROR: XMLRPC request failed [code: -32500]
RuntimeError: PyPI's XMLRPC API is currently disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information.
>

**Comment by WeilerP** [comment]
@shijianasdf seems like you did not calculate the UMAP embedding beforehand. You need to run

```python
import scanpy as sc

sc.tl.umap(adata)
```

first. This will save the embedding as `adata.obsm['X_umap']`.

**Comment by shijianasdf** [comment]
> @shijianasdf seems like you did not calculate the UMAP embedding beforehand. You need to run
> 
> ```python
> import scanpy as sc
> 
> sc.tl.umap(adata)
> ```
> 
> first. This will save the embedding as `adata.obsm['X_umap']`.

Thank you for helping me solve my big problem
