### ISSUE TITLE
Velcity graph not computed due to neighbor graph (computed in scVelo) 

### ISSUE THREAD

**Issue by christoffermattssonlangseth** [theislab/scvelo#637]
The error arises when I'm to compute the velocity graph using` scv.tl.velocity_graph`. I have an [anndata object ](https://drive.google.com/file/d/19dIPNjWJi1FazKDuwcw2a44sTPzx2rcH/view?usp=sharing) that is created using [SIRV](https://github.com/tabdelaal/SIRV), integrating single cell sequencing data and in situ sequencing data. 

```python
s1_imputed = scv.read('fetal_brain_sample1_HybISS_imputed_V2_only_more_labels_normalized_210813.h5ad') # in link above

# scanpy
sc.pp.scale(s1_imputed)
sc.tl.pca(s1_imputed)
sc.pl.pca_variance_ratio(s1_imputed, n_pcs=50, log=True)
sc.pp.neighbors(s1_imputed, n_neighbors=30, n_pcs=30)
sc.tl.umap(s1_imputed)
sc.tl.leiden(s1_imputed)

# scVelo
scv.pp.moments(s1_imputed, n_pcs=30, n_neighbors=30)
scv.tl.velocity(s1_imputed)
scv.pp.neighbors(s1_imputed)
scv.tl.velocity_graph(s1_imputed)

```

<details>
<summary> Error </summary>

```python
WARNING: The neighbor graph has an unexpected format (e.g. computed outside scvelo) 
or is corrupted (e.g. due to subsetting). Consider recomputing with `pp.neighbors`.
computing moments based on connectivities
    finished (0:00:00) --> added 
    'Ms' and 'Mu', moments of un/spliced abundances (adata.layers)
computing velocities
    finished (0:00:00) --> added 
    'velocity', velocity vectors for each individual cell (adata.layers)
computing neighbors
    finished (0:00:03) --> added 
    'distances' and 'connectivities', weighted adjacency matrices (adata.obsp)
WARNING: The neighbor graph has an unexpected format (e.g. computed outside scvelo) 
or is corrupted (e.g. due to subsetting). Consider recomputing with `pp.neighbors`.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-193-bce1f660bdf8> in <module>
      2 scv.tl.velocity(s1_imputed)
      3 scv.pp.neighbors(s1_imputed)
----> 4 scv.tl.velocity_graph(s1_imputed)

~/.local/lib/python3.8/site-packages/scvelo/tools/velocity_graph.py in velocity_graph(data, vkey, xkey, tkey, basis, n_neighbors, n_recurse_neighbors, random_neighbors_at_max, sqrt_transform, variance_stabilization, gene_subset, compute_uncertainties, approx, mode_neighbors, copy)
    292         sqrt_transform = variance_stabilization
    293 
--> 294     vgraph = VelocityGraph(
    295         adata,
    296         vkey=vkey,

~/.local/lib/python3.8/site-packages/scvelo/tools/velocity_graph.py in __init__(self, adata, vkey, xkey, tkey, basis, n_neighbors, sqrt_transform, n_recurse_neighbors, random_neighbors_at_max, gene_subset, approx, report, compute_uncertainties, mode_neighbors)
    100             neighbors(adata)
    101         if np.min((get_neighs(adata, "distances") > 0).sum(1).A1) == 0:
--> 102             raise ValueError(
    103                 "Your neighbor graph seems to be corrupted. "
    104                 "Consider recomputing via pp.neighbors."

ValueError: Your neighbor graph seems to be corrupted. Consider recomputing via pp.neighbors.
```
</details>

#### Versions:

> scvelo==0.2.3  
scanpy==1.8.1  
anndata==0.7.6  
loompy==3.0.6  
numpy==1.19.1  
scipy==1.7.0  
matplotlib==3.4.2  
sklearn==0.24.2  
pandas==1.3.0

**Comment by WeilerP** [comment]
@christoffermattssonlangseth, thanks for opening a blank issue after our previous brief discussion in #256.

I have two immediate comments:
1. The neighbor graph should be calculate once. I assume you added `scv.tl.neighbors` prior to `scv.tl.velocity_graph` because the warning popped up?
2. In scVelo, we do not scale the data. Scaling the data will also scale model parameters and velocities in the downstream analysis!
3. Is there a reason you do not filter out variables? Or is the data you load already filtered?

I'll have a look at it ASAP to try figure out what's causing the problem.

**Comment by WeilerP** [comment]
@christoffermattssonlangseth the problem are 814 duplicate observations in your data. After removing them, you can run the pipeline, i.e. simply use

```python
adata = sc.read('fetal_brain_sample1_HybISS_imputed_V2_only_more_labels_normalized_210813.h5ad')
adata = adata[~adata.to_df().duplicated(), :]
```

ATM, I'm not sure if the `ValueError` in `scvelo.tools.velocity_graph::VelocityGraph` [here](https://github.com/theislab/scvelo/blob/8dbc8ea6230ba66b219fc905ac668cfde0405caf/scvelo/tools/velocity_graph.py#L111) can simply be replaced by the warning thrown in e.g. `scvelo.pp.moments` or if this may cause problems later on. Will have to look into it.

**Comment by christoffermattssonlangseth** [comment]
Thank you so much @WeilerP! I should have know to check that. My bad!

**Comment by WeilerP** [comment]
I'll close this and open a more descriptive feature/enhancement request.
