### ISSUE TITLE
error in scvelo.tl.rank_velocity_genes()

### ISSUE THREAD

**Issue by yuqiyuqitan** [theislab/scvelo#64]
### command that gives me errors
`scv.tl.rank_velocity_genes(data, match_with = 'louvain',resolution = 0.2)`

TypeError                                 Traceback (most recent call last)
/anaconda3/envs/scpMay/lib/python3.6/site-packages/pandas/core/ops.py in na_op(x, y)
   1788         try:
-> 1789             result = op(x, y)
   1790         except TypeError:

/anaconda3/envs/scpMay/lib/python3.6/site-packages/pandas/core/ops.py in rand_(left, right)
    186 def rand_(left, right):
--> 187     return operator.and_(right, left)
    188 

TypeError: unsupported operand type(s) for &: 'numpy.ndarray' and 'Categorical'

During handling of the above exception, another exception occurred:

AssertionError                            Traceback (most recent call last)
<ipython-input-113-303c26215f5c> in <module>
----> 1 scv.tl.rank_velocity_genes(day11, match_with = 'louvain',resolution = 0.2)

/anaconda3/envs/scpMay/lib/python3.6/site-packages/scvelo/tools/rank_velocity_genes.py in rank_velocity_genes(data, vkey, n_genes, groupby, match_with, resolution, min_counts, min_r2, min_dispersion, copy)
    149 
    150     if groupby is None or groupby == 'velocity_clusters':
--> 151         velocity_clusters(adata, vkey=vkey, match_with=match_with, resolution=resolution)
    152         groupby = 'velocity_clusters'
    153 

/anaconda3/envs/scpMay/lib/python3.6/site-packages/scvelo/tools/rank_velocity_genes.py in velocity_clusters(data, vkey, match_with, resolution, copy)
     65     tmp_filter = np.ones(vdata.n_vars, dtype=bool)
     66     if vkey + '_genes' in vdata.var.keys():
---> 67         tmp_filter &= vdata.var[vkey + '_genes']
     68 
     69     if 'unspliced' in vdata.layers.keys():

/anaconda3/envs/scpMay/lib/python3.6/site-packages/pandas/core/ops.py in wrapper(self, other)
   1848         filler = (fill_int if is_self_int_dtype and is_other_int_dtype
   1849                   else fill_bool)
-> 1850         res_values = na_op(self.values, ovalues)
   1851         unfilled = self._constructor(res_values,
   1852                                      index=self.index, name=res_name)

/anaconda3/envs/scpMay/lib/python3.6/site-packages/pandas/core/ops.py in na_op(x, y)
   1792             if isinstance(y, np.ndarray):
   1793                 # bool-bool dtype operations should be OK, should not get here
-> 1794                 assert not (is_bool_dtype(x) and is_bool_dtype(y))
   1795                 x = ensure_object(x)
   1796                 y = ensure_object(y)

AssertionError: 

### session info
`import scvelo as scv
scv.logging.print_version()`
Running scvelo 0.1.17 (python 3.6.7) on 2019-05-31 15:02.

`import numpy as np
import pandas as pd
import scanpy as sc
sc.settings.verbosity = 3
sc.logging.print_versions()
sc.settings.set_figure_params(dpi=80)`
scanpy==1.4.3 anndata==0.6.20 umap==0.3.9 numpy==1.15.4 scipy==1.1.0 pandas==0.24.2 scikit-learn==0.20.0 statsmodels==0.9.0 python-igraph==0.7.1 louvain==0.6.1 

### attempt
I have try 
`data.obs['cluster'] = data.obs['louvain'].astype(str) `
but it still gave me the same error

**Comment by VolkerBergen** [comment]
That was indeed a bug and has been fixed after v0.1.17. Installing from source should solve it.

**Comment by yuqiyuqitan** [comment]
I install from source but there was still error though different. Do i need to cast the clustering/annotation into specific type?

`import scvelo as scv
scv.logging.print_version()`
Running scvelo 0.1.17.dev22+4cafc50 (python 3.6.7) on 2019-06-01 14:05.

`scv.tl.rank_velocity_genes(day11, match_with = 'louvain', resolution = 0.2)`

computing velocity clusters
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-18-0713d7646984> in <module>
----> 1 scv.tl.rank_velocity_genes(day11, resolution = 0.2)

/anaconda3/envs/scpMay/lib/python3.6/site-packages/scvelo/tools/rank_velocity_genes.py in rank_velocity_genes(data, vkey, n_genes, groupby, match_with, resolution, min_counts, min_r2, min_dispersion, copy)
    149 
    150     if groupby is None or groupby == 'velocity_clusters':
--> 151         velocity_clusters(adata, vkey=vkey, match_with=match_with, resolution=resolution)
    152         groupby = 'velocity_clusters'
    153 

/anaconda3/envs/scpMay/lib/python3.6/site-packages/scvelo/tools/rank_velocity_genes.py in velocity_clusters(data, vkey, match_with, resolution, copy)
     88     verbosity_tmp = sc.settings.verbosity
     89     sc.settings.verbosity = 0
---> 90     sc.pp.pca(vdata, n_comps=20, svd_solver='arpack')
     91     sc.pp.neighbors(vdata, n_pcs=20)
     92     sc.tl.louvain(vdata, resolution=resolution)

/anaconda3/envs/scpMay/lib/python3.6/site-packages/scanpy/preprocessing/_simple.py in pca(data, n_comps, zero_center, svd_solver, random_state, return_info, use_highly_variable, dtype, copy, chunked, chunk_size)
    462     if use_highly_variable:
    463         logg.info('computing PCA on highly variable genes')
--> 464     adata_comp = adata[:, adata.var['highly_variable']] if use_highly_variable else adata
    465 
    466     if chunked:

/anaconda3/envs/scpMay/lib/python3.6/site-packages/anndata/base.py in __getitem__(self, index)
   1320     def __getitem__(self, index: Index) -> 'AnnData':
   1321         """Returns a sliced view of the object."""
-> 1322         return self._getitem_view(index)
   1323 
   1324     def _getitem_view(self, index: Index) -> 'AnnData':

/anaconda3/envs/scpMay/lib/python3.6/site-packages/anndata/base.py in _getitem_view(self, index)
   1323 
   1324     def _getitem_view(self, index: Index) -> 'AnnData':
-> 1325         oidx, vidx = self._normalize_indices(index)
   1326         return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
   1327 

/anaconda3/envs/scpMay/lib/python3.6/site-packages/anndata/base.py in _normalize_indices(self, index)
   1300         obs, var = unpack_index(index)
   1301         obs = _normalize_index(obs, self.obs_names)
-> 1302         var = _normalize_index(var, self.var_names)
   1303         return obs, var
   1304 

/anaconda3/envs/scpMay/lib/python3.6/site-packages/anndata/base.py in _normalize_index(index, names)
    272     else:
    273         raise IndexError('Unknown index {!r} of type {}'
--> 274                          .format(index, type(index)))
    275 
    276 

IndexError: Unknown index [False, False, False, False, True, ..., False, True, False, False, False]
Length: 1495
Categories (2, object): [False, True] of type <class 'pandas.core.arrays.categorical.Categorical'>

**Comment by VolkerBergen** [comment]
Thanks for mentioning. scanpy's pca does not assume 'highly_variable' to be categorical. 
@falexwolf Maybe we should modify that line to
`adata_comp = adata[:, np.array(adata.var['highly_variable'], dtype=bool)]`?

@yuqiyuqitan Upgrading scvelo should solve it now.

**Comment by yuqiyuqitan** [comment]
Thanks. It is fixed after upgrading :)

**Comment by falexwolf** [comment]
Thanks, yes! Good point!
