### ISSUE TITLE
tl.latent_time() yields all NaNs

### ISSUE THREAD

**Issue by quarkmatter** [theislab/scvelo#661]
Hi! I'm running into some difficulty in computing latent times on my data set.  I do not get any error, but when I look at the latent times, they are all NaN. After a relatively standard preprocessing I run the following: 

```python
In: scv.tl.recover_dynamics(data)
Out: WARNING: KLF5 not recoverable due to insufficient samples.
    finished (2:40:07) --> added 
    'fit_pars', fitted parameters for splicing dynamics (adata.var)

In: scp.pp.scale(data)
scv.tl.velocity(data, diff_kinetics=True, method='dynamical')
scv.tl.velocity_graph(data)
Out: computing neighbors
    finished (0:00:01) --> added 
    'distances' and 'connectivities', weighted adjacency matrices (adata.obsp)
computing moments based on connectivities
    finished (0:00:09) --> added 
    'Ms' and 'Mu', moments of un/spliced abundances (adata.layers)
computing velocities
    finished (0:00:21) --> added 
    'velocity', velocity vectors for each individual cell (adata.layers)
computing velocity graph (using 1/8 cores)

In: scv.tl.latent_time(data)
Out: computing terminal states
WARNING: Uncertain or fuzzy root cell identification. Please verify.
    identified 9 regions of root cells and 1 region of end points .
    finished (0:00:03) --> added
    'root_cells', root cells of Markov diffusion process (adata.obs)
    'end_points', end points of Markov diffusion process (adata.obs)
computing latent time using root_cells as prior
    finished (0:00:23) --> added 
    'latent_time', shared time (adata.obs)
```

I've tried, for instance, not scaling the data, setting diff_kinetcs=False, setting mode='stochastic' but the issue persists. Most everything else looks okay and there's no errors.

Interestingly, there are regions of the data I would describe as saddle points which i find fascinating (see picture). I wonder if these subregions are causing an issue with the initialization of root states and/or the rest of the latent time calculation.

Thanks in advance for the help 

<img width="631" alt="Screen Shot 2021-08-24 at 1 40 03 PM" src="https://user-images.githubusercontent.com/25307346/130663862-80cadd84-eeff-4abd-a32b-16f8628010f1.png">

**Comment by WeilerP** [comment]
@quarkmatter please reopen an issue providing a code snippet to reproduce your steps as well as the versions you are using as asked for in the issue template.
