### ISSUE TITLE
tl.latent_time() yields all NaNs

### ISSUE THREAD

**Issue by quarkmatter** [theislab/scvelo#662]
Hi! I'm running into some difficulty in computing latent times on my data set. I do not get any error, but when I look at the latent times, they are all NaN. Also, the top ranked dynamical genes don't really look right. I run the following with no errors

```python
scv.pp.filter_and_normalize(data, min_shared_counts=20)
scv.pp.moments(data, n_pcs=30, n_neighbors=30)
scp.pp.regress_out(data, keys='batch')
scp.pp.regress_out(data, keys='TotalUMIs')
scv.tl.recover_dynamics(data)
data.write('dataAD_8_24.h5ad', compression='gzip')
```

Then in a new notebook

```python 
data=scp.read('dataAD_8_24.h5ad')
scp.pp.scale(data)
scv.tl.velocity(data, diff_kinetics=True, method='dynamical')
scv.tl.velocity_graph(data)
scp.tl.pca(data, n_comps=15)
scp.tl.umap(data)
scv.pl.velocity_embedding_stream(data, basis='umap', dpi=120) [attached]
scv.tl.latent_time(data)
```

![](https://user-images.githubusercontent.com/25307346/130663862-80cadd84-eeff-4abd-a32b-16f8628010f1.png)

But all the latent times are NaN. I've tried, for instance, not scaling the data, setting diff_kinetcs=False, setting mode='stochastic' but the issue persists. Most everything else looks okay and there's no errors.

Interestingly, there are regions of the data I would describe as saddle points which i find fascinating (see picture). I wonder if these subregions are causing an issue with the initialization of root states and/or the rest of the latent time calculation.

Additionally, I think it could be something to do with recover_dynamics, perhaps due to outliers, because when i look at the top ranked genes in the (u,s)-plane they don't look very well fit despite having high likelihood. This is the top ranked: 
<img width="625" alt="Screen Shot 2021-08-24 at 4 40 24 PM" src="https://user-images.githubusercontent.com/25307346/130686851-34cf2faf-9d91-4cbe-8f0a-62679430e125.png">

#### Versions:

> scvelo==0.2.4.dev44+gdc1a66a.d20210707  
scanpy==1.7.2  
anndata==0.7.6 
loompy==3.0.6  
numpy==1.20.2  
scipy==1.6.3  
matplotlib==3.3.4  
sklearn==0.24.2  
pandas==1.2.4

**Comment by WeilerP** [comment]
@quarkmatter, any news on this?

**Comment by quarkmatter** [comment]
Hi, 

Yes I took your advice and switched around the workflow and it seems to be working fine now. Still not sure why all the NaNs were there. didn't get a chance to check your last suggestion on that, but If the issue arises again its the first thing I'll do. 

thanks!!
