### ISSUE TITLE
The scvelo object writing into disk showing error by scv.write_h5ad("mouse.h5ad") 

### ISSUE THREAD

**Issue by honghh2018** [theislab/scvelo#665]
Hi guys,
     It seem to me that it make me confused as to save the scvelo object to disk. It show to me below error:
     I want to save the temporary object to disk to prevent the variable damage. 
    So, how can i fix this issue?
ValueError                                Traceback (most recent call last)
~/miniconda3/envs/scvelo/lib/python3.8/site-packages/anndata/_io/utils.py in func_wrapper(elem, key, val, *args, **kwargs)
    208         try:
--> 209             return func(elem, key, val, *args, **kwargs)
    210         except Exception as e:

~/miniconda3/envs/scvelo/lib/python3.8/site-packages/anndata/_io/h5ad.py in write_dataframe(f, key, df, dataset_kwargs)
    244         if reserved in df.columns:
--> 245             raise ValueError(f"{reserved!r} is a reserved name for dataframe columns.")
    246 

ValueError: '_index' is a reserved name for dataframe columns.

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-68-ef4d84448b39> in <module>
----> 1 adata.write("lc_process.h5ad")

~/miniconda3/envs/scvelo/lib/python3.8/site-packages/anndata/_core/anndata.py in write_h5ad(self, filename, compression, compression_opts, force_dense, as_dense)
   1903             filename = self.filename
   1904 
-> 1905         _write_h5ad(
   1906             Path(filename),
   1907             self,

~/miniconda3/envs/scvelo/lib/python3.8/site-packages/anndata/_io/h5ad.py in write_h5ad(filepath, adata, force_dense, as_dense, dataset_kwargs, **kwargs)
    108             )
    109         else:
--> 110             write_attribute(f, "raw", adata.raw, dataset_kwargs=dataset_kwargs)
    111         write_attribute(f, "obs", adata.obs, dataset_kwargs=dataset_kwargs)
    112         write_attribute(f, "var", adata.var, dataset_kwargs=dataset_kwargs)

~/miniconda3/envs/scvelo/lib/python3.8/functools.py in wrapper(*args, **kw)
    873                             '1 positional argument')
    874 
--> 875         return dispatch(args[0].__class__)(*args, **kw)
    876 
    877     funcname = getattr(func, '__name__', 'singledispatch function')

~/miniconda3/envs/scvelo/lib/python3.8/site-packages/anndata/_io/h5ad.py in write_attribute_h5ad(f, key, value, *args, **kwargs)
    128     if key in f:
    129         del f[key]
--> 130     _write_method(type(value))(f, key, value, *args, **kwargs)
    131 
    132 

~/miniconda3/envs/scvelo/lib/python3.8/site-packages/anndata/_io/h5ad.py in write_raw(f, key, value, dataset_kwargs)
    137     group.attrs["shape"] = value.shape
    138     write_attribute(f, "raw/X", value.X, dataset_kwargs=dataset_kwargs)
--> 139     write_attribute(f, "raw/var", value.var, dataset_kwargs=dataset_kwargs)
    140     write_attribute(f, "raw/varm", value.varm, dataset_kwargs=dataset_kwargs)
    141 

~/miniconda3/envs/scvelo/lib/python3.8/functools.py in wrapper(*args, **kw)
    873                             '1 positional argument')
    874 
--> 875         return dispatch(args[0].__class__)(*args, **kw)
    876 
    877     funcname = getattr(func, '__name__', 'singledispatch function')

~/miniconda3/envs/scvelo/lib/python3.8/site-packages/anndata/_io/h5ad.py in write_attribute_h5ad(f, key, value, *args, **kwargs)
    128     if key in f:
    129         del f[key]
--> 130     _write_method(type(value))(f, key, value, *args, **kwargs)
    131 
    132 

~/miniconda3/envs/scvelo/lib/python3.8/site-packages/anndata/_io/utils.py in func_wrapper(elem, key, val, *args, **kwargs)
    210         except Exception as e:
    211             parent = _get_parent(elem)
--> 212             raise type(e)(
    213                 f"{e}\n\n"
    214                 f"Above error raised while writing key {key!r} of {type(elem)}"

ValueError: '_index' is a reserved name for dataframe columns.

Above error raised while writing key 'raw/var' of <class 'h5py._hl.files.File'> from /.

The version:
scv.logging.print_versions()
scvelo==0.2.3  scanpy==1.8.1  anndata==0.7.6  loompy==3.0.6  numpy==1.20.1  scipy==1.6.1  matplotlib==3.3.4  sklearn==0.24.1  pandas==1.2.2
The workflow according to the scvelo document guide to analyze, consequently it should be problem-free. 
Best work
Hanhuihong

**Comment by WeilerP** [comment]
@honghh2018, the function `scv.write_h5ad` does not exist and the problem you are encountering is caused by `anndata`. Please open an issue [there](https://github.com/theislab/anndata/issues).
