### ISSUE TITLE
PAGA docs not displayed correctly

### ISSUE THREAD

**Issue by WeilerP** [theislab/scvelo#670]
The documentation of `scvelo.tl.paga` is not displayed correctly [here](https://scvelo.readthedocs.io/scvelo.tl.paga/#scvelo.tl.paga). The returned statements include redundant asterisks `****`.

#### Versions:

> scvelo==0.2.3
> scvelo@develop

**Comment by WeilerP** [comment]
The return statement should probably be similar to other functions, i.e. something along the lines of

> Returns or updates data with the attributes
> * **connectivities** _(.uns)_ ...
> * **connectivities_tree** _(.uns)_ ...
> * **transitions_confidence** _(.uns)_ ...

**Comment by VolkerBergen** [comment]
fixed
