### ISSUE TITLE
Return statement in docs not as expected

### ISSUE THREAD

**Issue by WeilerP** [theislab/scvelo#671]
The return statement in the documentation is not as expected: For `scvelo.tl.terminal_states`, for example, the expected output is

> Returns or updates data with the attributes
> * **root_cells** _(.obs)_ – sparse matrix with transition probabilities.
> * **end_points** _(.obs)_ – sparse matrix with transition probabilities.

but the actual output is

> * **Returns** or updates data with the attributes
> * **root_cells** _(.obs)_ – sparse matrix with transition probabilities.
> * **end_points** _(.obs)_ – sparse matrix with transition probabilities.

This behavior applies to several functions.

#### Versions:

> scvelo==0.2.3
> scvelo@develop

**Comment by VolkerBergen** [comment]
fixed
