### ISSUE TITLE
New version totally invert velocity

### ISSUE THREAD

**Issue by LouisFaure** [theislab/scvelo#68]
Hi, I have been using scvelo version 0.1.16 since some time on various datasets with success, but after upgrading the package to the last 0.1.18 version, I cannot manage to reproduce my results. Using the new version even lead to somehow an inverted velocity map which does not make sense biologically, here is the code used for both versions:

```
scv.pp.filter_and_normalize(adata, min_counts=20, min_counts_u=10,n_top_genes=4000)
scv.pp.moments(adata)
scv.tl.velocity(adata)
scv.tl.velocity_graph(adata)
```

The embedding is imported because it has been computed externally

Here is a stream plot from 0.1.16:
![velocity_pca_0 1 16](https://user-images.githubusercontent.com/27488782/60770698-4dcd6100-a0de-11e9-95a5-e395a7630798.png)

And here is the one made with the lastest version:
![velocity_pca_0 1 18](https://user-images.githubusercontent.com/27488782/60770704-5de54080-a0de-11e9-96fa-67172546d802.png)

What could explain such dramatic change? 

Thanks for the help!

**Comment by VolkerBergen** [comment]
Wow, such a dramatic change is very unusual. Is that on PCA space?

**Comment by VolkerBergen** [comment]
Two thoughts come to mind :

Either it is due to direct PCA protection. 
Try running `scv.tl.velocity_embedding(adata, direct_projection=False)`

Or the neighbor graph could be corrupted. To check on this rerun `scv.pp.neighbors(adata).

**Comment by LouisFaure** [comment]
Indeed, I am actually importing an external PCA embedding (only the two first PCs), so I guess that is why this issue was happening. Anyway, running the command: `scv.tl.velocity_embedding(adata, direct_projection=False)` solved the issue! 

Thanks for the fast response!

**Comment by VolkerBergen** [comment]
Glad to hear! 

Direct projection only uses PCA space, which is a lot faster but can be quite misleading when there is only 2 PCs. Further, note that PCs are computed internally and can be different from the underlying PCs of your imported PCA. 

Here, by setting direct projection to False, it projects via the velocity graph computed from the full high dimensional data and thus is not dependent on any embedding. This is the way to go. 

Thanks for sharing this. To be honest, I have not beard in mind that you could only have two PCs. With the next release I'll probably set the default to projection via graph for velocity displacement in PCA (which was the case in v0.1.16 and earlier).

**Comment by LouisFaure** [comment]
Yes this is probably a special case, I am using the two imported first PCs as an "embedding" for constitency from other analysis I am performing, but it is true that the best thing to do is rather to use the internally computed PCA!

As a small addition I also realised that the min_r2 parameter does not seem to work in the function rank_velocity_genes, I still get genes with r2 lower than I am setting up.

**Comment by VolkerBergen** [comment]
I included a warning when directly projecting into PCA without using velocity graph. Further, `min_r2` should now work as expected. Will release in a sec with these fixes.

**Comment by LouisFaure** [comment]
Thanks for the fast response and the fixes !

**Comment by graddi** [comment]
Hello @VolkerBergen was this fixed? From what I know of the biology when I run these commands the arrows appear all inverted! When I try to add the direct_projection=False various commands give me errors and this option seem to have disappeared?

I also imported data in.

sc.tl.paga(gr_all_sce_copy4, use_rna_velocity=True, groups='clust_states',model='v1.2')
axs = sc.pl.paga_compare(
    gr_all_sce_copy4, title='UMAP vs Lineages - Cell States', right_margin=0.2, size=10,
    threshold=0.23,
    transitions='transitions_confidence',
    root=(['clust_states'] == 'Prohem. Inactive'),
    node_size_scale=1.5,
    node_size_power=2,
    edge_width_scale=1,
    max_edge_width=1.5,
    fontsize=8,
    legend_fontsize=8, frameon=False)

**Comment by VolkerBergen** [comment]
This has been fixed in https://github.com/theislab/scvelo/issues/68. You would need to install from source as this is not on pypi yet. Did you get the 'misbehaving' arrows on source or pypi?

The mentioned option is called `direct_pca_projection` and defaulted to None/False.

**Comment by graddi** [comment]
Hello @VolkerBergen  thanks for this I just reinstalled from source but the issue sadly persists.
