### ISSUE TITLE
Accessing clusters and subsetting based on gene expression

### ISSUE THREAD

**Issue by kathirij** [theislab/scvelo#69]
Hi,
   I would like to see if I can subset data based on what I think are useful and relevant genes. e.g., using only a few clusters. It might be something super simple but I am unable to figure it out.

Thanks!

**Comment by VolkerBergen** [comment]
Sure, that's simply `adata = adata[:, subset_genes]` and `adata = adata[subset_cells]` for subset being an array of boolean, indices or gene/cell names. Is that what you were looking for?

**Comment by kathirij** [comment]
Thanks.. yes.. I am trying to subset the adata object with cell names. However, I am confused about how to format the cell names file... I tried to put it as an array: 

cell_names = ["AAACCTGAGGCAGGTT", "AAACCTGCACAAGACG", "AAACCTGCATTTGCTT", "AAACCTGGTACCGTAT"] 

But that doesn't seem to work.. it says:

KeyError: "None of [Index(['AAACCTGAGGCAGGTT', 'AAACCTGCACAAGACG', 'AAACCTGCATTTGCTT',\n       'AAACCTGGTACCGTAT'],\n      dtype='object', name='index')] are in the [index]"

I am basically extracting cell names from a seurat object as csv and subsequently trying to feed into scVelo.

**Comment by VolkerBergen** [comment]
You can check whether your cell names `adata.var_names` match with the ones from your csv.
Usually they have some prefix, that can be cleared via `scv.utils.clean_obs_names(adata)`.
