### ISSUE TITLE
Combine loom Objects and Force-rename Cells

### ISSUE THREAD

**Issue by angelussong** [theislab/scvelo#699]
Hi, 

I am planning to run scvelo on six samples which were already merged, QC-ed and analyzed in Seurat. And I've successfully generated the loom objects using velocyto for each sample using the aligned bam files as well as the barcode lists I generated from the merged Seurat object. 

But when I tried to use adata.concatenate(), the total number of cells did not match what I had in the Seurat objects. Individually, each loom object matched what I had for each sample. But together the number was off. 
These are the individual loom objects. 
![image](https://user-images.githubusercontent.com/40570906/133502849-0e05cea9-9544-4c45-871a-b070c8839fce.png)
These are the number of cells from my Seurat object: 
![image](https://user-images.githubusercontent.com/40570906/133502964-430b01b6-8be1-4265-9fb5-e638f87f4eda.png)

However, after combination (adata=adata.concatenate(adata_VC1,adata_VC2,adata_VE1,adata_VE2,adata_VR1,adata_VR2)), I have 3481 cells where I should only have 2723 cells. I don't really understand the cause of this. Would you please help me with this? 

And another issue is that I did not have individual Seurat objects/h5ad objects for each sample so I need to have a combined loom object where I could also import in the UMAP coordinates and annotation IDs. But Seurat has forced renaming the cells to prevent duplicate cell IDs. I am wondering if there is any way for me to force renaming the cells for each loom objects before combining them and then transfer the metadata from my combined Seurat/h5ad object to it so that all the cell IDs could match? 

Thanks so much!

**Comment by WeilerP** [comment]
Doesn't seem to be scvelo related but an anndata issue so please open an issue there.
