### ISSUE TITLE
"AttributeError: 'numpy.ndarray' object has no attribute 'toarray'" in scv.pp.moments

### ISSUE THREAD

**Issue by yyoshiaki** [theislab/scvelo#7]
Hi!

I tried [the example notebook](https://nbviewer.jupyter.org/github/theislab/scvelo_notebooks/blob/master/DentateGyrus.ipynb) and encounterd the error below.

The libraries are 
scvelo==0.1.3+1.g7af8818, Scanpy==1.3.1, anndata==0.6.10 , numpy==1.15.1 , scipy==1.0.0, 
pandas==0.23.4 , scikit-learn==0.19.1 , statsmodels==0.9.0 

![image](https://user-images.githubusercontent.com/19543497/44990801-2e9d0900-afcd-11e8-8b7d-63e39908838f.png)

The dot function applied is disturbing the type of csr. or should I specify some libraries? 

I'm appreciating your works and looking forward the advance of scvelo and scanpy every single day.
Best regards.

**Comment by VolkerBergen** [comment]
Thanks for pointing that out. 

The data would preferably be read sparsely, i.e. set `sparse=True`. The case of using dense data in `tl.moments` is fixed now as well.
