### ISSUE TITLE
Starting file? 

### ISSUE THREAD

**Issue by Seandelao** [theislab/scvelo#70]
Hello, 

I have 10x datasets that I have been using for Scanpy analysis, and would really like to incorporate scvelo into my analysis!

Sorry this is such a basic question, but what are the starting files for running scvelo (i.e. BAM files converted into loom files)? In the example you have posted (dendate gyrus dataset) it seems like the unspliced/spliced counts are already incorporated into the dataset.

Do I need to create a file from the BAM files, such as with RNA Velocyto? 

Thank you in advance!

**Comment by VolkerBergen** [comment]
Yes, exactly. You'd need to generate the loom files (from BAM files) with the [velocyto command line interface](http://velocyto.org/velocyto.py/tutorial/cli.html) to obtain the splicing data.

**Comment by Maarten-vd-Sande** [comment]
Just a ping to point out that this was also unclear for me form the tutorial.

**Comment by VolkerBergen** [comment]
Added some explanation on currently available read count pipelines at https://scvelo.readthedocs.io/getting_started.html

We may also include a wrapper into scvelo in the near futures, so that anndata with splicing data can be directly created from fastqs.
