### ISSUE TITLE
Handle CellRanger --include-introns results

### ISSUE THREAD

**Issue by stela2502** [theislab/scvelo#709]
CellRanger now should also support a velocyto analysis by counting intronic reads.
Unfortunately I am unable to read the results into scvelo.
It would be great if the result files from CellRanger would also be supported, not only loom files.

**Comment by WeilerP** [comment]
@stela2502, could you please share a link to some docs/data for me to have a look/asses how and if to implement this? Also, don't hesitate to implement this and open a PR!

**Comment by stela2502** [comment]
Hi I am not a good python programmer. So I can not implement this.
I actually need to dig deeper to find what is going wrong.
I assume that the unspliced is not populated.
Do not hold your breath - this seams to be quite an endeavor for me.
To be honest - I might need to create a new genome for CellRanger first. 
Or I just stick to kallisto/bustools instead...

**Comment by stela2502** [comment]
Obviously my 'naive' assumption that one could 'simply' use this --include-introns option to get the correct data was wrong.
I think that is as far as I will look into this problem. Sorry to have bothered you.

**Comment by stela2502** [comment]
This seams to be not correct:

The single-nuclei RNA-seq assay captures unspliced pre-mRNA as well as mature mRNA. However, after alignment, cellranger count only counts reads aligned to exons. Since the pre-mRNA will generate intronic reads, it may be useful to count these reads as well. Previously, it was recommended to create a custom “pre-mRNA” reference package, listing each gene transcript locus as an exon, in order to count intronic reads. In Cell Ranger 5.0, there is a new include-introns option for counting intronic reads that should be used instead, and the usage of pre-mRNA references is deprecated.

**Comment by WeilerP** [comment]
No worries @stela2502. Sorry, I am confused now: Is still something worthwhile implementing or can the issue be closed.
I haven't looked into this so don't take this too serious: Why can CellRanger now provide the relevant data without passing its result to velocyto first?

**Comment by WeilerP** [comment]
Okay, I'll close this then.

**Comment by HousLi** [comment]
> Okay, I'll close this then.

Hello,

Can I ask the same question? Cellragner_multi has an option to include intronic reads in counts. The default setting is FLASE, but you can change to TURE when running counts. Can this be used to pre-process data for scvelo? like getting spliced and unspliced infromation?

Here is the link to the descrption of cellranger multi,
https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/multi

Thanks!
H

**Comment by stela2502** [comment]
My take home message was that CellRanger neither is able to export (separate) intronic reads nor is this feature planned.
So I recommend to use kallisto/bustools instead. This has worked for me and is actually also faster than CellRanger (I think).
https://www.kallistobus.tools/

**Comment by stela2502** [comment]
As far as I remember - yes - I use CellRanger mkfastq to get the fastq files and then run kallisto on them.
I can not really remember out of my head now. But the documentation did work for me.

**Comment by JimmyXtesla** [comment]
> My take home message was that CellRanger neither is able to export (separate) intronic reads nor is this feature planned. So I recommend to use kallisto/bustools instead. This has worked for me and is actually also faster than CellRanger (I think). https://www.kallistobus.tools/

**Comment by stela2502** [comment]
That makes sense - is there an option to use Kallisto/Bustools with a BD Rhapsody whole genome dataset?

________________________________
Von: Jimmy Banda ***@***.***>
Gesendet: Montag, 2. Dezember 2024 13:43
An: theislab/scvelo ***@***.***>
Cc: Stefan Lang ***@***.***>; Mention ***@***.***>
Betreff: Re: [theislab/scvelo] Handle CellRanger --include-introns results (#709)


My take home message was that CellRanger neither is able to export (separate) intronic reads nor is this feature planned. So I recommend to use kallisto/bustools instead. This has worked for me and is actually also faster than CellRanger (I think). https://www.kallistobus.tools/
