### ISSUE TITLE
PosixPath Error when using scv.settings.figdir

### ISSUE THREAD

**Issue by mtvector** [theislab/scvelo#71]
Hi there, when I specify a figdir as a string path in the the settings and use `scv.settings.autosave=True
scv.settings.autoshow=False
`  I get the following output:
` scv.pl.velocity_embedding(avdata, basis='umap')
  File "/utils/miniconda3/envs/scanpy/lib/python3.6/site-packages/scvelo/plotting/velocity_embedding.py", line 138, in velocity_embedding
    ax = scatter(adata, x=x, y=y, layer=layer, color=color, size=size, title=title, ax=ax, zorder=0, **scatter_kwargs)
  File /utils/miniconda3/envs/scanpy/lib/python3.6/site-packages/scvelo/plotting/scatter.py", line 171, in scatter
    savefig_or_show('' if basis is None else basis, dpi=dpi, save=save, show=show)
  File "/utils/miniconda3/envs/scanpy/lib/python3.6/site-packages/scvelo/plotting/utils.py", line 263, in savefig_or_show
    if settings.figdir[-1] != '/': settings.figdir += '/'
TypeError: 'PosixPath' object does not support indexing
`

**Comment by VolkerBergen** [comment]
Thanks for raising. Should be fixed now. Shout aloud, if still bugging.
