### ISSUE TITLE
Why do I have two python processes with the whole data in one tl.recover_dynamics(adata, n_jobs=10) run?

### ISSUE THREAD

**Issue by stela2502** [theislab/scvelo#715]
scvelo==0.2.3

So maybe this has been changed already. I'll check later - want the process to finish first.
But why do I have two processes with exactly the same size in a tl.recover_dynamics(adata, n_jobs=10) run and 10 tiny processes?
Should it not be one big process and 10 small ones?

 
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                    
## BIG:
380341 stefanl   20   0  478.5g 154.8g  56840 S   0.3  41.1   6:01.02 python3
380600 stefanl   20   0  350.5g 154.6g   4332 S   0.0  41.1   0:00.20 python3
##SMALL:
380670 stefanl   20   0  145.5g   3.1g   1.4g R  99.7   0.8   6:01.37 python3
380685 stefanl   20   0  145.1g   2.5g   1.7g R  99.7   0.7   6:00.89 python3
380690 stefanl   20   0  144.2g   2.2g   1.8g R 100.0   0.6   6:01.92 python3
380655 stefanl   20   0  144.2g   2.2g   1.8g R 100.0   0.6   6:05.23 python3
380675 stefanl   20   0  144.2g   2.1g   1.7g R  99.7   0.6   6:03.91 python3
380680 stefanl   20   0  144.2g   2.0g   1.6g R  99.7   0.5   6:00.28 python3
380648 stefanl   20   0  144.2g   1.9g   1.5g R 101.3   0.5   6:06.23 python3
380650 stefanl   20   0  144.2g   1.9g   1.5g R  99.7   0.5   6:01.91 python3
380660 stefanl   20   0  144.2g   1.9g   1.5g R 115.9   0.5   6:04.18 python3                                                                                                   380665 stefanl   20   0  144.2g   1.9g   1.5g R  99.3   0.5   6:01.65 python3 
```

**Comment by stela2502** [comment]
I assume the run has finished as the second big python process is gone, but the 10 small ones persist.
Can anybody confirm this?

```
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                    
## Big doing the next thing
380341 stefanl   20   0  511.3g 172.7g  56880 R  99.7  45.9   7:49.67 python3                                                                                                                                    
## Small doing nothing?!
380670 stefanl   20   0  113.5g 721548  48520 S   0.0   0.2  29:46.95 python3                                                                                                                                    
380650 stefanl   20   0  113.5g 712492  48516 S   0.0   0.2  28:42.81 python3                                                                                                                                    
380675 stefanl   20   0  113.5g 712268  48520 S   0.0   0.2  28:15.68 python3                                                                                                                                    
380648 stefanl   20   0  113.5g 711580  48516 S   0.0   0.2  27:07.35 python3                                                                                                                                    
380680 stefanl   20   0  113.5g 711156  48516 S   0.0   0.2  28:29.60 python3                                                                                                                                    
380660 stefanl   20   0  113.5g 710800  48516 S   0.0   0.2  27:49.81 python3                                                                                                                                    
380690 stefanl   20   0  113.5g 708904  48516 S   0.0   0.2  26:51.17 python3                                                                                                                                    
380685 stefanl   20   0  113.5g 705900  48512 S   0.0   0.2  26:47.68 python3  
```

**Comment by WeilerP** [comment]
@stela2502 not sure why you are seeing two big processes ad a couple of small ones. The problem with the current implementation of `scv.tl.recover_dynamics` is that each spawned job uses the entire `AnnData`. The refactoring and improving performance is an ongoing process. I alreadt opened #405. Does this help?

**Comment by stela2502** [comment]
This just does not seam to be correct. I do not see 10 jobs with all data, but I see 1 with all and 9 with less. And most interestingly the one will all does not work at all. There seams to be possibility for a lot of improvement here.

**Comment by stela2502** [comment]
Hi again, I had counted wrong - 2 big and 10 small it is. Also with the version 0.2.4.

**Comment by stela2502** [comment]
But when you compare the CPU values - the implementation in 0.2.4 seams to be 'broken' - only one to two small workers do actually work: here none do :-(
```
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                                                
294855 stefanl   20   0  478.5g 154.7g  53692 S   0.0  41.1   6:48.63 python3                                                                                                                                                                                                
295012 stefanl   20   0  318.4g 154.6g   3792 S   0.0  41.1   0:00.09 python3                                                                                                                                                                                                
295082 stefanl   20   0  145.0g   2.0g 999.8m D   1.7   0.5   0:19.42 python3                                                                                                                                                                                                
295093 stefanl   20   0  145.0g   2.0g 999.8m D   2.0   0.5   0:19.06 python3                                                                                                                                                                                                
295062 stefanl   20   0  145.0g   1.9g   1.0g D   1.3   0.5   0:28.53 python3                                                                                                                                                                                                
295067 stefanl   20   0  145.0g   1.9g   1.0g D   2.0   0.5   0:36.20 python3                                                                                                                                                                                                
295098 stefanl   20   0  145.0g   1.9g   1.0g D   1.7   0.5   0:37.62 python3                                                                                                                                                                                                
295072 stefanl   20   0  145.0g   1.7g   1.0g D   2.6   0.5   1:16.87 python3                                                                                                                                                                                                
295060 stefanl   20   0  144.1g   1.5g   1.2g D   0.7   0.4   1:37.94 python3                                                                                                                                                                                                
295087 stefanl   20   0  144.1g   1.4g   1.1g D   0.3   0.4   0:52.45 python3                                                                                                                                                                                                
295077 stefanl   20   0  144.1g   1.4g   1.1g D   0.3   0.4   1:21.60 python3                                                                                                                                                                                                
295103 stefanl   20   0  144.1g   1.3g   1.1g D   0.3   0.4   0:17.86 python3    
```

**Comment by WeilerP** [comment]
> This just does not seam to be correct. I do not see 10 jobs with all data, but I see 1 with all and 9 with less. And most interestingly the one will all does not work at all. There seams to be possibility for a lot of improvement here.

Parallelization already works. Problem is running out of memory in case of large datasets, hence #405.

> But when you compare the CPU values - the implementation in 0.2.4 seams to be 'broken' - only one to two small workers do actually work: here none do :-(

Might just be an OOM problem/error? What's the size of the dataset you are passing to `recover_dynamics`? Also, what kind of system are you running this on?

**Comment by stela2502** [comment]
Hi again, I am running a 1e+5 cells 3e+4 genes anndata file on a 40 core 340Gb ram Intel computation node using a singularity image containing all Python code.

**Comment by stela2502** [comment]
And the small processes later on gained performance, but not a constant ~100% as in 0.2.3. The data might be split in too small parts in 0.2.4. All in all not too problematic as the system processes the data and 50% more time in this rather efficient step are not a problematic time loss over all. The single processor parts of a velocity analysis do take way more time than this.

**Comment by stela2502** [comment]
Had to google "OOM problem" and no - if I get a OOM problem the process dies. The small ones got to 100% later during this analysis.

**Comment by WeilerP** [comment]
> Hi again, I am running a 1e+5 cells 3e+4 genes anndata file on a 40 core 340Gb ram Intel computation node using a singularity image containing all Python code. And please count again using the new process table. I count 10 small ones and assume I just forgot to copy one in the first process list.

Is there a reason for using 30000 genes? In the usual pipeline you subset to highly variable genes (~2000 to begin with). See e.g. [here](https://scvelo.readthedocs.io/vignettes/Pancreas/) for the common pipeline.

**Comment by stela2502** [comment]
I do not want to subset my data as I want to actually be able to plot all genes later on. I have 3000 var genes in the data and e.g. umap does also work on just the var genes. I am actively not using the common pipeline as I do not like the results.

**Comment by stela2502** [comment]
https://scanpy.readthedocs.io/en/stable/generated/scanpy.pp.filter_genes_dispersion.html#scanpy.pp.filter_genes_dispersionEspecially the sentence:
"subset=False in the new function, it suffices to merely annotate the genes, tools like pp.pca will detect the annotation"
Would be cool if scvelo could also do that ;-)

**Comment by WeilerP** [comment]
> https://scanpy.readthedocs.io/en/stable/generated/scanpy.pp.filter_genes_dispersion.html#scanpy.pp.filter_genes_dispersionEspecially the sentence: "subset=False in the new function, it suffices to merely annotate the genes, tools like pp.pca will detect the annotation" Would be cool if scvelo could also do that ;-)

Should already be working. In `filter_and_normalize`, you can set `subset_highly_variable=False` (it is `True` by default). PCA in scvelo is simply ported from Scanpy for convenience.

**Comment by stela2502** [comment]
It was never a problem and I did not expect that I needed to subset the data before I run the velocity analysis. But subseting the data mad the velocity run possible.
Thank you for this input.
