### ISSUE TITLE
Can we add support for observation variables to `scvelo.pl.velocity`?

### ISSUE THREAD

**Issue by naity** [theislab/scvelo#716]
I was wondering if it would be possible to support using `obs` variables in `scv.pl.velocity` similar to `scanpy.pl.umap` so that one could visualize protein expression data stored as columns in `obs`.

Thanks very much!

**Comment by WeilerP** [comment]
@naity, do you mean coloring the observations based on a column in `.obs`? Could you please provide a minimal working example that I can simply copy and paste showing the feature in `scanpy.pl.umap` you are referring to? Thanks!

**Comment by naity** [comment]
Hi @WeilerP, Thank you so much for your response! After more careful thought, I realized that this was a bad request and will close it. Thank you again!
