### ISSUE TITLE
Velocity-embedding-stream color_map argument not working in 0.2.4

### ISSUE THREAD

**Issue by wes-lewis** [theislab/scvelo#719]
I installed scvelo from source as mentioned in #432 yielding version 0.2.4. However, this issue still persists, with different color map choices eliciting no difference in the displayed color map (at least for categorical variables).
![clusters_scvelo_cmaps](https://user-images.githubusercontent.com/59123674/135916218-fa6cc6f2-b6fe-4e79-9f81-40d8ab346d7b.PNG)
)

_Originally posted by @wes-lewis in https://github.com/theislab/scvelo/issues/432#issuecomment-933808879_

**Comment by WeilerP** [comment]
I think one problem is that the colors are already stored in `.uns['R_cluster_colors']`. Is this the case? Although, I think it still won't work if `.obs['R_cluster']` is categorical. A workaround is to either define the colors manually or define a new column ,`obs['R_clusters_num']` for example, where the clusters are defined using numerical values.
Either way, please provide the used package versions. You can do so easily with `scv.logging.print_versions()`.

**Comment by WeilerP** [comment]
I'll close this in favor of #720 where I provided a clear problem description, reproducible code and package versions used.
