### ISSUE TITLE
Incomplete scvelo.pl.proportions() 

### ISSUE THREAD

**Issue by DrLucyMac** [theislab/scvelo#733]
Hello, I am having issue of wrong directionality (macrophages to monocytes) instead of vice versa. I think it likely due to the fact that my scvelo.pl.proportions() do not equal 100%. See image below. Please help!

Cheers,
Lucy 

<img width="901" alt="image" src="https://user-images.githubusercontent.com/40166451/138150827-922f51c5-0174-4e1c-b31d-3b7539bf812a.png">

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/40166451/138150656-88615735-57cb-4695-ab62-1141a86e06d0.png">

<details> <summary> Versions </summary>

```pytb
scvelo==0.2.3  scanpy==1.6.0  anndata==0.7.4  loompy==3.0.6  numpy==1.18.5  scipy==1.5.0  matplotlib==3.4.1  sklearn==0.23.1  pandas==1.2.4  
```
</details>

**Comment by lcymcdnld** [comment]
<img width="798" alt="image" src="https://user-images.githubusercontent.com/40166451/138241365-41f807c2-6e74-4ac1-acf1-16dc8d9313a8.png">

**Comment by WeilerP** [comment]
@lcymcdnld are your counts already processed, *i.e.*, filtered, normalized, etc.? The function `scv.pl.proportions` is meant to be called prior to any analysis. See #575 for a similar (but maybe different) issue where this has been discussed previously.
