### ISSUE TITLE
meaning of rank_velocity_genes

### ISSUE THREAD

**Issue by hmassalha** [theislab/scvelo#75]
Hi, 
I am wondering what this function `rank_velocity_genes` is actually doing? 
In my case, I am working on a statice tissue or a non-developmental organ, the liver. That mean, I have no previous knowledge about the differentiation processes in the tissue, and I am not expecting a flow of information between different cells types, even though velocity is giving me nice vectors. 
The function of `rank_velocity_genes` is giving a group of biologically meaningless genes. My question is what would you suggest to test such results? the number of PCA, neighbors...

*I have three clusters and I am getting the same genes, in a different order, for the three clusters.

Thanks a lot, 
HM

**Comment by VolkerBergen** [comment]
`rank_velocity_genes` simply runs a differential expression test w.r.t velocities. Do you observe any indication of induction/repression in your phase portraits?
If you set `groupy=None` in `rank_velocity_genes`, velocity clusters are computed beforehand (based on louvain modularity) which may give you better sets of differential genes.

**Comment by hmassalha** [comment]
I have two clusters, and I see the same genes in a different order (only 10 genes showed!)

**Comment by VolkerBergen** [comment]
You can select the number of genes with `n_genes`, checkout the [API](https://scvelo.readthedocs.io/en/latest/scvelo.tl.rank_velocity_genes.html#scvelo.tl.rank_velocity_genes) for details.

If the same genes pop up, they appear to be indicative for both clusters, perhaps being significantly low and high for each cluster respectively.
