### ISSUE TITLE
data to make plots using matlab 

### ISSUE THREAD

**Issue by hmassalha** [theislab/scvelo#76]
Hi, 
Unfortunately, I am not a python expert! Somehow I managed to run the pipeline and get nice results. However, I feel more comfortable and I have control using Matlab. 
I managed to save my work as loom file and open it in Matlab. My question is what are the relevant data slots that I have to use to replot the, for example, the phase diagram as the output of `scv.pl.velocity`? 

Thanks a lot, HM

**Comment by VolkerBergen** [comment]
I think, the velocities are stored in vlm.ca and the spliced and unspliced count matrices are found in vlm.layers (after reading as vlm = loompy.connect...).

Whatsoever, I would not recommend trying to reproduce the plots in MatLab, but advise learning a bit of python.

**Comment by VolkerBergen** [comment]
You find some nice tutorials on plotting with scvelo/scanpy here:
https://icb-scanpy.readthedocs-hosted.com/en/stable/tutorials.html

**Comment by hmassalha** [comment]
Thanks a lot, 
I am trying to plot pseudotime vs. expression for spliced and unspliced data of selected genes (see ref panel d)! The pseudotime was calculated with home-based script, this is way I looking to export the data somehow. 


https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41586-018-0414-6/MediaObjects/41586_2018_414_Fig4_HTML.png?as=webp

**Comment by VolkerBergen** [comment]
That was also done in python, see https://github.com/velocyto-team/velocyto-notebooks/blob/master/python/hgForebrainGlutamatergic.ipynb

**Comment by hmassalha** [comment]
Thanks a lot, HM

**Comment by VolkerBergen** [comment]
Just as a side note: You can now also plot expression along a time coordinate (such as pseudotime) with `scv.pl.scatter(adata, x='dpt_pseudotime', y='gene_name', layers='Ms, Mu', color='blue, green')`. If you only need expression change and no spliced/unspliced comparison, just leave layers and colors blank.
