### ISSUE TITLE
Is it possible to draw the CytoTRACE pseudotime-directed PAGA graph?

### ISSUE THREAD

**Issue by hyjforesight** [theislab/scvelo#773]
...
**Hello scVelo,
We know by recovering the latent time, it's available to combine the 'velocity_pseudotime' or 'latent_time' with the initial state and terminal state calculated by CellRank to draw the directed PAGA graph by the below coding:**

```
scv.tl.recover_latent_time(adata, root_key="initial_states_probs", end_key="terminal_states_probs")    # recover latent time by using the CellRank determined initial states and terminal states
scv.tl.paga(adata, groups="clusters", root_key="initial_states_probs", end_key="terminal_states_probs", use_time_prior="latent_time")    # combine the latent-time with the CellRank determined initial states and terminal states to calculate PAGA
cr.pl.cluster_fates(adata, mode="paga_pie", cluster_key="clusters", basis="umap")    # latent time directed fate-probability-PAGA
```

**Because CytoTRACE can also calculate 'ct_pseudotime' by ctk = CytoTRACEKernel(adata), we tried to use ct_pseudotime to draw the CytoTRACE pseudotime-directed PAGA, but it failed. It looks like directed PAGA can be only done based on scVelo?**
![image](https://user-images.githubusercontent.com/75048821/144786851-4ac385f5-7746-407e-92cf-487199803846.png)

**We're wondering whether it is possible to draw the CytoTRACE pseudotime-directed PAGA graph with or without combining with the CellRank determined initial states and terminal states?
The original question is here (https://github.com/theislab/cellrank/issues/788). @Marius1311 told me it's OK to open this request here. 
Thanks!
Best,
YJ**

**Comment by WeilerP** [comment]
@hyjforesight, based on the error message, the problem isn't the pseudotime but that your AnnData seems to be missing the velocity graph which PAGA uses.

**Comment by hyjforesight** [comment]
Hello @WeilerP ,
Thanks for the response!
scVelo generates the adata.uns.velocity_graph by calling
```
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
scv.tl.recover_dynamics(adata, n_jobs=16)
scv.tl.velocity(adata, mode='dynamical', use_raw=False)
scv.tl.velocity_graph(adata, n_jobs=16)
```

Because we're using the CytoTRACE kernal, which is based on gene counts, not gene velocity, by below coding
![image](https://user-images.githubusercontent.com/75048821/145434944-a9dd7aca-6519-4825-9e01-54e22d19342a.png)
and it will not generate velocity_graph, but a velocity-like map
![image](https://user-images.githubusercontent.com/75048821/145435370-2df901f2-7116-4f52-9aa3-30a97c0a0873.png)

So it looks like scv.tl.paga() can only calling the 'velocity_graph' generated by scVelo. Velocity-like map generated by CytoTRACE is not accepted? Am I right?
Thanks!
Best,
YJ

**Comment by WeilerP** [comment]
@hyjforesight, PAGA operates on a graph. As far as I can tell, the problem you encounter has nothing to do with CytoTRACE or the projection onto a 2D UMAP embedding. The PAGA function in scvelo looks for a graph called `f{vkey}_graph`, with ``vkey='velocity' by default, which does not exist in your case. As suggested in my previous comment, you should duplicate/rename the neighbor graph to `velocity_graph` to use the function with the standard neighbor graph used to calculate the 2D UMAP embedding.

**Comment by hyjforesight** [comment]
Hello @WeilerP,
Sorry, I misunderstood before. Thanks for the explanation!
Does it mean that I just need to copy the adata.uns['neighbors'] to adata.uns['velocity_graph']? I tried, but it generated errors. Could you please give any further recommendations?
![image](https://user-images.githubusercontent.com/75048821/145479498-be8dcc19-22aa-49ab-9a5e-915e2ff48aae.png)
![image](https://user-images.githubusercontent.com/75048821/145479791-3e57d6eb-a8fe-441f-a129-4ec3c46d5ac7.png)
Thanks!
Best,
YJ

**Comment by WeilerP** [comment]
@hyjforesight, `adata.uns['neighbors']` does not contain the actual graph but only parameters used to calculate it. You can double check this by printing the output of `adata.uns['neighbors']`. You should do `adata.uns['velocity_graph']` = adata.obsp['connectivities']` if I am not mistaken.

P.s.: On a gerenal note: Please copy, paste and format you code snippet and the stack trace instead of pasting an image. This makes referencing easier and allows me to copy your code easily to check it on my own dataset.

**Comment by hyjforesight** [comment]
Hello @WeilerP,
Sorry for copying and pasting the picture.
Thanks for the response and patience! 
The CytoTRACE pseudotime-directed PAGA and CytoTRACE-fate-probability-directed PAGA are successfully drawn by following coding:
```
adata.uns['velocity_graph'] = adata.obsp['connectivities']
scv.tl.paga(adata, groups='leiden', vkey='velocity', use_time_prior='ct_pseudotime')
scv.pl.paga(adata, basis='umap', vkey='velocity', node_size_scale=1.5, min_edge_width=2, use_raw=False, size=50, alpha=0.1)
cr.pl.cluster_fates(adata, mode="paga_pie", cluster_key='leiden', basis="umap",
                    legend_kwargs={"loc": "top right out"}, legend_loc="top left out", node_size_scale=5, edge_width_scale=1, max_edge_width=4, title="directed PAGA")
```
![image](https://user-images.githubusercontent.com/75048821/146098269-c46105b7-877e-4207-bc37-ca4a2087d8ec.png)
![image](https://user-images.githubusercontent.com/75048821/146098305-940cfe5c-80ca-4208-9a1e-0bb9f685fea3.png)

That is awesome!
Thanks!
Best,
YJ
