### ISSUE TITLE
fit parameters yield NaNs

### ISSUE THREAD

**Issue by quarkmatter** [theislab/scvelo#774]
Hi, 

I've been running scvelo on a fairly large set. When I ran it on my VM it didnt give any errors and saved everything just fine. I went to plot and examine the results and everything looked okay. The streamline plots looked nice, the phase diagrams were decent (as far as i can tell), heat maps were fine.

 However when i looked at my data.var many of the genes had NaN for all the parameter fits. I'm wondering if this was something on my end, like some issues in the preprocessing pipeline or something, or if its nothing to really be that concerned about. is it that these genes were just bad in the model? or did i do something wrong?

```python
scp.pp.normalize_total(data,target_sum=10000, exclude_highly_expressed=True)
scp.pp.log1p(data)
scp.pp.regress_out(data, keys='totalUMIs')
scp.pp.regress_out(data, keys='sample')
scp.pp.pca(data)
scp.pp.neighbors(data, use_rep='X_pca', n_neighbors=30, n_pcs=50)
scv.pp.moments(data)
scp.pp.highly_variable_genes(data, flavor='seurat')

if scale is True:
    scp.pp.scale(data)
print('preprocessing complete')
print('computing embeddings')
print(' ')
scp.tl.umap(data)
scp.tl.tsne(data)

print('limiting analysis to highly variable genes')
print(' ')
highVar=data.var.loc[data.var['highly_variable']==True, :].index.tolist()
dataHV=data[:,highVar]

print('recovering dynamics (this will take forever')

scv.tl.recover_dynamics(dataHV)
dataHV.write('fullADHiVarDyn.h5ad', compression='gzip')
print(' ')
print('computing velocities')

scv.tl.velocity(dataHV, mode='dynamical')
scv.tl.velocity_graph(dataHV)
scv.tl.velocity_embedding(dataHV)
scv.tl.latent_time(dataHV)
scv.tl.terminal_states(dataHV)
scv.tl.rank_velocity_genes(dataHV, groupby='subType')
scv.tl.rank_dynamical_genes(dataHV, n_genes=500, groupby='subType')
print(' ')
print('saving final output')
dataHV.write('fullADwVelocity.h5ad', compression='gzip')
```

<details>

<summary> Error output </summary>

```pytb
# paste the error output here, if applicable
```
![Screen Shot 2021-12-08 at 11 47 03 AM](https://user-images.githubusercontent.com/25307346/145274127-016b1f7e-bada-4236-84e6-92d9a69d3c22.png)

</details>

<details> <summary> Versions </summary>

```pytb
scvelo==0.2.4.dev44+gdc1a66a.d20210707  scanpy==1.7.2  anndata==0.7.6  loompy==3.0.6  numpy==1.20.2  scipy==1.6.3  matplotlib==3.3.4  sklearn==1.0  pandas==1.2.4
```
</details>

**Comment by WeilerP** [comment]
This not a bug. As explained in the docs, `scvelo.tl.recover_dynamics` "_recovers the full splicing kinetics of specified genes._" By default (which you are running), this is the set velocity genes. They are genes exhibiting the relevant/required signal and if not provided by the user, these genes are inferred automatically by a simple regression test.

**Comment by quarkmatter** [comment]
yeah i figured it wasn't a bug i just didnt know how to change the labels. thank you!!
