### ISSUE TITLE
Installation from github failed.

### ISSUE THREAD

**Issue by mbuttner** [theislab/scvelo#8]
Hi,

I tried to install scvelo from Github on a Linux machine:

 git clone https://github.com/theislab/scvelo.git
 cd scvelo
 pip install .
> Directory '.' is not installable. File 'setup.py' not found.

Can you provide a setup.py file in order to make the installation work?

**Comment by VolkerBergen** [comment]
Thanks for pointing that out. Will be fixed asap. For now, use `pip install scvelo==0.1.3`.

**Comment by VolkerBergen** [comment]
fixed in v0.1.5

However, I recommend installing directly from PyPI (every beta version will have its own release).
