### ISSUE TITLE
scv.tl.velocity_pseudotime(adata) or scv.tl.terminal_states(adata) does not end.

### ISSUE THREAD

**Issue by realzehuali** [theislab/scvelo#809]
scv.tl.velocity_pseudotime(adata) or scv.tl.terminal_states(adata) does not end.
I run this step on a dataset with 60k cells. This step did not end within 6 hours. I stopped this step and the error output was as below:

computing terminal states
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-11-7bdb65ca1e79> in <module>
----> 1 scv.tl.velocity_pseudotime(adata)
      2 adata
      3 scv.pl.scatter(adata, color='velocity_pseudotime', cmap='gnuplot', size=20, colorbar=True, basis = 'X_UMAP_HARM_TRO30', figsize = (12,12), ncols = 1, title = '', save = "UMAP_HARM_pseudotime.pdf")
      4 scv.pl.scatter(adata, color='velocity_pseudotime', cmap='gnuplot', size=20, colorbar=True, basis = 'X_diffmap', figsize = (12,12), ncols = 1, title = '', components = '2,3', save = "diffmap_pseudotime.pdf")

c:\users\msi\anaconda3\envs\scvelo\lib\site-packages\scvelo\tools\velocity_pseudotime.py in velocity_pseudotime(adata, vkey, groupby, groups, root_key, end_key, n_dcs, use_velocity_graph, save_diffmap, return_model, **kwargs)
    221             and np.max(adata.obs[root_key]) == np.min(adata.obs[root_key])
    222         ):
--> 223             terminal_states(adata, vkey=vkey, groupby=groupby, groups=groups)
    224             root_key, end_key = "root_cells", "end_points"
    225         cell_subset = groups_to_bool(adata, groups=groups, groupby=groupby)

c:\users\msi\anaconda3\envs\scvelo\lib\site-packages\scvelo\tools\terminal_states.py in terminal_states(data, vkey, modality, groupby, groups, self_transitions, eps, random_state, copy, **kwargs)
    291 
    292         T = transition_matrix(_adata, vkey=vkey, backward=True, **kwargs)
--> 293         eigvecs_roots = eigs(T, eps=eps, perc=[2, 98], random_state=random_state)[1]
    294         roots = csr_matrix.dot(connectivities, eigvecs_roots).sum(1)
    295         roots = scale(np.clip(roots, 0, np.percentile(roots, 98)))

c:\users\msi\anaconda3\envs\scvelo\lib\site-packages\scvelo\tools\terminal_states.py in eigs(T, k, eps, perc, random_state, v0)
    150     try:
    151         # find k eigs with largest real part, and sort in descending order of eigenvals
--> 152         eigvals, eigvecs = linalg.eigs(T.T, k=k, which="LR", v0=v0)
    153         p = np.argsort(eigvals)[::-1]
    154         eigvals = eigvals.real[p]

c:\users\msi\anaconda3\envs\scvelo\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py in eigs(A, k, M, sigma, which, v0, ncv, maxiter, tol, return_eigenvectors, Minv, OPinv, OPpart)
   1344     with _ARPACK_LOCK:
   1345         while not params.converged:
-> 1346             params.iterate()
   1347 
   1348         return params.extract(return_eigenvectors)

c:\users\msi\anaconda3\envs\scvelo\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py in iterate(self)
    740             # compute y = Op*x
    741             if self.mode in (1, 2):
--> 742                 self.workd[yslice] = self.OP(self.workd[xslice])
    743             else:
    744                 Bxslice = slice(self.ipntr[2] - 1, self.ipntr[2] - 1 + self.n)

c:\users\msi\anaconda3\envs\scvelo\lib\site-packages\scipy\sparse\linalg\interface.py in matvec(self, x)
    230             raise ValueError('dimension mismatch')
    231 
--> 232         y = self._matvec(x)
    233 
    234         if isinstance(x, np.matrix):

c:\users\msi\anaconda3\envs\scvelo\lib\site-packages\scipy\sparse\linalg\interface.py in _matvec(self, x)
    197         will define matrix-vector multiplication as well.
    198         """
--> 199         return self.matmat(x.reshape(-1, 1))
    200 
    201     def matvec(self, x):

c:\users\msi\anaconda3\envs\scvelo\lib\site-packages\scipy\sparse\linalg\interface.py in matmat(self, X)
    335                              % (self.shape, X.shape))
    336 
--> 337         Y = self._matmat(X)
    338 
    339         if isinstance(Y, np.matrix):

c:\users\msi\anaconda3\envs\scvelo\lib\site-packages\scipy\sparse\linalg\interface.py in _matmat(self, X)
    729 
    730     def _matmat(self, X):
--> 731         return self.A.dot(X)
    732 
    733     def _adjoint(self):

c:\users\msi\anaconda3\envs\scvelo\lib\site-packages\scipy\sparse\base.py in dot(self, other)
    357 
    358         """
--> 359         return self * other
    360 
    361     def power(self, n, dtype=None):

c:\users\msi\anaconda3\envs\scvelo\lib\site-packages\scipy\sparse\base.py in __mul__(self, other)
    467                 return self._mul_vector(other)
    468             elif other.shape == (N, 1):
--> 469                 return self._mul_vector(other.ravel()).reshape(M, 1)
    470             elif other.ndim == 2 and other.shape[0] == N:
    471                 return self._mul_multivector(other)

c:\users\msi\anaconda3\envs\scvelo\lib\site-packages\scipy\sparse\compressed.py in _mul_vector(self, other)
    476         # csr_matvec or csc_matvec
    477         fn = getattr(_sparsetools, self.format + '_matvec')
--> 478         fn(M, N, self.indptr, self.indices, self.data, other, result)
    479 
    480         return result

KeyboardInterrupt: 

Any help would be thankful!

**Comment by WeilerP** [comment]
With the limited info given, there is nothing I could help with. Please open a new issue using the provided template, i.e. give all the info asked for (reproducible code snippet, stack trace, used versions) properly formatted, etc.
You can also try running your code on a subset of the data. Might be that you are running out of the memory? This is just a (almost random) guess, though.

**Comment by LynnChan99** [comment]
> With the limited info given, there is nothing I could help with. Please open a new issue using the provided template, i.e. give all the info asked for (reproducible code snippet, stack trace, used versions) properly formatted, etc. You can also try running your code on a subset of the data. Might be that you are running out of the memory? This is just a (almost random) guess, though.

same problelm. Not the memory problem. And other similar dataset could run this code smoothly. 
Any idea to check the source of this problem?
