### ISSUE TITLE
Filtering error - analysis on subset cells

### ISSUE THREAD

**Issue by graddi** [theislab/scvelo#81]
Hello,

Great package! One issue.

I am trying to get velocity information and analysis only on a subset of cells. However when I process the data like this:

import scvelo as scv
 ((Load previous object with UMAP embeddigns and diffusion maps))
gr_all_sce_copy4 = gr_all_sce_copy.copy()    
 
ldata = scv.read('/Users/gr11/Documents/Results/Latest/Seurat/CCA_no_bf24_sug48/V3Seurat/Velocyto/merged.loom', cache=True)
gr_all_sce_copy4 = scv.utils.merge(gr_all_sce_copy4, ldata)

only_hemocytes = gr_all_sce_copy4.obs.index[(gr_all_sce_copy4.obs['clust_types']=='Effector') | (gr_all_sce_copy4.obs['clust_types']=='Prohemocytes') |
                               (gr_all_sce_copy4.obs['clust_types']=='Dividing cells') | (gr_all_sce_copy4.obs['clust_types']=='Granulocytes') |
                               (gr_all_sce_copy4.obs['clust_types']=='Secretory')]

gr_all_sce_copy4 = gr_all_sce_copy4[only_hemocytes, :]

scv.pp.filter_genes(gr_all_sce_copy4, min_shared_counts=3)
scv.pp.normalize_per_cell(gr_all_sce_copy4)
scv.pp.filter_genes_dispersion(gr_all_sce_copy4, n_top_genes=1000)
scv.pp.log1p(gr_all_sce_copy4)

scv.pp.filter_and_normalize(gr_all_sce_copy4, min_shared_counts=3, n_top_genes=1000)
scv.pp.moments(gr_all_sce_copy4, n_pcs=20, n_neighbors=20)

I get this error:
<img width="857" alt="Figure 1" src="https://user-images.githubusercontent.com/20108378/62786950-8edcda80-babb-11e9-89ea-28e2579630ea.png">

Any thoughts? Thanks!

**Comment by VolkerBergen** [comment]
First guess is the neighbor graph, which might not match anymore after subsetting. Try recomputing `pp.neighbors` before running `pp.moments`.

Is that is not the catch, check what dimensions you get on 
`scv.utils.get_connectivities(adata)` and `adata.shape`.

**Comment by graddi** [comment]
The first solution solved it! Thank you for quick reply, I'm closing the issue.
