### ISSUE TITLE
Spliced and unspliced proportions don't add up

### ISSUE THREAD

**Issue by gauravsinghrathore** [theislab/scvelo#821]
I am trying to integrate two time point data sets with mnn_correct and run velocity. 
After integration the spliced and unspliced proportions don't add up. Should i be worried?
<img width="1137" alt="Screenshot 2022-02-09 at 14 16 59" src="https://user-images.githubusercontent.com/34302005/153209501-e72ee801-e369-4037-84a6-e33ba8bdb920.png">

**Comment by WeilerP** [comment]
Seems like a duplicate to #733.
