### ISSUE TITLE
How to change cluster labels in velocity_embedding_stream plot?

### ISSUE THREAD

**Issue by shaln** [theislab/scvelo#822]
Hello. I have a question regarding the cluster labels shown in the `velocity_embedding_stream` plots. How do I change it to reflect the cell type names (stored under 'celltype' in the object's metadata)? 

The clusters are labelled according to the seurat_clusters (ie 0, 1, 2, 3) and this remains the case even when I change the line below to `color='celltype'`. 

`scv.pl.velocity_embedding_stream(control, basis='umap', color='seurat_clusters', dpi=250, cutoff_perc=0.5, save='dy_control_projection.png')`

**Comment by WeilerP** [comment]
This should work. You can try it yourself by changing the parameter [here](https://scvelo.readthedocs.io/VelocityBasics/#Project-the-velocities) in the tutorial.
Could you please share the package versions you are using (output of `scv.logging.print_versions`) as well as the output of `adata.obs[['seurat_clusters', 'celltype']].head()`?

**Comment by shaln** [comment]
Here are the package versions. The ERROR below only started appearing recently when I revisited scVelo - last time I used it was in December and did not have the error.

```
scv.logging.print_versions()
scvelo==0.2.4  scanpy==1.8.2  anndata==0.7.8  loompy==3.0.6  numpy==1.21.5  scipy==1.7.3  matplotlib==3.4.3  sklearn==1.0.2  pandas==1.3.5  
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
ERROR: XMLRPC request failed [code: -32500]
RuntimeError: PyPI's XMLRPC API is currently disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information.
```

Here is the output for `control.obs[['seurat_clusters', 'celltype']].head()`. I'm not sure why celltype here came out as numbers... They were Artery, Vein and Capillary in the files prior to saving as h5ad. Is there something I should do prior to saving as h5ad so that the characters do not get converted to numbers here?

```
	seurat_clusters	celltype
Cont1_AAACCTGCAAGTTAAG-1	0	0
Cont1_AAACCTGGTATGAAAC-1	0	0
Cont1_AAACCTGGTCTCCACT-1	3	3
Cont1_AAACCTGGTTTGGGCC-1	0	0
Cont1_AAACCTGTCACCCGAG-1	0	0
```

**Comment by WeilerP** [comment]
The two columns are identical so the code is doing what it is supposed to do.
