### ISSUE TITLE
Fixed spliced/unspliced proportion

### ISSUE THREAD

**Issue by haerin0106** [theislab/scvelo#825]
Hello! I'm trying to use scvelo on a loom dataset where the cluster annotations are added in from seurat using the directions[ here](https://github.com/basilkhuder/Seurat-to-RNA-Velocity)
When I try to compute the proportion of spliced to unspliced using the scv.pl.proportions command, the following happens.

![image](https://user-images.githubusercontent.com/92518297/153642401-c873b0fc-17f7-4552-9525-dc8055634004.png)

The proportion is all 26%-74%. I've tried several different cluster methods and this happens to all the results. 
This is the adata and obs section of the adata object (49804 rows × 6 columns)
![Screenshot 2022-02-11 at 17 53 01](https://user-images.githubusercontent.com/92518297/153643476-e80f59ea-f6da-4a24-9b4a-240c2d331253.png)

![Screenshot 2022-02-11 at 17 48 08](https://user-images.githubusercontent.com/92518297/153642756-a62c2ab9-9161-4306-8391-4ec0c1aa50d7.png)

I saw a previous issue similar to this, and you said you tried it on the developer version and it worked, but unfortunately this didn't work for me (Running scvelo 0.2.5.dev65+gbc4cdf0 (python 3.7.12)) 

When I continue with the CellRank pipeline, the results seem very wrong. 
![image](https://user-images.githubusercontent.com/92518297/153646992-d94eccc3-1124-4d51-b801-cdf2f3a3be05.png)

Any help is much appreciated!

```python
scv.pl.proportions(adata, groupby='celltype_big', layers=['spliced','unspliced'])
```

**Comment by WeilerP** [comment]
@haerin0106, are you running `scv.pl.proportions` on the raw data? The function is **not** made to be run on preprocessed (e.g. normalized) data! This can lead to unexpected behavior (see e.g. #733).

> When I continue with the CellRank pipeline, the results seem very wrong.

I presume the shown directionality differs from what you expected/known biology? There are several issues and discussions on this. Please have a look at them. In a nutshell: This most likely boils down to phase portraits not having the expected shape.

**Comment by WeilerP** [comment]
Closing this, since no response.

**Comment by haerin0106** [comment]
Hi, sorry for the late response. Yes, it was raw data, but I was importing the wrong UMAP coordinates from my Seurat object in R, hense the chaos. It got fixed, and the spliced to unspliced ratio varies for each cluster now. However, the average spliced/unspliced ratio is indeed 26:74 (and it’s not that different in each cluster (ex. 30:70)) which is opposite to what I would expect in normal data. I am yet to try phase portraits, but would there be any reasons for this overall trend in ratio? Is there a difference between 5’ 10x data and 3’ data?
