### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by lh12565** [theislab/scvelo#827]
Hi, the scvelo workered fine before, but there was an error now when I import scvelo

```python
import scvelo as scv
```

<details>

<summary> Error output </summary>

```pytb
ERROR; return code from pthread_create() is 11
        Error detail: Resource temporarily unavailable
```
</details>

<details> <summary>Python 3.8.5 </summary>

```pytb

```
</details>

**Comment by WeilerP** [comment]
Seems like you reached your system user limit for the number of processes you can run at most. Nothing scVelo can do there. Try increasing the maximum number of user processes.
