### ISSUE TITLE
Error when save the result of proportions()

### ISSUE THREAD

**Issue by lh12565** [theislab/scvelo#828]
Hi, I try to save the proportion of spliced to unspliced, there is an error as below. I saw that the parameters of this function (scv.pl.proportions) do have "save", I don't know why it is not recognized?

```python
scv.pl.proportions(rep2,save='umap-velocity-splice.pdf')
```

<details>

<summary> Error output </summary>

```pytb
TypeError: proportions() got an unexpected keyword argument 'save'
```
</details>

<details> <summary> Python 3.8.5 </summary>

```pytb
scvelo==0.2.2  scanpy==1.8.2  anndata==0.7.5  loompy==3.0.6  numpy==1.19.2  scipy==1.6.0  matplotlib==3.3.2  sklearn==0.24.1  pandas==1.1.5
```
</details>

**Comment by WeilerP** [comment]
@lh12565, you need to update to the latest version of scVelo.
