### ISSUE TITLE
Plot saving conflicts with scanpy's sc.settings.autosave = True

### ISSUE THREAD

**Issue by TobiTekath** [theislab/scvelo#83]
Hi,

I just wanted to leave a quick note, that the plot saving of scvelo does not work as intended when scanpy's `sc.settings.autosave` is set to  `True`.

The plot is already saved by scanpy (into scanpy's `sc.settings.figdir` directroy) and is not returned, so that scvelo saves empty files to the `scv.settings.figdir`.

### Problematic behaviour

suppose we have a plotting ready anndata object:
```
import scanpy as sc
import scvelo as scv

sc.settings.autosave = True
sc.settings.figdir = "scanpy_dir/"

scv.settings.set_figure_params('scvelo', dpi_save=320, format="png")
scv.settings.figdir = "scvelo_dir/"

scv.pl.velocity_embedding(anndata, basis='umap', save="velo")
```

> `WARNING: saving figure to file scanpy_dir/umap.png`
> `saving figure to file scvelo_dir/scvelo_velo.png`
> `<Figure size 700x500 with 0 Axes>`

**Comment by VolkerBergen** [comment]
Thanks for pointing that out. Should be fixed now.
