### ISSUE TITLE
scale data for scvelo

### ISSUE THREAD

**Issue by lh12565** [theislab/scvelo#831]
Hi, I have a anadata from seurat data which adata.X was scaled. I want to know if I can run it as below:

```python
adata=scv.read('adata.h5ad')  #adata.X is normalised and scaled
loom=scv.read('my.loom', cache=True)
rep2=scv.utils.merge(adata,loom)
scv.pp.filter_and_normalize(rep2, min_shared_counts=20, n_top_genes=3000)
scv.pp.moments(rep2, n_pcs=30, n_neighbors=30)

scv.tl.recover_dynamics(rep2)
scv.tl.velocity(rep2, mode='dynamical')
scv.tl.velocity_graph(rep2)
scv.pl.velocity_embedding_stream(rep2, basis='umap',color='celltype',save='umap-velocity_embedding.png')
```

<details>

<summary> Error output </summary>

```pytb

```
</details>

<details> <summary> python 3.8 </summary>

```pytb

```
</details>

**Comment by WeilerP** [comment]
This is not a bug. Please do not open an issue (especially with a wrong tag) if you have a question but open a discussion instead.
