### ISSUE TITLE
number of genes in tl.rank_velocity_genes result

### ISSUE THREAD

**Issue by natallah** [theislab/scvelo#858]
...

```python
scv.tl.rank_dynamical_genes(adata, groupby='clusters',n_genes=2000)
```

I want scVelo to output the top 2000 genes for each cluster, however only 706 genes were output for each cluster.  There is no error message and it seems to run fine and work well, so I don't know that this is a bug and is likely moreso that I do not understand how scVelo is selecting the genes to output (I understand the ranking and statistics, but not why the list is cut at 706 rather than 2000 genes).  Of note, I also computed velocities on every gene using scv.tl.recover_dynamics(adata, var_names='all') so the issue shouldnt be that some genes do not have velocities associated with them.

**Comment by WeilerP** [comment]
@natallah would you please provide the full pipeline you are running including the traceback and package versions are asked for in the issue template? Thanks!
Note also that passing `var_names='all'` to `recover_dynamics` does not mean that one model per gene can always be fitted as there might be insufficient number of counts. You can, for example, check for how many genes a model was fit by counting the number of entries in `adata.var['fit_alpha']` wich are not `NaN`, e.g. something along the lines of `adata.var['fit_var_names'].isnull()` would give you the NaN entries.

**Comment by natallah** [comment]
scvelo version 0.2.4 was used.  

I do not have the traceback anymore, but there was no error when I ran it (sorry!).   I recognize that you will not be able to look into my specific question/use case.  I assume that the other entries are NaN, which I'll check.  So then is the way that rank_velocity_genes works to output all genes, ranked?  Is there any way to see which were statistically significant?

**Comment by WeilerP** [comment]
> I do not have the traceback anymore, but there was no error when I ran it (sorry!).

Sorry, did not necessarily mean error stack trace but also the logging statements (along with the corresponding code) provided by scvelo/scanpy which can be helpful to pinpoint why a certain behaviour is being observed (see e.g. #775 where the number of selected highly variable genes differed from the specified number).

> So then is the way that rank_velocity_genes works to output all genes with velocity measurements regardless of statistical significance, ranked (up to the max number of genes)?

No, there is a bit of gene selection going on (see [here](https://github.com/theislab/scvelo/blob/85295fc43e9582423e4b977d5fba5c2c65869d71/scvelo/tools/rank_velocity_genes.py#L301-L333)) which could also explain why might also contribute to the number of genes being smaller than 2000.

> Is there any way to see which were statistically significant?

No, unfortunately not yet (see #154).

**Comment by natallah** [comment]
Sorry for the delay!  Attached are the logging statements and code.  I separated the commands into small chunks so that I could troubleshoot easier.  I also commented out irrelevant lines (for the purposes of this issue). 

[2_velocity_analysis_loom_macs_all.txt](https://github.com/theislab/scvelo/files/8490566/2_velocity_analysis_loom_macs_all.txt)
[5_differential_velocity_macs.txt](https://github.com/
[Velocity_compute-14593416-natallah.txt](https://github.com/theislab/scvelo/files/8490570/Velocity_compute-14593416-natallah.txt)
[Velocity_diff-14735181-natallah.txt](https://github.com/theislab/scvelo/files/8490571/Velocity_diff-14735181-natallah.txt)
theislab/scvelo/files/8490567/5_differential_velocity_macs.txt)

**Comment by WeilerP** [comment]
@natallah, I'm closing this for now. Please provide reproducible code snippets I can simply copy and paste, here on GitHub. Additionally, please provide the accompanying traceback. Sorry, I do not have the time to go through different, random text files that do not contain merely the essential information.
