### ISSUE TITLE
Edge case in pl.velocity_embedding_grid

### ISSUE THREAD

**Issue by TobiTekath** [theislab/scvelo#86]
Hi Volker,

I think I stumbled upon an edge case for the velocity grid embedding plot based upon graph embedding.

The call `scv.pl.velocity_embedding_grid(anncells_scv, basis='draw_graph_fa')` yields the following error:

```
ValueError                                Traceback (most recent call last)
----> 1 scv.pl.velocity_embedding_grid(anncells_scv, basis='draw_graph_fa')

/miniconda/lib/python3.7/site-packages/scvelo/plotting/velocity_embedding_grid.py in velocity_embedding_grid(adata, basis, vkey, density, smooth, min_mass, arrow_size, arrow_length, arrow_color, scale, autoscale, n_neighbors, X, V, X_grid, V_grid, principal_curve, color, use_raw, layer, color_map, colorbar, palette, size, alpha, perc, sort_order, groups, components, projection, legend_loc, legend_fontsize, legend_fontweight, right_margin, left_margin, xlabel, ylabel, title, fontsize, figsize, dpi, frameon, show, save, ax, ncols, **kwargs)
    127         V_emb = np.array(_adata.obsm[vkey + '_' + basis][:, get_components(components, basis)]) if V is None else V[:, :2]
    128         X_grid, V_grid = compute_velocity_on_grid(X_emb=X_emb, V_emb=V_emb, density=density, autoscale=autoscale,
--> 129                                                   smooth=smooth, n_neighbors=n_neighbors, min_mass=min_mass)
    130 
    131     scatter_kwargs = {"basis": basis, "perc": perc, "use_raw": use_raw, "sort_order": sort_order, "alpha": alpha,

/miniconda/lib/python3.7/site-packages/scvelo/plotting/velocity_embedding_grid.py in compute_velocity_on_grid(X_emb, V_emb, density, smooth, n_neighbors, min_mass, autoscale, adjust_for_stream)
     61         X_grid, V_grid = X_grid[p_mass > min_mass], V_grid[p_mass > min_mass]
     62 
---> 63         if autoscale: V_grid /= 3 * quiver_autoscale(X_grid, V_grid)
     64 
     65     return X_grid, V_grid

/miniconda/lib/python3.7/site-packages/scvelo/tools/velocity_embedding.py in quiver_autoscale(X_emb, V_emb)
     11 def quiver_autoscale(X_emb, V_emb):
     12     import matplotlib.pyplot as pl
---> 13     scale_factor = np.abs(X_emb).max()  # just so that it handles very large values
     14     fig, ax = pl.subplots()
     15     Q = ax.quiver(X_emb[:, 0] / scale_factor, X_emb[:, 1] / scale_factor,

/miniconda/lib/python3.7/site-packages/numpy/core/_methods.py in _amax(a, axis, out, keepdims, initial, where)
     28 def _amax(a, axis=None, out=None, keepdims=False,
     29           initial=_NoValue, where=True):
---> 30     return umr_maximum(a, axis, None, out, keepdims, initial, where)
     31 
     32 def _amin(a, axis=None, out=None, keepdims=False,

ValueError: zero-size array to reduction operation maximum which has no identity
```
A little bit of debugging brought me to the conclusion, that these lines are the cause:

https://github.com/theislab/scvelo/blob/00e7af695ef81ccdd48d5ca5e85873c30969616d/scvelo/plotting/velocity_embedding_grid.py#L60-L61

The min_mass is calculated to be 0.01; but all p_mass values are below that. So all values are filtered away, which causes the error.

Is there any nice way how to handle this besides setting the min_mass to an extremely low value?

The p_mass values look like this:

```
array([4.82423663e-147, 4.46068037e-147, 6.48723654e-149, ...,
       3.35574285e-032, 2.58555260e-043, 3.14624938e-056])
```

All other plots (like stream embedding, plots based on umap projection) are not creating this error.

## Info that might be useful:
The anndata object I am trying to plot was originally created by scanpy, where also the force directed graph (based on ForceAtlas2) was computed. I subsequently merge the anndata object with a quite small velocyto object - subsetting the number of cells to ~1/7th of the original cellnumber. The number of genes is also heavily reduced by the `scv.pp.filter_and_normalize` function to ~1/10th of the original number of genes.

## Version Info:
```
scvelo==0.1.19.dev47+8d111c8  scanpy==1.4.4  anndata==0.6.22.post1  loompy==2.0.17  numpy==1.17.0  scipy==1.2.1  matplotlib==3.0.2  sklearn==0.21.3  pandas==0.25.0  
```

**Comment by VolkerBergen** [comment]
Ah, good point! That has indeed nothing to do with the data nor the velocities.. Low p_mass values arise with extremely large values of your embeddin, thus the workaround `adata.obsm['draw_graph_fa'] /= np.max(np.abs( adata.obsm['draw_graph_fa'])) fixes it.

For the future, I'll probably just remove the clipping in that line. 

Regarding the gene number reduction, that is not unusual as only a subset of genes have sufficient number for **both** spliced and unspliced counts.

**Comment by TobiTekath** [comment]
Thanks for the clarification, I really thought the initial problem would have been the subsetting.
The workaround works just fine.

Best,
Tobias
