### ISSUE TITLE
X will not be normalized if SoupX was done on the 10X matrix

### ISSUE THREAD

**Issue by hyjforesight** [theislab/scvelo#862]
Hello scVelo and @WeilerP,
A similar issue like days before, but related with normalization at this time. Not sure whether it's the problem caused by SoupX or scVelo's `scv.pp.normalize_per_cell()` function.
I performed SoupX to remove ambient RNA in 10X matrix and import the matrix corrected by SoupX, but `scv.pp.normalize_per_cell(adata)` does normalize `X`.
Is it appropriate to enforce the normalization? Appreciate it if you could help me with this issue.
Thanks!
Best,
YJ

```python
ACTWT = sc.read_10x_mtx(path='C:/Users/Park_Lab/Documents/filtered_feature_bc_matrix_Soup_X/', var_names='gene_symbols')    # load 10X matrix after SoupX correction
ACTWT.var_names_make_unique()
ACTWT
AnnData object with n_obs × n_vars = 18228 × 32285
    var: 'gene_ids'

ldata = scv.read(filename='C:/Users/Park_Lab/Documents/Tumor.loom')
test = scv.utils.merge(ACTWT, ldata)

scv.pp.filter_genes(adata, min_shared_counts=20)
scv.pp.normalize_per_cell(adata)
WARNING: Did not normalize X as it looks processed already. To enforce normalization, set `enforce=True`.
Normalized count data: spliced, unspliced.

scv.pp.filter_genes_dispersion(adata, n_top_genes=2000)
scv.pp.log1p(adata)
```

<summary> Error output </summary>

```pytb
WARNING: Did not normalize X as it looks processed already. To enforce normalization, set `enforce=True`.
Normalized count data: spliced, unspliced.
```
</details>

<details> <summary> Versions </summary>

```pytb
scanpy==1.8.2 anndata==0.7.8 umap==0.5.2 numpy==1.21.5 scipy==1.7.3 pandas==1.3.5 scikit-learn==1.0.2 statsmodels==0.13.1 python-igraph==0.9.9 pynndescent==0.5.5
scvelo==0.2.4  scanpy==1.8.2  anndata==0.7.8  loompy==3.0.6  numpy==1.21.5  scipy==1.7.3  matplotlib==3.5.1  sklearn==1.0.2  pandas==1.3.5  
cellrank==1.5.1 scanpy==1.8.2 anndata==0.7.8 numpy==1.21.5 numba==0.55.0 scipy==1.7.3 pandas==1.3.5 pygpcca==1.0.3 scikit-learn==1.0.2 statsmodels==0.13.1 python-igraph==0.9.9 scvelo==0.2.4 pygam==0.8.0 matplotlib==3.5.1 seaborn==0.11.2
```
</details>

**Comment by WeilerP** [comment]
Would have to double check but, as far as I am aware of/remember, `soupX` doesn't return whole counts which scvelo in turn interprets as the data having been normalized. Consequently, you can/should pass `enforce-True` to normalize the data.

**Comment by hyjforesight** [comment]
check this https://github.com/constantAmateur/SoupX/issues/107
