### ISSUE TITLE
Unable to load loom file generated with recent version (3.0.7) of loompy fromfq

### ISSUE THREAD

**Issue by edg1983** [theislab/scvelo#864]
Hi,

I've generate a .loom file from 10X fastq files using loompy fromfq latest version (3.0.7) following the steps described in the documentation (http://linnarssonlab.org/loompy/kallisto/index.html).

Then I tried to read the generated loom file using scvelo v0.2.4 (python 3.9.7) with the following commnad `adata = scv.read_loom("test.loom")`. This results in the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.9/site-packages/anndata/compat/__init__.py", line 305, in inner_f
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/anndata/_io/read.py", line 271, in read_loom
    var, varm = _fmt_loom_axis_attrs(dict(lc.row_attrs), var_names, varm_mapping)
  File "/opt/conda/lib/python3.9/site-packages/anndata/_io/read.py", line 149, in _fmt_loom_axis_attrs
    if v.ndim > 1 and v.shape[1] > 1:
AttributeError: 'NoneType' object has no attribute 'ndim'
```
I can load and process the same file correctly using loompy itself. I've also tested with some old files generated with an old version of loompy or using velocyto and I can load them correctly as well. 
Is it possible that loom files written by recent versions of loompy are no longer compatible with scvelo (I noticed from loompy repo that from version 3.0.3 they switched to new loom v3.0 standard)?

**Comment by edg1983** [comment]
I've tracked down the issue. The problem is that the loom file produced by loompy using their reference file for hg38 has a  row attribute `Aliases` which contains None object and thus crash the code.
I've fixed the code in anndata read.py by adding a quick check to skip dict element when value is None.

**Comment by WeilerP** [comment]
Thanks @edg1983! Might be worth opening a PR in the `anndata` repo. @ivirshup are you aware of this or has this already been fixed? Closing this as it is unrelated to the `scvelo` code.
