### ISSUE TITLE
scv.pp.filter_and_normalize 'layers_normalize' argument does not work as expected.

### ISSUE THREAD

**Issue by JesseRop** [theislab/scvelo#875]
scv.pp.filter_and_normalize normalized X even when I specify that I only want ['spliced', 'unspliced] in the 'layers_normalize' argument.

```python
import scanpy as sc
import scvelo as scv
import cellrank as cr

adata = cr.datasets.pancreas()

adata

scv.pp.filter_and_normalize(adata, n_top_genes=200, subset_highly_variable=False, layers_normalize=['spliced', 'unspliced'])
```

<details> <summary> Versions </summary>

```pytb
scvelo==0.2.5.dev71+g85295fc  scanpy==1.9.1  anndata==0.7.8  loompy==3.0.7  numpy==1.21.5  scipy==1.8.0  matplotlib==3.5.1  sklearn==1.0.2  pandas==1.4.2
```

</details>

**Comment by WeilerP** [comment]
`adata.X` is always normalized as it is used in any subsequent analysis (calculation of highly variable genes, PCA, neighbor graph calculation) which requires it to be preprocessed.

**Comment by lupin90** [comment]
First, Thank you for providing such a useful tool! And Yes, I understand that the normalize operation on X is necessary. However, sometimes my data has already been normalized, and I don't want to normalize it again. If I don't include the layers_normalize parameter, scVelo will show a warning: "WARNING: Did not normalize X as it looks processed already. To enforce normalization, set enforce=True." In fact, it does not perform any normalization calculation on X. On the contrary, if I add the layers_normalize parameter, regardless of whether I include X in the layers_normalize parameter or not, it will perform calculations on X without any warning. Moreover, I saw in the help prompt for layers_normalize that "layers_normalize: list of str (default: None)......If set to None, the layers {'X', 'spliced', 'unspliced'} are considered for normalization upon testing whether they have already been normalized." This can easily lead to problems.
