### ISSUE TITLE
errors when use precomputed UMAP embeddings

### ISSUE THREAD

**Issue by JuanXie19** [theislab/scvelo#884]
...
Hi,
I tried to plot velocity on precomputed UMAP embeddings, and I added these embeddings as suggested in issue#37. Yet I got the following error:

```python
adata.obsm['X_umap'] = scv.load('/fs/scratch/PCON0024/scVelo/Gang_umap.csv')
scv.pl.velocity_embedding_stream(adata, basis='umap')

```

![image](https://user-images.githubusercontent.com/98572468/172664695-03b54922-6432-4ded-a4f8-fa1c66d12717.png)
![image](https://user-images.githubusercontent.com/98572468/172665761-5a49b44d-43be-4a6a-871a-5a64826b78f7.png)
<summary> Error output </summary>

```pytb


```
</details>

<details> <summary> Versions </summary>

```pytb

```
![image](https://user-images.githubusercontent.com/98572468/172665427-7bf3d2c3-2aad-415f-8472-a4beca8ed30d.png)

**Comment by WeilerP** [comment]
@JuanXie19, the entry `.obsm['X_umap']` should be an array, not Pandas DataFrame. Can you please check if the issue persists when storing the data appropriately?

**Comment by JuanXie19** [comment]
> @JuanXie19, the entry `.obsm['X_umap']` should be an array, not Pandas DataFrame. Can you please check if the issue persists when storing the data appropriately?

@WeilerP , thanks for the reply. Yes, I realized this point and stored the umap as an array, which solved the issue perfectly.
