### ISSUE TITLE
using scv.pl.heatmap, have  a gap in the gene expression value of each row

### ISSUE THREAD

**Issue by yanpinlu** [theislab/scvelo#920]
When using scv.pl.heatmap, there is a gap in the gene expression value of each row，

`scv.pl.heatmap(adata,var_names=top_genes,sortby='latent_time',col_color='celltype',n_convolve=100)
`
But when using the code above, when the selected gene set is 1000, there is no problem, and it may occur when using gene sets 2000 or 500, which is relatively random

![heatmap](https://user-images.githubusercontent.com/102843242/188370877-1cfa2583-5ad3-4c5f-9eff-8d34663361f4.png)
![heatmap1](https://user-images.githubusercontent.com/102843242/188370880-377fc1ea-33a3-437d-9e0a-b96d1f41e184.png)

**Comment by WeilerP** [comment]
@yanpinlu, are you possibly fitting fewer gene models than you are trying to plot here? The number of fitted models is the number of not null entries in `adata.var["fit_alpha"]`, for example.
