### ISSUE TITLE
Problem with loom file structure

### ISSUE THREAD

**Issue by mayurdoke6** [theislab/scvelo#943]
Hello,
I have earlier created .loom files with the following code which resulted in .loom files being correctly read by scvelow
velocyto run -b filtered_barcodes.tsv -o output_path bam_file.bam annotation.gtf

However, now when I created new .loom files using the same barcodes and .bam files, scvelo cannot read the loom files and I am getting the following error. Could you please help me with the issue-

ValueError Traceback (most recent call last)
Input In [6], in <cell line: 4>()
2 ldata2 = scv.read('Control_2ST2_OM2ZO.loom', cache=True)
3 ldata3 = scv.read('Control_3ST2_DBUWB.loom', cache=True)
----> 4 ldata4 = scv.read('possorted_genome_bam_25ZIW.loom', cache=True)
5 ldata5 = scv.read('Control_2ST3_1P2UQ.loom', cache=True)
6 ldata6 = scv.read('Control_3ST3_2GYNM.loom', cache=True)

File ~/.conda/envs/pib792/lib/python3.9/site-packages/scanpy/readwrite.py:112, in read(filename, backed, sheet, ext, delimiter, first_column_names, backup_url, cache, cache_compression, **kwargs)
110 filename = Path(filename) # allow passing strings
111 if is_valid_filename(filename):
--> 112 return _read(
113 filename,
114 backed=backed,
115 sheet=sheet,
116 ext=ext,
117 delimiter=delimiter,
118 first_column_names=first_column_names,
119 backup_url=backup_url,
120 cache=cache,
121 cache_compression=cache_compression,
122 **kwargs,
123 )
124 # generate filename and read to dict
125 filekey = str(filename)

File ~/.conda/envs/pib792/lib/python3.9/site-packages/scanpy/readwrite.py:764, in _read(filename, backed, sheet, ext, delimiter, first_column_names, backup_url, cache, cache_compression, suppress_cache_warning, **kwargs)
762 adata = _read_softgz(filename)
763 elif ext == 'loom':
--> 764 adata = read_loom(filename=filename, **kwargs)
765 else:
766 raise ValueError(f'Unknown extension {ext}.')

File ~/.conda/envs/pib792/lib/python3.9/site-packages/anndata/compat/init.py:305, in _deprecate_positional_args.._inner_deprecate_positional_args..inner_f(*args, **kwargs)
303 extra_args = len(args) - len(all_args)
304 if extra_args <= 0:
--> 305 return f(*args, **kwargs)
307 # extra_args > 0
308 args_msg = [
309 "{}={}".format(name, arg)
310 for name, arg in zip(kwonly_args[:extra_args], args[-extra_args:])
311 ]

File ~/.conda/envs/pib792/lib/python3.9/site-packages/anndata/_io/read.py:251, in read_loom(filename, sparse, cleanup, X_name, obs_names, obsm_names, var_names, varm_names, dtype, obsm_mapping, varm_mapping, **kwargs)
248 filename = fspath(filename) # allow passing pathlib.Path objects
249 from loompy import connect
--> 251 with connect(filename, "r", **kwargs) as lc:
252 if X_name not in lc.layers.keys():
253 X_name = ""

File ~/.conda/envs/pib792/lib/python3.9/site-packages/loompy/loompy.py:1140, in connect(filename, mode, validate, spec_version)
1114 def connect(filename: str, mode: str = 'r+', *, validate: bool = True, spec_version: str = "2.0.1") -> LoomConnection:
1115 """
1116 Establish a connection to a .loom file.
1117
(...)
1138 Note: if validation is requested, an exception is raised if validation fails.
1139 """
-> 1140 return LoomConnection(filename, mode, validate=validate, spec_version=spec_version)

File ~/.conda/envs/pib792/lib/python3.9/site-packages/loompy/loompy.py:84, in LoomConnection.init(self, filename, mode, validate, spec_version)
82 lv = loompy.LoomValidator(version=spec_version)
83 if not lv.validate(filename):
---> 84 raise ValueError("\n".join(lv.errors) + f"\n{filename} does not appead to be a valid Loom file according to Loom spec version '{spec_version}'")
86 self._file = h5py.File(filename, mode)
87 self._closed = False

ValueError: Row attribute 'Accession' dtype object is not allowed
Row attribute 'Chromosome' dtype object is not allowed
Row attribute 'Gene' dtype object is not allowed
Row attribute 'Strand' dtype object is not allowed
Column attribute 'CellID' dtype object is not allowed
For help, see http://linnarssonlab.org/loompy/format/
possorted_genome_bam_25ZIW.loom does not appead to be a valid Loom file according to Loom spec version '2.0.1'

**Comment by WeilerP** [comment]
@mayurdoke6 please see #942 and **do not** open another issue. Thanks!
