### ISSUE TITLE
error in computing velocity graph

### ISSUE THREAD

**Issue by vivekbhr** [theislab/scvelo#95]
Hi
I am trying the scVelo implementation with my dataset of ~1500 cells. I ran. 
```
scv.pp.filter_and_normalize(adata, min_shared_counts=10, n_top_genes=3000)
scv.pp.neighbors(adata)
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
scv.tl.velocity(adata)
``` 
Which seems to go fine.

My anndata object:
```
AnnData object with n_obs × n_vars = 1531 × 528 
    obs: 'bcs', 'sample', 'CellID', 'initial_size_unspliced', 'initial_size_spliced', 'initial_size', 'n_counts', 'louvain'
    var: 'gid', 'velocity_gamma', 'velocity_r2', 'velocity_genes'
    uns: 'pca', 'neighbors', 'velocity_settings', 'louvain', 'louvain_colors'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    layers: 'spliced', 'unspliced', 'ambiguous', 'Ms', 'Mu', 'velocity'
```

But then I ran `scv.tl.velocity_graph(data= adata)` and got an error:

```
computing velocity graph

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-54-a8135f883ff9> in <module>
----> 1 scv.tl.velocity_graph(data= adata)
      2 #(adata)

~/miniconda3/envs/velocyto/lib/python3.6/site-packages/scvelo/tools/velocity_graph.py in velocity_graph(data, vkey, xkey, tkey, basis, n_neighbors, n_recurse_neighbors, random_neighbors_at_max, sqrt_transform, gene_subset, approx, copy)
    176 
    177     logg.info('computing velocity graph', r=True)
--> 178     vgraph.compute_cosines()
    179 
    180     adata.uns[vkey+'_graph'] = vgraph.graph

~/miniconda3/envs/velocyto/lib/python3.6/site-packages/scvelo/tools/velocity_graph.py in compute_cosines(self)
    123         if self.report: progress.finish()
    124 
--> 125         vals = np.hstack(vals)
    126         vals[np.isnan(vals)] = 0
    127 

<__array_function__ internals> in hstack(*args, **kwargs)

~/miniconda3/envs/velocyto/lib/python3.6/site-packages/numpy/core/shape_base.py in hstack(tup)
    342         return _nx.concatenate(arrs, 0)
    343     else:
--> 344         return _nx.concatenate(arrs, 1)
    345 
    346 

<__array_function__ internals> in concatenate(*args, **kwargs)

ValueError: need at least one array to concatenate
```
Any idea how I can fix this? Thanks in advance.

Vivek

**Comment by VolkerBergen** [comment]
Hi Vivek,

let's start checking whether the resulting velocities are meaningful. That error would usually result from velocity vectors solely consisting of NANs or zeros. So something here must have gone wrong.

Can you print `adata.var['velocity_genes'].sum()` and `adata.layers['velocity']`. 
and checkout one phase portrait via `scv.pl.velocity(adata, 'your_favorite_gene')`

**Comment by vivekbhr** [comment]
Here are the results:

`adata.var['velocity_genes'].sum()`

```
1
```

`adata.layers['velocity']`

```
array([[-0.02767229,  0.14965096,  0.        , ..., -0.05770133,
         0.19322886,  0.        ],
       [ 0.02391018,  0.00350496,  0.02789727, ...,  0.04131896,
         0.00507082,  0.04892104],
       [-0.0025649 ,  0.04813718,  0.00212415, ...,  0.02393282,
         0.01267096,  0.00648124],
       ...,
       [ 0.00909867, -0.02024829, -0.03217068, ...,  0.02062673,
         0.0254678 ,  0.03346164],
       [ 0.00891567,  0.00249186,  0.0094989 , ...,  0.04083861,
         0.02019788,  0.04903129],
       [ 0.00537897, -0.00851214,  0.15095225, ..., -0.02220573,
        -0.02613821, -0.0005979 ]], dtype=float32)
```
scv.pl.velocity(adata, 'ENSG00000169057')

<img width="558" alt="test" src="https://user-images.githubusercontent.com/8420267/66332806-dce45200-e935-11e9-9c33-17a7ce4db5a2.png">

**Comment by VolkerBergen** [comment]
One 'velocity gene' left (i.e. selected genes that are taken into account for the velocity graph).. looks like you got very small R2 values.

You can plot a histogram `scv.pl.hist(adata.var['velocity_r2'])` for visual inspection and adjust the threshold with `scv.tl.velocity_genes(adata, min_r2=1e-3)` to obtain more velocity genes.

**Comment by vivekbhr** [comment]
Thanks @VolkerBergen . Changing the threshold got me more genes and this fixed the issue. But I think I need more intuition of the paramaters and functions in scVelo. Is there more documentation somewhere? (the one [here](https://scvelo.readthedocs.io/getting_started.html) seems to be WIP)

**Comment by VolkerBergen** [comment]
More details on the parameters are provided in the [API](https://scvelo.org/api.html). Further explanations (in particular on the dynamical model) are about to come with our preprint.

**Comment by vivekbhr** [comment]
Thanks. Looking forward to it  :+1:

**Comment by mdm247** [comment]
Hi scvelo team, hoping you can help me with this error.

I initially get issue #95 . `adata.var['velocity_genes'].sum() ` shows 1 gene, so I ran `scv.tl.velocity_genes(adata, min_r2=1e-3)`. That changes the gene number to 18.
When re-running code again, it goes one step further, but then gives me an error:
"zero-size array to reduction operation maximum which has no identity"

Screenshot attached.

![Error_1](https://github.com/theislab/scvelo/assets/106946357/fbbd7b00-69db-4ecb-9ea7-355715b61de3)
![Error_2](https://github.com/theislab/scvelo/assets/106946357/70ae4574-f85c-4f50-985a-59385ed57c81)
