### ISSUE TITLE
scv.tl.recover_dynamics() ends before completion

### ISSUE THREAD

**Issue by spkhowe** [theislab/scvelo#956]
Hi, I'm trying to use scv.tl.recover_dynamics() on my dataset (which is enhanced with spliced and unspliced counts)

I'm running this on a xeon-p8 cluster with 48 cores and 192GB of RAM.  The command I ran is scv.tl.recover_dynamics(adata, n_jobs=16)

The job completes quickly (11 minutes) and populates the adata object with fit parameters, but all values are Nan.

Other times I have tried to run this from a cluster's Jupyter notebook result in the memory error that is currently an open issue.

Let me know how I can run this successfully, thanks!

**Comment by WeilerP** [comment]
Please have a look at #872, for example.
