### ISSUE TITLE
Different velocity trajectories between stochastic and dynamic models

### ISSUE THREAD

**Issue by DaianeH** [theislab/scvelo#975]
Hi,

Thank you for developing scVelo. I've been working with it to study trajectories and drivers of differentiation in AML cells under two treatments.
I got very different results when running scVelo on dynamic and on stochastic mode on the same datasets.

First, attached are plots of velocity vectors. In blue are progenitors, in orange GMPs, and in green monocytes. The plot "stochastic" shows the directionality as I expect: blue->orange->green. However, the "dynamic" plot somehow shows green->orange, which does not make much sense since GMPs differentiate into monocytes, not the other way around.

[stochastic.pdf](https://github.com/theislab/scvelo/files/10238415/stochastic.pdf)
[dynamic.pdf](https://github.com/theislab/scvelo/files/10238418/dynamic.pdf)

How do you explain the different results?

**Comment by WeilerP** [comment]
Closing this since it's neither a bug nor code related, and discussed in numerous other discussions (and old issues).
