### ISSUE TITLE
plot velocity on HE images for spatial data

### ISSUE THREAD

**Issue by JunMa11** [theislab/scvelo#976]
Dear scvelo team,

Thanks for providing the awesome tool.

I want to plot the velocity on histology images (from 10x visium). How should I add the image to `adata` and set the `basis` parameter in `velocity_embedding_stream`?

```python
scv.pl.velocity_embedding_stream(
    adata,
    basis="?", # how to set the basis as histology images
    legend_fontsize=9,
    dpi=150,  # increase dpi for higher resolution
    save="./figures/velocity_demo.png"
)
```

**Comment by WeilerP** [comment]
Good question. I don't have enough experience with spatial data formats, I'm afraid. @giovp, maybe you can pitch in? `basis` is always a key from `adata.obsm`. If the coordinates can be/are stored in `adata.obsm`, everything should work out of the box.

**Comment by WeilerP** [comment]
Closing issue as stale.
