### ISSUE TITLE
Unbound Local Error

### ISSUE THREAD

**Issue by rekharichardson1** [theislab/scvelo#983]
UnboundLocalError when trying to run code that has previously run fine before. 
...

```python
loom_path = '/Users/rekha/Desktop/jupyter/data/filtered_feature_bc_matrix_aggr/combined_loom.loom'

ldata = scv.read(loom_path, cache=False)
#adata = scv.utils.merge(adata, ldata)
adata = scv.utils.merge(adata, ldata)

```

<details>

UnboundLocalError                         Traceback (most recent call last)
Cell In[54], line 1
----> 1 adata = scv.utils.merge(adata, ldata)

File /opt/homebrew/lib/python3.10/site-packages/scvelo/core/_anndata.py:526, in merge(adata, ldata, copy, **kwargs)
    524 if "id_length" in kwargs:
    525     id_length = kwargs.get("id_length")
--> 526 clean_obs_names(adata, id_length=id_length)
    527 clean_obs_names(ldata, id_length=id_length)
    528 common_obs = adata.obs_names.intersection(ldata.obs_names)

UnboundLocalError: local variable 'id_length' referenced before assignment
<summary> Error output </summary>

```pytb
# paste the error output here, if applicable
```

</details>

<details> <summary> Versions </summary>

```pytb
# paste the ouput of scv.logging.print_versions() here
```

</details>

**Comment by Roger-GOAT** [comment]
@rekharichardson1 
I have the same issue, do u solve it?

**Comment by coolmak32** [comment]
Getting the same error.

**Comment by coolmak32** [comment]
running these two commands before merging did solve the issue for me
scv.utils.clean_obs_names(adata)
scv.utils.clean_obs_names(ldata)

adata = scv.utils.merge(adata, ldata)

**Comment by LikaiTan** [comment]
> running these two commands before merging did solve the issue for me scv.utils.clean_obs_names(adata) scv.utils.clean_obs_names(ldata)
> 
> adata = scv.utils.merge(adata, ldata)

I suggest carefully using this solution if the issue comes from merging/integrating different loom files into one. It will remove the sample suffixes in the barcodes so that two identical barcodes from two libraries may be regarded as 'duplicates".

My suggestion is to edit the barcode suffixes in loom files according to the adata you"d like to merge.

**Comment by yamihn** [comment]
HI @LikaiTan , I modified the suffix but the solution does not work. Im new I'm python so I'm not able to find the error and where it comes from. Any help is appreciate

**Comment by Urology-weiyu** [comment]
I came up with the same question and now it's resolved. First check if the .obs.index was consistent in both your adata and ldata. If not, try to make it right and check if the problem was solved.
