### ISSUE TITLE
scv.pl.heatmap IndexError

### ISSUE THREAD

**Issue by mimisikai** [theislab/scvelo#988]
return error when run scv.pl.heatmap:
feed in str or list of str gene name, always return this error. 

But, if use this top_gene
top_genes = adata.var['fit_likelihood'].sort_values(ascending=False).index[:300]
it works in the heatmap
...

```python
    scv.pl.heatmap(adata, var_names="CD68", sortby='latent_time',
                   col_color='clusters', n_convolve=100, figsize=(16, 8),
                   yticklabels=True, sort=True, colorbar=True, show=True, layer="count",
                   save='scVelo-heatmap-mono-latent_time.png')
```

<details>

<summary> Error output </summary>

```pytb
Traceback (most recent call last):
  File "/Users/jhou2/PycharmProjects/VelocityAnalysis/Step1 Load data.py", line 240, in <module>
    scv.pl.heatmap(adata, var_names="CD68", sortby='latent_time',
  File "/Users/jhou2/PycharmProjects/VelocityAnalysis/venv/lib/python3.8/site-packages/scvelo/plotting/heatmap.py", line 99, in heatmap
    else adata[:, var_names].X
  File "/Users/jhou2/PycharmProjects/VelocityAnalysis/venv/lib/python3.8/site-packages/anndata/_core/anndata.py", line 622, in X
    _subset(self._adata_ref.X, (self._oidx, self._vidx)),
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/jhou2/PycharmProjects/VelocityAnalysis/venv/lib/python3.8/site-packages/anndata/_core/index.py", line 127, in _subset
    return a[subset_idx]
IndexError: arrays used as indices must be of integer (or boolean) type
```

</details>

<details> <summary> Versions </summary>

```pytb
scvelo==0.2.4  scanpy==1.9.1  anndata==0.8.0  loompy==3.0.7  numpy==1.23.4  scipy==1.9.3  matplotlib==3.6.2  sklearn==1.1.3  pandas==1.5.1  
```

</details>

**Comment by WeilerP** [comment]
@mimisikai, can you please update to the latest version of scVelo and check if the issue still occurs?

**Comment by mimisikai** [comment]
> @mimisikai, can you please update to the latest version of scVelo and check if the issue still occurs?

I have python 3.8.9. After running -U scvelo, it seems the version is still 0.2.4.

**Comment by WeilerP** [comment]
> I have python 3.8.9. After running -U scvelo, it seems the version is still 0.2.4.

@mimisikai, you need to run `pip install --upgrade scvelo`.

**Comment by mimisikai** [comment]
I didn't expect an another error pop up after upgrading to 0.2.5. 
    adata = scv.utils.merge(adata, ldata)
  File "/Users/jhou2/PycharmProjects/VelocityAnalysis/venv/lib/python3.8/site-packages/scvelo/core/_anndata.py", line 526, in merge
    clean_obs_names(adata, id_length=id_length)
UnboundLocalError: local variable 'id_length' referenced before assignment

Never saw this problem when ran 0.2.4

**Comment by WeilerP** [comment]
You have duplicate observations (see #983). It's been fixed in #990. You can run 

```python
scv.utils.clean_obs_names(adata)
scv.utils.clean_obs_names(ldata)

adata = scv.utils.merge(adata, ldata)
```

or install the latest developer version.

**Comment by mimisikai** [comment]
Fixed. Thanks.

**Comment by WeilerP** [comment]
@mimisikai, do you still encounter the original issue when trying to plot the heatmap or has this been resolved?
