### ISSUE TITLE
scv.pl.scatter plot resolution 

### ISSUE THREAD

**Issue by mimisikai** [theislab/scvelo#998]
When using scv.pl.scatter plotting speed and coherence results (I believer it doesn't matter with which data, but generally occurs),
if plotting two variables in one image, no matter how to tune dpi, the real image is still in very low resolution. 

If one plotting one variable, dpi setting is working. 

```python
keys = 'velocity_length', 'velocity_confidence'
scv.pl.scatter(adata, c=keys, cmap='coolwarm', perc=[5, 95], size=30, alpha=0.8,
                   figsize=(7, 5), save='4-speed-coherence.png', dpi=600)

scv.pl.scatter(adata, c='velocity_length', cmap='coolwarm', perc=[5, 95], size=30, alpha=0.8,
                   figsize=(7, 5), save='4-speed.png', dpi=300)
```

<details>

![Screen Shot 2023-02-02 at 2 00 57 PM](https://user-images.githubusercontent.com/4881411/216459229-f1f5e554-29db-4bf6-af4c-92ab161f0e0b.png)

![Screen Shot 2023-02-02 at 2 01 13 PM](https://user-images.githubusercontent.com/4881411/216459266-92be7e59-5f52-45bd-8d31-9a0573f39a6b.png)

</details>

<details> <summary> Versions </summary>

```pytb
# paste the ouput of scv.logging.print_versions() here
```

</details>

**Comment by mimisikai** [comment]
This problem occurs as well when using scatter plot with other data. Like this below:
![Screen Shot 2023-02-02 at 2 07 51 PM](https://user-images.githubusercontent.com/4881411/216460324-6aa357b3-999f-4dfd-b276-c68588fe4e88.png)

**Comment by WeilerP** [comment]
@mimisikai, please provide the package versions you are using as asked for. Closing for the issue for now. Please reopen once you've provided the required information. Thanks.

**Comment by ETAOIK** [comment]
@mimisikai I guess you might not run the following codes before scvelo analysis:
`scv.settings.verbosity = 3  `
`scv.settings.presenter_view= True  `
`scv.set_figure_params('scvelo')  `

Hope this would help you

**Comment by mimisikai** [comment]
> @mimisikai, please provide the package versions you are using as asked for. Closing for the issue for now. Please reopen once you've provided the required information. Thanks.

print(scv.__version__) --> 0.2.5
print(sc.__version__) --> 1.9.1
print(cr.__version__) --> 1.5.1
print(np.__version__) --> 1.23.4
print(pd.__version__) --> 1.5.1
print(ad.__version__) --> 0.8.0

**Comment by mimisikai** [comment]
> 

Actually, I did. But not change on the plot resolution.

**Comment by ETAOIK** [comment]
maybe you can run these codes twice. I met the same problem with you when I follow the pipeline and run the codes, I got the low-resolution plots, but after I ran the set_figure codes I mentioned above the second time, the problem was automatically solved. I can't explain why it happens but it actually works.
